### ISSUE TITLE
When deploying management resources, Security Center resources are not being deployed

### ISSUE THREAD

**Issue by calexandre** [Azure/terraform-azurerm-caf-enterprise-scale#101]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

- **terraform**: `0.14.10`
- **azure provider**: `hashicorp/azurerm v2.58.0`
- **module**: `0.3.1`

### Description

When reconfiguring the `configured_management_resources` section to enable `security_center` (after a successful `plan` and `apply` with only `log_analytics` enabled), terraform will not detect any changes and no security center resources will be deployed.

This is the first deployed management resources:
* notice the `log_analytics=true` and `security_center=false`

```hcl
configure_management_resources = {
    settings = {
      log_analytics = {
        enabled = true
        config = {
          retention_in_days                           = 60
          enable_monitoring_for_arc                   = true
          enable_monitoring_for_vm                    = true
          enable_monitoring_for_vmss                  = true
          enable_solution_for_agent_health_assessment = true
          enable_solution_for_anti_malware            = false
          enable_solution_for_azure_activity          = true
          enable_solution_for_change_tracking         = true
          enable_solution_for_service_map             = true
          enable_solution_for_sql_assessment          = false
          enable_solution_for_updates                 = true
          enable_solution_for_vm_insights             = true
          enable_sentinel                             = false
        }
      }
      security_center = {
        enabled = false
        config = {
          email_security_contact             = "something@somewhere.pt"
          enable_defender_for_acr            = false
          enable_defender_for_app_services   = false
          enable_defender_for_arm            = false
          enable_defender_for_dns            = false
          enable_defender_for_key_vault      = true
          enable_defender_for_kubernetes     = false
          enable_defender_for_servers        = false
          enable_defender_for_sql_servers    = false
          enable_defender_for_sql_server_vms = false
          enable_defender_for_storage        = false
        }
      }
    }

    location = "westeurope"
    tags     = null
    advanced = null
  }
```
After changing the configuration to also deploy the security center, the following results in  "no changes" by Terraform.
* notice the `log_analytics=true` and `security_center=true`

```hcl
configure_management_resources = {
    settings = {
      log_analytics = {
        enabled = true
        config = {
          retention_in_days                           = 60
          enable_monitoring_for_arc                   = true
          enable_monitoring_for_vm                    = true
          enable_monitoring_for_vmss                  = true
          enable_solution_for_agent_health_assessment = true
          enable_solution_for_anti_malware            = false
          enable_solution_for_azure_activity          = true
          enable_solution_for_change_tracking         = true
          enable_solution_for_service_map             = true
          enable_solution_for_sql_assessment          = false
          enable_solution_for_updates                 = true
          enable_solution_for_vm_insights             = true
          enable_sentinel                             = false
        }
      }
      security_center = {
        enabled = true
        config = {
          email_security_contact             = "something@somewhere.pt"
          enable_defender_for_acr            = false
          enable_defender_for_app_services   = false
          enable_defender_for_arm            = false
          enable_defender_for_dns            = false
          enable_defender_for_key_vault      = true
          enable_defender_for_kubernetes     = false
          enable_defender_for_servers        = false
          enable_defender_for_sql_servers    = false
          enable_defender_for_sql_server_vms = false
          enable_defender_for_storage        = false
        }
      }
    }

    location = "westeurope"
    tags     = null
    advanced = null
  }
```

**Steps to Reproduce**

1. Create the management resources for the first time, with log_analytics enabled and security_center disabled.
2. The plan and apply should go smoothly and only the log_analytics resources should be created as expected.
3. Now reconfigure the `configured_management_resources` section and set `security_center.enabled = true`, followed by `terraform plan`
4. Terraform will report that infrastructure is up-to-date, but it should have planned changes to deploy the security_center resources.

**Comment by krowlandson** [comment]
I'm just trying to reproduce this behaviour but don't seem to be able to. I'm not sure whether this is linked to the way you had your providers configured (ref. #102) but when I run the configuration changes you provided for `configure_management_resources`, I get the following outcome when updating `security_center.enabled` from `false` to `true`.

```shell
Terraform will perform the following actions:

  # module.enterprise_scale.azurerm_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/sn/providers/Microsoft.Authorization/policyAssignments/Deploy-ASC-Defender"] will be updated in-place
  ~ resource "azurerm_policy_assignment" "enterprise_scale" {
      ~ enforcement_mode     = false -> true
        id                   = "/providers/Microsoft.Management/managementGroups/sn/providers/Microsoft.Authorization/policyAssignments/Deploy-ASC-Defender"
        name                 = "Deploy-ASC-Defender"
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

As you can see, this setting is toggling the `enforcement_mode` on the `Deploy-ASC-Defender` Policy Assignment.

As an FYI, the other settings within this config block are adjusting the parameter values sent to this Policy Assignment to control the Azure Defender pricing tier settings.

If you are still seeing no change when updating this setting, please let me know and we can try to work out what else might be causing this.

**Comment by calexandre** [comment]
I figured it out... 🤦‍♂️
We have an `archetype_exclusion_org.json` where we explicitly disabled all the ASC policy assignments, which of course, led to this case of Security Center not being deployed...

We thought that even with the excluded policies, the ASC would still be deployed... But I guess that from an ES perspective, it does not make sense to deploy ASC if we don't have the required policy assignment.

For reference, this is our `archetype_exclusion_org.json`:
```json
{
  "exclude_es_root": {
    "policy_assignments": [
      "Deploy-ASC-Monitoring",
      "Deploy-ASC-Defender"
    ],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {},
      "access_control": {}
    }
  }
}
```

You can close this :)

**Comment by krowlandson** [comment]
OK, great thank you. Yes, for ES we are very reliant on having those policies in place in order to configure and monitor compliance these settings 😄
