### ISSUE TITLE
How do we perform a VNet Gateway connection with local n/w gateway using ALZ module?

### ISSUE THREAD

**Issue by ctrlaltcloud** [Azure/terraform-azurerm-caf-enterprise-scale#1015]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### I deployed the ALZ module. While setting up the connectivity subscription and perform the site-to-site connection between VNet gateway and local n/w gateway, terraform plan doesn't show any resources for creation.

Here is the code snippet I am using to deploy connection. 

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/26025867/1f868a2e-e75e-4de8-95e9-c2c8344b10d4)

**Comment by SvenAelterman** [comment]
I would not expect this to work. I have always created those resources separately.

**Comment by matt-FFFFFF** [comment]
> I would not expect this to work. I have always created those resources separately.

Yes, this is by design. Use the module outputs to do this
