### ISSUE TITLE
Ability to rename AMA management resources

### ISSUE THREAD

**Issue by Greg-Court** [Azure/terraform-azurerm-caf-enterprise-scale#1016]
Similar to how we have the ability to rename the management resource group, automation account and log analytics workspace to follow a custom naming convention, these options should be provided for the new AMA user assigned managed identity, vminsights dcr, change tracking dcr and defender for sql dcr introduced in V6.0.0

Is there a workaround for this in the short run?

``` 
configure_management_resources = {
    settings = {
      ama = {
        enable_uami                                                         = true
        enable_vminsights_dcr                                               = true
        enable_change_tracking_dcr                                          = true
        enable_mdfc_defender_for_sql_dcr                                    = false
        enable_mdfc_defender_for_sql_query_collection_for_security_research = false
      }
```

**Comment by Greg-Court** [comment]
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/83063651/da7afcb7-c50a-4ebf-871d-5d32494aff98)
Perhaps something like the above

**Comment by matt-FFFFFF** [comment]
Hi you can do this already with the custom_settings_by_resource_type

It uses the AzureRM resource names for consistency. See the pinned issue on this repo.

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/management/locals.tf#L33-L42

**Comment by steph409** [comment]
had the same problem, in the enterprise_scale module there is a parameter called `configure_management_resources`, I set it like this and it worked:

```hcl
  configure_management_resources = {
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_automation_account = {
          management = {
            name = "automation-custom" # set the name here for the automation account
          }
        }
        azurerm_user_assigned_identity = {
          management = {
            name = "id-custom" # set the name here for the identity
          }
        }
      }
    }
}

```

hope it helps!
