### ISSUE TITLE
Errors when upgrading from v5.0.0 to v5.2.0

### ISSUE THREAD

**Issue by qaiserali** [Azure/terraform-azurerm-caf-enterprise-scale#1019]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: ~> 3.107

**azure provider**: 3.111.0

**module**: 5.2.0

#### Describe the bug

I'm having trouble upgrading from version v5.0.0 to v5.2.0.  I updated the settings.connectivity.tf file by setting the threat_intelligence_allowlist to {} as required, and the connectivity module deployed successfully. However, when deploying the core module, I encountered the following error.

```
Planning failed. Terraform encountered an error while generating this plan.
│ Error: Invalid value for input variable
│ 
│   on main.tf line 69, in module "alz":
│   69:   configure_connectivity_resources = data.terraform_remote_state.connectivity.outputs.configuration
│ 
│ The given value is not suitable for
│ module.alz.var.configure_connectivity_resources declared at
│ .terraform/modules/alz/variables.tf:156,1-44: attribute "settings":
│ attribute "hub_networks": element 0: attribute "config": attribute
│ "azure_firewall": attribute "config": attribute
│ "threat_intelligence_allowlist": map of list of string required.
╵
##[error]Terraform command 'plan' failed with exit code '1'.
##[error]╷
│ Error: Invalid value for input variable
│ 
│   on main.tf line 69, in module "alz":
│   69:   configure_connectivity_resources = data.terraform_remote_state.connectivity.outputs.configuration
│ 
│ The given value is not suitable for
│ module.alz.var.configure_connectivity_resources declared at
│ .terraform/modules/alz/variables.tf:156,1-44: attribute "settings":
│ attribute "hub_networks": element 0: attribute "config": attribute
│ "azure_firewall": attribute "config": attribute
│ "threat_intelligence_allowlist": map of list of string required.
```

#### Steps to Reproduce
I've updated the custom settings in settings.connectivity.tf file as below:
```
threat_intelligence_allowlist = {}
```

My core module settings
``` 
  deploy_connectivity_resources    = false 
  configure_connectivity_resources = data.terraform_remote_state.connectivity.outputs.configuration
  subscription_id_connectivity     = data.terraform_remote_state.connectivity.outputs.subscription_id
```

As mentioned above, I am encountering an issue when trying to upgrade the core module. I successfully upgraded the connectivity module by implementing the necessary changes.

**Comment by qaiserali** [comment]
It was my mistake; as I referenced the wrong (old) state files for the connectivity resources. Everything worked as expected after updating the remote backend for the connectivity resources.

**Comment by qaiserali** [comment]
Closing this issue!

**Comment by matt-FFFFFF** [comment]
Thanks for confirming!
