### ISSUE TITLE
Bug Report: Customization of new management resources not working as expected

### ISSUE THREAD

**Issue by steph409** [Azure/terraform-azurerm-caf-enterprise-scale#1028]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**: 6.0.0

### Description

I want to customize the new management resources. This works fine for some parts, and not for others. I saw the following:

In the submodule "management", there are ultimately three data collection rules which are defined:
*  azure_monitor_data_collection_rule_change_tracking
* azure_monitor_data_collection_rule_sql
* azure_monitor_data_collection_rule_vm_insight
  
The way the custom parameter work in this case is not straight forward. It might just be a simple copy-paste error:
In the custom settings, there are only [two local variables ](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/283edaaa8dec633c5b015218c80c32c4b1c0936a/modules/management/locals.tf#L40)defined for the overrides:
* custom_settings_dcr_vm_insights     
* custom_settings_dcr_change_tracking 

So from my understanding, there is already one missing, the one for sql.

Then, when used, [in the same file](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/283edaaa8dec633c5b015218c80c32c4b1c0936a/modules/management/locals.tf#L426), things get mixed up. For example, it seems not possible to explicitly specify the three data collection rule names.

<img width="697" alt="image" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/33083326/5ee0dda3-baa4-479d-a2fb-e5945301803f">

Also from what I can see, the way to set tags for all management resources using configure_management_resources.tags does not work for the new resources.

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

**Comment by matt-FFFFFF** [comment]
Thank you for identifying these issues @steph409 - Your diligence is most helpful 😊

We will put on our backlog to fix or would be welcoming of a PR to do the same

**Comment by birdnathan** [comment]
FYI - The DCR stuff always gets deployed now even if you dont want it to so the boolean logic for that is wrong. Custom names on all Managemeng Resources doesnt seem to work for me now either. Not had time to see exactly why.

**Comment by MoussaBangre** [comment]
Also facing the same issue. Any progress on that ?

**Comment by robearTest** [comment]
Also experiencing this issue.

**Comment by SvenAelterman** [comment]
@steph409 If you were customizing the configuration of the DCRs (not just name, for example, but actual collection settings), can you share a sample, please?

**Comment by matt-FFFFFF** [comment]
Hi @SvenAelterman it's not possible to customize the DCRs. You'll have to create your own and pass them in to the policies as parameters.

**Comment by SvenAelterman** [comment]
@matt-FFFFFF Is there guidance for that? The DCR should be created before the module runs (so that the DCR ID is known) but at the same time, the module creates the resource groups where you might want to deploy the custom DCR.
