### ISSUE TITLE
v6.0.0 has ContainerInsights log analytics solution being removed, which results in tables needed by current Container Insights deployments to be deleted

### ISSUE THREAD

**Issue by eehret** [Azure/terraform-azurerm-caf-enterprise-scale#1030]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
1.8.5

**azure provider**:
3.111.0

**module**:
6.0.0

#### Describe the bug

With v.6.0.0, a slew of log analytics solutions are marked for removal.   Some of these are understood to be deprecated and that's fine, but the 'containerinsights' one in particular is concerning us.  This seems to indicate that, while prometheus managed service is now an option that could replace it, ContainerInsights is still a valid and supported option: https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-overview

We followed Microsoft's guidance to transition from the old "Container Monitoring Solution" to Container Insights, and now we are concerned that this recent change in the CAF terraform might break our AKS container insights setup if we allow it to remove the "ContainerInsights" LA solution (which results in removal of a bunch of required tables)

I'm hoping someone can clarify this for us :)

#### Steps to Reproduce

n/a

#### Screenshots

n/a

**Comment by eehret** [comment]
Btw, I do have a 'Plan B' here in case the behaviour here is deemed correct by design.  I could simply remove those resources from the Terraform back end state and then they would be ignored going forward.

But clarification would still be helpful I think, not just for myself but potentially for others as well who are wondering the same thing.

**Comment by eehret** [comment]
Update:  We have the same question for the 'VMInsights' solution

**Comment by matt-FFFFFF** [comment]
We plan to re-instate VM and container insights in the next release. Apologies!

**Comment by eehret** [comment]
@matt-FFFFFF No problem , thanks for the information and all your efforts :)
