### ISSUE TITLE
[Feature Request] lifecycle ignore_changes

### ISSUE THREAD

**Issue by Greg-Court** [Azure/terraform-azurerm-caf-enterprise-scale#1047]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Lack of lifecycle ignore_changes for resources & resource groups.

#### Describe the solution you'd like

I know this has been suggested before, but when bootstrapping a customer environment via the terraform CAF Enterprise scale module, if the customer starts adding tags on the resources before the deployment is finalised, is the only option to manually add all the tags for their resources to avoid overwriting their tags, or is there another workaround for this?

**Comment by matt-FFFFFF** [comment]
We cannot parameterize this and expose it to the caller.

This is a limitation of Terraform core. Hopefully the work that is going on at OpenTofu (I believe they are working on addressing this) will also be realised in TF core
