### ISSUE TITLE
Feature Request: add a way to override name of the resource group created by the management resources.

### ISSUE THREAD

**Issue by ofbjansen** [Azure/terraform-azurerm-caf-enterprise-scale#105]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
I am not sure if I can set this up, but I would like to change the name of the management resource group created by the module to be able to fit our naming convention.

The current behaviour is  a resource group with the name <id>-mgmt.

It would be awesome to have it fit in with the azurecaf_name and azurecaf_naming_convention modules.

**Additional context**

**Comment by krowlandson** [comment]
Thank you for your request @ofbjansen.

You are currently able to do this with the following example configuration:

```hcl
module "caf-enterprise-scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.3.1"

  root_parent_id = var.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name

  library_path = "${path.root}/lib"

  deploy_core_landing_zones = true

  deploy_management_resources = true
  subscription_id_management = "00000000-0000-0000-0000-000000000000"
  configure_management_resources = {
    settings = {
      log_analytics = {
        enabled = true
        config = {
          retention_in_days                           = 30
          enable_monitoring_for_arc                   = true
          enable_monitoring_for_vm                    = true
          enable_monitoring_for_vmss                  = true
          enable_solution_for_agent_health_assessment = true
          enable_solution_for_anti_malware            = true
          enable_solution_for_azure_activity          = true
          enable_solution_for_change_tracking         = true
          enable_solution_for_service_map             = true
          enable_solution_for_sql_assessment          = true
          enable_solution_for_updates                 = true
          enable_solution_for_vm_insights             = true
          enable_sentinel                             = true
        }
      }
      security_center = {
        enabled = true
        config = {
          email_security_contact             = "security_contact@replace_me"
          enable_defender_for_acr            = true
          enable_defender_for_app_services   = true
          enable_defender_for_arm            = true
          enable_defender_for_dns            = true
          enable_defender_for_key_vault      = true
          enable_defender_for_kubernetes     = true
          enable_defender_for_servers        = true
          enable_defender_for_sql_servers    = true
          enable_defender_for_sql_server_vms = true
          enable_defender_for_storage        = true
        }
      }
    }
    location = null
    tags     = null
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          name = "custom-rsg-name"
        }
      }
    }
  }
}
```

Hopefully this will give you the flexibility you're looking for.

> **Note:** You can use this approach to modify the name and some other settings for each of the resource types deployed by the management child module, including:
> - azurerm_resource_group
> - azurerm_log_analytics_workspace
> - azurerm_log_analytics_solution
> - azurerm_automation_account
> - azurerm_log_analytics_linked_service

We're undecided on whether to document this feature in the Wiki, and as this is still in early development we may provide a slightly different experience in the future. Please keep this in mind if you're using this in a production environment. Any changes to impact this will be clearly documented in the release notes, and `terraform plan` will always make you aware of these changes when moving from one minor release to another (e.g. `0.3.1` to `0.4.0`).

I will also take this to the team to see their thoughts on integrating this module with the azurecaf_name and azurecaf_naming_convention modules.

**Comment by ofbjansen** [comment]
This is exactly what I am looking for.

Curious what else can be done with the advanced variable, but probably will be documented in feature releases.

Thanks.
