### ISSUE TITLE
Bug Report: deploy_diagnostics_for_mg generates invalid az_api call

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/terraform-azurerm-caf-enterprise-scale#1052]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.9.2

**azure provider**: 3.113.0

**module**: 6.0.0

#### Describe the bug

When setting `deploy_diagnostics_for_mg` to true, it uses resources_management_groups.tf:85, which attempts to set a `location` property which doesn't exist.

#### Steps to Reproduce

1. Set `deploy_diagnostics_for_mg` to `true`

**Comment by matt-FFFFFF** [comment]
closed by #1053
