### ISSUE TITLE
Query : Possible to add multiple subscriptions under connectivity management group?

### ISSUE THREAD

**Issue by kiranmanohar-manohar** [Azure/terraform-azurerm-caf-enterprise-scale#1085]
### Community Note

We use Enterprise CAF, and when we deployed enterprise can, default subscription under connectivity management group is created. I have got a request to move multiple subscriptions under connectivity management group.

### Description

Is it possible to add multiple subscriptions under connectivity management group? If yes, How can we move those subscriptions under connectivity management group? If I move manually, will it create any issue when I upgrade CAF module? As we use terraform to deploy our enterprise car

**Comment by jtracey93** [comment]
Hey @kiranmanohar-manohar,

You should be able to add more subscriptions beneath the connectivity management group using the [`subscription_id_overrides` input variable](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale#-subscription_id_overrides)

something like this:

```tf
# other module declaration and config
...
subscription_id_overrides = {
    connectivity           = ["xxxxxx-xxx-xx-xxx-xxxxxx", "yyyy-y-yyyy-yyyyyy-yyyyy"]
}
... 
# other module declaration and config
```

**Comment by kiranmanohar-manohar** [comment]
@jtracey93  thank you
