### ISSUE TITLE
Bug Report: root_name limited to 24 characters, should be 90

### ISSUE THREAD

**Issue by Arhughes14** [Azure/terraform-azurerm-caf-enterprise-scale#1089]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Describe the bug

The variable root_name for management groups is limited to 24 characters. Please amend the validation check to a max character limit of 90 as per the resource name restrictions documentation

#### Steps to Reproduce

1. In the variables.tf file in the enterprise_scale folder, change the condition on line 29 to a max character limit of 90.

#### Screenshots

![image](https://github.com/user-attachments/assets/38e4de7c-f85b-4010-93cf-69866962f61b)

![image](https://github.com/user-attachments/assets/c49294cd-d2e5-4fe9-9091-64bb2b9c8b2d)

**Comment by Poltergeisen** [comment]
Just spitballing here, is it possible that this is limited because of other resource naming being limited?

I've seen the root name prepended to some resource names so I'm not sure if this is intentional or not.

**Comment by Arhughes14** [comment]
Possibly, I could be a character limit when using the Azure API's to deploy the resources by code, however this isn't restricted in the portal and doesn't cause other resources to fail due to character limits

**Comment by matt-FFFFFF** [comment]
The limit is low, but was designed so that it could be prepended to the other MG names and still be within the 90 chars.

We shouldn't allow the root name to be 90 I don't think. What would be a sensible compromise?

**Comment by Arhughes14** [comment]
That makes sense, the customer I’m working with would need 35 characters but don’t imagine many customers would need much more then that
