### ISSUE TITLE
Upgrade from 0.2.0 > 0.3.0 breaking on Automation Account linking

### ISSUE THREAD

**Issue by grtn316** [Azure/terraform-azurerm-caf-enterprise-scale#109]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 0.14.8

**azure provider**: >= 2.46.1

**module**: 0.3.0

### Description

When upgrading from 0.2.0 to 0.3.0, I am presented with the following error:

```
Error: creating Linked Service 'main-la/Automation' (Resource Group "main-mgmt"): operationalinsights.LinkedServicesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Automation account not found"

  on .terraform/modules/custom_root_id/resources.management.tf line 75, in resource "azurerm_log_analytics_linked_service" "enterprise_scale":
  75: resource "azurerm_log_analytics_linked_service" "enterprise_scale" {

```

The deployment fails when trying to delete the automation account and fails to unlink it from the workspace....preventing the new automation account from getting linked to the workspace.

1. Deploy module version 0.2.0
2. Deploy module version 0.3.0

Example code [here](https://github.com/grtn316/ESLZTFPipelining)

**Comment by krowlandson** [comment]
Thank you for reporting this @grtn316... as discussed offline, I believe this is due to a missing dependency within the module, allowing the automation account to be recreated without recreating the other dependent resources.

We will test this and try to add a fix to the next release.
