### ISSUE TITLE
Bug Report upgrading from v5.2.0 to v6.0.0.0 produces ChainedTokenCredential authentication failed Microsoft.Insights/dataCollectionRules

### ISSUE THREAD

**Issue by anwarnk** [Azure/terraform-azurerm-caf-enterprise-scale#1092]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.94

**azure provider**:  v3.116.0

**module**: 6.0.0

#### Describe the bug

Upgrade from v5.2.0 to v6.0.0 errors with:

 Error: Failed to retrieve resource
│ 
│   with module.enterprise_scale.azapi_resource.data_collection_rule["/subscriptions/***/resourceGroups/bhamdev-mgmt/providers/Microsoft.Insights/dataCollectionRules/bhamdev-dcr-defendersql-prod"],
│   on .terraform/modules/enterprise_scale/resources.management.tf line 158, in resource "azapi_resource" "data_collection_rule":
│  158: resource "azapi_resource" "data_collection_rule" {
│ 
│ checking for presence of existing Resource: (ResourceId
│ "/subscriptions/***/resourceGroups/bhamdev-mgmt/providers/Microsoft.Insights/dataCollectionRules/bhamdev-dcr-defendersql-prod"
│ / Api Version "2021-04-01"): ChainedTokenCredential authentication failed
│ GET http://169.254.169.254/metadata/identity/oauth2/token
│ --------------------------------------------------------------------------------
│ RESPONSE 400 Bad Request
│ --------------------------------------------------------------------------------
│ {
│   "error": "invalid_request",
│   "error_description": "Identity not found"
│ }

This is also true for the other data rule collections see attachment.

#### Steps to Reproduce

1. Chnage module version in main.tf to v6.0.0
2. Plan executes fines
3. Errors on apply 

#### Additional context

We have added the azapi provider to:

*redacted
```terraform
    azapi = {
      source  = "Azure/azapi"
      version = ">= 1.13.1"
    }
```
[│ Error Failed to retrieve resource.txt](https://github.com/user-attachments/files/16675999/Error.Failed.to.retrieve.resource.txt)

**Comment by matt-FFFFFF** [comment]
Hi this is not a module issue, please disable MSI auth in the provider.

**Comment by anwarnk** [comment]
That worked, thanks!
