### ISSUE TITLE
Broken Wiki Links

### ISSUE THREAD

**Issue by sissonsrob** [Azure/terraform-azurerm-caf-enterprise-scale#1094]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.7.0

**azure provider**: 3.65.0

**module**: 6.0.0

#### Describe the bug

Broken links in wiki since rename of files

#### Steps to Reproduce

1. Navigate to the wiki
2. Select any link which refers to multi-region networking with custom settings (hub/spoke and vwan) - including side bar
3. links are broken and send you 'home'

#### Screenshots

n/a

#### Additional context

looks like the files were renamed in this commit but the links on the sidebar and other pages were not updated.

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/commit/b7bff069ad321d329a6090231eac2fd0dd95d83e

~~I have raised a PR to fix the links but there may also be a desire to rename the link descriptions?~~

I tried to raise a PR but the bot didn't trigger and I received an error advising that I aren't a collaborator :/

**Comment by AndrewBatchelorWpp** [comment]
I also observed this issue, 
the broken link is:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Virtual-WAN-Resources-With-Custom-Settings

I found this page, which I assume is the missing one:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/docs/wiki/%5BExamples%5D-Deploy-Virtual-WAN-Multi-Region-With-Custom-Settings.md

**Comment by sissonsrob** [comment]
Yes, sorry I didn't add the full details above because I had intended on linking my PR - can anyone help with how I can trigger the bot to become a collaborator so I can submit the PR from my fork?

Otherwise the two broken links are:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Virtual-WAN-Multi-Region-With-Custom-Settings

and 

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Multi-Region-Networking-With-Custom-Settings

These two pages are referenced in the following places which need to have their links updated at the bottom of the pages to fix:

docs/wiki/Examples.md
docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
docs/wiki/[Examples]-Deploy-Multi-Region-Networking-With-Custom-Settings.md
docs/wiki/[Examples]-Deploy-Virtual-WAN-Multi-Region-With-Custom-Settings.md
docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md
docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-orchestration.md
docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-remote-state.md
docs/wiki/_Sidebar.md

**Comment by matt-FFFFFF** [comment]
closed by #1110
