### ISSUE TITLE
Bug Report: TFC error with federated credntials and DCR ressource in management module example

### ISSUE THREAD

**Issue by mrcljnff1** [Azure/terraform-azurerm-caf-enterprise-scale#1103]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
1.9.5

**azure provider**:
~> 3.107

**module**:
6.0.0

#### Describe the bug

After deploy management module example with TFC (App registration + OIDC used), after the next run i get this error:

![error](https://github.com/user-attachments/assets/aa81dd4e-e438-43f1-a2fd-7cf2a31316b5)

#### Steps to Reproduce

1. GitHub Repo connection with TFC
2. Appregistration in Azure with federated credentials
3. push management module example and run apply
4. Change a ressource or add any ressource to code and run again. 
5. Plan gets an error

**Comment by matt-FFFFFF** [comment]
This is an issue with the provider authentication - suggest raising an issue on the azapi repo
