### ISSUE TITLE
private_endpoint_network_policies_enabled no longer exists

### ISSUE THREAD

**Issue by michael-brown-22** [Azure/terraform-azurerm-caf-enterprise-scale#1109]
The variable used in the file [resources.connectivity.tf](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/resources.connectivity.tf) "private_endpoint_network_policies_enabled" no longer exists on the specified AzureRM provider version for release 6.0.0. It is now "private_endpoint_network_policies" as detailed on the AzureRM documentation https://registry.terraform.io/providers/hashicorp/azurerm/3.107.0/docs/resources/subnet#private_endpoint_network_policies

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/e4850a207acc90b46a208f0457d0be396b9952d8/resources.connectivity.tf#L58C3-L58C44

I was unable to create a branch to contribute this change back.

**Comment by kzap** [comment]
would it be possible to backport this into the 5.x version?
