### ISSUE TITLE
Deployment orders to follow for Advanced (Level 300)

### ISSUE THREAD

**Issue by sumanbikram** [Azure/terraform-azurerm-caf-enterprise-scale#1113]
I'm in the process of configuring a landing zone using Advanced (Level 300). Is there any particular order for the deployment mentioned below? I will go with Hub and spoke. 

**Advanced (Level 300)**

1. Deploy connectivity resources with custom settings (Hub and Spoke)
2. Deploy connectivity resources with custom settings (Virtual WAN)
3. Deploy identity resources with custom settings
4. Deploy management resources with custom settings
5. Expand built-in archetype definitions
6. Create custom policies, policy sets and assignments
7. Override module role assignments
8. Deploy policies without enforcing them

**Comment by matt-FFFFFF** [comment]
The approach seems sound to me
