### ISSUE TITLE
Feature Request How can create an other "managment" workspace analytics in multiple region

### ISSUE THREAD

**Issue by 8ast1en** [Azure/terraform-azurerm-caf-enterprise-scale#1128]
**Hi Guys,**

I would like create a other workspace analytics ["management"] in a other region. 

Actually I've my principal workspace in France central and I want to create an other workspace in West Europe for example.

Please can you tell me if it's possible or not ? And if it's possible a little tips please :)

Thanks a lot in advance 👍

**Comment by JamesDLD** [comment]
According to this [announcement](https://techcommunity.microsoft.com/t5/azure-governance-and-management/announcing-zone-redundancy-and-multi-region-capabilities-in/ba-p/4170742?WT.mc_id=AZ-MVP-5003548) the Terraform Module will be zone redundant by default by default by end of calendar year 2024.

**Comment by matt-FFFFFF** [comment]
Hi, unfortunately we will not support deploying multiple azure monitor logs workspaces.

You'll have to deploy it outside the module and assign policy yourself.
