### ISSUE TITLE
Why Doesn't Corp and Online Get Deployed In the Base Configuration?

### ISSUE THREAD

**Issue by briantaylor87** [Azure/terraform-azurerm-caf-enterprise-scale#1129]
I've noticed that the core resource deployment documentation shows the management group structure pictured here: 

![image](https://github.com/user-attachments/assets/efeab6e0-c819-407a-b4d6-6df879d906df)

But deploying the Module as is will not deploy the Corp or Online management groups. Am I missing a specific configuration flag? I've had to add them in as custom landing zones using the appropriate archtype configs: 

![image](https://github.com/user-attachments/assets/332f5e1f-808a-4aa3-bfbf-f4f4c326867e)

**Comment by matt-FFFFFF** [comment]
Hi,

They can be deployed, see the `deploy_corp_landing_zones` flag, and the other one for online.
