### ISSUE TITLE
Cannot deploy module without core landing zones

### ISSUE THREAD

**Issue by tohov** [Azure/terraform-azurerm-caf-enterprise-scale#113]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 15.4

**azure provider**: >=2.41.0

**module**: 0.3.1

### Description

**Describe the bug**

I cannot seem to deploy the module using just custom_landing_zones config block and /lib folder for custom archetype definitions. Terraform plan throws an error saying that policy (set) definition could not be found.

I'm under impression that 

**Steps to Reproduce**

1. Make sure there are no previous policy definitions deployed by this module before trying to reproduce
2. Set deploy_core_landing_zones = false
3. Create /lib folder
4. Create a file "archetype_definition_custom_root.json" and paste in the skeleton/empty archetype definition
5. Add for example all the contents of built-in es_root archetype
6. Rename the archetype from _"default_empty": {..._  -->  _"es_custom": {..._
7. Create one custom landing zone (with any naming) below the Tenant Root Group
8. Use es_custom archetype as archetype_id in the custom landing zone

Terraform plan should result in error stating that the policy definitions are not found and refers to the locals.policy_assignments.tf file in the "external_lookup" section(s) at line(s) 90 and/or 152.

**Screenshots**

![image](https://user-images.githubusercontent.com/38506856/119339748-3bd91500-bc9a-11eb-8453-0516f27ac4e4.png)
![image](https://user-images.githubusercontent.com/38506856/119339809-53180280-bc9a-11eb-8e92-047513cc6bf8.png)

**Additional context**
Use case: deploy totally custom management group hierarchy for example in case of Company Group + subsidiaries. Like to have all the subsidiaries and the main group at the same management group level and then build custom structure under those companies.

Also would like to define custom archetypes to use with the custom landing zones by defining them in the lib folder and to copy all the existing policy definitions from the es_root to my "custom_root" archetype definition.

I'd like to understand if this use case is achievable with this module. As MSP I'd like to see the module logic to perform separately from the customer specific configurations so that I can have all the customers using your module but with customer specific custom management groups structures and custom archetypes and not to deply the core landing zones at all.

**Comment by tohov** [comment]
I just tried to deploy core landing zones plus one custom landing zone. Then remove core landing zones and leave the custom. I get the same error(s).

**Comment by krowlandson** [comment]
Hi @tohov... thank you for logging your issue. This is definitely possible.

Just to set out a working example, please try the following which I believe addresses your scenario:

File: `main.tf`

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.41.0"
    }
    time = {
      source  = "hashicorp/time"
      version = ">= 0.7.0"
    }
  }
}

provider "azurerm" {
  subscription_id = "b472fb3a-8b1f-4494-bfdb-5f2f380d04f8"
  features {}
}

data "azurerm_client_config" "current" {
}

locals {
  root_id          = "msp-demo"
  root_name        = "Custom Root"
  default_location = "uksouth"
}

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.3.1"

  # Base module configuration settings.
  root_parent_id   = data.azurerm_client_config.current.tenant_id
  root_id          = local.root_id
  root_name        = local.root_name
  library_path     = "${path.root}/lib"
  default_location = local.default_location

  # Configure deployment of core landing zones
  deploy_core_landing_zones = false

  # Configuration settings for custom landing zones
  custom_landing_zones = {
    "${local.root_id}" = {
      display_name               = local.root_name
      parent_management_group_id = data.azurerm_client_config.current.tenant_id
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "custom_root"
        parameters     = {}
        access_control = {}
      }
    }
  }

  # The following is just to make the demo deployment complete
  # faster as we don't have any real dependencies.
  create_duration_delay = {
    azurerm_management_group      = "0s"
    azurerm_policy_assignment     = "0s"
    azurerm_policy_definition     = "0s"
    azurerm_policy_set_definition = "0s"
    azurerm_role_assignment       = "0s"
    azurerm_role_definition       = "0s"
  }

}
```

File: `lib/archetype_definition_custom_root.json`

```json
{
    "custom_root": {
        "policy_assignments": [],
        "policy_definitions": [],
        "policy_set_definitions": [],
        "role_definitions": [],
        "archetype_config": {
            "parameters": {},
            "access_control": {}
        }
    }
}
```

A couple of points to note:

- You must always ensure that each of your `custom_landing_zones` are configured to use a `parent_management_group_id` that either already exists or is deployed by this module. For the "custom root" in your scenario, the `parent_management_group_id` must also match the `root_parent_id` value set in the module block.
- When creating a completely custom hierarchy, the module logic still relies on you setting a valid `root_id` value. If this is being deployed using `custom_landing_zones`, you must ensure your "custom root" Management Group ID matches the ID provided to the module through `root_id`.

I believe this should address your issue, even when adding values into the archetype definition, but please remember to ensure that all dependencies between policies must also be met, such as:

- Policy Assignments to Policy Definitions
- Policy Assignments to Policy Set Definitions
- Policy Set Definitions to Policy Definitions

When building a custom archetype definition, the resource templates within the module are designed on the basis that you create all of your definitions at the scope of `root_id`. This is an Enterprise-scale design pattern which ensures they're available for assignment anywhere beneath this scope, whilst still allowing for exceptions to be created elsewhere under the `Tenant Root Group`. You can change this behaviour, but this requires configuring more complex template variables within the template files, and using the `template_file_variables` input variable to inject these into the `templatefile()` function when loading these. As such, we would advise against this.

Hope this helps, and please let us know how you get on!

**Comment by tohov** [comment]
Thank you! I believe in the habit of defining the policy definitions at the scope of `root_id`. I do not wish to break that. Also worth mentioning that I got it working the way I wanted as you said it would be possible.

I bumped into another problem but will raise an separate issue on that one.

**Comment by krowlandson** [comment]
Great, I'll close this issue and keep a look out for your new one.
