### ISSUE TITLE
Possible to customize content of the provided DCRs?

### ISSUE THREAD

**Issue by eehret** [Azure/terraform-azurerm-caf-enterprise-scale#1133]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

This is really more of a question than a feature request.   I'm just wondering if it's technically possible to customize the content of the provided DCRs.   We have a requirement to alter the DCR for VM Insights for additional log collection.  One way would be to set the module to NOT produce the DCR, and then customize the related policy assignment parameters to bring in our own DCR but I'm wondering if there's an alternate way to customize it.

**Comment by matt-FFFFFF** [comment]
Not with this module, you can supply your own to the policy as a parameter if you would like to
