### ISSUE TITLE
Race condition results in InternalServerError when deploying in vhub a firewall, an express route gateway, vhub peering and routing intent

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-azurerm-caf-enterprise-scale#1135]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.9.4

**azure provider**: 3.108.0

**module**: 6.1.0

#### Describe the bug

When deploying the virtual hub connectivity services with an Azure firewall, an express route gateway, routing intent and vhub connections the deployment ends-up with an InternalServerError and deployment time and destroy time.

#### Steps to Reproduce

enable vwan
enable vhub
enable firewall (secure hub)
enable routing intent
peer existing vnets to the hub
apply

#### Screenshots

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/a0078c9e-cd59-4648-ab55-993406a18271">

#### Additional context

By adding a depends_on azurerm_express_route_gateway.virtual_wan to the azurerm_virtual_hub_connection and azurerm_virtual_hub_routing_intent I managed to fix the deploy and destroy issues described above. 
I am going to submit the PR.

**Comment by matt-FFFFFF** [comment]
Thank you @LaurentLesle

**Comment by matt-FFFFFF** [comment]
Released in v6.2.0
