### ISSUE TITLE
Document the benefits and use of template_file_variables

### ISSUE THREAD

**Issue by tohov** [Azure/terraform-azurerm-caf-enterprise-scale#114]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

I'm trying to use the module as effectively as it can be, but the lack of more extensive documentation is at least holding me back to understand all the configuration options in depth. `template_file_variables` is an input option that I haven't yet understood why and where to use. Please enhance the wiki documentation on this part.

**Describe the solution you'd like**
Humbly asking enhancing the wiki documentation for the use of `template_file_variables`. Use cases and why and how should we use this?

**Additional context**

**Comment by krowlandson** [comment]
Definitely planning to add this, but for now please take a look at #104 and let me know whether that helps?

**Comment by tohov** [comment]
I read through that issue. Yes. Makes sense now how to use it and already had thoughts about using this in the future after giving it a test run with something fairly simple first. Thank you again!

**Comment by krowlandson** [comment]
Should be addressed now, as per #104
