### ISSUE TITLE
Feature Request: Default to cost-conscious settings or warn users about the cost of the current default settings. 

### ISSUE THREAD

**Issue by c4milo** [Azure/terraform-azurerm-caf-enterprise-scale#1141]
We discovered the hard way how expensive the default management settings are. A warning about it or defaulting to more cost-conscious settings would be highly desired. Here are some of the things we did in case it helps others: 

1. Disabled Sentinel
2. Put a daily cap on the Log Analytics ingestion (although we ran into https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/1143)
3. Disabled most Azure Diagnostics and Security features 

We plan to re-enable those features once we understand better the cost implications and how to keep them under control.

**Comment by anwarnk** [comment]
Is this for v6.1?

**Comment by matt-FFFFFF** [comment]
I'm sorry you had an unexpected bill. Our strategy with these modules is to set customers up for security and availability by default so we will be moving in the opposite direction.

One thing we could do is publish an example with a test/dev configuration that didn't have all the bells and whistles.

**Comment by chrishawl** [comment]
> I'm sorry you had an unexpected bill. Our strategy with these modules is to set customers up for security and availability by default so we will be moving in the opposite direction.
> 
> One thing we could do is publish an example with a test/dev configuration that didn't have all the bells and whistles.

Hello. A dev/test example would be great. I'm currently looking at how we would deliver this iteratively, so as a first pass it would be great to have an example that say just setup the management groups and some archetypes, with just a single baseline policy set definition like the Microsoft security benchmark.

It'd be good to have a view on how you say moved from just management group setup into basic governance, followed by defender enablement and then log analytics onboarding.

**Comment by matt-FFFFFF** [comment]
#1143 is now merged, I hope this helps in the future. We will consider the dev test example
