### ISSUE TITLE
Deployment of Management resources errors out: Invalid value for module argument

### ISSUE THREAD

**Issue by tohov** [Azure/terraform-azurerm-caf-enterprise-scale#116]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 0.15.4

**azure provider**: v2.59.0

**module**: 0.3.2

### Description

When deploying management resources Terraform throws an error: `Error: Invalid value for module argument` `The given value is not suitable for child module variable
"configure_management_resources" defined at .terraform/modules/landing-zone/variables.tf:57,1-42: attributes "advanced", "location", and "tags" are required.`

**Steps to Reproduce**

1. Set all the traditional variables like `root_parent_id`, `root_id`, `root_name`, `default_location` etc.
2. Set `deploy_management_resources` to `true`
3. Set `subscription_id_management` to `data.azurerm_client_config.current.subscription_id`
4. Configure management resources
```
configure_management_resources = {
    settings = {
      log_analytics = {
        enabled = true
        config = {
          retention_in_days                           = 30
          enable_monitoring_for_arc                   = true
          enable_monitoring_for_vm                    = true
          enable_monitoring_for_vmss                  = true
          enable_solution_for_agent_health_assessment = true
          enable_solution_for_anti_malware            = true
          enable_solution_for_azure_activity          = true
          enable_solution_for_change_tracking         = true
          enable_solution_for_service_map             = true
          enable_solution_for_sql_assessment          = true
          enable_solution_for_updates                 = true
          enable_solution_for_vm_insights             = true
          enable_sentinel                             = true
        }
      }
      security_center = {
        enabled = true
        config = {
          email_security_contact             = "firstname_lastname@domain.com"
          enable_defender_for_acr            = true
          enable_defender_for_app_services   = true
          enable_defender_for_arm            = true
          enable_defender_for_dns            = true
          enable_defender_for_key_vault      = true
          enable_defender_for_kubernetes     = true
          enable_defender_for_servers        = true
          enable_defender_for_sql_servers    = true
          enable_defender_for_sql_server_vms = true
          enable_defender_for_storage        = true
        }
      }
    }
    location = var.default_location
    tags     = null
    advanced = null
  }
  ```

5. Run `terraform plan`

![image](https://user-images.githubusercontent.com/38506856/119668650-0837ef80-be40-11eb-932c-ffbc3f336a6e.png)

**Additional context**

**Comment by grtn316** [comment]
@tohov - your error shows (on line 58):

```
      }
    }
    location = var.default_location
    tags     = null
    advanced = null
  }
}
```

while you code above shows:

```
        }
      }
    }
    location = var.default_location
    tags     = null
    advanced = null
  }
```

I believe the error may be related to your brackets.

**Comment by tohov** [comment]
Thanks. Been working on this for too many hours. I some how had the location, tags and advanced inside `configure_management_resources.settings`. Once moved them out got a different looking error 😄

**Comment by tohov** [comment]
We're okay to close.
