### ISSUE TITLE
Question - should Decomm & Sandbox policies be in the root archetype?

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-caf-enterprise-scale#1163]
I spotted these when reviewing policies in the default lib folder, are these supposed to be here?

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/0ae041755b3e1fc41b75d57eb47e22061151d5b1/modules/archetypes/lib/archetype_definitions/archetype_definition_es_root.tmpl.json#L194-L195

Also I note that the lib folder contains deprecated policies such as ``Deploy-MDFC-Config`` replaced by ``Deploy-MDFC-Config_20240319`` - are these kept to assist with transition?

**Comment by falowomi** [comment]
The listed policies "Decomm and Sandbox" are definition sets and yes they're all created in the root management group scope. You would only see assignments of those policies under each corresponding management group files. In short, all policy definitions and set definitions are created on the root level.

For the **MDFC** configs, both the deprecated and current defender policies are created as part of the deployment but if you look in the assignment block of the archetype, you would see that only **Deploy-MDFC-Config_20240319** is assigned.

So you should be good.

**Comment by kewalaka** [comment]
@falowomi yes of course I see now - how silly I was reading the wrong segment of the json file.  Thanks!
