### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kevinevans1** [Azure/terraform-azurerm-caf-enterprise-scale#1164]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.9.7

**azure provider**: ~> 3.107

**module**:6.0

#### Describe the bug

When trying to deploy version 6 of the module using terraform cloud as the back, we receive these errors around data collection rules via the azapi.

#### Steps to Reproduce

1. Terraform Init
2. Terraform Apply
3. Verbose error messages from terraform raw logs.

#### Screenshots

Error: Failed to retrieve resource
with module.enterprise_scale.azapi_resource.data_collection_rule["/subscriptions/sub/resourceGroups/c2c-mgmt/providers/Microsoft.Insights/dataCollectionRules/c2c-dcr-defendersql-prod"]
on .terraform/modules/enterprise_scale/resources.management.tf line 158, in resource "azapi_resource" "data_collection_rule":
resource "azapi_resource" "data_collection_rule" {
checking for presence of existing Resource: (ResourceId "/subscriptions/sub/resourceGroups/c2c-mgmt/providers/Microsoft.Insights/dataCollectionRules/c2c-dcr-defendersql-prod" / Api Version "2021-04-01"): ChainedTokenCredential: failed to acquire a token.
Attempted credentials:
	managed identity timed out
	AzureCLICredential: Azure CLI not found on path

Error: Failed to retrieve resource
with module.enterprise_scale.azapi_resource.data_collection_rule["/subscriptions/sub/resourceGroups/c2c-mgmt/providers/Microsoft.Insights/dataCollectionRules/c2c-dcr-vm-insights"]
on .terraform/modules/enterprise_scale/resources.management.tf line 158, in resource "azapi_resource" "data_collection_rule":
resource "azapi_resource" "data_collection_rule" {
checking for presence of existing Resource: (ResourceId "/subscriptions/sub/resourceGroups/c2c-mgmt/providers/Microsoft.Insights/dataCollectionRules/c2c-dcr-vm-insights" / Api Version "2021-04-01"): ChainedTokenCredential: failed to acquire a token.
Attempted credentials:
	managed identity timed out
	AzureCLICredential: Azure CLI not found on path

#### Additional context

not at this time.

**Comment by matt-FFFFFF** [comment]
Hi,

This is not a module bug, it's due to the AzAPI provider not being able to authenticate. #RR
