### ISSUE TITLE
Make policy library available as module

### ISSUE THREAD

**Issue by simongottschlag** [Azure/terraform-azurerm-caf-enterprise-scale#1168]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi team!

It would be amazing if all the content of the [archetypes library](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/modules/archetypes) that you are keeping up-to-date could be exported using a terraform module to be consumed by others outside of this module. Right now, you need to pass settings to it and get different results based on it.

But if we want to incorporate this into our modules, it would be amazing if we could get everything without any conditions or settings and handle that on our side instead.

If this is already possible, please help me understand how.

Thank you for your fantastic work!

**Comment by matt-FFFFFF** [comment]
Hi!

Have you seen this? https://github.com/Azure/Azure-Landing-Zones-Library/tree/main/platform/alz

For the next version of the terraform module we are decoupling the policy library from the module and provider.

Please checkout the module: avm-ptn-alz, which is currently in beta but will be moving to GA very soon.

**Comment by simongottschlag** [comment]
> Hi!
> 
> Have you seen this? https://github.com/Azure/Azure-Landing-Zones-Library/tree/main/platform/alz
> 
> For the next version of the terraform module we are decoupling the policy library from the module and provider.
> 
> Please checkout the module: avm-ptn-alz, which is currently in beta but will be moving to GA very soon.

Hey Matt!

I think this is exactly what we are looking for. Thanks! 🙏
