### ISSUE TITLE
Destroying the ES LZ module does not destroy all management resources

### ISSUE THREAD

**Issue by tohov** [Azure/terraform-azurerm-caf-enterprise-scale#117]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 0.15.4

**azure provider**: 2.59.0

**module**: 0.3.2

### Description

**Describe the bug**
Running `terraform plan -destroy` and applying the destroy does not destroy all management resources. I ran the terraform destroy from TF cloud (see screenshot below). For my scenario destroying left behind the resource group `${var.root_id}-asc-export`

**Steps to Reproduce**

1. Deploy landing zones with management resources. `deploy_managment_resources` = `true`
2. Set `configure_management_resources.settings.log_analytics.enabled` = `true`
3. Set `configure_management_resources.settings.security_center.enabled` = `true`
4. Verify that all the resources were deployed
5. Queue destroy plan
6. Verify leftover resources after destruction

**Screenshots**
TF Cloud destroy command
![image](https://user-images.githubusercontent.com/38506856/119716935-5c59c880-be6e-11eb-8bbf-2c84e5b9eed6.png)

azure cli rg list after destroy
![image](https://user-images.githubusercontent.com/38506856/119718044-c45cde80-be6f-11eb-92d8-7fbaef779748.png)

**Additional context**
I would expect all the resources to be destroyed. I consider this to be low prio issue that only shows up mostly when playing around with LZ deployments.

**Comment by krowlandson** [comment]
Interesting observation and thank you for raising this. This resource group (and the hidden resource within for ASC Export) is created by a DeployIfNotExists policy which is why Terraform doesn't destroy it. We're considering adding these to the scope of resources managed by the module which will resolve this issue.

**Comment by krowlandson** [comment]
@tohov... we've been discussing this further and would appreciate your feedback please.

The concerns we've raised with making this change are as follows:

1. If we add this Resource Group and Resource to the module, it will require users to either delete or import the existing instance (created by Policy) before being able to successfully run the next `terraform apply`.
2. As this Policy is assigned across ALL Azure Subscriptions within the ES management group hierarchy, these resources will be created in all Subscriptions. As Terraform can only manage resource in a single Subscription (per provider instance), it won't be practical to manage these resources at scale using Terraform.

I cannot find the issue where this was previously discussed, but the second point above is also why this resource is created in a dedicated Resource Group, and not alongside the other "management resources" (which wouldn't exist in any Subscriptions other than `Management`).

On this basis, I would like to propose that we close this issue but track it as something we need to improve documentation covering "unmanaged resources created by Azure Policy, not Terraform".

**Comment by tohov** [comment]
@krowlandson That will work for me. I think as long as the documentation is clear on separating the different lifecycles (others managed by the Terraform and others that are independent of Terraform) there is no change that needs to be made, especially considering the points that you brought up.

**Comment by krowlandson** [comment]
Great stuff, thank you for confirming. We will close this issue now.
