### ISSUE TITLE
Feature Request - Ability to add lifecycle to ignore tag changes

### ISSUE THREAD

**Issue by scottbrewerton-cardfactory** [Azure/terraform-azurerm-caf-enterprise-scale#1172]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Could we have a way to add/apply lifecycle rules to ignore tag changes on subsequent Terraform pipeline runs?

#### Is your feature request related to a problem?

We have a set of mandatory tags that are applied to our Azure Terraform CAF deployment. One of these tags contains the timestamp that the deployed item is created. As a result of this, every subsequent run of TF detects the new timestamp and tries to modify the tags for deployed items.

Specifically this is impacting the Private DNS zones created by the connectivity settings file. Every time the pipeline runs we see masses of output like this:

```
module.alz.azurerm_private_dns_zone_virtual_network_link.connectivity["/subscriptions/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx/resourceGroups/rg-prod-uks-dns-001/providers/Microsoft.Network/privateDnsZones/privatelink.azure-automation.net/virtualNetworkLinks/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx-138faeb6-972b-5bb1-8c6a-xxxxxxxxxxxx"]: Modifications complete after 33s [id=/subscriptions/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx/resourceGroups/rg-prod-uks-dns-001/providers/Microsoft.Network/privateDnsZones/privatelink.azure-automation.net/virtualNetworkLinks/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx-138faeb6-972b-5bb1-xxxx-xxxxxxxxxxxx]


module.alz.azurerm_private_dns_zone_virtual_network_link.connectivity["/subscriptions/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx/resourceGroups/rg-prod-uks-dns-001/providers/Microsoft.Network/privateDnsZones/privatelink.siterecovery.windowsazure.com/virtualNetworkLinks/79b947c4-5831-458a-8824-a249b65df2f5-15b18972-ad61-5886-xxxx-xxxxxxxxxxxx"]: Modifying... [id=/subscriptions/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx/resourceGroups/rg-prod-uks-dns-001/providers/Microsoft.Network/privateDnsZones/privatelink.siterecovery.windowsazure.com/virtualNetworkLinks/79b947c4-5831-458a-8824-a249b65df2f5-15b18972-ad61-5886-xxxx-xxxxxxxxxxxx]


module.alz.azurerm_private_dns_zone_virtual_network_link.connectivity["/subscriptions/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx/resourceGroups/rg-prod-uks-dns-001/providers/Microsoft.Network/privateDnsZones/privatelink.monitor.azure.com/virtualNetworkLinks/79b947c4-5831-458a-8824-a249b65df2f5-15b18972-ad61-5886-xxxx-xxxxxxxxxxxx"]: Still modifying... [id=/subscriptions/8098e6e4-2d0d-43ac-xxxx-...5-15b18972-ad61-5886-xxxx-xxxxxxxxxxxx, 10s elapsed]


module.alz.azurerm_private_dns_zone_virtual_network_link.connectivity["/subscriptions/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx/resourceGroups/rg-prod-uks-dns-001/providers/Microsoft.Network/privateDnsZones/privatelink.eventgrid.azure.net/virtualNetworkLinks/79b947c4-5831-458a-8824-a249b65df2f5-15b18972-ad61-5886-xxxx-xxxxxxxxxxxx"]: Modifying... [id=/subscriptions/8098e6e4-2d0d-43ac-xxxx-xxxxxxxxxxxx/resourceGroups/rg-prod-uks-dns-001/providers/Microsoft.Network/privateDnsZones/privatelink.eventgrid.azure.net/virtualNetworkLinks/79b947c4-5831-458a-8824-a249b65df2f5-15b18972-ad61-xxxx-xxxx-xxxxxxxxxxxx]
```

And it's pushing the pipeline completion time to over 30mins in some cases.

#### Describe the solution you'd like

A way to add/apply something like this to the CAF setup.

```
  lifecycle {
    ignore_changes = [
      tags
    ]
  }
```

**Comment by matt-FFFFFF** [comment]
Hi there. Unfortunately this isn't possible due to limitations in terraform.

The ignore changes values are not strings and cannot be passed in via a module variable. Until this changes in TF we cannot implement. It has been a long requested feature but I do not see any progress. Hence I will have to close this as a won't fix.
