### ISSUE TITLE
Defender for Cloud VM plan 1 or 2

### ISSUE THREAD

**Issue by GokhanAltan1** [Azure/terraform-azurerm-caf-enterprise-scale#1176]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

I would like to manage the Defender for Cloud VM plan. At this moment there is no option to set plan to 1 or 2.

#### Describe the solution you'd like

A parameter in the policy to set the plan version to 1 or 2.

**Comment by falowomi** [comment]
@GokhanAltan1 You can deploy your Defender for Cloud policies using custom configuration and then set the **enable_defender_for_servers** to **false**. This will give you the opportunity to assign a built-in policy in your deployment. See configuration in the link below. 

[**Deploy-Management-Resources-With-Custom-Settings**](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Management-Resources-With-Custom-Settings#settingsmanagementtf)

Now, you need to create a custom policy assignment using the built-in policy name **Configure Microsoft Defender for Servers plan** specifically to MDFC for Server. Follow the instruction provided in the link below to achieve this.

[**Assign-a-Built-in-Policy**](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Assign-a-Built-in-Policy)

Hope that helps

**Comment by matt-FFFFFF** [comment]
This is added in #1201 in the latest policy refresh

**Comment by GokhanAltan1** [comment]
@matt-FFFFFF @falowomi We have upgraded our CAF module to tag version 6.2.0 but cannot find the pollicy assignment "Deploy-MDFC-Config-H324" in it. Is this policy already includes in this CAF version?

**Comment by GokhanAltan1** [comment]
@matt-FFFFFF @falowomi Hello, Is there an update on this? Thanks.
