### ISSUE TITLE
Example for the configure_management_resources 

### ISSUE THREAD

**Issue by skelso01** [Azure/terraform-azurerm-caf-enterprise-scale#118]
At the moment there is no information about the detailed configuration in this section of the documentation. Many points can be guessed what they do.
I would be interested to know what can be configured as "advanced". Can you please give an example here?

Best regards
skelso01

**Comment by jtracey93** [comment]
Hi @skelso01, 

Firstly, thanks for raising this issue. We are indeed working on creating documentation as we speak for the Management sub-module which will include details on the `advanced` block.

For now though @krowlandson provided detail around the `advanced` block on this issue: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/105#issuecomment-841523849 that will hopefully help you here.

Keep and eye out for the upcoming documentation and if you have any questions please feel free to ask them here 👍

Thanks

Jack

**Comment by jtracey93** [comment]
@skelso01 did the link to the other issue help here?

**Comment by skelso01** [comment]
Hi @jtracey93,
sorry for my late answer. Yes this helps. Thx for your help
