### ISSUE TITLE
Is it possible to lower-case the names of Connectivity, Identity, Management, Sandbox and Decommissioned management groups?

### ISSUE THREAD

**Issue by cc-tomswaby** [Azure/terraform-azurerm-caf-enterprise-scale#1204]
Hey all,

I am using 6.1.0 of the module, and have successfully deployed it. However one thing... I want to have my management groups all lower case. The module delivers the Connectivity, Identity, Management, Sandbox and Decommissioned management groups all with capitalised first letters. I know about custom_settings_by_resource_type, but am not sure this involved azurerm_management_group, and if so, im not sure how to force lower case all round.

Can anyone help?

thanks

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

**Comment by matt-FFFFFF** [comment]
Hi @cc-tomswaby 

This isn't possible today without defining the entire management group hierarchy in custom landing zones.

Doing so removes much of the value of this module as it prevents many of the policy parameters from being set correctly.

**Comment by cc-tomswaby** [comment]
Hi Matt,

Thanks for getting back to me so quick. Really appreciate that.

OK cool no problem. Amazing work you guys have done on this module, so thanks!
