### ISSUE TITLE
MDFC is not fully disabled despite setting all parameter values to `false`

### ISSUE THREAD

**Issue by c4milo** [Azure/terraform-azurerm-caf-enterprise-scale#1213]
```
 security_center = {
        enabled = true
        config = {
          # Configure a valid security contact email address
          email_security_contact = var.email_security_contact
          # We are disabling all these while we understand their cost better.
          enable_defender_for_apis                              = false
          enable_defender_for_app_services                      = false
          enable_defender_for_arm                               = false
          enable_defender_for_containers                        = false
          enable_defender_for_cosmosdbs                         = false
          enable_defender_for_cspm                              = false
          enable_defender_for_dns                               = false
          enable_defender_for_key_vault                         = false
          enable_defender_for_oss_databases                     = false
          enable_defender_for_servers                           = false
          enable_defender_for_servers_vulnerability_assessments = false
          enable_defender_for_sql_servers                       = false
          enable_defender_for_sql_server_vms                    = false
          enable_defender_for_storage                           = false
        }
      }
    }
```

![Image](https://github.com/user-attachments/assets/d21492cb-5390-405e-aa36-0c9966f9f194)

### Azure Policy Assignment
<img width="1554" alt="Image" src="https://github.com/user-attachments/assets/3926ad09-3866-4f8d-866e-f63f97a7a821" />

### Versions

**terraform**: v1.9.3

**azure provider**:  "~> 3.84"

**module**: 6.2.0

#### Describe the bug

Despite setting all possible settings to `false` regarding Microsoft Defender, we still are getting billed lots of money for it. 

#### Steps to Reproduce

1. Deploy landing zones with default settings
2. Deploy resources in subscriptions: VMs, containers, etc
3. Set all the above settings to `false`

**Comment by matt-FFFFFF** [comment]
Hi,

This setting controls the policy, which is correctly set. It will not manage the settings on the subscriptions if they are set already. You will have to disable them manually.

**Comment by c4milo** [comment]
@matt-FFFFFF, hm, that's strange, we did not explicitly enable them in the subscriptions.

**Comment by c4milo** [comment]
@matt-FFFFFF, gotcha, that took us by surprise. Thanks!
