### ISSUE TITLE
Unable to create management groups without core management groups.

### ISSUE THREAD

**Issue by basavarajb** [Azure/terraform-azurerm-caf-enterprise-scale#126]
I want to create my own management groups . so that i made deploy_core_landing_zones=false.

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.3.3"

  root_parent_id = data.azurerm_client_config.current.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.root}/lib"
  deploy_core_landing_zones=false
  custom_landing_zones = {
    "${var.root_id}-core" = {
      display_name               = "core"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty" #default_empty
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-work-load" = {
      display_name               = "workload"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {
          Deny-Resource-Locations = {
            listOfAllowedLocations = ["eastus",]
          }
          Deny-RSG-Locations = {
            listOfAllowedLocations = ["eastus",]
          }
        }
        access_control = {}
      }
    }
  }

}

**Comment by jtracey93** [comment]
Hi @basavarajb,

Are there any error messages you can share?

Also have you followed this article here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes

Let us know

**Comment by jtracey93** [comment]
From your config it look like you need to define the landing zone management group that you have set as the parent for the 2 management groups defined. 

Setting 'deploy_core_landing_zones' to 'false' will deploy no enterprise scale management groups. 

So you must define them all. 

If you just want to deploy different management groups beneath the enterprise scale landing zone management group in the hierarchy follow the link I shared above 👍

**Comment by basavarajb** [comment]
I'm trying to deploy the mentioned hierarchy
I dnt need default management group.
![image](https://user-images.githubusercontent.com/9286143/123075678-16286280-d436-11eb-8323-c3832971ff0a.png)

**Comment by jtracey93** [comment]
Hi @basavarajb,

This can be done with the module, however it should be noted this design does not conform with Enterprise Scales critical design areas for the Management Group & Subscription Organization area (as documented here https://docs.microsoft.com/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization).

**I strongly suggest stay close to the Enterprise Scale architecture.**

However, if you want to use to module to achieve your architecture you can do by using the below code which I have just created as a test:

```hcl
# Configure Terraform to set the required AzureRM provider
# version and features{} block.

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.46.1"
    }
  }
}

provider "azurerm" {
  features {}
}

# Use variables to customise the deployment

variable "root_id" {
  type    = string
  default = "core"
}

# Get the current client configuration from the AzureRM provider.
# This is used to populate the root_parent_id variable with the
# current Tenant ID used as the ID for the "Tenant Root Group"
# Management Group.

data "azurerm_client_config" "current" {}

# Declare the Terraform Module for Cloud Adoption Framework
# Enterprise-scale and provide a base configuration.

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.3.3"

  root_parent_id = data.azurerm_client_config.current.tenant_id
  library_path   = "${path.root}/lib"

  deploy_core_landing_zones = false

  custom_landing_zones = {
    "${var.root_id}" = {
      display_name               = "Core"
      parent_management_group_id = data.azurerm_client_config.current.tenant_id
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
    "prod-${var.root_id}" = {
      display_name               = "Prod Core"
      parent_management_group_id = "${var.root_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
    "non-prod-${var.root_id}" = {
      display_name               = "Non-Prod Core"
      parent_management_group_id = "${var.root_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
    "workload" = {
      display_name               = "Workload"
      parent_management_group_id = data.azurerm_client_config.current.tenant_id
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
    "abc-workload" = {
      display_name               = "ABC Workload"
      parent_management_group_id = "workload"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
  }
}
```

However i strongly suggest you follow the Enterprise Scale design as we suggest an intermediate management group so policy definitions and assignments as well a RBAC role definitions and assignments can be stored and place beneath the intermediate management group without duplicating definitions etc. 

The tenant root management group should be left alone apart from a few role assignments for emergency access.

**Comment by jtracey93** [comment]
Hi @basavarajb, 

Did this help and work for you?

Let us know if we can close the issue 👍 

Thanks

Jack

**Comment by jtracey93** [comment]
Hi @basavarajb,

I'm going to close the issue as we haven't heard back from you in a while. 

Please feel free to reopen if required 👍
