### ISSUE TITLE
Can not deploy Enterprise Scale module in Terraform Enterprise in house

### ISSUE THREAD

**Issue by benoitedi** [Azure/terraform-azurerm-caf-enterprise-scale#128]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**Terraform Enterprise**:  v202001-5

**terraform**:  0.15.1+

**azure provider**: 2.65+

**module**: Does not deploy

### Description

**Describe the bug**

We have downloaded the latest at the time (0.3.1) version of Enterprise Scale and are trying to register the module to our own Terraform Enterprise. 
While other module deploy with no issue, this one does not deploy and we can not see any reason in the log why

**Steps to Reproduce**

Install Terraform Enterprise v202001-5
Go to Module and register a new module
Provide information of the VCS setting for you new module 
Enterprise scale is shown as successfully register, but no module is available

**Screenshots**

No screenshot

**Additional context**

This is not a code as per say, but a deployment issue or registration issue of the module within our local TFE (Terraform Enterprise) module registry.
Please not TFE is on version v202001-5.

While we could use directly github registry for the module and this is working on local development boxes, we are not allowed to do so as we need to have the code validated and in house.

**Comment by jtracey93** [comment]
Thanks for reporting this. 

Have you been able to try it with v0.3.3? 

Also do the nested modules (sub-modules) show at all?

Finally are there any logs at all that can be shared that may assist us here?

Let us know 👍

**Comment by benoitedi** [comment]
Hi,

The issue got fixed. The configuration_aliases was causing the module to fail deployment on TFE as our server is on version V202001-5 and only support up to 0.12 version officially.

HashiCorp Support:
I see that you are using TFE V202001-5 (414) which was released on Feb 7, 2020. The first version of TFE to introduce full support for TF 0.13+ was v202009-1 (460). Additionally, if you are attempting to use configuration_aliases, support for that was included in Terraform 0.15+ which gained TFE support in v202104-1 (528).

Could you please close the ticket?

Thank you

Benoit Culioli - Contractor
Cloud Architect
[A picture containing drawing  Description automatically generated]
***@***.******@***.***>
+44 (0) 7 800 543 761 |  natwestgroup.com
RBS | Gogarburn | House B, 1st Floor | PO Box 1000 | Edinburgh | EH12 1HQ
The information classification of this email is Confidential unless otherwise stated.

**Comment by krowlandson** [comment]
Thank you for the update @benoitedi. We will now close this issue.

Just as a heads-up... We are working on some features for the module which will require a minimum version of `Terraform v0.15.0`. These will be included in the next major release and will require you to be running TFE `v202104-1 (528)`, so please keep an eye out for this!
