### ISSUE TITLE
Add Defender support for Open-source relational databases

### ISSUE THREAD

**Issue by grtn316** [Azure/terraform-azurerm-caf-enterprise-scale#131]
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/65a69f108bc410150653eb73b1f7ef25cd071d98/modules/management/locals.tf#L63-L72

Please add a flag to enable Open-source relational databases for Azure defender as part of the management resources configuration.

**Comment by krowlandson** [comment]
Hi David... thank you for the feature request.

Just for clarity, do you mean for the following?
https://docs.microsoft.com/en-us/azure/security-center/defender-for-databases-introduction

If so, I believe we will need to make a few updates to the associated policies before we can add a feature flag for this, but this shouldn't be a problem. Will add this to our backlog and discuss with the team.

**Comment by grtn316** [comment]
@krowlandson that is the one. Thanks!

**Comment by krowlandson** [comment]
Great, thank you for confirming. We will try to pull this in with the next policy update but as the "feature flag" will require an additional value in the `configure_management_resources` variable, this will be a breaking change. As such, we may need to hold back on updating the schema until a major release. Will keep you posted!

**Comment by krowlandson** [comment]
Once [Azure/Enterprise-Scale/issues/733](https://github.com/Azure/Enterprise-Scale/issues/733) is resolved, I will pull the updated policies in and we can hopefully add a feature flag to enable this particular feature.
