### ISSUE TITLE
Map to use custom resource group name for management resources has one nesting level to deep

### ISSUE THREAD

**Issue by jwueste** [Azure/terraform-azurerm-caf-enterprise-scale#139]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0

**azure provider**: 2.69.0

**module**: release-0-4-0

### Description

Map for configuring custom name of management resource group has one nesting level to much.
Advanced settings map has to look like this to work (see duplicate "management" key in resource group settings)
```hcl
advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          management = {
            management = {
              name = "${var.customer}-${var.project}-${var.environment}-rg-management"
            }
          }
        }
        azurerm_log_analytics_workspace = {
          management = {
            name = "${var.customer}-${var.project}-${var.environment}-la-management"
          }
        }
        azurerm_automation_account = {
          management = {
            name = "${var.customer}-${var.project}-${var.environment}-aacc-management"
          }
        }
      }
    }
```

**Steps to Reproduce**

Try to create a management resource group with "consistent" map layout 
```hcl
advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          management = {
            name = "${var.customer}-${var.project}-${var.environment}-rg-management"
          }
        }
        azurerm_log_analytics_workspace = {
          management = {
            name = "${var.customer}-${var.project}-${var.environment}-la-management"
          }
        }
        azurerm_automation_account = {
          management = {
            name = "${var.customer}-${var.project}-${var.environment}-aacc-management"
          }
        }
      }
    }
```
It will always use the default "${local.resource_prefix}-mgmt" name

**Comment by krowlandson** [comment]
Reviewed and merged PR where you will find additional details regarding this issue.

Thank you for your contribution.
