### ISSUE TITLE
Bug Report: Expected behavior for deploying connectivity and management resources

### ISSUE THREAD

**Issue by anwather** [Azure/terraform-azurerm-caf-enterprise-scale#147]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.1

**azure provider**: 

**module**: 0.4.0

### Description

Subscription context needs to be changed before deploying management and connectivity resources

**Steps to Reproduce**

1. Configure main.tf as below
```
 deploy_management_resources = true
 subscription_id_management = "838e9e33-645e-44fe-a094-209ed395a055"
```
2. Account context is not set to 838e9e33-645e-44fe-a094-209ed395a055
3.  Automation account and log analytics are deployed into a different subscription and then solutions fail to link

Just want to know if this is expected behaviour i.e. should I expect the set a new context using ```az account set``` each time?

Can we have an example to deploy foundation, management, and connectivity to multiple subscriptions?

**Comment by krowlandson** [comment]
Appreciate this may not be as prescriptively detailed as it could, but does the following cover most of what you are looking for?

[[User Guide] Provider Configuration # Multi-Subscription deployment](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Provider-Configuration#multi-subscription-deployment)

To add to the above, I also like to use an [azurerm_subscription](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/subscription) data resource for each provider, and then use these to populate the module as per the following example:

```hcl
# Declare a standard provider block using your preferred configuration.
# This will be used for the deployment of all "Core resources".
provider "azurerm" {
  features {}
}

# Declare an aliased provider block using your preferred configuration.
# This will be used for the deployment of all "Connectivity resources" to the specified `subscription_id`.
provider "azurerm" {
  alias           = "connectivity"
  subscription_id = "00000000-0000-0000-0000-000000000000"
  features {}
}

# Declare a standard provider block using your preferred configuration.
# This will be used for the deployment of all "Management resources" to the specified `subscription_id`.
provider "azurerm" {
  alias           = "management"
  subscription_id = "11111111-1111-1111-1111-111111111111"
  features {}
}

# Obtain client configuration from the core provider
data "azurerm_client_config" "core" {
  provider = azurerm
}

# Obtain client configuration from the management provider
data "azurerm_client_config" "management" {
  provider = azurerm.management
}

# Obtain client configuration from the connectivity provider
data "azurerm_client_config" "connectivity" {
  provider = azurerm.connectivity
}

# Build the module configuration
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"
  providers = {
    azurerm              = azurerm
    azurerm.management   = azurerm.management
    azurerm.connectivity = azurerm.connectivity
  }

  # Base module configuration settings.
  root_parent_id           = data.azurerm_client_config.core.tenant_id
  root_id                  = local.root_id
  root_name                = local.root_name
  library_path             = "${path.root}/lib"
  default_location         = local.default_location
  disable_base_module_tags = false


  # Configure deployment of core and demo landing zones.
  deploy_core_landing_zones   = true
  deploy_demo_landing_zones   = false
  deploy_corp_landing_zones   = true
  deploy_online_landing_zones = true
  deploy_sap_landing_zones    = true

  # Configuration settings for core resources.
  custom_landing_zones       = {}
  archetype_config_overrides = {}
  subscription_id_overrides  = {}

  # Configuration settings for management resources.
  # These are used to ensure Azure Policy is correctly
  # configured with the same settings as the resources
  # deployed by module.enterprise_scale_management.
  deploy_management_resources    = true
  subscription_id_management     = data.azurerm_client_config.management.subscription_id

  # Configuration settings for connectivity resources.
  # These are used to ensure Azure Policy is correctly
  # configured with the same settings as the resources
  # deployed by module.enterprise_scale_connectivity.
  deploy_connectivity_resources    = true
  subscription_id_connectivity     = data.azurerm_client_config.connectivity.subscription_id

}
```

If you think this additional information is useful, I will add this to the Wiki.

I am also currently working on the Wiki docs for these parts of the module, so please keep an eye out for updates this week which should give a clearer idea of how the `configure_management_resources` and `configure_connectivity_resources` inputs (which I've intentionally removed from the above to keep this example simple) help you to configure the deployment.

**Comment by anwather** [comment]
Thanks will give that a try, I didn't see that page in the wiki. I'll close this for now - cheers

**Comment by krowlandson** [comment]
Great, thank you... will still update the page to provide the additional detail as I think this will be useful
