### ISSUE TITLE
Cannot add custom policy definitions using \lib

### ISSUE THREAD

**Issue by tohov** [Azure/terraform-azurerm-caf-enterprise-scale#148]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.4

**azure provider**: 2.71

**module**: 0.4.0

### Description

I have added the lib folder for custom archetypes. I also have some custom policy assignments there. I ran into a situation where I wanted to create custom policy definition. I have named it "policy_definition_my_custom_policy.json". To my surprise, terraform plan does not do anything or "recognize" the policy definition. Is this by design?  And if I wanted to add one or two custom policies, how to do it?

**Steps to Reproduce**

1. create lib folder in the repo
2. add "policy_definition_custom_policy.json"
3. run terraform plan

**Expected behaviour**
I'd expect the module to grab the policy definition the same way as it does with custom policy assignments. 

**Screenshot**
![Screenshot 2021-08-17 112720](https://user-images.githubusercontent.com/38506856/129691615-96704d00-9c9f-4dbc-bfe7-d7289d0d2ffe.png)

**Comment by jtracey93** [comment]
Hey @tohov, 

Have you added the policy key name to an archetype definition in the policy definitions list that is used for one of your management groups?

Example here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/edd4ec093c5d3aa2468cf58dc867ae20e0698254/modules/archetypes/lib/archetype_definitions/archetype_definition_es_root.tmpl.json#L13

Let us know 👍

**Comment by tohov** [comment]
Nice. No I haven't. 😄 My bad. Thanks for the help @jtracey93! It works like a charm now. No bugs.

**Comment by jtracey93** [comment]
Superb! Not a problem at all and glad to help 👍 

Will close this issue off now 👍

**Comment by krowlandson** [comment]
I would also recommend that you check out our feature which enables you to [Expand built in archetype definitions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions).

This should significantly reduce any maintenance overhead on managing custom archetype definitions.

> Note that you can also exclude specific items from the built-in archetype definitions too (guidance in the same Wiki page).
