### ISSUE TITLE
Error when policies are being assigned with names longer than 24 characters

### ISSUE THREAD

**Issue by sagar-dholakia** [Azure/terraform-azurerm-caf-enterprise-scale#150]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.0.1 for linux_amd64

**azure provider**: hashicorp/azurerm v2.66.0

**module**: archetypes

### Description

When adding policies to policy assignments, you are required to put in the "name" of the policy. This corresponds to the name within the policy definition.

When using the following policy -- Deny-AppServiceWebApp-http  -- after creating a policy assignment for it, and then running terraform plan, an error appears as follows:

`Error: Invalid function argument`

 `on /home/vscode/.terraform.cache/modules/enterprise_scale/resources.policy_assignments.tf line 6, in resource ``"azurerm_policy_assignment" "enterprise_scale": 6:   name = tonumber(length(each.value.template.name) > 24 ? "The policy assignment name '${each.value.template.name}' is invalid. The policy assignment name length must not exceed '24' characters." : length(each.value.template.name)) > 24 ? null : each.value.template.name`

`each.value.template.name is "Deny-AppServiceWebApp-http"`
 
 `Invalid value for "v" parameter: cannot convert "The policy assignment name
 'Deny-AppServiceWebApp-http' is invalid. The policy assignment name length
 must not exceed '24' characters." to number; given string must be a decimal representation of a number.
`

**Steps to Reproduce**

1. create a policy assignment using the policy: Deny-AppServiceWebApp-http 
2. add the policy to a root extension (archetype_extensions_es_root.json)
2. run a terraform plan

**Additional context**

The problem itself is that there are policies within the repository that have been named which are longer than 24 characters, however if we try to assign these policies we are not allowed due to limitations within the code. 
What is the justification of this limit? if policies can be created with names longer than 24 characters, why can we not assign the same policies?

**Comment by krowlandson** [comment]
Thank you for raising this question.

As per the Microsoft documentation, Policy Assignment name length is limited to 24 characters when deployed at the Management Group scope (as all of ours currently are). This error message is embedded in the code to prevent a successful `plan` then failing at `apply` in this situation.

Please refer to: [Naming rules and restrictions for Azure resources # Microsoft.Authorization](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftauthorization)

Hopefully this helps?

**Comment by sagar-dholakia** [comment]
Thank you for the quick response! 

Yes that certainly helps, after taking a look at that doc, it seems like policySetDefinitions don't have the same restriction. Does that mean if I create a setDefinition with all of the policies with names longer than 24 chars, it would work around the restriction? or would it still fail because the policies within the setDefinition still are breaking the limit?

**Comment by jtracey93** [comment]
This would likely work if the setDefinitions at the MG scope support more than 24 characters,as they would be properties of that assignment. 

Well that's my thinking 😁

Would you be able to test and report back?

**Comment by jtracey93** [comment]
But the assignment name must be less than 24 characters still

**Comment by krowlandson** [comment]
Based on the documentation, I would say the following limits apply regardless of how you approach your naming strategy for each resource type...

![image](https://user-images.githubusercontent.com/12268562/130087176-25558c2b-5c89-486d-8973-b64461d2e206.png)

And as @jtracey93 says, ultimately the Policy Assignment Name will be limited to 24 characters so you will need to keep it within this limit.

Depending on what you would like to achieve, it's worth noting that the Portal uses the Display Name in most instances so you can use this to make the "name" more meaningful.

Will close this issue as I don't believe this is something we can work-around with the module / Terraform but please feel free to re-open and add to this if you feel this needs further consideration as happy to help.
