### ISSUE TITLE
Provider configuration not present 

### ISSUE THREAD

**Issue by saadq01** [Azure/terraform-azurerm-caf-enterprise-scale#153]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
v4.0

**terraform**:
v1.0.3
**azure provider**:
2.73
**module**:
v4.0

### Description

When I am running the initial v4 of CAF I am getting "Provider Configuration not Present". I am sure I am missing something simple but would appreciate if anyone can help. 
I have tried verifying the providers.t and terraform.tf files and currently they looks like this:

terraform.tf

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.66.0"
      configuration_aliases = [
        azurerm.connectivity,
        azurerm.management,
      ]
    }
    time = {
      source  = "hashicorp/time"
      version = ">= 0.7.0"
    }
  }
}
```

provider.tf

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.66.0"
      configuration_aliases = [
        azurerm.connectivity,
        azurerm.management,
      ]
    }
  }
}

provider "azurerm" {
  features {}
}

provider "azurerm" {
  alias = "connectivity"
  features {}
}

provider "azurerm" {
  alias = "management"
  features {}
}
```

# Configure the minimum required providers supported by this module

terraform init - runs ok!
terraform Plan - throws provider error 

**Screenshots**

![image](https://user-images.githubusercontent.com/86080845/130299595-3299466f-bc3b-482c-a9b9-4c5b133b2bbe.png)

**Additional context**

**Comment by jtracey93** [comment]
Hi @saadq01, 

Please review: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Provider-Configuration

Also I would suggest doing this in a clean Terraform state, as per the error message stated, it looks like something exist in your existing state file.

Let us know how you get on

Thanks

**Comment by krowlandson** [comment]
@saadq01, as mentioned by @jtracey93, our best source of information is on the Wiki and this should cover your scenario but just a couple of pointers based on what you've posted above.

You only need to declare the `required_providers` configuration once. It looks like you currently have this declared in two location. (I've also just wrapped your code in code blocks to make it easier to read).

You also need to ensure you add the provide configuration in your module block, when calling our module. Based on your example code above, you would go with the following example:

```hcl
# Map each module provider to your default `azurerm` provider using the providers input object.
module "caf-enterprise-scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  # insert the required input variables here
}
```

Please note, at this point although you have 3 providers declared, they all point to the same Subscription. For more information on how to configure the provider block for the Azure RM Provider, please refer to the [argument reference within the provider documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#argument-reference).

**Comment by ChrisCalzaretta** [comment]
So directions kind of stink, took me quite a bit of time to figure out what need to be done to make this run 
Got it to work like this
Update the 
  client_id =""
  client_secret = ""
  subscription_id =""
  tenant_id=""
and root parent id

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.66.0"
      configuration_aliases = [
        azurerm.connectivity,
        azurerm.management,
      ]
    }
    time = {
      source  = "hashicorp/time"
      version = ">= 0.7.0"
    }
  

  }
}
module "caf-enterprise-scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }
  root_parent_id = ""
  root_id        = "myorg"
  root_name      = "My Organization"
}
provider "azurerm" {
  alias           = "management"
  client_id =""
  client_secret = ""
  subscription_id =""
  tenant_id=""

  features {}
}
provider "azurerm" {
  alias           = "connectivity"
  client_id =""
  client_secret = ""
  subscription_id =""
  tenant_id=""

  features {}
}
provider "azurerm" {
  features {}
  client_id =""
  client_secret = ""
  subscription_id =""
  tenant_id=""
}
data "azurerm_client_config" "core" {
  provider = azurerm
}

# Obtain client configuration from the "management" provider
data "azurerm_client_config" "management" {
  provider = azurerm.management
}

# Obtain client configuration from the "connectivity" provider
data "azurerm_client_config" "connectivity" {
  provider = azurerm.connectivity
}

**Comment by jtracey93** [comment]
@saadq01 did our answers help you here? If so, can we close the issue

**Comment by saadq01** [comment]
Sorry for the late reply, you can close this ticket as I need to do some addition testing on v3.0 before I move to v4.0. 
Thanks.
