### ISSUE TITLE
Policy remidiation

### ISSUE THREAD

**Issue by turbut** [Azure/terraform-azurerm-caf-enterprise-scale#16]
Hi,
Is there a milestone to assign roles for managed identities for policy auto-remediation.
Or should principal ID of managed identities be an output of the module?

**Comment by krowlandson** [comment]
Great question... yes this is on the roadmap and needs further consideration. I'll bump this up the priorities.

Thank you

**Comment by krowlandson** [comment]
Should now be fixed as part of the latest release. Please let us know how you get on with this.
