### ISSUE TITLE
Ability to add "notScopes" value to preconfigured archetypes

### ISSUE THREAD

**Issue by gbr759** [Azure/terraform-azurerm-caf-enterprise-scale#161]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Afternoon all,

I'm hoping this is something that I've overlooked and someone can answer this easily for me.  I'm using deploy_core_landing_zones with the preconfigured "es_landing_zones" archetype, but I have a child management group underneath the standard "Landing Zones" management group which I'd like to exclude a policy from (the backup without a tag policy in this case).  I know I could create a custom policy assignment, create an archetype exclusion for the standard policy, and then an archetype extension to re-add the policy using a different name with the "notScopes" values, but I'm trying to keep the number of extra definitions to a minimum and use the automation where possible.

Is there a way to pass these values through to the module without having to do the above?

Thanks

**Comment by gbr759** [comment]
I do apologise, I just noticed this was answered in #96 

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/96

**Comment by jtracey93** [comment]
Hey @gbr759,

Are we okay to close this, in this case?

**Comment by jtracey93** [comment]
As discussed offline, closing as answered in #96
