### ISSUE TITLE
Monitoring Policies Related Parameters Not Being Updated

### ISSUE THREAD

**Issue by Eslam10** [Azure/terraform-azurerm-caf-enterprise-scale#169]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Versions
Module: 0.4.0
Terraform:  1.0.3
AzureRM: 2.66.0 

### Description
When deploying custom archetype definition "without deploying any Management resources" and trying to update the policies parameters, Some parameters are not taking any effect, what I have noticed so far are the parameters related to "Management" resources

**Steps to Reproduce**

1. Add custom json file to archetype_definition.
2. Add policy assignments/definitions/set_definitions
3. Update parameters of each policy assignment.
4. In the below code, only parameters related to "Deploy-VM-Backup, Enable-DDoS-VNET, Deploy-ASC-Monitoring" are getting updated, other policies are being assigned correctly to the management group however the policies parameters are not being updated as per the json file definition.

**Archetype Json File**

```hcl
{
  "any_name": {
    "policy_assignments": [
      "Deploy-VM-Backup",
      "Deploy-ASC-Monitoring",
      "Deploy-ASC-Configuration",
      "Deploy-AzActivity-Log",
      "Deploy-LX-Arc-Monitoring",
      "Deploy-Resource-Diag",
      "Deploy-VM-Monitoring",
      "Deploy-VMSS-Monitoring",
      "Deploy-WS-Arc-Monitoring",
      "Enable-DDoS-VNET"
    ],
    "policy_definitions": [
      "Deploy-ASC-Defender-ACR",
      "Deploy-ASC-Defender-AKS",
      "Deploy-ASC-Defender-AKV",
      "Deploy-ASC-Defender-AppSrv",
      "Deploy-ASC-Defender-ARM",
      "Deploy-ASC-Defender-DNS",
      "Deploy-ASC-Defender-SA",
      "Deploy-ASC-Defender-Sql",
      "Deploy-ASC-Defender-SQLVM",
      "Deploy-ASC-Defender-VMs",
      "Deploy-ASC-SecurityContacts",
      "Deploy-Diagnostics-AA",
      "Deploy-Diagnostics-ACI",
      "Deploy-Diagnostics-ACR",
      "Deploy-Diagnostics-AnalysisService",
      "Deploy-Diagnostics-ApiForFHIR",
      "Deploy-Diagnostics-APIMgmt",
      "Deploy-Diagnostics-ApplicationGateway",
      "Deploy-Diagnostics-CDNEndpoints",
      "Deploy-Diagnostics-CognitiveServices",
      "Deploy-Diagnostics-CosmosDB",
      "Deploy-Diagnostics-Databricks",
      "Deploy-Diagnostics-DataExplorerCluster",
      "Deploy-Diagnostics-DataFactory",
      "Deploy-Diagnostics-DLAnalytics",
      "Deploy-Diagnostics-EventGridSub",
      "Deploy-Diagnostics-EventGridSystemTopic",
      "Deploy-Diagnostics-EventGridTopic",
      "Deploy-Diagnostics-ExpressRoute",
      "Deploy-Diagnostics-Firewall",
      "Deploy-Diagnostics-FrontDoor",
      "Deploy-Diagnostics-Function",
      "Deploy-Diagnostics-HDInsight",
      "Deploy-Diagnostics-iotHub",
      "Deploy-Diagnostics-LoadBalancer",
      "Deploy-Diagnostics-LogicAppsISE",
      "Deploy-Diagnostics-MariaDB",
      "Deploy-Diagnostics-MediaService",
      "Deploy-Diagnostics-MlWorkspace",
      "Deploy-Diagnostics-MySQL",
      "Deploy-Diagnostics-NetworkSecurityGroups",
      "Deploy-Diagnostics-NIC",
      "Deploy-Diagnostics-PostgreSQL",
      "Deploy-Diagnostics-PowerBIEmbedded",
      "Deploy-Diagnostics-RedisCache",
      "Deploy-Diagnostics-Relay",
      "Deploy-Diagnostics-SignalR",
      "Deploy-Diagnostics-SQLElasticPools",
      "Deploy-Diagnostics-SQLMI",
      "Deploy-Diagnostics-TimeSeriesInsights",
      "Deploy-Diagnostics-TrafficManager",
      "Deploy-Diagnostics-VirtualNetwork",
      "Deploy-Diagnostics-VM",
      "Deploy-Diagnostics-VMSS",
      "Deploy-Diagnostics-VNetGW",
      "Deploy-Diagnostics-WebServerFarm",
      "Deploy-Diagnostics-Website",
      "Deploy-Diagnostics-WVDAppGroup",
      "Deploy-Diagnostics-WVDHostPools",
      "Deploy-Diagnostics-WVDWorkspace"
    ],
    "policy_set_definitions": [
      "Deploy-ASC-Config",
      "Deploy-Diagnostics-LogAnalytics"
    ],
    "role_definitions": [
      "Network-Subnet-Contributor"
    ],
    "archetype_config": {
      "parameters": {
        "Deploy-VM-Backup": {
          "effect": "auditIfNotExists"
        },
        "Deploy-ASC-Monitoring": {
          "identityEnableMFAForWritePermissionsMonitoringEffect": "AuditIfNotExists"
        },
        "Deploy-ASC-Configuration": {
          "emailSecurityContact": "email@email.com"
        },
        "Deploy-AzActivity-Log": {
          "logAnalytics": "/subscriptions/00000000-0000-0000-0000-1111111111/resourceGroups"
        },
        "Deploy-LX-Arc-Monitoring": {
          "logAnalytics": "/subscriptions/00000000-0000-0000-0000-1111111111/resourceGroups"
        },
        "Deploy-VM-Monitoring": {
          "logAnalytics_1": "/subscriptions/00000000-0000-0000-0000-1111111111/resourceGroups"
        },
        "Deploy-VMSS-Monitoring": {
          "logAnalytics_1": "/subscriptions/00000000-0000-0000-0000-1111111111/resourceGroups"
        },
        "Deploy-Resource-Diag": {
          "AKSLogAnalyticsEffect": "Disabled"
        },
        "Deploy-WS-Arc-Monitoring": {
          "effect": "Disabled"
        },
        "Enable-DDoS-VNET": {
          "effect": "Audit"
        }
      },
      "access_control": {}
    }
  }
}
```

**Comment by Eslam10** [comment]
Same issue exists even when the management resources are deployed.

**Comment by krowlandson** [comment]
Thank you for your issue @Eslam10 

The order of merging parameter input objects within the module is as follows:

1. Policy Assignment template file parameter values
2. Archetype definition template file parameter values
3. "Managed by module" parameter values (auto-generated by the module at the Connectivity, Identity, and Management scopes)
4. Customer-specified parameter values within the `custom_landing_zones` and `archetype_config_overrides` input variables

I believe the issue you are observing is that these particular policy assignments are being set by yourself at level `2` from the above list, and then over-written by the module at level `3`.

To override these, please try setting the values at level `4`.

> We advise against this if possible as the module is designed to ensure the values set in these particular Policy Assignments are fully managed and match the values for the resources created by the module.

Please let me know if this helps, or if you require further assistance.

**Comment by Eslam10** [comment]
Hi @krowlandson, Thanks for the explanation.
I am setting the `deploy_core_landing_zones` as `false` because we need different management groups hierarchy than the default.
The I am defining the `custom_landing_zones`, but the parameter values I set in the json file under `lib - archetype_definition` folder not from the `custom_landing_zones`. I thought to keep the `custom_landing_zones` variable only for the definition of the different management groups hierarchy, and the separate archetype definition template file parameter values to be the one which includes all the settings for each management group. 
I will try setting the parameters in `custom_landing_zones` input variables and let you know.

**Comment by krowlandson** [comment]
Thank you for the update. Will await your confirmation once you've tried this.

**Comment by Eslam10** [comment]
Hi @krowlandson,
Thank you, I tried setting the values from the `custom_landing_zones` input variable and it works as expected. 
As mentioned before, I thought to keep all the related parameters of each management group to be in the Archetype definition file, but if there is no other option, I will exclude these policies and assign the values from `cusotm_landing_zones` instead. 

One more note, based on the assignment order level 3, I collected all the related policies from the modules "Connectivity, Identity, and Management scopes" and tried to update the parameter values from the archetype definition json file.
As per my testing, the parameters values are not being updated only for most of the policies related to `Management` Scope `Deploy-ASC-Configuration, Deploy-LX-Arc-Monitoring, Deploy-VM-Monitoring, Deploy-VMSS-Monitoring, Deploy-WS-Arc-Monitoring, Deploy-AzActivity-Log, Deploy-Resource-Diag`.
For `Deploy-Log-Analytics` which is also in `Management` scope, parameters could be updated from the archetype definition file.
For `Deny-Public-IP, Deny-RDP-From-Internet, Deny-Subnet-Without-Nsg, Deploy-VM-Backup, Enable-DDoS-VNET, Deploy-Private-DNS-Zones` which are related to `Identity, Connectivity` scopes, parameters could be also updated normally from the archetype json file.

**Comment by krowlandson** [comment]
Great, glad to hear you've got this working.

In relation to your additional note, the "Managed" policies must also be applied at the expected scope (which is determined by the Management Group ID). Also, not all policies at a given scope necessarily have a corresponding set of managed parameters.

You will see "interference" on managed policies if you build a custom MG hierarchy and use the same IDs and policies from the default hierarchy. To avoid this, either use a different MG ID within your hierarchy, or custom copies of the policies with different names.

Hope this helps?

**Comment by Eslam10** [comment]
Yes, to avoid this conflict I tried already using custom copies of the policies with different names and it also worked fine, however in this case I think I'll loose this feature of the module updating the log analytics workspace ID in the related policies with the id of the created workspace by the `Management` resources, and I have to add this id as a parameter instead.

**Comment by krowlandson** [comment]
@Eslam10 In the context of #170, can I assume that this issue is no longer needed and can be closed?

**Comment by Eslam10** [comment]
@krowlandson, yes thanks a lot for your help and the quick response, we can close this issue.
