### ISSUE TITLE
Ability to Break up Deployment into Multiple Instances of the Module

### ISSUE THREAD

**Issue by Eslam10** [Azure/terraform-azurerm-caf-enterprise-scale#170]
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
Module: 0.4.0
Terraform: 1.0.3
AzureRM: 2.66.0

### Description
Trying to split the deployment into multiple instances for better arrangement of the deployment, so one to deploy the management groups hierarchy/policy definitions/assignments/etc... another one to deploy the `Management` resources, another one for `Connectivity` resources and so on. I came across this issue where the management resources will be deployed however the related security policies are not being applied however `configure_management_resources.settings.security_center.enabled` is set to `true`. I guess this is related to that the `enforcement_mode` value will remain as `false`. 
There is something similar mentioned here but this issue in specific wasn't addressed https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/102 

**Steps to Reproduce**
1. Deploy management resources with a separate module instance than the one deployed the management groups.
2. Check the related policies "Azure Defender, Monitoring" 
3. The policies parameters will not be updated as per the configuration in "configure_management_resources" variable

**Comment by krowlandson** [comment]
@Eslam10 - are you able to provide sample code re-producing this issue please?

**Comment by Eslam10** [comment]
Hi @krowlandson, 
Thanks for your reply, I will upload my code and share it with you once ready.

**Comment by Eslam10** [comment]
Hi @krowlandson, I have uploaded the code here https://github.com/Eslam10/ES-CAF-Testing.
`MGs` folder to deploy the management groups hierarchy/policies/etc... and `Management` folder to deploy the `Management` related resources.

**Comment by krowlandson** [comment]
Great stuff, thank you for providing that.

Just to check, have you tried entering the same values for `subscription_id_management` and `configure_management_resources` into both deployments, but setting `deploy_management_resources` to `false` in the `MGs` deployment?

I believe this should then work as you describe, but please let me know if not.

**Comment by krowlandson** [comment]
Just to explain the above, the `subscription_id_management` and `configure_management_resources` input variables control the data model which determines the settings for both the `parameters` and `enforcement_mode` settings on [managed] Policy Assignments, as well as the configuration of Management resources.

The `deploy_management_resources` input variable then simply controls whether to deploy the Resources within that particular deployment (using the specified `provider`), or not.

**Comment by Eslam10** [comment]
No, in `MGs` deployment I didn't add any of these parameter `subscription_id_management, configure_management_resources, deploy_management_resources`. 
I added them only in `Management` deployment.

**Comment by krowlandson** [comment]
OK, thank you for confirming.

Please try updating your configuration as above and let us know how you get on.

**Comment by Eslam10** [comment]
Ok, thank you, so I think I understood where was the issue.
Initially I didn't add these values `subscription_id_management, configure_management_resources` to the `MGs` deployment because I thought they're not relevant.

Apparently they're being used to define the parameter values for the monitoring related policies "workspace id, email, ...", so when I re-deployed the `MGs` code with these values `subscription_id_management, configure_management_resources` set, the policies parameters were updated with these values instead of the dummy values in normal deployment "however the management related resources were not yet deployed"

The only downside is now there is a duplication on the variables/files in the two folders and the values must be the same in both of them. the main idea was to split the deployments into different instances/repos/pipelines because they'll be managed by different teams.

**Comment by krowlandson** [comment]
Yes, that's correct...

To work-around the duplicate code, you could move the config into a dedicated module which only outputs the config (i.e. no resource deployments) and reference this from each pipeline, but this all adds complexity which is why we tend to recommend keeping the deployment coupled into a single pipeline.

Assuming you are using GitHub, have you considered using [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to allow you to control who has permission to review changes on specific files? This might be another approach you can consider?

**Comment by Eslam10** [comment]
Thanks @krowlandson for the suggestion, I am using Azure DevOps, I will check how can we achieve similar approach there.

**Comment by Eslam10** [comment]
Yes this is for the ADO repository then should be linked with Terraform cloud pipeline.
Thanks @krowlandson for all your help, I am going to close this issue.
