### ISSUE TITLE
Bug Report: Error: Variables not allowed

### ISSUE THREAD

**Issue by Ashley72** [Azure/terraform-azurerm-caf-enterprise-scale#183]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

terraform: 0.14.6

azure provider:
    azurerm              = azurerm
    azurerm.management   = azurerm.management
    azurerm.connectivity = azurerm.connectivity

**module**: "enterprise_scale" 
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

### Description
on using the new Provider information and code in an Azure DevOps Pipeline in receive this error on running the "terraform init" task. 

Error: Error: Variables not allowed

On .terraform/modules/enterprise_scale/terraform.tf line 8: Variables may not
be used here.

Error: Variables not allowed

On .terraform/modules/enterprise_scale/terraform.tf line 9: Variables may not
be used here.

which repeats several times. 

Steps to Reproduce
I have a backend File with storage account details and my main file with code from the providers section for multiple subscriptions

**Comment by krowlandson** [comment]
@Ashley72... Thank you for your issue.

I'm jumping to a bit of a conclusion here, but if I recall correctly, this is one of the reasons we updated the minimum supported version of Terraform to be `v0.15.0`. In previous Terraform versions we got this error.

This was the only way we could reliably add multi-Subscription support into the module with forward compatibility.

Please try your configuration with `v0.15.0` or later, and confirm.

**Comment by krowlandson** [comment]
I'll assume we can close this then, but please drop another message if you need further support on this.
