### ISSUE TITLE
Policies incompatible with Terraform

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#186]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: <em>all</em> </p>
<p><strong>azure provider</strong>: <em>all</em> </p>
<p><strong>module</strong>: <em>all</em> </p>
<h3 id=description>Description </h3>
<p>Due to the way the <code>azurerm</code> provider works, the following Policy Definitions are incompatible with Terraform: </p>
<ul>
<li><code>Deny-Subnet-Without-NSG</code> </li>
<li><code>Deny-Subnet-Without-UDR</code> </li>
</ul>
<p><strong>Steps to Reproduce</strong> </p>
<ol>
<li>Create a deployment where these policies are assigned at a specific scope. </li>
<li>Place a Subscription under this scope. </li>
<li>Try to create a Virtual Network with Subnets missing NSG and UDR configurations (note that even if you add these using the approach available by Terraform, the deployment fails) </li>
</ol>
<p><strong>Screenshots</strong> </p>
<p><strong>Additional context</strong> </p>

**Comment by krowlandson** [comment]
Considering the option to set these to "Audit" as default effect in the Terraform module.

Does anyone have thoughts on how best to approach this?

Also thinking this could be developed alongside updating the module to simplify the approach for controlling whether DINE policies are enabled or not, in alignment with the guidance recently published by @jtracey93: [Adopt policy-driven guardrails](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/dine-guidance)

**Comment by nikolai-fraport** [comment]
We did set these to "Audit" to workaround this issue.

To do this we used a custom archetype_extension and set the required parameter:

File `lib/archetype_extension_es_landing_zones.tmpl.json`
```
{
  "extend_es_landing_zones": {
    "policy_assignments": [],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {
        "Deny-Subnet-Without-Nsg": {
          "effect": "Audit"
        }
      },
      "access_control": {}
    }
  }
}
```

Probably we could set this parameter as default in the `archetype_definition` [here](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/archetype_definitions/archetype_definition_es_landing_zones.tmpl.json#L22)?

In addition a mention in the docs? 
Then it would be easy for users to customize the effect again ...

But this would be rather a patch than your proposed changes from the linked CAF article.


Did you asked how to fix the root cause? Sry I'm no help here.

**Comment by jtracey93** [comment]
Thanks @nikolai-fraport for sharing your insights here, that's certainly a good way to do this 👍

Myself & @krowlandson have just been discussing this and have agreed that we will provide guidance similar to what you have shared above in a Wiki docs page, adding to what we say here already https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Getting-Started#additional-considerations-when-deploying-landing-zone-resources-with-terraform

Likely this section will become a new Wiki page on its own and the "Getting Started" page will be left as just that.

We will also be bringing this back up with the relevant engineering teams internally to work out a better approach than effectively changing the policies desired effect.

**Comment by jtracey93** [comment]
Trigger ADO Sync
