### ISSUE TITLE
Changing root_parent_id results in Management Groups not being deployed

### ISSUE THREAD

**Issue by lpmulligan** [Azure/terraform-azurerm-caf-enterprise-scale#190]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.8

**azure provider**: 2.80.0

**module**: 1.0.0

### Description

I'm trying to deploy an Enterprise Scale LZ deployment within an existing EA structure.  I've been assigned owner to a Management Group 3 levels down from the Tenant Root Group.  I would like to deploy a stock ES LZ within that management group.   Changing root_parent_id from:

```
root_parent_id = data.azurerm_client_config.core.tenant_id
root_id        = "myorg"
root_name      = "My Organization"

deploy_demo_landing_zones = true
```

to
```
root_parent_id = "ELZDemo"
root_id        = "myorg"
root_name      = "My Organization"

deploy_demo_landing_zones = true
```

Results in all the
resource "azurerm_management_group" "level_1", resource "azurerm_management_group" "level_2", etc resources being skipped.

Manually creating the Management Groups under "ELZDemo" by hand allows the core management `terraform apply` to run successfully.

**Steps to Reproduce**

1. Set `root_parent_id = data.azurerm_client_config.core.tenant_id` in main.tf
2. Run `terraform plan`
3. You get MG groups created with 191 resources
2. Set `root_parent_id = "ELZDemo"`
3.  You get no MG groups with 180 resources.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by jtracey93** [comment]
You certainly led us down the right path, so thank you 👍

We will leave this open so we can track the bug fix 👍

If you have another issue, feel free to open a another issue on the repo. Happy to help 👍
