### ISSUE TITLE
Unable to see Management Groups deployed due to lack of RBAC - Highly Regulated Environment - Not deploying to tenant root management group

### ISSUE THREAD

**Issue by Ashley72** [Azure/terraform-azurerm-caf-enterprise-scale#195]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In a highly regulated environment where access to to management Groups is restricted at Root level, it would be nice to understand how to set permissions on the Management groups as they get deployed so overwriting default permissions

Example: our SPN has permissions to deploy via CI/CD pipeline to create management Group structure. After its deployed no user can see all management groups deployed as they don't have permissions on the Management groups. In order to grant permissions to users it would be useful to know how this can be set from original 1st deployment of management groups 

**Describe the solution you'd like**

**Additional context**

**Comment by krowlandson** [comment]
@Ashley72... do you have any further questions on the above, or can we close this issue?

**Comment by krowlandson** [comment]
Closing this issue as no response from author, and documentation update being tracked in issue #262
