### ISSUE TITLE
Compliance with ISO 27001:2013

### ISSUE THREAD

**Issue by skelso01** [Azure/terraform-azurerm-caf-enterprise-scale#198]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
**terraform**: v 1.0.9

**azure provider**: 
- provider registry.terraform.io/hashicorp/azurerm v2.83.0

**module**:
- provider registry.terraform.io/aztfmod/azurecaf v1.2.6
- provider registry.terraform.io/hashicorp/azuread v2.8.0
- provider registry.terraform.io/hashicorp/azurerm v2.83.0
- provider registry.terraform.io/hashicorp/random v3.1.0
- provider registry.terraform.io/hashicorp/time v0.7.2
- provider registry.terraform.io/hashicorp/tls v3.1.0

### Description

In our template, which uses the caf enterprise scale modul, we added with custom libs the Initiative 27001:2013 and removed the default "ISO 27001". The enterprise scale module deploys a custom role definition named "Network-Subnet-Contributor". But in the ISO 27001:2013 initiative is a policy, which audits, that we should not use custom roles ("Audit usage of custom RBAC rules" with policy definition id "/providers/Microsoft.Authorization/policyDefinitions/a451c1ef-c6ca-483d-87ed-f49761e3ffb5").
We would expect, that the caf enterprise scale module deploys resources, which arre complient to the ISO 27001:2013, too.

**Steps to Reproduce**

1. Role out the terraform "caf enterprise scale" template
2. Assign the Initiative "ISO 27001:2013"
   (I did this with custom libs)
3. Start Complience Scan
   (I did this with the powershell Az module)
4. Check the compliance state of the initative "ISO 27001:2013"

**Comment by krowlandson** [comment]
Hi @skelso01... thank you for logging your issue.

If I understand the ask correctly, you would like to remove the custom role definition which is included as part of the default implementation so you can achieve compliance with the ISO 27001:2013 initiative? This role is included to show how this is possible, and at some point we may include the others documented in the [Identity and access management](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/identity-and-access-management) critical design area.

For now, you can remove this role by simply adding the following to your custom library:

File: `lib/archetype_exclusion_es_landing_zones.tmpl.json`
```hcl
{
  "exclude_es_root": {
    "policy_assignments": [],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [
      "Network-Subnet-Contributor"
    ],
    "archetype_config": {
      "parameters": {},
      "access_control": {}
    }
  }
}
```

For more information on adding or removing items from the included archetype definitions, please refer to the following article on the GitHub Wiki:
[[Examples] Expand built in archetype definitions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions)

**Comment by skelso01** [comment]
Hi @krowlandson,
thanks for the very quick answer. Now if I understand correctly, you have included the role definition for demonstration to show how to create user defined roles, but not currently in use?
We were already aware of the exclude at that point, but we were wondering if the role was intended for a specific purpose that we didn't see directly. That's why we didn't want to simply exclude the role. But since this role is not currently in use, we take it out then. Thank you very much for your help. It would be cool if you could make a small note in the documentation, which is really good and helpful.

**Comment by krowlandson** [comment]
> Now if I understand correctly, you have included the role definition for demonstration to show how to create user defined roles, but not currently in use?

Correct.

> It would be cool if you could make a small note in the documentation, which is really good and helpful.

Agreed... I will add this to our backlog.

Thank you for the feedback.
