### ISSUE TITLE
Add custom role definitions from critical design areas and provide documentation around their use.

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#199]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add all custom roles as recommended in the [Identity and access management](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/identity-and-access-management) documentation:

Role | Usage | Actions | No actions
-- | -- | -- | --
Azure platform owner (such as the built-in Owner role) | Management group and subscription lifecycle management | \* |  
Network management (NetOps) | Platform-wide global connectivity management: Virtual networks, UDRs, NSGs, NVAs, VPN, Azure ExpressRoute, and others | \*/read,</br>Microsoft.Network/\*,</br>Microsoft.Resources/deployments/\*,</br>Microsoft.Support/\* |  
Security operations (SecOps) | Security administrator role with a horizontal view across the entire Azure estate and the Azure Key Vault purge policy | \*/read,</br>\*/register/action,</br>Microsoft.KeyVault/locations/deletedVaults/purge/action,</br>Microsoft.PolicyInsights/\*,</br>Microsoft.Authorization/policyAssignments/\*,</br>Microsoft.Authorization/policyDefinitions/\*,</br>Microsoft.Authorization/policyExemptions/\*,</br>Microsoft.Authorization/policySetDefinitions/\*,</br>Microsoft.Insights/alertRules/\*,</br>Microsoft.Resources/deployments/\*,</br>Microsoft.Security/\*,</br>Microsoft.Support/\* |  
Subscription owner | Delegated role for subscription owner derived from subscription Owner role | \* | Microsoft.Authorization/\*/write,</br>Microsoft.Network/vpnGateways/\*,</br>Microsoft.Network/expressRouteCircuits/\*,</br>Microsoft.Network/routeTables/write,</br>Microsoft.Network/vpnSites/\*
Application owners (DevOps/AppOps) | Contributor role granted for application/operations team at resource group level | \* | Microsoft.Authorization/\*/write,</br>Microsoft.Network/publicIPAddresses/write,</br>Microsoft.Network/virtualNetworks/write,</br>Microsoft.KeyVault/locations/deletedVaults/purge/action

**Describe the solution you'd like**

The Role Definitions listed above should be deployed into the customer environment as part of the `es_root` archetype definition.

Clear documentation should be added to the Wiki regarding custom Role Definitions included within the module.

**Additional context**

As mentioned in #198

**Comment by dimilider** [comment]
custom roles on management group scope are still in preview. https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles
