### ISSUE TITLE
Add ability to Deploy Azure Sentinel

### ISSUE THREAD

**Issue by Ashley72** [Azure/terraform-azurerm-caf-enterprise-scale#202]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As we are deploying LA, it would also be useful to be able to deploy Sentinel workspace to pull LA logs etc.

**Describe the solution you'd like**

Deploy Sentinel with basic settings into Management Subscription so it can then be used to monitor Landing Zones

**Comment by jtracey93** [comment]
Hi @Ashley72,

Thanks for raising this feature request. We have reviewed as a team and have decided, for now (at this current time), that we will not expand upon what we already do as part of the module today; which is:

1. Deploy the Log Analytics Workspace into the Management Subscription
2. Deploy the `SecurityInsights` Solution onto the Log Analytics Workspace, which is the Solution that makes a workspace "Sentinel enabled"

This is documented here for reference: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Management-Resources

We then leave it to the security teams to configure Sentinel by adding Data Connectors, alert rules, workbooks etc. however they wish to (deployment tooling/method wise) outside of this Terraform module as this is more an application/service workload configuration task than a platform team task.

Hope that helps and makes sense 👍 

Any questions or further feedback, please let us know 🙂
