### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Ashley72** [Azure/terraform-azurerm-caf-enterprise-scale#203]
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Using terraform 0.15.0
Module 1.0.0
Using Pipeline in Azure Devops

### Description

when deploying the step in the example - expand built-in Archtype definitions. During the Plan phase I get teh following errors

1.	Error: Error in function call 
│ 
│ on .terraform/modules/enterprise_scale/modules/archetypes/locals.archetype_definitions.tf line 44, in locals: 
│ 44: filepath => jsondecode(templatefile("${local.custom_library_path}/${filepath}", local.template_file_vars)) 
│ ├──────────────── 
│ │ local.custom_library_path is "./lib" 
│ │ local.template_file_vars is object with 11 attributes 
│ 
│ Call to function "jsondecode" failed: invalid character ',' after object 
│ key. 
╵ 
##[error]Bash exited with code '1'. 
Finishing: Terraform plan 

is this a bug or have I done something wrong?

I've retraced my steps several times and everything appears as per the example, only differance is I'm running from a pipeline

**Comment by krowlandson** [comment]
> Call to function "jsondecode" failed: invalid character ',' after object key.

Assuming this part of the error message is correct, are you able to check that all files within your custom library are valid JSON?

This sounds like you have an invalid comma in one of your custom templates, so that would be the first thing I would check.

As a side note, we have also observed that the `jsondecode()` function in Terraform doesn't support JSON with comments, although I believe that gives a different error to the above.

**Comment by Ashley72** [comment]
Thanks Kevin, I ended up recreating the json files and that fixed the issue.

**Comment by krowlandson** [comment]
Great to hear, thank you for confirming.
