### ISSUE TITLE
Bug Report: hub_network enabled flag doesn't do the job

### ISSUE THREAD

**Issue by tisigoncalve** [Azure/terraform-azurerm-caf-enterprise-scale#205]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.10

**azure provider**: 2.82.0

**module**: 1.0

### Description

**Describe the bug**

In setting.connectivity.tf file you have to delete hub_network object, isn't enough to change the enabled value to false.

      hub_networks = [
        ......{
          enabled = **false**
          config = {
            address_space                = ["10.158.67.0/24"]
            location                     = "westeurope"
            link_to_ddos_protection_plan = false
            dns_servers                  = []
            bgp_community                = ""
            subnets                      = []
            virtual_network_gateway = {
              enabled = false
              config = {
                address_prefix           = ""
                gateway_sku_expressroute = "ErGw2AZ"
                gateway_sku_vpn          = ""
              }
            }

**Steps to Reproduce**

1. in the setting.connectivity.tf file leave the hub network object filled, change the enabled value to false.
2. The VNET is created anyway, only deleting the object works.

**Comment by krowlandson** [comment]
@tisigoncalve, try as I might, I don't seem to be able to reproduce this issue.

**Comment by krowlandson** [comment]
@tisigoncalve, were you able to resolve this issue? As per my previous message, I was unable to reproduce this behaviour.
