### ISSUE TITLE
Ability to extend CAF module supplied policySetDefinitions and policy assignments similar to archetypes

### ISSUE THREAD

**Issue by samiwel** [Azure/terraform-azurerm-caf-enterprise-scale#208]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is documented on the Wiki that archetype definitions supplied with the module can be extended or excluded. It would be useful to be able to add and remove policies from the module supplied policy set definitions and extend the parameters which can be passed into policy assignments supplied by the module in a similar way (i.e. policy_set_definition_extention_*.json and policy_assignment_definition_extention_*.json). As this would allow customisation of the module supplied configuration without having to take a full copy and modify it.

**Describe the solution you'd like**

**Additional context**

**Comment by krowlandson** [comment]
Thank you for logging this issue @samiwel

If I am understanding this correctly, you would like the ability to modify the Policy Set Definitions included within the `lib` folder of the module without having to create a duplicate copy in your `root module`?

I can see the reason for wanting to do this, but given the complexity of policies our guidance is to copy them to your local lib folder. This mitigates the risk of conflicting changes if the original template is updated within the module.

If you simply want to set parameters through a Policy Assignment where the associated template doesn't have the parameter declared, the module already allows you to do this by passing them through the `parameters` object in the `archetype_config` as long as the assigned Policy [Set] Definition has them available for setting.

You can see more details around how to do this on the Wiki page: [Working with the archetype_config object](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions#working-with-the-archetype_config-object)

Unfortunately I don't see us being able to safely provide the ability to edit Policy Set Definitions so I will close this issue.
