### ISSUE TITLE
Question concerning firewall policy

### ISSUE THREAD

**Issue by manfred0191** [Azure/terraform-azurerm-caf-enterprise-scale#214]
Hello,
this is not a bug, but I don't know how and where to address this question:

I need an example how I can deploy a firewall policy, for instance a DNAT rule that traffic from my personal notebook to a virtual machine can be deployed. In mstsc, I want to put in the public IP address of the firewall and I want to get access granted on port 3389.

Where and how can I deploy this via terraform using your module ??

Can you show me an example of how to use this?

Another question would be route tables: Are route tables within the scope of the module and how to deploy them?

**Comment by krowlandson** [comment]
@manfred0191 thank you for this question.

We made a conscious decision to deploy only the firewall using the module. All module configuration including the addition of rules can be done using standard Azure RM provider resources such as:

- [azurerm_firewall_application_rule_collection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_application_rule_collection)
- [azurerm_firewall_nat_rule_collection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_nat_rule_collection)
- [azurerm_firewall_network_rule_collection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_network_rule_collection)
- [azurerm_firewall_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy)
- [azurerm_firewall_policy_rule_collection_group](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy_rule_collection_group)

Our recommendation would be to implement these via a separate execution plan, using the [azurerm_firewall](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/firewall) data resource to get details of the firewall being configured.

We also recommend the same approach for route tables, UDRs, etc.

Hope this helps?

**Comment by manfred0191** [comment]
It actuall helps a little bit, but if I want to set up a route table, I need the name of the firewall, that has been deployed.

But in fact not the name itself, I need this one:

```
resource "azurerm_route_table" "fw-dg" {
  name                          = "acceptanceSecurityGroup1"
  location                      = var.location
  resource_group_name           = var.rg_connect
  disable_bgp_route_propagation = false

  route {
    name                    = "fw-dg"
    address_prefix          = "0.0.0.0/0"
    next_hop_type           = "Virtualappliance"
    next_hop_in_ip_address  = azurerm_firewall.example.ip_configuration.private_ip_address
  }

  tags = {
    environment = "Production"
  }
}
```

The thing is the name in my case is definitely not "**example**" but as the firewall was deployed by the module, I don't know what to put in there as I cannot see that code

You understand my problem?

**Comment by krowlandson** [comment]
You should be able to determine the resource reference by running the following command and looking for the firewall entry:

`terraform state list`

It should look something like the following:

`module.enterprise_scale.azurerm_firewall.connectivity["/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/es-connectivity-northeurope/providers/Microsoft.Network/azureFirewalls/es-fw-northeurope"]`

**Comment by manfred0191** [comment]
In your example, what would be the reference then?

**Comment by krowlandson** [comment]
Assuming the properties you specified are correct, just append `.ip_configuration[0].private_ip_address` to the resource ID

**Comment by manfred0191** [comment]
I understand, but what is the ressource id in your example?

module.enterprise_scale.azurerm_firewall.connectivity["/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/es-connectivity-northeurope/providers/Microsoft.Network/azureFirewalls/es-fw-northeurope"]

or

module.enterprise_scale.azurerm_firewall.connectivity

or

/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/es-connectivity-northeurope/providers/Microsoft.Network/azureFirewalls/es-fw-northeurope

or what else?

**Comment by krowlandson** [comment]
As a universal standard across the module, we use the actual `resourceId` value (from Azure) of each resource as the `key` in our `for_each` loops.

So in your example above you would use it like this:

```hcl
resource "azurerm_route_table" "fw-dg" {
  name                          = "acceptanceSecurityGroup1"
  location                      = var.location
  resource_group_name           = var.rg_connect
  disable_bgp_route_propagation = false

  route {
    name                    = "fw-dg"
    address_prefix          = "0.0.0.0/0"
    next_hop_type           = "Virtualappliance"
    next_hop_in_ip_address  = module.enterprise_scale.azurerm_firewall.connectivity["/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/es-connectivity-northeurope/providers/Microsoft.Network/azureFirewalls/es-fw-northeurope"].ip_configuration.private_ip_address
  }

  tags = {
    environment = "Production"
  }
}
```

As that isn't very friendly cosmetically, we would recommend using the [dependency inversion](https://www.terraform.io/docs/language/modules/develop/composition.html#dependency-inversion) technique recommended by HashiCorp to define a `data` resource for the Azure Firewall and then reference this in your firewall rules. This also allows you to create a separate module for managing firewall rules.

We liken this scenario to "the platform team install the firewall (using the caf-enterprise-scale module)" and then "the network/security team manage the firewall configuration".

Or if you want to continue running this within a single pipeline, to make the code easier to read you can us locals to break apart the value(s).

For example:

```hcl
locals {
  azfw_resource_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/es-connectivity-northeurope/providers/Microsoft.Network/azureFirewalls/es-fw-northeurope"
  azfw_config      = module.enterprise_scale.azurerm_firewall.connectivity[local.azfw_resource_id]
}

resource "azurerm_route_table" "fw-dg" {
  name                          = "acceptanceSecurityGroup1"
  location                      = var.location
  resource_group_name           = var.rg_connect
  disable_bgp_route_propagation = false

  route {
    name                    = "fw-dg"
    address_prefix          = "0.0.0.0/0"
    next_hop_type           = "Virtualappliance"
    next_hop_in_ip_address  = local.azfw_config.ip_configuration.private_ip_address
  }

  tags = {
    environment = "Production"
  }
}
```

Hope this helps.

**Comment by manfred0191** [comment]
Great answer, thank you so much. Will try that immediately tomorrow and inform you about the final result,,,,

**Comment by manfred0191** [comment]
Is there any chance I can get in direct contact to a developer on your site by zoom or google meet to check this issue?

**Comment by krowlandson** [comment]
> Great answer, thank you so much. Will try that immediately tomorrow and inform you about the final result...
> 
> Just a last thing: Somewhere in the code I found this one:
> 
> ```
> # The following output is used to ensure all Azure Firewall
> # data is returned to the root module.
> output "azurerm_firewall" {
>   value = {
>     connectivity = azurerm_firewall.connectivity
>   }
>   description = "Returns the configuration data for all Azure Firewalls created by this module."
> }
> ```
> 
> That in fact doesn't help, right? Because this was for me somewhat like a hint we get data we can access later, but we do not as it seems.
> 
> Because there is one thing that is not so nice: We do not know the id in advance which means I always have to deploy twice or more with this solution.....

The above is a bit of a hint, but the module basically outputs the full configuration of every resource it creates, grouped by "resource type" and then by "capability" (i.e. `enterprise_scale`, `level_X`, `management`, and `connectivity`.

So in the example above, this gives a clue to the fact that the `azurerm_firewall` resources created by the module will be output by the following:

1. Module name, e.g. `module.enterprise_scale`
2. Resource type, e.g. `.azurerm_firewall`
3. Capability, e.g. `.connectivity`
4. Resource ID (from `for_each` loop), e.g. `["/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/es-connectivity-northeurope/providers/Microsoft.Network/azureFirewalls/es-fw-northeurope"]`

Because of the way Azure generates Resource IDs in a predictable way, you should be able to work out what this will be ahead of time if you really need to.

This conversation is making me reconsider this decision for resource naming standards, but the we face two challenges:

1. What could we replace it with that would be easier to determine, given some of the conditions under which we need to ensure uniqueness of these IDs?
2. Would it be acceptable to introduce such a dramatic breaking change to the module which would result in many resources being redeployed, or a complicated resource move scenario within an existing Terraform state file?

**Comment by krowlandson** [comment]
> Is there any chance I can get in direct contact to a developer on your site by zoom or google meet to check this issue?

Drop me a message on [LinkedIn](https://www.linkedin.com/in/kevinrowlandson/) and let's see what we can setup.

**Comment by manfred0191** [comment]
Unfortunately I haven't got LinkedIn.

My current problem is to attach the firewall policy to the firewall itself as I don't know how to do that and I have to put in the route table in AzureGatewaySubnet, where I also have to access to with terraform.

Actually I can meet you on Google meet or zoom, but you can also help me if you provide me an example of how to build up a firewall together with policy and route tables

**Comment by manfred0191** [comment]
Seriously, this is not the way it's meant to be:

```
resource "azurerm_firewall_policy_rule_collection_group" "rulepolicies" {
  name               = "fwpolicy-rcg"
  firewall_policy_id = azurerm_firewall_policy.hybrid-test-pol.id
  priority           = 200
  application_rule_collection {
    name     = "app_rule_collection1"
    priority = 204
    action   = "Allow"
    rule {
      name = "app_rule_collection1_rule1"
      protocols {
        type = "Http"
        port = 80
      }
      protocols {
        type = "Https"
        port = 443
      }
      source_addresses  = ["*"]
      destination_fqdns = ["www.google.com"]
    }
  }

  network_rule_collection {
    name     = "network_rule_collection1"
    priority = 202
    action   = "Allow"
    rule {
      name                  = "network_rule_collection1_rule1"
      protocols             = ["TCP", "UDP"]
      source_addresses      = ["*"]
      destination_addresses = ["*"]
      destination_ports     = ["80", "8000-9000"]
    }
  }

  nat_rule_collection {
    name     = "nat_rule_collection1"
    priority = 200
    action   = "Dnat"
    rule {
      name                = "nat_rule_collection1_rule1"
      protocols           = ["TCP", "UDP"]
      source_addresses    = ["*"]
      destination_address = module.enterprise_scale.azurerm_public_ip.connectivity["/subscriptions/0000-0000-0000-0000/resourceGroups/mk-02-connectivity-westeurope/providers/Microsoft.Network/publicIPAddresses/mk-02-ergw-westeurope-pip"].ip_address
      destination_ports   = ["3389"]
      translated_address  = "10.10.2.4"
      translated_port     = "3389"
    }
  }
}

resource "azurerm_subnet" "connectivity" {
  address_prefixes     = ["10.10.1.224/27"]
  name                 = "GatewaySubnet"
  resource_group_name  = module.enterprise_scale.azurerm_resource_group.connectivity["/subscriptions/0000-0000-0000-0000/resourceGroups/mk-02-connectivity-westeurope"].name
  virtual_network_name = "mk-02-hub-westeurope"
}

resource "azurerm_subnet_route_table_association" "fw-dg" {
  subnet_id      = azurerm_subnet.connectivity.id
  route_table_id = azurerm_route_table.fw-dg.id
}
```

I don't want to put in the id's from the statefile, I want to deploy infrastructure as code and not look up things in a statefile or the GUI or whereever.

P.S.: the 0000-0000-0000-0000 is a substitute for my real subscription names I don't want to put on the internet you know,,,,

**Comment by krowlandson** [comment]
To be honest, this is going a bit beyond the scope of supporting the module, but did you try the [dependency inversion](https://www.terraform.io/docs/language/modules/develop/composition.html#dependency-inversion) approach I recommended above?

This is our recommended approach as we prefer not to encourage customers to put everything in a single Terraform deployment. This is also a recommendation from HashiCorp.

For your example above (which I don't believe is complete, as you appear to reference resources not included in the code), you could add something like the following to extract the configuration of the resources created by the module and then reference values from these in a simpler manner:

```hcl
locals {
  root_id   = "mk-02"
  location  = "westeurope"
  rsg_name  = "${local.root_id}-connectivity-${local.location}"
  fw_name   = "${local.root_id}-fw-${local.location}"
  vnet_name = "${local.root_id}-hub-${local.location}"
  ergw_name = "${local.root_id}-ergw-${local.location}"
}

data "azurerm_firewall" "westeurope" {
  name                = local.fw_name
  resource_group_name = local.rsg_name
}

data "azurerm_virtual_network_gateway" "westeurope_expressroute" {
  name                = local.ergw_name
  resource_group_name = local.rsg_name
}

data "azurerm_subnet" "westeurope_gateway" {
  name                 = "GatewaySubnet"
  virtual_network_name = local.vnet_name
  resource_group_name  = local.rsg_name
}

resource "azurerm_firewall_policy_rule_collection_group" "rulepolicies" {
  name               = "fwpolicy-rcg"
  firewall_policy_id = azurerm_firewall_policy.hybrid-test-pol.id
  priority           = 200
  application_rule_collection {
    name     = "app_rule_collection1"
    priority = 204
    action   = "Allow"
    rule {
      name = "app_rule_collection1_rule1"
      protocols {
        type = "Http"
        port = 80
      }
      protocols {
        type = "Https"
        port = 443
      }
      source_addresses  = ["*"]
      destination_fqdns = ["www.google.com"]
    }
  }

  network_rule_collection {
    name     = "network_rule_collection1"
    priority = 202
    action   = "Allow"
    rule {
      name                  = "network_rule_collection1_rule1"
      protocols             = ["TCP", "UDP"]
      source_addresses      = ["*"]
      destination_addresses = ["*"]
      destination_ports     = ["80", "8000-9000"]
    }
  }

  nat_rule_collection {
    name     = "nat_rule_collection1"
    priority = 200
    action   = "Dnat"
    rule {
      name                = "nat_rule_collection1_rule1"
      protocols           = ["TCP", "UDP"]
      source_addresses    = ["*"]
      destination_address = data.azurerm_firewall.westeurope.ip_configuration[0].private_ip_address
      destination_ports   = ["3389"]
      translated_address  = "10.10.2.4"
      translated_port     = "3389"
    }
  }
}

resource "azurerm_subnet_route_table_association" "fw-dg" {
  subnet_id      = data.azurerm_subnet.westeurope_gateway.id
  route_table_id = azurerm_route_table.fw-dg.id
}

```

Just remember to ensure you correctly configure/map the provider to the correct Subscription, and add a `depends_on` block to link the data resources to the module if running within a single root module. Also, adjust things like the `locals` used to determine the names if you need to as some may already exist, and some might be better configured as `variables` depending on your overall configuration.

**Comment by manfred0191** [comment]
Thanks for your help and your patience with me.

Although the firewall had been deployed before by the module, using your suggestion leads to

_│ Error: Firewall "mk-02-fw-westeurope" was not found in Resource Group "mk-02-connectivity-westeurope"
│ 
│   with data.azurerm_firewall.westeurope,
│   on firewall.tf line 1, in data "azurerm_firewall" "westeurope":
│    1: data "azurerm_firewall" "westeurope" {
│_ 

But I can see the resource exactly there from the Azure Portal

**Comment by krowlandson** [comment]
Are you running this within the same deployment, or as part of a new deployment?

**Comment by manfred0191** [comment]
Either way, the error is the same

**Comment by manfred0191** [comment]
Look, here I have some screenshots:

![Screenshot 2021-11-29 124101](https://user-images.githubusercontent.com/83340030/143861974-6c735621-8425-4f90-93eb-c0824262a8b7.png)


![Screenshot 2021-11-29 124130](https://user-images.githubusercontent.com/83340030/143862006-d23b3ef2-e1ca-4ff6-b70f-e20bd16230a7.png)

**Comment by krowlandson** [comment]
Did you also make sure to correctly configure/map the provider to the correct Subscription?

In my example I made the assumption of using the default provider configuration, but you may need to set it to an aliased provider depending on your personal setup.

This should match whatever you set for the `azurerm.connectivity` mapping in the module declaration, which should look something like:

```hcl
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "1.1.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  # insert the required input variables here
}
```

In the case of the above configuration, this would be done by adding `provider = azurerm.connectivity` to each of the resources you are declaring for the connectivity Subscription, including data resources. Below is an example of how this would look for the `azurerm_firewall` data resource:

```hcl
data "azurerm_firewall" "westeurope" {
  provider = azurerm.connectivity

  name                = local.fw_name
  resource_group_name = local.rsg_name
}
```

**Comment by manfred0191** [comment]
Awesome. I'm not just excited, I am **totally excited** and even that is an understatement.

**Comment by krowlandson** [comment]
> Awesome. I'm not just excited, I am **totally excited** and even that is an understatement.
> 
> The only thing I have to find out is how to attach the firewall policy to the firewall, but the rest is complete.

Great to hear 💯

**Comment by krowlandson** [comment]
I think attaching the firewall policy could be an interesting one and is maybe something we should add into the base configuration and then having the associated rules created outside of the module only. It's a tricky one though as I think this depends largely on each organisation and how they want to do this.

I'll discuss this with my "network expert" colleagues to figure out the best approach though.

For now, depending on what else you have set for this input, I believe you should be able to attach the policy you created by merging the following into your configuration:

```hcl
  configure_connectivity_resources = {
    settings = {
      # (hidden)
    }
    location = null # or whatever else you set here
    tags     = null # or whatever else you set here
    advanced = {
      custom_settings_by_resource_type = {
        connectivity = {
          westeurope = {            # Change to your target location if needed
            firewall_policy_id = "" # Specify your firewall_policy_id value here
          }
        }
      }
    }
  }
```

Please give this a try and let me know how you get on - we should be adding more documentation about these scenarios at some point.

**Comment by manfred0191** [comment]
Unfortunately this doesn't work. If I put in a typo, he recoognizes it which means he reads the configuration, but when I deploy it he says there is nothing to be changed and the policy isn't attached.

**Comment by manfred0191** [comment]
Sure, let me know if you need more files. I also attach the firewall.tf for you (as txt as I cannot attach .tf as it seems)
[firewall.tf.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/7624849/firewall.tf.txt)

**Comment by krowlandson** [comment]
Whilst I get this setup (might not be today, just to set expectations), are you able to test replacing `azurerm_firewall_policy.hybrid-test-pol.id` with the actual string value of this resource ID to confirm whether this is just a sequencing issue, vs. logic issue within the module.

**Comment by manfred0191** [comment]
No difference

_No changes. Your infrastructure matches the configuration._

**Comment by manfred0191** [comment]
Good morning,
do I need to worry that the firewall policy cannot be attached from the GUI either?

![Screenshot 2021-12-01 111040](https://user-images.githubusercontent.com/83340030/144215368-7e032c16-b3d7-4d56-88be-db96796f1e9f.png)

I am asking because when choosing "Migrate to firewall policy" and create a new firewall policy from there, it's working.

You should try to reproduce this as well if you are testing the whole case....

**Comment by manfred0191** [comment]
Some more news:

I tried to deploy the firewall policy in advance with firewall set to false in the module.

Then I switched to enable true and the firewall was deployed. The policy was not attached, but I was able to attach it from the azure portal this time.

So this step is the only one that still has to be automated

**Comment by krowlandson** [comment]
Great stuff... thank you for these updates. I've not had a chance to look further into this yet but this is on our backlog.

**Comment by mmyl** [comment]
Hello @krowlandson, 

I've read whole conversation and still one question is on top of my mind. Do you have any plans integrating firewall policies and other related resources (UDRs, application rules, NAT rules etc.) in the module? Or this will be left for the user to build up on a side?

Thanks in advance

**Comment by manfred0191** [comment]
As far as I understood it, all these prerequirements are already implemented, The only thing is that I don't know how to set them up and the programmers of the module recommend not to use these features

**Comment by krowlandson** [comment]
Hi @mmyl... as stated by @manfred0191 these resources must be implemented outside of the scope of the module.

You can use dependency inversion as recommended above if you want to reference resources deployed by this module for linking resources where needed.

**Comment by krowlandson** [comment]
> [settings.connectivity.tf.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/7624777/settings.connectivity.tf.txt) Unfortunately this doesn't work. If I put in a typo, he recoognizes it which means he reads the configuration, but when I deploy it he says there is nothing to be changed and the policy isn't attached.
> 
> In the azure portal, there is a menu called "Migrate to firewall policy" in the firewall itself. The dropdown then accepts "Attach an existing firewall policy". Therefore there must be a way to attach it also by terraform

@manfred0191 I think I've just realised why the suggested code wasn't working.

I had accidentally missed the resource type `azurerm_firewall = {}` from the object.

I've updated the example provided in my earlier comment, so please try with that and let me know how you get on with this.

For ease, here's a copy:

```hcl
  configure_connectivity_resources = {
    settings = {
      # (hidden)
    }
    location = null # or whatever else you set here
    tags     = null # or whatever else you set here
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_firewall = { # Added in **UPDATE (8th Dec 2021)**
          connectivity = {
            westeurope = {            # Change to your target location if needed
              firewall_policy_id = "" # Specify your firewall_policy_id value here
            }
          }
        }
      }
    }
  }
```

**Comment by krowlandson** [comment]
> Hi @mmyl... as stated by @manfred0191 these resources must be implemented outside of the scope of the module.
> 
> You can use dependency inversion as recommended above if you want to reference resources deployed by this module for linking resources where needed.

@mmyl - just to add, the reason for our recommendation is simply down to the fact that there are multiple ways a lot of these child/linked resources can be configured, and different organisations will want to use different approaches depending on operational considerations. As such, we didn't feel it was a good idea to be overly prescriptive by baking it into the module.

**Comment by manfred0191** [comment]
Wow, sounds good. Will test it tomorrow morning

**Comment by manfred0191** [comment]
Hey Kevin, I was able to test it. The good news is: it's basically working, which means the policy is attached:

![firwall_azure](https://user-images.githubusercontent.com/83340030/145416304-436947a3-75e2-463d-b9fd-b0511ee628bd.png)

Unfortunately, there are some details to be considered, which in my opinion leads to further discussion:

- the deployment has to be done stepwise. It's not possible to deploy the whole landscape together with the firewall in one terraform execution.
- these steps have to be executed in the correct order, otherwise it doesn't work.

This order is:

1. Run the basic deployment without firewall and everything else in conjunction with firewall.
2. Create the firewall policy and only the policy.
3. Create the firewall without policy attachment (advanced = null).
4. Attach the policy to the firewall
5. Deploy the rest (subnet, firewall policy rules, route table).

Anyway I am glad that it's at least working, although these hurdles mentioned somewhat suck.

Cheers
Manfred

**Comment by krowlandson** [comment]
That's great to hear @manfred0191.

Regarding your concern around sequencing, are you not able to set a `depends_on` between the module and your firewall policy to ensure the firewall policy is created first, and the same for the subnet, firewall policy rules, route table, etc.?

**Comment by manfred0191** [comment]
In my own tf-files, I know how to do that, but how do I set this in the module?

I mean I only know that I have to do these changes in the settings.connectivity.tf .....

**Comment by krowlandson** [comment]
Just to check @manfred0191, is this the kind of issue you faced when trying to deploy in a single hit?

![image](https://user-images.githubusercontent.com/12268562/145428741-8ede8839-fb06-4b06-90f2-b22392bf2890.png)

**Comment by manfred0191** [comment]
Nope, it was something different, I have to look what the error message was

**Comment by krowlandson** [comment]
So I'm not sure there's much we can do about this, but I will look. To maintain clarity and purpose on our issues, I'm going to close this and open a new one to address the specific concern not being investigated.
