### ISSUE TITLE
Subscription override for corp and online

### ISSUE THREAD

**Issue by linus-lysell** [Azure/terraform-azurerm-caf-enterprise-scale#222]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi, 

I am using the enterprise scale module to create corp and online management groups under "Landing Zones" with this config: 
  deploy_corp_landing_zones   = true
  deploy_online_landing_zones = true

How am I supposed to assign my Landing zone subscriptions to corp and online management groups? 

I have tried with the following code in "settings.core.tf": 

locals {
  subscription_id_overrides = {
    root           = []
    decommissioned = []
    sandboxes      = []
    landing-zones  = [] # Not recommended, put Subscriptions in child management groups.
    platform       = [] # Not recommended, put Subscriptions in child management groups.
    connectivity   = [] # Not recommended, use subscription_id_connectivity instead.
    management     = [] # Not recommended, use subscription_id_management instead.
    identity       = [] # Not recommended, use subscription_id_identity instead.
    corp           = ["ID"]
    online         = ["ID"]

  }
}

Have also tried with the Custom landing zone. 
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/docs/wiki/%5BVariables%5D-custom_landing_zones.md

Do I have to add archetype_config_overrides? If the answer is yes, do you have a guide available for how to use archetype config?
https://registry.terraform.io/modules/Azure/caf-enterprise-scale/azurerm/0.0.3-preview

Thanks in advance! 

**Describe the solution you'd like**

**Additional context**

**Comment by matt-FFFFFF** [comment]
Hi @linus-lysell,

Thanks for raising this issue. How have you deployed your `corp` and `online` management groups?

If you have used the `deploy_demo_landing_zones` option, then you can add subscriptions to these management groups using the [`subscription_id_overrides` variable](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/e4019d8f8943cc341ba8fd13ba29c105d48031d1/docs/wiki/%5BVariables%5D-subscription_id_overrides.md) in the module.

```hcl
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "1.0.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.root}/lib"

  deploy_demo_landing_zones = true

  subscription_id_overrides = {
    corp = [
      "00000000-0000-0000-0000-000000000000",
      "00000000-0000-0000-0000-000000000001"
    ]
  }
}
```

If you are using a local to define the subscription_ids, then you can map this as follows:

```hcl
module "enterprise_scale" {
  //...
  subscription_id_overrides = local.subscription_id_overrides
  //...
}
```

Note, that you don't have to specify an empty list for the other management groups. You can be explicit and omit any others that you do not want to manage.

However, if you are deploying `corp` and `online` as a [custom landing zone archetype](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes), then you should use the `subscription_ids` list in that definition, just like the [example `main.tf`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes#maintf).

Hope this helps!

**Comment by linus-lysell** [comment]
Hi, 

Thanks for a quick and good answer. 

I had missed to map the local value. "subscription_id_overrides = local.subscription_id_overrides"
