### ISSUE TITLE
Expose top level variables for built-in archetype configuraitons

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azurerm-caf-enterprise-scale#225]
<p>Simplify the configuration of the built-in management groups by exposing a top-level variable for each one. </p>
<p>e.g. of how this could look: </p>
<pre><code class="hcl language-hcl">variable &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;configure_management_group_management&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; {
  archetype_id = es_landingzones
  parameters = {
    MyPolicyAssignment = {
      MyStringParameter = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;MyValue&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
    }
  }
  access_control = {
    MyRoleDefinition = [
      &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;037d9f0c-f79e-40d5-828d-a5ae3c661003&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; #object id of directory principal
    ]
  }
  deploy_management_resources = true
  configure_management_resources = {
  //... configuration of MG resources
  }
}
</code></pre>

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by matt-FFFFFF** [comment]
Closing as other options being considered
