### ISSUE TITLE
Replace `try()` with `lookup()` where possible

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azurerm-caf-enterprise-scale#227]
<p>Within the module we make regular use of the <code>try()</code> function to allow <em><strong>optional</strong></em> fields to be gracefully skipped when not present in the input variable. </p>
<p>A side-effect of this is a lot of noise in the verbose logging, but this is possibly not the most efficient function to use. </p>
<p>To reduce the impact of this and provide more logical handling of scenarios where the base object exists, but a specific <code>key</code> may or may not exist, the <a href="https://www.terraform.io/docs/language/functions/lookup.html"><code>lookup()</code> function</a> would make more sense. </p>

**Comment by roberthstrand** [comment]
If no one is currently working on this, I could take this on. I don't want to just start doing stuff on my own if someone has already started to work on this 😊

**Comment by krowlandson** [comment]
@roberthstrand... No-one working on this yet from our side so if you'd like to contribute that would be awesome.

Just be aware that there are still a lot of legitimate cases where we will still need to use `try()` for cases where the input of a complex object is optional.

We could probably remove these completely but would require building up the objects in layers using tertiaries.

**Comment by krowlandson** [comment]
@roberthstrand - just a heads up that I am partially covering this as part of an upcoming update. The files I will be resolving include the following:

- main.tf
- locals.tf
- connectivity/locals.tf

**Comment by roberthstrand** [comment]
> @roberthstrand - just a heads up that I am partially covering this as part of an upcoming update. The files I will be resolving include the following:
> 
> 
> 
> - main.tf
> 
> - locals.tf
> 
> - connectivity/locals.tf

I went on Christmas vacation and forgot all about this. I will look over the next version and see what remains, thanks for letting me know.

**Comment by krowlandson** [comment]
Upon further investigation and testing, care needs to be taken when using `lookup()` to avoid errors similar to the following:

```shell
╷
│ Error: Invalid function argument
│
│   on ..\..\..\main.tf line 49, in module "management_resources":
│   49:   custom_settings_by_resource_type             = lookup(local.management_resources_advanced, "custom_settings_by_resource_type", local.empty_map)
│     ├────────────────
│     │ local.empty_map is object with no attributes
│
│ Invalid value for "default" parameter: the default value must have the same type as the map elements.
╵
```

Workaround needed before this can be successfully implemented.

**Comment by krowlandson** [comment]
Workaround for the above... if you want an `object()` instead of a `map()` in Terraform, create an `object()` and merge your input into it...

![image](https://user-images.githubusercontent.com/12268562/163124975-e3ab2f51-6bcc-40dc-ad8d-5e2709afc801.png)

I could have done this with actual expected keys with default values, so merge overrides the values, but it felt like a more generic approach would avoid confusion and make the base object generic.

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Closing this issue as this is now considered a coding standard for this module and will be addressed over time as code is refactored.
