### ISSUE TITLE
Hardcoded location value in policy definition

### ISSUE THREAD

**Issue by tohov** [Azure/terraform-azurerm-caf-enterprise-scale#23]
policy_definition_es_deploy_asc_standard.json contains hardcoded 'northeurope' value on "location" at line 126. Should this be a variable?

**Comment by krowlandson** [comment]
Thank you for reporting this @tohov.

This particular value is only controlling the location of the deployment, although I agree this should probably also match the location of the resource(s) being deployed by this policy.

We are due a policy refresh shortly so I will look to ensure this is addressed as a part of that.

**Comment by krowlandson** [comment]
Issue raised at source. Will close this issue once we have this resolved in the source repo and pulled into a future release on the Terraform module.

**Comment by krowlandson** [comment]
This appears to be blocked due to a platform limitation. Will continue to track progress though, so leaving issue open for now.

**Comment by sandman-battelle** [comment]
I'm trying to deploy this to AzureGov and getting a lot of these types of errors and thinking it's related to the hard coded locations

```
Error: reading Policy Definition "9d2b61b4-1d14-4a63-be30-d4498e7ad2cf": policy.DefinitionsClient#GetBuiltIn: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicyDefinitionNotFound" Message="The policy definition '9d2b61b4-1d14-4a63-be30-d4498e7ad2cf' could not be found."
│ 
│   on .terraform/modules/enterprise_scale/locals.policy_assignments.tf line 148, in data "azurerm_policy_definition" "external_lookup":
│  148: data "azurerm_policy_definition" "external_lookup" {

**Comment by krowlandson** [comment]
@sandman-battelle... unfortunately the hardcoded values within some of our templates are due to a limitation in ARM. To overcome this, you can simply copy the required templates into your custom `library_path` and modify this value. The module will then pick these up in preference to the built-in copies.

However I do not believe this is your particular issue based on the above error. Please can you verify that a `Policy Definition` or `Policy Set Definition` exists in the AzureGov cloud with an ID `9d2b61b4-1d14-4a63-be30-d4498e7ad2cf`? This should map to the `[Preview]: Deploy Log Analytics agent to Linux Azure Arc machines` policy. Unfortunately I don't have access an AzureGov cloud environment to validate this.

**Comment by sandman-battelle** [comment]
@krowlandson I think you are correct.  In Azure commercial I can see the policy

```

$ az cloud set -n AzureCloud
Switched active cloud to 'AzureCloud'.

$ az policy definition show --name "9d2b61b4-1d14-4a63-be30-d4498e7ad2cf"
{
  "description": "This policy deploys the Log Analytics agent to Linux Azure Arc machines if the agent isn't installed.",
  "displayName": "[Preview]: Deploy Log Analytics agent to Linux Azure Arc machines",
  "id": "/providers/Microsoft.Authorization/policyDefinitions/9d2b61b4-1d14-4a63-be30-d4498e7ad2cf",
...
```
But AzureGov....

```
$ az cloud set -n AzureUSGovernment
Switched active cloud to 'AzureUSGovernment'.

$ az policy definition show --name "9d2b61b4-1d14-4a63-be30-d4498e7ad2cf"
The policy definition '9d2b61b4-1d14-4a63-be30-d4498e7ad2cf' could not be found.
```

I'm hoping I can export the definitions from commercial and import into my gov tenant.  Any advice before I get down a rabbit hole? I'm happy to work through this and document my work in this repo. Would you like me to open a new issue to continue this conversation?

**Comment by krowlandson** [comment]
@sandman-battelle 
> I'm hoping I can export the definitions from commercial and import into my gov tenant. Any advice before I get down a rabbit hole?

Unfortunately that won't help as the scope of custom Policy Definitions will be different from built-in. It seems unfortunately that the GUIDs do not match across Clouds.

Assuming the "correct" policy is available in AzureGov, you're better off creating a copy of the failing Policy Assignment(s) in your custom lib, and updating the `policyDefinitionId` in the template to point to a valid policy.

I don't think there's much I can do from this side at the moment, but please raise an issue and I'll see whether we can add a switch for different Clouds to automate the re-mapping of IDs.

**Comment by krowlandson** [comment]
Closing issue as stale and no updates forthcoming from the platform to help resolve this.
