### ISSUE TITLE
Ignoring subscriptions added to sandboxes management groups

### ISSUE THREAD

**Issue by nspyke** [Azure/terraform-azurerm-caf-enterprise-scale#24]
As per the recommendation here (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization#define-a-management-group-hierarchy) I've set the default subscription management group to Sandboxes, and then manually moved the Visual Studio subscriptions within the Azure account to that management group.

Subsequently, when I run a plan, Terraform is looking to remove those subscriptions from the Sandboxes management group

```hcl
  # module.cip_enterprise_scale.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/cip-sandboxes"] will be updated in-place
  ~ resource "azurerm_management_group" "level_2" {
        id                         = "/providers/Microsoft.Management/managementGroups/cip-sandboxes"
        name                       = "cip-sandboxes"
      ~ subscription_ids           = [
          - "4551fd90-6a3f-4bcc-9002-xxxxxxxxxxxxx",
          - "78a034e4-11b5-4f96-9543-xxxxxxxxxxxxx",
          - "90dce378-333f-407e-8e3b-xxxxxxxxxxxxx",
          - "f1dd6316-e7e6-453f-91da-xxxxxxxxxxxxx",
            # (2 unchanged elements hidden)
        ]
        # (3 unchanged attributes hidden)
    }
```

Two issues here;
Firstly, I don't know what would happen to those subscriptions should I apply this plan, so I'm rather apprehensive to do so.

Secondly, I know I could just add them to the Terraform subscription_id_overrides definition, but as an organisation with developers who could at any point create their own new Visual Studio subscription, this is not maintainable.

Ideally, it would be great to be able to continue to use subscription_id_overrides, but only on an adding basis. Ignore / don't remove any subscriptions added outside of Terraform.

I'm thinking adding `lifecycle.ignore_changes` to level 1 and 2, similar to below, in `resources.management_groups.tf` should fix this?
```hcl
resource "azurerm_management_group" "level_1" {
  for_each = local.azurerm_management_group_level_1

  name                       = each.value.id
  display_name               = each.value.display_name
  parent_management_group_id = "${local.provider_path.management_groups}${each.value.parent_management_group_id}"
  subscription_ids           = each.value.subscription_ids

  lifecycle {
    ignore_changes = [ subscription_ids ]
  }
}
```

**Comment by krowlandson** [comment]
Great find, and thank you for reporting this @nspyke.

Within the initial Enterprise-scale guidance we haven't made consideration for this however we are actively discussing internally as we decide how best to handle Subscription provisioning with the new [Microsoft.Subscription aliases](https://docs.microsoft.com/en-us/azure/templates/microsoft.subscription/aliases) API.

We've had previous requests regarding `ignore_changes` for this but our concern has always centered around the fact that the module is supposed to be the "guardian" for Subscription placement in the hierarchy as this is how the governance model is enforced. This feels like a much more valid reason for enabling this. I'll look into the possibility of enabling this at a more specific scope, controlled conditionally through a variable stating which Management Group is the "default" to cover this scenario.

I'll add this to our backlog and hope to have an answer for you shortly.

Regarding what will happen if you apply the current config... these Subscriptions will simply be moved to your "Tenant Root Group" if not specified elsewhere in your configuration. This should only cause an issue if you're applying any policies or RBAC at the Sandboxes Management Group scope, but I think you are right to question this and exercise caution.

**Comment by nspyke** [comment]
Ok cool. Thank you. For now, I will just have to keep manually adding the subscriptions until this has been resolved

**Comment by nspyke** [comment]
I've been experimenting a bit more with this issue.
In my Azure account, I've changed the default root management group to Sandbox, as per recommendation.

I previously defined some subscriptions within the Landing Zones management group. When removed from the overrides, I get the following expected plan.
```hcl
  # module.cip_enterprise_scale.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/cip-landing-zones"] will be updated in-place
  ~ resource "azurerm_management_group" "level_2" {
        id                         = "/providers/Microsoft.Management/managementGroups/cip-landing-zones"
        name                       = "cip-landing-zones"
      ~ subscription_ids           = [
          - "1cc22636-197f-44f8-aa2c-xxxxxxxxxxxx",
          - "a58a8145-a5db-4ff7-9b96-xxxxxxxxxxxx",
        ]
        # (3 unchanged attributes hidden)
    }
```
However, I did not define where they should go instead.
After the apply step, they ended up in the default management group, which in my case is Sandbox. 

In a subsequent run however, Terraform is now wanting to remove them from the Sandbox management group.
```hcl
  # module.cip_enterprise_scale.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/cip-sandboxes"] will be updated in-place
  ~ resource "azurerm_management_group" "level_2" {
        id                         = "/providers/Microsoft.Management/managementGroups/cip-sandboxes"
        name                       = "cip-sandboxes"
      ~ subscription_ids           = [
          - "1cc22636-197f-44f8-aa2c-xxxxxxxxxxxx",
          - "a58a8145-a5db-4ff7-9b96-xxxxxxxxxxxx",
            # (6 unchanged elements hidden)
        ]
        # (3 unchanged attributes hidden)
    }
```

But the apply fails with the following error;
```
Error: unable to de-associate Subscription "a58a8145-a5db-4ff7-9b96-xxxxxxxxxxxx" from Management Group "cip-sandboxes": managementgroups.SubscriptionsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Cannot remove subscription from the default management group."

  on .terraform/modules/cip_enterprise_scale/resources.management_groups.tf line 19, in resource "azurerm_management_group" "level_2":
  19: resource "azurerm_management_group" "level_2" {
```

Leaves me with two options, either change the default management group back to Root, or manually add the subscriptions into the Sandbox subscription_id_overrides definition

**Comment by krowlandson** [comment]
Interesting issue. We'll definitely have to consider this when planning how to handle customer defined default Management Groups, so thank you for providing some more details on this.

Obviously when the `Tenant Root Group` is used as both the default root and default location for new Subscriptions, this falls outside of the scope of management for our module, hence why we haven't come across this yet.

One approach would be to exclude your `cip-sandboxes` Management Group from our module completely but then you would lose the policy and RBAC management benefits.

An alternative which may be how we can handle it within the module, but may also be an approach you can build yourself in the meantime...
1. Ensure you handle all Subscription ID assignments againt the module using `var` or `local` list objects;
2. Use [data.azurerm_management_group](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/management_group) as a data source to get a list of all Subscriptions currently in your `cip-sandboxes` Management Group from the `subscription_ids` attribute;
3. Use a logic expression to create a new list from the list of current Subscription IDs (2) which doesn't contain any which are being assigned elsewhere in the module (1), excluding `cip-sandboxes`;
4. Add any Subscription IDs you want to manually assign to it using your list for `cip-sandboxes` Subscription IDs (1);
5. Ensure any duplicates are removed (may not be necessary);
6. Use the resultant list as the input to your `cip-sandboxes` definition;

I'll have to do some experimentation and testing before we can release an update to cover this scenario but please let me know how you get on.

**Comment by matt-FFFFFF** [comment]
This will be fixed when this is implemented

* #223
