### ISSUE TITLE
Error: waiting for Virtual Network Link ... "Virtual network resource not found for..."

### ISSUE THREAD

**Issue by kevinevans1** [Azure/terraform-azurerm-caf-enterprise-scale#243]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform* *:v1.1.0

**azure provider**:2.89.0

**module*connectivity*:

### Description

**Describe the bug**

When deploying connectivity resources via terraform , I run into deployment issues around deployment sequence

**Steps to Reproduce**

1.Terraform init
2. terraform plan (Succeeds)
3. terraform apply failed deployment / manual remediation/ clean-up
**Screenshots**
![image](https://user-images.githubusercontent.com/68919619/146181765-3b8653f6-93de-47ab-b691-866ee7849144.png)

**Additional context**
1st time deployment running Contoso reference

**Comment by krowlandson** [comment]
@kevinevans1, if you look at the code we already have these dependencies managed.

Specifically, the following code shows the `depends_on` block correctly referencing the dependencies:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/ee2b36e88fdf7151f336147a1f562c0adad4b8bc/resources.connectivity.tf#L378-L400

Given the current on-going situation with the APIs as documented in #239, my suspicion at this point is that these are related.

**Comment by krowlandson** [comment]
@kevinevans1 is this still an issue since the main fix for https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/239 has been released?

If not, please provide more details of the code you used to control the `configure_connectivity_resources` input variable so we can try to debug.

**Comment by kevinevans1** [comment]
@krowlandson please close this issue :)
