### ISSUE TITLE
Target only subscriptions during policy assignments

### ISSUE THREAD

**Issue by riyasriy** [Azure/terraform-azurerm-caf-enterprise-scale#245]
Hello Team,

We are doing policy assignments on our organization and currently we are trying to find how to apply policy assignment to a particular subscription in a scope, or target only a particular subscription(s) from the apply pipeline.

I have updated my rover file updating the target_subscription variable to the desired subscription.

-tfstate_subscription_id XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \
-target_subscription XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \

When the plan is run, I can see the target subscription set correctly.

level (current)               : 'level1'
environment                   : 'sandpit'
workspace                     : 'tfstate'
tfstate                       : 'caf_eslz.tfstate'
tfstate subscription id       : 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
target subscription           : 'DEMOAZSG-IAC-SANDPIT-ACN-ENVIRONMENT'
CI/CD enabled                 : 'false'
Symphony Yaml file path       : ''
Run all tasks                 : 'true'
TF_IN_AUTOMATION              : 'true'

I can see the scope is still targeted to 'sandpit' when I run the plan.

And this is my policy assignment:
"properties": {
      "description": "Audit If Access key policies is set to rotate 90 days on Account level",
      "displayName": "Audit Storage Account Access Key policy Rotation days",
      "notScopes": [],
      "parameters": {
        "effect": {
          "value": "Audit"
        }
      },
      "policyDefinitionId": "${root_scope_resource_id}/providers/Microsoft.Authorization/policyDefinitions/Audit-acct-key-pol",
      "scope": "${current_scope_resource_id}",
      "enforcementMode": false
}

Once the policy is applied, the policy is targeted at scope, this makes the policies are applied to all subscriptions inside the scope.
But is there a way to apply policy assignment to a particular subscription.

There is an option I can see to exclude scope. But, Is there a similar way to exclude subscriptions inside a scope or target only subscriptions.
Any assistance would be highly appreciated.

**Comment by krowlandson** [comment]
This is not currently a capability within the [caf-enterprise-scale](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale) module, and not something currently on the roadmap for adding.

I believe this issue is better suited to being raised against the [caf-terraform-landingzones](https://github.com/Azure/caf-)terraform-landingzones) so moving to that repository for further support.
