### ISSUE TITLE
Implement `parameterScope` policy assignment parameter metadata

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azurerm-caf-enterprise-scale#246]
<p>See Azure/Enterprise-Scale#882 </p>
<p>Related to #244 </p>

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
As part of improving the handling of Role Assignments for policies, I think we should implement this as part of the broader work required around issue

- #439 

Closing issue as duplicate, as will track against #439.
