### ISSUE TITLE
Race conditions causing partial deployment of level0 - how to import orphans?

### ISSUE THREAD

**Issue by jkewley** [Azure/terraform-azurerm-caf-enterprise-scale#248]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.1.2

**azure provider**: 2.9.0

**module**: 1.1.1

### Description

I have been trying to lay down a very basic level0 foundation based on the wiki and readmes found in this repo. My first attempt i used `-parallelism=50` based on a video Kevin Rowlandson did with Microsoft DevRadio back in May. This died quickly when it tried to create the second tier of custom management groups under the group named after my `root_name` value. I assumed that this was a race condition and ran it again. This time everything completed.

I soon realized that the MSDN subscription I was going to play with was attached to a tenant which wouldn't allow me to create multiple subscriptions, so I signed up for a brand new Azure account with a personal email and added a couple of subs under it.

I ran the exact same tf config as I did in my original attempt - basically just this:
```
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "1.1.1" # latest as of 12/29/21

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = "jc"
  root_name      = "Josh Corp"

```
This one failed several times with race conditions, complaining that referenced resources weren't found. I had to run `apply` 3-4 times before I realized the 5 or so remaining failures were due to policy defs that had been added by a prior run, but that weren't captured to state for some reason. They're telling me to import:

```
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/jfk/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-SQLElasticPools" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_policy_definition" for more information.
│
│   with module.enterprise_scale.azurerm_policy_definition.enterprise_scale["/providers/Microsoft.Management/managementGroups/jc/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-HDInsight"],
│   on .terraform\modules\enterprise_scale\resources.policy_definitions.tf line 1, in resource "azurerm_policy_definition" "enterprise_scale":
│    1: resource "azurerm_policy_definition" "enterprise_scale" {
```

I tried to just delete the policy definitions in the portal to run `apply` again, but the diagnostics rules are part of a rule set which belongs to another rule set, etc. It'd be easier to pull in the resources using `import`.

I'm new to TF, and this is where I'm unsure of how to proceed. None of these have worked for me:

```
terraform import Deploy-Diagnostics-HDInsight providers/Microsoft.Management/managementGroups/jfk/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-HDInsight

terraform import Deploy-Diagnostics-HDInsight /providers/Microsoft.Management/managementGroups/jfk/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-HDInsight

terraform import azurerm_policy_definition.Deploy-Diagnostics-HDInsight /providers/Microsoft.Management/managementGroups/jfk/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-HDInsight
```
as well as several others which I knew wouldn't work.
I think the problem is that I don't know the naming path for these resources and, being new to TF, I don't know how to discover them.

I guess two things here 
- I wanted to share my high failure rate with the team. It was surprising.
- I'd like some help figuring out how to import the policy defs which were created but not added to state

**Comment by jkewley** [comment]
I ran a `terrafrom destroy` to start over and had the root race condition happen again on a fresh `apply`:

```
Plan: 174 to add, 0 to change, 0 to destroy.
module.enterprise_scale.azurerm_management_group.level_1["/providers/Microsoft.Management/managementGroups/jfk"]: Creating...
module.enterprise_scale.azurerm_management_group.level_1["/providers/Microsoft.Management/managementGroups/jfk"]: Still creating... [10s elapsed]
module.enterprise_scale.azurerm_management_group.level_1["/providers/Microsoft.Management/managementGroups/jfk"]: Still creating... [20s elapsed]
module.enterprise_scale.azurerm_management_group.level_1["/providers/Microsoft.Management/managementGroups/jfk"]: Creation complete after 22s [id=/providers/Microsoft.Management/managementGroups/jfk]
module.enterprise_scale.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/jfk-decommissioned"]: Creating...
module.enterprise_scale.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/jfk-sandboxes"]: Creating...
module.enterprise_scale.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/jfk-platform"]: Creating...
module.enterprise_scale.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/jfk-landing-zones"]: Creating...
╷
│ Error: unable to create Management Group "jfk-landing-zones": managementgroups.Client#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Permission to Microsoft.Management/managementGroups on resources of type 'Write' is required on the management group or its ancestors." Details=[{"raw":"Management Group ID: '/providers/Microsoft.Management/managementGroups/jfk'"}]
│
│   with module.enterprise_scale.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/jfk-landing-zones"],
│   on .terraform\modules\enterprise_scale\resources.management_groups.tf line 19, in resource "azurerm_management_group" "level_2":
│   19: resource "azurerm_management_group" "level_2" {
│
```
I just ran apply again and those items were created and the level0 config ran to completion.

Is this something that is just a known issue with Terraform? Didn't have these kinds of issues with ARM.

**Comment by krowlandson** [comment]
@jkewley unfortunately I'm not able to reproduce this problem.

To help with diagnosis, are you able to confirm whether you tried to delete the `root` Management Group and re-run deployment from fresh?

Please also confirm whether you are using `jc` or `jfk` as the `root_id` value, as your code and the errors do not match. Thank you

**Comment by KingBain** [comment]
Having a similar issue as the user except using bicep scripts https://github.com/Azure/CanadaPubSecALZ/issues/129

I believe CAF and CanadaPubSecALZ are related/cousins of the MS cloud framework :)

**Comment by jkewley** [comment]
apologies, we abandoned this in favor of trying to get CAF/rover to stand up the same bits. Testing this in the same azure tenant, so I can't rerun to confirm race condition, but when I have time I'll come back here. 
Wish CAF/Rover was as simple as this project, but we're going to try to use CAF/rover for landing zones so we need the launchpad assets to be rover-friendly
