### ISSUE TITLE
404 url

### ISSUE THREAD

**Issue by DanGiffen** [Azure/terraform-azurerm-caf-enterprise-scale#26]
Hi,

Dead link on this one.

![image](https://user-images.githubusercontent.com/38534725/104898082-14331280-5971-11eb-8523-1ec20dbc27aa.png)

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/modules/terraform-azurerm-caf-enterprise-scale-archetypes/lib

**Comment by krowlandson** [comment]
Well spotted, thank you. This was missed when we updated the naming convention for our child module to reduce the risk of hitting file path limits on Windows (without [enabling long file paths](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later)).

I'll add this to the next release.

In the meantime, you can find the built-in module library here:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/modules/archetypes/lib

**Comment by DanGiffen** [comment]
No problem at all Kevin. Good stuff, thanks.
