### ISSUE TITLE
Create Wiki docs page for role assignments

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#262]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The module provides a mechanism by which to create Role Assignments as part of the resources hierarchy.
Currently, the Wiki doesn't provide clear guidance on how to do this.

**Describe the solution you'd like**

Create a Wiki page describing the options for creating Role Assignments using the module.

**Additional context**

**Comment by jtracey93** [comment]
@PaulJohnston88 assigning this to you as discussed 👍

**Comment by krowlandson** [comment]
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-and-Assign-Custom-RBAC-Roles#assign-role
