### ISSUE TITLE
Feature Request - update documentation to alleviate ambiguity

### ISSUE THREAD

**Issue by danailedms** [Azure/terraform-azurerm-caf-enterprise-scale#263]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

Documentation is open to misinterpretation.

**Describe the solution you'd like**

The main.tf snippet in the connectivity example (https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources) implies that if the subscription_id_connectivity value is set to data.azurerm_client_config.core.subscription_id, then the connectivity subscription should be linked to the associated management group. This is only the case when the connectivity resources are deployed by themselves and the core subscription is set to the same as the connectivity subscription. If we deploy connectivity, management and identity resources, and we use the management subscription as our core (for example), then the value should really be set as data.azurerm_client_config.connectivity.subscription_id.

**Additional context**

N/A

**Comment by krowlandson** [comment]
Thank you for your feedback @danailedms.

Do you have any suggestions for how we could make this clearer? Replacing "core" with "connectivity" is a simple rename, but will that help or do you feel it would be clearer if we differentiated between them by using both in the example?

**Comment by danailedms** [comment]
@krowlandson , it would definitely be clearer if both are used in the example and are differentiated between. That way, less experienced users can easily differentiate the additional provider variables from the variables of the root provider.

Root, connectivity and management are all listed in the providers block just above, which is why it is confusing when the connectivity subscription id is set to the value of the core subscription id at the bottom of the example.

**Comment by krowlandson** [comment]
Sounds good, thank you @danailedms... would you be happy to contribute to making this update via a PR covering each of the guide pages for management, connectivity and identity?
