### ISSUE TITLE
Core Management Group Hierachy

### ISSUE THREAD

**Issue by DanGiffen** [Azure/terraform-azurerm-caf-enterprise-scale#27]
Hi,

Is it possible to be able to adapt the core "mandatory" Management Group hierarchy?

e.g. Push then down to the next level. 
I would like a prod\no-prod group under the root and have the Enterprise Scale hierarchy under the prod one.

e.g. Some may not be required. Maybe an on\off toggle?

Thanks
Dan

**Comment by krowlandson** [comment]
Thank you for your question @DanGiffen 

This is generally a more complicated discussion around your motive for why you want to creat the division this way, but I'll do my best to provide a quick answer here.

The core Management Group hierarchy is an all or nothing structure as this is our recommended structure. To disable the core Management Groups, set another Management Group as the parent, or build your own hierarchy whilst still benefiting from the other aspects of our module, you can use the following settings:

```hcl
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.0.8"

  # Mandatory Variables
  root_parent_id            = {{Set to your Tenant Root Group ID}}

  # Optional Variables
  root_id                   = {{Use a unique value for prod/non-prod}}
  deploy_core_landing_zones = false // Setting this value to false will disable our default hierarchy.

  custom_landing_zones = {
    // Enter your custom hierarchy here
  }
```

By doing this, you can use our module to manage the entire hierarchy as you want as a single deployment or you could split into 3:
- One for your "customer root" prod/non-prod MGs
- One for the prod hierarchy under your "customer root" MGs
- One for the non-prod hierarchy under your "customer root" MGs

However, as Management Groups don't have a cost associated with them, our usual recommendation to clients asking this would be to either:
- Use a single core hierarchy for all environments and use Subscriptions to segregate prod/non-prod workloads within the Landing Zones.
- Deploy the core hierarcy into your tenant twice, once for each of prod/non-prod with a unique root ID.

Of course this also depends on what your other motives are for making this differentiation. If you are doing this for testing policy releases and other changes to the deployment, a side-by-side deployment works well. It also works well if you want to consciously implement different policies for your full prod/non-prod stack (although we wouldn't recommend this as this can negatively impact testing as part of release management for your application workloads). If you need to segregate prod/non-prod workloads at the network hub-level then this may also make some sense, although we would actually recommend deploying multiple hubs within the same hierarchy instead to achieve policy consistency for the reasons I mention above about consistency. 

Hope this helps? If you want to provide some more details about your planned layout, I'd be happy to offer further insights based on our experience if that helps, or more detail on how best to do this using the module?

**Comment by DanGiffen** [comment]
Thanks Kevin, really appreciate the detailed reply. The design came through from an opportunity with a customer of ours. Not entirely sure on the reasoning, didn't make sense to me, will look into further based on your suggestions. Your module looks great, just running through some testing testing. Policy as Code was an area I'm looking at so this could plug in nicely.

**Comment by DanGiffen** [comment]
Hi Kevin, sorry me again :) If I turn the core landing zone flag to "false" and define a custom hierarchy I get a "nothing to deploy". If I set to "true" the plan confirms my additional hierarchy plus to ES standards. I guess there a dependency to deploy the level 1 root MG?

**Comment by krowlandson** [comment]
> Hi Kevin, sorry me again :) If I turn the core landing zone flag to "false" and define a custom hierarchy I get a "nothing to deploy". If I set to "true" the plan confirms my additional hierarchy plus to ES standards. I guess there a dependency to deploy the level 1 root MG?

My guess would be that you have skipped a level in the hierarchy. I would suggest ensuring you have an existing Management Group specified for the `root_parent_id` value, and that all child Management Groups in the hierarchy are linked to this either directly or indirectly with the `parent_management_group_id` value for each entry in the `custom_landing_zones` object. The module should work the rest out for you and "grow your branch of the resource hierarchy tree".

Hope this helps.

**Comment by DanGiffen** [comment]
Thanks Kevin really appreciate the speedy responses. Yep that helps. Sorry I assumed it would still create my level 1 MG with the "deploy_core_landing_zones" flag at false. I brought the whole hierarchy into the custom landing zone config and all good. Onto Policy and RBAC.

**Comment by krowlandson** [comment]
Closing issue as I believe this is now resolved.
