### ISSUE TITLE
Unexpected ID from Role Definitions

### ISSUE THREAD

**Issue by RAWRitsCloud** [Azure/terraform-azurerm-caf-enterprise-scale#275]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

1.1.2

**terraform**: 1.1.6

**azure provider**: 2.93.1

**module**: enterprise_scale

### Description

The ID in the Output from `azurerm_role_definition` appears to have the "|" inside of it indicating the scope, however having this means when using the ID output it is causing an error in the definition as it sees the definition ID as having the "|" character at the end.

```
azurerm_role_definition = {
       enterprise_scale = {
/providers/Microsoft.Authorization/roleDefinitions/56ad2a7e-cda9-5638-b81e-4bfd940fe9c1 = {
               assignable_scopes           = [
                   "/providers/Microsoft.Management/managementGroups/dev",
                ]
               description                 = "Enterprise-scale custom Role Definition. Grants full access to manage Virtual Network subnets, but no other network resources."
               id                          = "/providers/Microsoft.Authorization/roleDefinitions/56ad2a7e-cda9-5638-b81e-4bfd940fe9c1|/providers/Microsoft.Management/managementGroups/dev"
               name                        = "[DEV] Network-Subnet-Contributor"
               permissions                 = [
                   {
                       actions          = [
                           "Microsoft.Authorization/*/read",
                           "Microsoft.Insights/alertRules/*",
                           "Microsoft.ResourceHealth/availabilityStatuses/read",
                           "Microsoft.Resources/deployments/*",
                           "Microsoft.Resources/subscriptions/resourceGroups/read",
                           "Microsoft.Support/*",
                           "Microsoft.Network/*/read",
                           "Microsoft.Network/virtualNetworks/subnets/*",
                        ]
                       data_actions     = []
                       not_actions      = []
                       not_data_actions = []
                    },
                ]
               role_definition_id          = "56ad2a7e-cda9-5638-b81e-4bfd940fe9c1"
               role_definition_resource_id = "/providers/Microsoft.Authorization/roleDefinitions/56ad2a7e-cda9-5638-b81e-4bfd940fe9c1"
               scope                       = "/providers/Microsoft.Management/managementGroups/dev"
               timeouts                    = null
            }

```

Error message when calling the output:
`With error: Status=400 Code="InvalidRoleDefinitionId" Message="The role definition ID '56ad2a7e-cda9-5638-b81e-4bfd940fe9c1|' is not valid.`

**Comment by krowlandson** [comment]
i.e. what leads to the error message?

**Comment by krowlandson** [comment]
Just trying to second guess things here, but are you trying to use the `id` field from the resource when creating a Role Assignment?

If so, have you tried using `role_definition_resource_id` instead?

As per the example in the provider docs, this is the attribute which should be used as an input to the `azurerm_role_assignment` resource:

```hcl
data "azurerm_subscription" "primary" {
}

data "azurerm_client_config" "example" {
}

resource "azurerm_role_definition" "example" {
  role_definition_id = "00000000-0000-0000-0000-000000000000"
  name               = "my-custom-role-definition"
  scope              = data.azurerm_subscription.primary.id

  permissions {
    actions     = ["Microsoft.Resources/subscriptions/resourceGroups/read"]
    not_actions = []
  }

  assignable_scopes = [
    data.azurerm_subscription.primary.id,
  ]
}

resource "azurerm_role_assignment" "example" {
  name               = "00000000-0000-0000-0000-000000000000"
  scope              = data.azurerm_subscription.primary.id
  role_definition_id = azurerm_role_definition.example.role_definition_resource_id
  principal_id       = data.azurerm_client_config.example.object_id
}
```

My reason for thinking the above may be your issue is the fact that the `id` field from Terraform contains the scope too. In your case, the value for `id` is `/providers/Microsoft.Authorization/roleDefinitions/56ad2a7e-cda9-5638-b81e-4bfd940fe9c1|/providers/Microsoft.Management/managementGroups/dev`.

Instead, I think you want to use `role_definition_resource_id` which is `/providers/Microsoft.Authorization/roleDefinitions/56ad2a7e-cda9-5638-b81e-4bfd940fe9c1`.

**Comment by RAWRitsCloud** [comment]
Hey @krowlandson you are absolutely correct! I do want the role definition resource ID instead! I didn't read the field enough to actually notice that though!

Thank you!
