### ISSUE TITLE
[Bug Report] log analytics workspace solutions fail in WESTUS3

### ISSUE THREAD

**Issue by Justin-DynamicD** [Azure/terraform-azurerm-caf-enterprise-scale#276]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.1.5

**azure provider**: 2.97.0

**module**: 1.1.2

### Description

**Describe the bug**

This is likely an Azure issue, but I couldn't find any clear documentation on why this shouldn't work so I'm posting here just in case.

Attempting to deploy the management submodule into WESTUS3 will fail when attempting to link the Log Analytics workspace to the automation account:

>Error: creating Linked Service 'contoso-la/Automation' (Resource Group "contoso-mgmt"): operationalinsights.LinkedServicesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="Conflict" Message="The regions of the resources do not match the expected mapping. See https://aka.ms/regionmappings for more information on supported region mappings."

**Additional context**

changing to another region such as WESTUS2 resolves the issue.

May be problematic, but we may consider adding a validation condition to limit the module deployment only to regions that support all the resources.

**Comment by SteveBurkettNZ** [comment]
As per the [link](https://aka.ms/regionmappings) included in the error text, you can only map Azure Automation to Log Analytics workspaces for limited regions. WestUS2's on the [Supported mapping](https://docs.microsoft.com/en-gb/azure/automation/how-to/region-mappings#supported-mappings) list, but WestUS3 is not. So believe this is working as expected, and yes, validation of supported regions might help prevent some confusion there.

**Comment by krowlandson** [comment]
Hi @Justin-DynamicD and thank you for logging this issue, and @SteveBurkettNZ for your support.

We have intentionally not put restrictions in place within the module for scenarios like this because these things can change on the platform and we don't want to have to maintain the list of supported locations.

> Another example where you may face this issue is when using locations which don't support Availability Zones for resources like gateways and firewall which have their AZ configuration controlled by a simple SKU value.

As you've discovered, deploying to a region with support for these capabilities works but another approach (if you must use a region which doesn't support creation of the Linked Service) is to make the following changes to your code:

1. Set the following values to false to disable Log Analytics solutions which depend on the Linked Service:
    1. `configure_management_resources.settings.log_analytics.config.enable_solution_for_change_tracking`
    2. `configure_management_resources.settings.log_analytics.config.enable_solution_for_updates`
2. Add `link_log_analytics_to_automation_account = false` to the `configure_management_resources.advanced` input:

Below is an example of what this may look like:
```hcl
  configure_management_resources = {
    settings = {
      log_analytics = {
        enabled = true
        config = {
          retention_in_days                           = 30
          enable_monitoring_for_arc                   = true
          enable_monitoring_for_vm                    = true
          enable_monitoring_for_vmss                  = true
          enable_solution_for_agent_health_assessment = true
          enable_solution_for_anti_malware            = true
          enable_solution_for_azure_activity          = true
          enable_solution_for_change_tracking         = false # Set to false as depends on Linked Service
          enable_solution_for_service_map             = true
          enable_solution_for_sql_assessment          = true
          enable_solution_for_updates                 = false # Set to false as depends on Linked Service
          enable_solution_for_vm_insights             = true
          enable_sentinel                             = true
        }
      }
      security_center = {
        enabled = true
        config = {
          email_security_contact             = var.email_security_contact
          enable_defender_for_acr            = true
          enable_defender_for_app_services   = true
          enable_defender_for_arm            = true
          enable_defender_for_dns            = true
          enable_defender_for_key_vault      = true
          enable_defender_for_kubernetes     = true
          enable_defender_for_oss_databases  = true
          enable_defender_for_servers        = true
          enable_defender_for_sql_servers    = true
          enable_defender_for_sql_server_vms = true
          enable_defender_for_storage        = true
        }
      }
    }

    location = null
    tags     = null
    advanced = {
      link_log_analytics_to_automation_account = false # Disable deployment of the Linked Service
    }
  }
}

```

Using the configuration like this should allow you to make the most of the management solution in locations with this feature availability constraint.

_**We are also actively working with the product teams to see whether we can get broader roll-out of this specific capability to the platform. If you can confirm on this issue for tracking we will use this as evidence of demand to hopefully further prioritise this.**_

**Comment by krowlandson** [comment]
@Justin-DynamicD @SteveBurkettNZ - if either of you have access to a customer or partner CSA in Microsoft, please can you ask them to get in contact with me regarding this issue? I would like to talk them through an internal process for getting this escalated with the product engineering teams. All customer evidence we can gather will greatly help us with this! Thank you

**Comment by Justin-DynamicD** [comment]
@SteveBurkettNZ thank you for the confirmation.  I posted anyway as WESTUS3 was announced in February, but that particular link was last updated in Jan ... so I wasn't certain if there was merely a documentation gap. Seems like it's current after all :)

@krowlandson hear you loud and clear when it comes to not wanting to maintain a compatibility list with the cloud rate of change. The company I work at is a managed partner so I'll see what I can do about escalating through internal channels.

**Comment by Justin-DynamicD** [comment]
closing the issue as it was confirmed to be working as intended.
