### ISSUE TITLE
I would be happy to see an example - policy & access_control

### ISSUE THREAD

**Issue by SteffenKohlhagen** [Azure/terraform-azurerm-caf-enterprise-scale#28]
Hello Kevin,
first of all many thanks for your effort with the repro :-)

Would you have an example for me, I can find the right values in the portal.azure.... :
```
 parameters = {
     policy_assignment_id = {
     param_name_1 = param_value_1

    }
     }
    access_control = {
    role_definition_name = {
    "member_1_object_id"
    }
```

I would also be happy to write the wiki article following this?

**Comment by tohov** [comment]
@SteffenKohlhagen Do you mean the archetype_config_overrides config block?

**Comment by tohov** [comment]
Here's one example that I've used (involves also syntax for lists)

`archetype_config_overrides = {
    root = {
      archetype_id   = "es_root"
      parameters     = {
        ES-Allowed-Locations = {
          "listOfAllowedLocations": [
              "westeurope",
              "northeurope"
            ]
        }
        ES-Allowed-RSG-Locations = {
          "listOfAllowedLocations": [
              "westeurope",
              "northeurope",
              "uksouth",
              "ukwest"
            ]
        }
        ES-Deploy-ASC-Monitoring = {
          "networkSecurityGroupsOnSubnetsMonitoringEffect" = "Disabled"
          "sqlDbEncryptionMonitoringEffect" = "AuditIfNotExists"
        }
      }
      access_control = {}
    }
  }`
  
  So you have to input the policy assignment name and the depending what type of parameter is expected you fill in the parameter and values.
  
  Have not tried to modify any role definitions yet.

**Comment by SteffenKohlhagen** [comment]
thx! that helps :-)

**Comment by krowlandson** [comment]
Thank you for your example @tohov 

Just a point to note... due to the way Go handles objects derived from a loosely defined schema, there's an interesting issue which comes up within the `parameters` block. To make this optional and because the values from one Policy Assignment to another are going to vary, we cannot define a tight schema on this object. As such, Terraform treats these as `tuples`. As such, it means all values must be of the same type. In the example above you are OK because `ES-Allowed-Locations` and `ES-Allowed-RSG-Locations` only reference lists, whilst `ES-Deploy-ASC-Monitoring` only references strings.

If you had a Policy Assignment which required a combination of different parameter value types this would cause an error.

To get around this, we actually use `jsondecode()` within the module so you can input all values as type `string` regardless of what the actual value is supposed to look like. To support the "native" object types used above we actually catch errors on `jsondecode()` then try with the provided value but may remove this in the future.

As such, we would also recommend that you always provide your values as JSON encoded strings. To do this, you can simply wrap your existing values in the `jsonencode()` function.

```hcl
archetype_config_overrides = {
    root = {
      archetype_id   = "es_root"
      parameters     = {
        ES-Allowed-Locations = {
          "listOfAllowedLocations" = jsonencode([
              "westeurope",
              "northeurope",
            ])
        }
        ES-Allowed-RSG-Locations = {
          "listOfAllowedLocations" = jsonencode([
              "westeurope",
              "northeurope",
              "uksouth",
              "ukwest",
            ])
        }
        ES-Deploy-ASC-Monitoring = {
          "networkSecurityGroupsOnSubnetsMonitoringEffect" = jsonencode("Disabled")
          "sqlDbEncryptionMonitoringEffect" = jsonencode("AuditIfNotExists")
        }
      }
      access_control = {}
    }
  }
```

**Comment by krowlandson** [comment]
I should also mention that we plan to simplify the readme and create additional documented guidance in GitHub using the wiki as you suggest @SteffenKohlhagen so please keep an eye out and feel free to contribute :)

**Comment by tohov** [comment]
Nice! @krowlandson you might just have saved me a ton of troubleshooting work, because sooner or later I would have gotten an error on that one.

**Comment by AlexBevan** [comment]
Thanks for the policy examples, having some issues with access_control

This works (built in standard roles):
```        access_control = {
          Owner = ["66ebc7b5-8a3b-4c0a-bd58-6b72879de304"]
        }
```
But this does not work (custom role):
```
        access_control = {
          ES-Network-Subnet-Contributor = ["66ebc7b5-8a3b-4c0a-bd58-6b72879de304"]
        }
```

Also the README has them in a map {} but i get an error and can only get it working in a list []

Any help appreciated!

**Comment by LaurentLesle** [comment]
I had to add the key and wrap it in square brackets and upper case 

![image](https://user-images.githubusercontent.com/4702224/109394263-1a99ae80-7961-11eb-8bf5-c5f69ecafb75.png)

**Comment by krowlandson** [comment]
> I had to add the key and wrap it in square brackets and upper case
> 
> ![image](https://user-images.githubusercontent.com/4702224/109394263-1a99ae80-7961-11eb-8bf5-c5f69ecafb75.png)

Sorry, slow response but just to confirm that to ensure uniqueness of the `name` field for Role Definitions, we prefix the provided `name` with the scope at which is created (usually you root, as specified by the input variable `root_id`) in the format mentioned by @LaurentLesle 

i.e. transform to uppercase, and wrap in square brackets, followed by a space

I am now working specifically on documentation updates so will look to ensure we are making this clearer in the Wiki.

**Comment by krowlandson** [comment]
Would welcome feedback on the latest updates published here ahead of pushing to the live Wiki:

[[Variables] archetype_config_overrides](https://github.com/krowlandson/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-archetype_config_overrides)

and

[Working with the archetype_config object](https://github.com/krowlandson/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions#working-with-the-archetype_config-object)

Does this help to make this clearer or do you require additional information?

**Comment by krowlandson** [comment]
Still need to update the [[Variables] custom_landing_zones](https://github.com/krowlandson/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-custom_landing_zones) page to provide coverage for this.
