### ISSUE TITLE
Update policy_set_definition_es_deploy_ascdf to reference Defender for Containers

### ISSUE THREAD

**Issue by johankardell** [Azure/terraform-azurerm-caf-enterprise-scale#280]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I just noticed that the policy set definition "policy_set_definition_es_deploy_ascdf" references the old "enableAscForKubernetes " and "enableAscForRegistries" - and not the new "Defender for Containers". ASC for Kubernetes and ASC for ACR is deprecated, so this should be replaced by the new built-in policy that can deploy "Defender for Containers".

**Describe the solution you'd like**

Remove the references to the old policies that references deprecated functionality and replace with the new policy: "/providers/Microsoft.Authorization/policyDefinitions/c9ddb292-b203-4738-aead-18e2716e858f"

**Additional context**

**Comment by jtracey93** [comment]
Thanks for raising this👍 Going to close this as we already have this tracked in #264 as we have made the policy change upstream already so just need to pull the latest into the TF module 👍
