### ISSUE TITLE
default_location being ignored?

### ISSUE THREAD

**Issue by gawainXX** [Azure/terraform-azurerm-caf-enterprise-scale#288]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
1.1.6
**azure provider**:
2.98.0
**module**:

### Description

**Describe the bug**

default_location appears to be ignored, Any plans I generate only reference useast.

**Steps to Reproduce**
Running the following Main.TF
```
# Configure Terraform to set the required AzureRM provider
# version and features{} block.

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.77.0"
    }
  }
}

provider "azurerm" {
  features {}
}

# Get the current client configuration from the AzureRM provider.
# This is used to populate the root_parent_id variable with the
# current Tenant ID used as the ID for the "Tenant Root Group"
# Management Group.

data "azurerm_client_config" "core" {}


# Declare the Terraform Module for Cloud Adoption Framework
# Enterprise-scale and provide a base configuration.

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "1.1.3"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  default_location = "westus"

  subscription_id_connectivity  = data.azurerm_client_config.core.subscription_id
  deploy_connectivity_resources = true
}
```

**Additional context**

variables.tf is configured as follows
```
# Use variables to customize the deployment

variable "root_id" {
  type    = string
  default = "test"
}

variable "root_name" {
  type    = string
  default = "REDACTED"
}

variable "default_location" {
  type    = string
  default = "westus"
}

variable "log_retention_in_days" {
  type    = number
  default = 30
}

variable "security_alerts_email_address" {
  type    = string
  default = "myemail@mydomain.net" # Replace this value with your own email address.
}

variable "connectivity_resources_location" {
  type    = string
  default = "westus"
}

variable "connectivity_resources_tags" {
  type = map(string)
  default = {
    demo_type = "deploy_connectivity_resources_custom"
  }
}
```

lib/archetype_definition_customer_online.json has the following configuration
```
{
  "customer_online": {
    "policy_assignments": ["Deny-Resource-Locations", "Deny-RSG-Locations"],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {
        "Deny-Resource-Locations": {
          "listOfAllowedLocations": [
            "westus",
            "westus2",
          ]
        },
        "Deny-RSG-Locations": {
          "listOfAllowedLocations": [
            "westus",
            "westus2",
          ]
        }
      },
      "access_control": {}
    }
  }
}
```

**Comment by SteveBurkettNZ** [comment]
Not your problem, but line in **main.tf** should read:
`default_location           = var.default_location`

That'll get main.tf to reference your variables.tf file for the location setting.

Saying that, default_location does seem to work, we deploy to australiaeast ok.

**Comment by gawainXX** [comment]
Ah yeah, I had set it to var.default_location at one point but ended up
manually declaring it Incase it wasn't picking up the car for whatever
reason
Any thoughts on why it may insist on trying to build resources in useast?

**Comment by krowlandson** [comment]
@gawainXX are you able to provide any additional information showing why you believe the `default_location` is being ignored?

I've just run a test plan using the config you provided, and it uses `westus` as seen in the below example from my plan:

![image](https://user-images.githubusercontent.com/12268562/156537624-52c6df89-32f4-4eaf-8bc0-dc38fdb47f03.png)

A couple of additional points to note:

1. We would recommend using the latest release, as the one you have specified is now a few iterations old.
2. Most of the variables you've declared in `variables.tf` are not being used as you haven't mapped them to anywhere within the module declaration. I would advise looking at the examples in our Wiki for how to customise configuration of things like the [management](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Management-Resources-With-Custom-Settings) and [connectivity](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings) settings. Once this is done, you will see a few subtle differences, such as the config for the example above being updated to include your custom tags:

![image](https://user-images.githubusercontent.com/12268562/156537771-4aeb5299-02f0-40aa-a3ec-71defc16fc49.png)

Also, thank you @SteveBurkettNZ for the additional support on this issue 👍🏻

**Comment by gawainXX** [comment]
I was able to get through this issue after moving the following files to a new directory and running a TF init.

main.tf
variables.tf
lib/archetype_definition_customer_online.json

After that the plan reference the correct region I had specified, Something must have been getting left behind as residual after having previously ran an apply using the default vaules.

**Comment by krowlandson** [comment]
Interesting, I've not observed this behaviour but good to know for awareness. Thank you for sharing your feedback @gawainXX
