### ISSUE TITLE
Bug Report - Incorrect links in Wiki documentation

### ISSUE THREAD

**Issue by roblongdon-contino** [Azure/terraform-azurerm-caf-enterprise-scale#290]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
NA
### Description
Multiple broken *.md links in wiki pages:

Example:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/docs/wiki/%5BExamples%5D-Deploy-Management-Resources.md

Link at bottom of the page 404s.

[Management resources with custom settings](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/docs/wiki/%5BExamples%5D-Deploy-Management-Resources-With-Custom-Settings)

Change to [Management resources with custom settings](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/docs/wiki/%5BExamples%5D-Deploy-Management-Resources-With-Custom-Settings.md)

**Steps to Reproduce**
See above
**Screenshots**
NA (404)

**Additional context**

Works fine navigating through Wiki, just not through code directly.

**Comment by krowlandson** [comment]
Hi @roblongdon-contino thank you for logging this issue.

I've had a look and believe the links are correct, but you should be viewing this content in the context of the Wiki, not by browsing the repository.

For the page you mention above, please use the following link and you will see the links you mention should all work as expected:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Management-Resources

**Comment by roblongdon-contino** [comment]
OK, thanks Kevin. I'll navigate through the wiki route.
