### ISSUE TITLE
Missing data policies

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#295]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

The Terraform implementation is currently missing some of the policies included within the ARM implementation relating to data services, such as the following:

![image](https://user-images.githubusercontent.com/12268562/157405402-033b398d-fea2-4247-8599-49f2a1857a01.png)

**Describe the solution you'd like**

To ensure feature parity between implementations, these policies should be included within the Terraform implementation of ALZ.

**Additional context**

**Comment by krowlandson** [comment]
@jtracey93 are these included in the Bicep implementation?

**Comment by jtracey93** [comment]
@krowlandson Looks like they are. https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/lib/policy_definitions/policy_definition_es_deny_databricks_nopublicip.json

**Comment by krowlandson** [comment]
We also appear to have the definitions (pulled in by automation) but not the assignments:

![image](https://user-images.githubusercontent.com/12268562/157406591-819a2db0-0b1a-4090-b31c-8263c88e8a17.png)
