### ISSUE TITLE
What is the reason for this example?

### ISSUE THREAD

**Issue by mlomat** [Azure/terraform-azurerm-caf-enterprise-scale#298]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello guys, 

Can someone explain me reason for this example: 
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/docs/wiki/%5BExamples%5D-Deploy-Using-Module-Nesting.md 

I don't understand use case here, it's easier to achieve this same with custom Landing Zone / dummy Management group. What benefits is giving this example? 

    "${var.root_id}-example-mg" = {
      display_name               = "${upper(var.root_id)} Example Lg"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-online-example-1" = {
      display_name               = "${upper(var.root_id)} Online Example 1"
      parent_management_group_id = "${var.root_id}-example-mg"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "customer_online"
        parameters     = {}
        access_control = {}
      }
    }

**Comment by krowlandson** [comment]
@mlomat thank you for your question.

In some cases, customers wish to break apart their deployment across multiple pipelines, sometimes with delegated administration at different scope to meet security and governance requirements.

Some customers also prefer to manage their deployments in smaller units of scale (i.e. fewer resources per deployment).

Module nesting allows our customers to have a flexible approach to building out their Azure landing zones using this module.

**Comment by krowlandson** [comment]
In short, yes you are only creating two Management Groups in this example but you can change the configuration to update this as needed.

The example is only really intended to show how to create the distinct deployments, rather than to do something specifically useful.

To see a better example of using the module in this way, please see the latest test framework update here:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/1288f401ad8cf85b3e527729a4dddded58aef2ef/tests/modules/test_003_add_mgmt_conn/main.tf#L1-L146

**Comment by mlomat** [comment]
Ok, now I get it, make sense for me, and I will also use it to split deployments. Thanks! 
Maybe it will be more clear if default setup will be "deploy_core_landing_zones = false" and should be explicitly set to true when deploying. Or even better to allow choice which part of Enterprise scale you need. 
Something like: 
deploy_core_landing_zones = 
{
deploy_platform = 
  {
  connectivity=true
  identity=false
  management=true
}
decommissioned = true
sandbox = false
}

I have currently case where I will probably have 2 nested levels of Enterprise Scale with only some elements and most of them will be optional and could be added in the future. If I have such option with config, I won't need to implement this through Custom Landing Zones. 

Best
Mateusz

**Comment by krowlandson** [comment]
Thank you for the feedback @mlomat. Interestingly we did consider changing the default for `deploy_core_landing_zones` to `false` but we fell this is too risky for customers already using this module in production.

I will close this issue now as I don't believe there is anything we will change in the module regarding this, but please feel free to re-open if you have any further questions regarding your scenario above.
