### ISSUE TITLE
Any ETA if and when Hub network(s) for an Azure Virtual WAN network topology will be added

### ISSUE THREAD

**Issue by giovannifl** [Azure/terraform-azurerm-caf-enterprise-scale#301]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**
Please can you confirm if and when Hub network(s) for an Azure Virtual WAN network topology should be available ?

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources

Is somebody working on it ?
Thanks

**Describe the solution you'd like**

**Additional context**

**Comment by krowlandson** [comment]
Closing as the above hopefully answers this question.
