### ISSUE TITLE
Deny-Subnet-Without-Nsg - Seems to prevent deployment of subnets with terraform

### ISSUE THREAD

**Issue by hmb133** [Azure/terraform-azurerm-caf-enterprise-scale#302]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:  1.1.3

**azure provider**: 2.99

**module**: archtypes, policy_definitions

### Description

Hi,
Issue isn't so much with your code, it is more with a particular policy Deny-Subnet-Without-Nsg
I know this possibly isnt the right place, perhaps it would be better raised at the https://github.com/Azure/Enterprise-Scale however seeing as its a terraform specific issue I thought I would raise it here.

This policy once assigned seems to render it impossible to deploy subnets with Terraform due to subnet<->NSG association being split out to a separate resource in relatively recent versions of the azurerm provider, and the provider feature to assign an NSG to a subnet inline has been completely removed (which is a good thing)

As the subnet is deployed initially without an NSG, and then the NSG is attached in a subsequent resource definition, this policy flags and denies the creation of the subnet

**Steps to Reproduce**

resource "azurerm_subnet" "subnet" {

    for_each                = var.subnets
    name                    = each.value.name
    resource_group_name     = var.resource_group[each.value.resource_group_index].name
    virtual_network_name    = each.value.virtual_network_name
    address_prefixes        = each.value.address_prefixes

}

resource "azurerm_subnet_network_security_group_association" "nsg_association" {

    for_each                    = var.subnets
    subnet_id                   = azurerm_subnet.subnet[each.key].id
    network_security_group_id   = var.network_security_group[each.value.security_group_index].id
}

Causes the below error when deployed to landing zone with Deny-Subnet-Without-Nsg assigned

`creating/updating Subnet: (Name "<subnet name>" / Virtual Network Name "<vnet name>" / Resource Group "<resource group name>"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="RequestDisallowedByPolicy" Message="Resource '<subnet name>' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"pol-es - Subnets should have a Network Security Group\",\"id\":\"/providers/Microsoft.Management/managementgroups/<redacted>-landingzones/providers/Microsoft.Authorization/policyAssignments/Deny-Subnet-Without-Nsg\"},\"policyDefinition\":{\"name\":\"Subnets should have a Network Security Group\",\"id\":\"/providers/Microsoft.Management/managementGroups/<redacted>/providers/Microsoft.Authorization/policyDefinitions/pol-es-Deny-Subnet-Without-Nsg\"}}]'." Target="<subnet name>" AdditionalInfo=[{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"type","expressionKind":"Field","expressionValue":"Microsoft.Network/virtualNetworks/subnets","operator":"Equals","path":"type","result":"True","targetValue":"Microsoft.Network/virtualNetworks/subnets"},{"expression":"name","expressionKind":"Field","expressionValue":"<subnet name>","operator":"NotIn","path":"name","result":"True","targetValue":["GatewaySubnet","AzureFirewallSubnet","AzureFirewallManagementSubnet"]},{"expression":"Microsoft.Network/virtualNetworks/subnets/networkSecurityGroup.id","expressionKind":"Field","operator":"Exists","path":"properties.networkSecurityGroup.id","result":"True","targetValue":"false"}]},"policyAssignmentDisplayName":"pol-es - Subnets should have a Network Security Group","policyAssignmentId":"/providers/Microsoft.Management/managementgroups/<redacted>-landingzones/providers/Microsoft.Authorization/policyAssignments/Deny-Subnet-Without-Nsg","policyAssignmentName":"Deny-Subnet-Without-Nsg","policyAssignmentParameters":{},"policyAssignmentScope":"/providers/Microsoft.Management/managementgroups/<redacted>-landingzones","policyDefinitionDisplayName":"Subnets should have a Network Security Group","policyDefinitionEffect":"Deny","policyDefinitionId":"/providers/Microsoft.Management/managementGroups/<redacted>/providers/Microsoft.Authorization/policyDefinitions/pol-es-Deny-Subnet-Without-Nsg","policyDefinitionName":"pol-es-Deny-Subnet-Without-Nsg"},"type":"PolicyViolation"}]`

**Screenshots**

**Additional context**

Sorry for the initial submission of this i fat fingered ctrl+enter

**Comment by krowlandson** [comment]
Hi @hmb133, thank you for your question.

As you have already identified, our policies are managed in the upstream [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale) repository, but in the case of this specific policy, the challenge you are facing is actually a limitation of the way Terraform interacts with Azure.

We actually have this specific issue documented under the [Getting Started](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Getting-Started#additional-considerations-when-deploying-landing-zone-resources-with-terraform) page in our Wiki, where you will see our recommendation:

> One remediation is to override the policy assignment and change the policy effect from deny to audit.

Before we close this issue, do you have a specific ask around this?

For additional context, we have discussed whether to update the module defaults for the Terraform module, but as this is the recommended setting we decided to leave this to customers to update if wanted/needed.

**Comment by hmb133** [comment]
Thanks Kevin, no that answers my question. That'll teach me to read the manual.

I also don't see any other way around it besides switching to audit, I just thought I'd ask as I'm sure you would have considered this.

Thanks for the response!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by krowlandson** [comment]
Great stuff, thank you for confirming @hmb133
