### ISSUE TITLE
Policy assignments using User Assigned Identities are not supported

### ISSUE THREAD

**Issue by larsakerlund** [Azure/terraform-azurerm-caf-enterprise-scale#304]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `1.1.3`

**azure provider**: `2.99.0`

**module**: `1.1.3`

### Description

**Describe the bug**

When trying to create a policy assignment which uses user assigned identities, the module fails with the following error:

```
│ Error: Invalid function argument
│
│   on .terraform\modules\enterprise_scale\resources.policy_assignments.tf line 28, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│   28:       if lower(iv) == "systemassigned"
│
│ Invalid value for "str" parameter: string required.
```

Looking into the source code, it is clear that the identity block only supports system assigned identities:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/1288f401ad8cf85b3e527729a4dddded58aef2ef/resources.policy_assignments.tf#L19-L33

```
```

**Steps to Reproduce**

1. Create a user assigned identity
2. Refer to the user assigned identity in a policy assignment
3. Run `terraform plan`

**Comment by krowlandson** [comment]
Hi @larsakerlund... I believe this is still a limitation in the Azure provider for Terraform:

[![image](https://user-images.githubusercontent.com/12268562/158853612-865188d0-b2de-4f62-a4d4-68a9f23a424b.png)
](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_policy_assignment#type)

Once support for User Assigned Identities is available within the provider, we will look to add this support to the module. If available in time, we will try to include this as part of fixing issue #266.

**Comment by larsakerlund** [comment]
Thanks @krowlandson! Good catch regarding the provider, I completely missed that it doesn't support this yet. There's an open issue regarding this: https://github.com/hashicorp/terraform-provider-azurerm/issues/14087

**Comment by krowlandson** [comment]
@larsakerlund... Yes, and hopefully they resolve this soon. I will close this issue for now as this is already something we are tracking in the background and will add once support is available in the provider.
