### ISSUE TITLE
Bug Report - AzureRM provider 3.0.0 availability zones error

### ISSUE THREAD

**Issue by dan-dimitrov** [Azure/terraform-azurerm-caf-enterprise-scale#309]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 0.15.0

**azure provider**: 3.0.0 and 3.0.1

**module**: 1.1.2

### Description

**Describe the bug**

Build validation fails with the following message...
<img width="807" alt="image" src="https://user-images.githubusercontent.com/97536685/160115146-774a0116-5bb5-466d-b18d-7fa6e2f4984a.png">

This seems to be caused by the availability zones update in version 3.0.0 of the Azure RM provider which was released in the last 24 hours (https://www.hashicorp.com/blog/terraform-azurerm-3-0-brings-enhanced-azure-function-support).
 
**Steps to Reproduce**

1. Ensure provider version is not specified (this defaults to the latest 3.0.1).
2. Execute terraform init.
3. Execute terraform validate - this will throw the error message above.

**Screenshots**

Provided aboove.

**Additional context**

Explicitly specifying provider version 2.99.0 resolves the issue.

**Comment by krowlandson** [comment]
Thank you for reporting this @dan-dimitrov 

For now we would recommend setting the required provider version to no greater than version `2.99.0` and we will look at the impact of addressing this for the next release.

**Comment by dan-dimitrov** [comment]
For the purpose of matching this to search results. The error message received in plain text is...

```
│ Error: Unsupported argument
│ 
│   on .terraform/modules/enterprise_scale/resources.connectivity.tf line 122, in resource "azurerm_public_ip" "connectivity":
│  122:   availability_zone       = each.value.template.availability_zone
│ 
│ An argument named "availability_zone" is not expected here.

│ Error: Unsupported argument
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_definitions.tf line 12, in resource "azurerm_policy_definition" "enterprise_scale":
│   12:   management_group_name = try(basename(each.value.scope_id), null)
│ 
│ An argument named "management_group_name" is not expected here.
```

**Comment by jtracey93** [comment]
For those wondering how to pin your `azurerm` provider to `2.99.0` please see: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#pinning-your-provider-version

**Comment by mlomat** [comment]
Thanks @dan-dimitrov  for reporting this... I am fighting with this issue since 2h... All my deployments failed.

**Comment by matt-FFFFFF** [comment]
Please see v2.0.0 release that supports v3.0.2 and above of the provider.
