### ISSUE TITLE
Copy/paste error - policy_definition_es_deploy_hub.json

### ISSUE THREAD

**Issue by WilliamDahlen** [Azure/terraform-azurerm-caf-enterprise-scale#31]
Hi, the displayname and description of "azfw" object in the [policy_definition_es_deploy_hub.json](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_hub.json) is wrong. Probably a copy/paste error.

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/fe4ad5b67fde8f47d5181dc2fbfaab4695c3e418/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_hub.json#L44

Best regards!

**Comment by krowlandson** [comment]
Good catch... thank you @WilliamDahlen

I will ensure this gets resolved at source for when we perform our next policy refresh.
