### ISSUE TITLE
Policy Assignment `Deploy-Private-DNS-Zones` of archetype `es_corp` is missing permissions on Connectivity Management Group

### ISSUE THREAD

**Issue by nikolai-fra** [Azure/terraform-azurerm-caf-enterprise-scale#310]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: v1.0.11 </p>
<p><strong>azure provider</strong>: 2.86.0 </p>
<p><strong>module</strong>: v1.1.0 </p>
<h3 id=description>Description </h3>
<p>We have defined a custom landing zone with archetype_id <code>es_corp</code> below the <code>&quot;${var.root_id}-landing-zones&quot;</code> ManagementGroup.
The <code>es_corp</code> archetype assigns the <code>Deploy-Private-DNS-Zones</code> policy set on it's scope. </p>
<p>This policy set contains among others the policy &quot;Configure Container registries to use private DNS zones&quot; (with id <code>/providers/Microsoft.Authorization/policyDefinitions/e9585a95-5b8c-4d03-b193-dc7eb5ac4c32</code>).
That's a DINE policy linking private endpoints in landingzones via <code>privateDnsZoneGroup</code> to the Privatelink Private DNS Zone deployed in the Connectivity Subscription. </p>
<p>Now when deploying a Private Endpoint for an ACR the DINE deployment fails with the following error message:
<code>{&quot;code&quot;:&quot;DeploymentFailed&quot;,&quot;message&quot;:&quot;At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.&quot;,&quot;details&quot;:[{&quot;code&quot;:&quot;LinkedAuthorizationFailed&quot;,&quot;message&quot;:&quot;The client '&lt;some id&gt;' with object id 'XXXXX' has permission to perform action 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups/write' on scope '/subscriptions/&lt;subscription id below landingzone management group&gt;/resourcegroups/&lt;some rg&gt;/providers/Microsoft.Network/privateEndpoints/private-endpoint-&lt;some name&gt;/privateDnsZoneGroups/deployedByPolicy'; however, it does not have permission to perform action 'Microsoft.Network/privateDnsZones/join/action' on the linked scope(s) '/subscriptions/&lt;connectivity subscripition&gt;/resourceGroups/&lt;root_id&gt;-dns/providers/Microsoft.Network/privateDnsZones/privatelink.database.windows.net' or the linked scope(s) are invalid.&quot;}]}</code>
(error message edited to redact IDs) </p>
<p>The XXXXX object_id matches to the SystemAssigned identity of the poliy set assignment in Azure AD (Enterprise application &quot;Deploy-Private-DNS-Zones&quot;) </p>
<p>The policy mentioned above defines 
<code>
    &quot;roleDefinitionIds&quot;: [
            &quot;/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7&quot;
          ]
</code>
(= Network Contributor)
The Network Contributor role is assigned at the management group level at the scope the policy set is assigned.
(with two more roles comming from the policy set assignment:
<img src="https://user-images.githubusercontent.com/84312293/160419679-5fbc6223-7177-4b30-826e-997b593b37ac.png" alt=image>
) </p>
<p>But the SystemAssigned Identity does NOT have any permissions at the Connectivity subscription scope. </p>
<p>Therefore the error. </p>
<p>When we've deployed custom policies to DINE privateDnsZoneGroups for private link subresources not covered by the builtin policies we encountered the exact same error.
We added an role assignment at the Connectivity subscription scope (and the landingzone MG scope of course) and the DINE deployments worked afterwards. </p>
<p>Probably the CAF module should add such an role assignment at the Connectivity Management Group scope? </p>
<p>Note: We don't have deployed the &quot;Connectivity Resources&quot; via this module. We have deployed the required Privatelink Private DNS Zones in the required resource group with our own terraform code. But I was not able to find the missing role assignment in this module's code to be created when the &quot;Connectivity Resources&quot; would be used. </p>

**Comment by krowlandson** [comment]
@nikolai-fra this is a great ask, and very timely too as we were discussing this just last week.

To create the Role Assignments, we have to determine the Role Definition(s) required by the Policy Definition(s) being assigned. This is one of the steps already performed by the module.

We then need to identify the scope(s) at which the Role Assignment(s) need to be created. Currently we are only able to use the scope of the corresponding Policy Assignment, but we are looking to make use of the relatively new metadata values for parameters within a Policy Definition which allow us to identify parameters which contain a resource ID for something which the Role Assignment must cover.

You can see a little more about this by reviewing the `metadata.assignPermissions` attribute under [Parameter properties for a Policy Definition](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#parameter-properties).

This may take a while to reach the top of our backlog, but we are hoping to use this feature to drive support additional scopes when creating these Role Assignments, and you can see this in the following refactor of how we create Role Assignments to fix #266 (pending PR):

https://github.com/krowlandson/terraform-azurerm-caf-enterprise-scale/blob/23020c03c2e5d45a7e6675da53769046c5b674f4/resources.role_assignments.tf#L24-L50

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Going to close as tracking on #439

**Comment by krowlandson** [comment]
Trigger ADO Sync
