### ISSUE TITLE
Question - nesting

### ISSUE THREAD

**Issue by mlomat** [Azure/terraform-azurerm-caf-enterprise-scale#314]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello Team, 

I am working on nested structure for Enterprise Scale. I found out a way to deploy second level of ES to have 
ES main and nested one, but I want to customize second one more. I don't want to have Sandboxes there and decommissioned, because will be enough to have one at main ES level in my case. Even if it's possible, I will remove second root and assign nested Landing Zones and Platform directly to main Landing Zone as it is in green box. Green box has been deployed also with nested Enterprise scale, but it's not easy to use benefits from terraform-azurerm-caf-enterprise-scale framwork, because I cannot easily inject custom configuration into template. 
My question is: Do you see any way to achieve what I need, without fork from your project? Especially how to remove Decom and Sandbox? 

![image](https://user-images.githubusercontent.com/7577121/160624606-bc546367-5cee-4c30-997d-fe6391a211b2.png)

Thanks! 
Mateusz

**Comment by matt-FFFFFF** [comment]
Hi @mlomat 

Can I ask why you want to use two instances of the module to achieve this?

It is possible to do what you what you describe using a single instance, and then defining additional LZs using the `custom_landing_zones` feature, however I am aware of some organizations that require delegated identities and separation of duties.

**Comment by mlomat** [comment]
Hi @matt-FFFFFF, sure you can. It's because of delegation of duties between different business units. From one perspective they want to manage "their" stuff themselves, from another perspective some business units don't have resources to do this themselves. So we need to have hybrid. Central location for BUs which cannot handle it themselves and separate level which will overwrite org one. (This will be also optional, so default setup will be to have one level, but if they need, we can deploy it later). 

How can I achieve that with custom_landing_zones? I was able to create config like one below, but no idea how can I easily inject resources for Connectivity, Identity and Management. 

```

locals {
  
name = var.name
display_name = (var.display_name != null) ? var.display_name : title(var.name)

deploy_platform_details = (var.deploy_platform == true && var.deploy_platform_details != null) ? var.deploy_platform_details : {
    connectivity = true
    identity = true
    management = true
}

main =  {
      "${var.root_id}-${local.name}" = {
      display_name               = "${local.display_name}"
      parent_management_group_id = "${var.root_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
}

platform =  {
      "${local.name}-platform" = {
      display_name               = "${local.display_name} Platform"
      parent_management_group_id =  var.deploy_root ? "${var.root_id}-${local.name}" : "${var.root_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
}

platform_connectivity =  {
      "${local.name}-platform-connectivity" = {
      display_name               = "${local.display_name} Platform Connectivity"
      parent_management_group_id = "${local.name}-platform"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "es_connectivity"
        parameters     = {}
        access_control = {}
      }
    }
}

platform_identity =  {
      "${local.name}-platform-identity" = {
      display_name               = "${local.display_name} Platform Identity"
      parent_management_group_id = "${local.name}-platform"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "es_identity"
        parameters     = {}
        access_control = {}
      }
    }
}

platform_management =  {
      "${local.name}-platform-management" = {
      display_name               = "${local.display_name} Platform Management"
      parent_management_group_id = "${local.name}-platform"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "es_management"
        parameters     = {}
        access_control = {}
      }
    }
}



landing_zone =  {
      "${local.name}-landing-zones" = {
      display_name               = "${local.display_name} Landing Zones"
      parent_management_group_id = var.deploy_root ? "${var.root_id}-${local.name}" : "${var.root_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
}


}
```

**Comment by matt-FFFFFF** [comment]
Thanks for getting back to me.

If I understand you correctly the parent layer will provide governance to the child layers?

If this is the case, would you need the platform subscriptions and resources in the parent? Or could you achieve this through custom archetype definitions and custom landing zones purely as a governance layer?

At the moment there is no way to avoid the creation of sandboxes and decommissioned, however we may add more flexibility for `v2.0` of the module.

**Comment by mlomat** [comment]
1. Sounds good for v2.0 to add optional sandbox and decom. 
2. I need platform at parent, because some e.g. Connectivity resources will be shared between business units and some will be dedicated for specific one e.g. multiple VPNs / express routes.

**Comment by matt-FFFFFF** [comment]
Thanks for the feedback, this is really useful to understand how the module is being used in the real world.

We will take the customisation of the core management groups as feedback and consider for v2.0.

I am going to close this now as we have #115 logged as an enhancement already.

**Comment by mlomat** [comment]
Thanks! This #115 looks promising ;)
