### ISSUE TITLE
`azurerm_public_ip` prevents support of azurerm provider >= 3.0.0

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#319]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `any`

**azure provider**: `v3.0.0` onwards

**module**: `any`

### Description

**Describe the bug**

As mentioned in #309, the following error occurs when using the latest `v3.0.0` or newer version of the Azure provider for Terraform:
```shell
│ Error: Unsupported argument
│ 
│   on .terraform/modules/enterprise_scale/resources.connectivity.tf line 122, in resource "azurerm_public_ip" "connectivity":
│  122:   availability_zone       = each.value.template.availability_zone
│ 
│ An argument named "availability_zone" is not expected here.
```

**Steps to Reproduce**

1. Configure a root module using `v1.1.4` of the module, and set a version constraint on the provider required version to `v3.0.0` or later.
2. Run `terraform init -upgrade`
3. Run `terraform plan`
4. Observe the error.

**Screenshots**

- Image taken from #309</br>
  ![image](https://user-images.githubusercontent.com/12268562/161043259-edf58742-88aa-48cf-8391-3cbe869c92c7.png)

**Additional context**

This resource attribute was "hard" deprecated in `v3.0.0` so no opportunity was available to make the transition whilst offering support for `v2.x` of the provider.

As such, this will require a complete shift of the module only support provider versions from `v3.0.0` onwards. `v2.x` of the provider will no longer work so need to consider whether this requires a `major` release to support, or will `minor` suffice?

**Comment by roblongdon-wpp** [comment]
Can confirm that pinning the azurerm provider to <3.0.0 is a workaround for now.

**Comment by krowlandson** [comment]
Thank you for confirming @roblongdon-wpp... if you are using the latest `v1.1.4` release, this version constraint should be already included within the module, but we still recommend that you pin to a specific provider version in your root module configuration.

**Comment by matt-FFFFFF** [comment]
Please see v2.0.0 release that supports v3.0.2 and above of the provider.
