### ISSUE TITLE
Options to Deploy Multiple Enterprise scales

### ISSUE THREAD

**Issue by mlomat** [Azure/terraform-azurerm-caf-enterprise-scale#326]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello Team,

Sorry for another question, but I am looking for optimal solution for our org structure and requirements. Is it possible to somehow deploy Enterprise Scale with terraform CAF framework and have azure policy definitions at root level of Management group and assignments at lower levels with different parameters? 

I want to have possibility to deploy multiple enterprise scales, but I don't want to have multiple copies of policy definitions. I was testing it with different setups and I cannot achieve that. Is it possible? 

For example, I would like to have separate Log Analytics workspace for each Product. 

![image](https://user-images.githubusercontent.com/7577121/161732578-190e0f54-b0fe-4ac1-a05d-6b61a89f0846.png)

Best
Mateusz

**Comment by krowlandson** [comment]
Hi @mlomat ... thank you for your question.

Have you reviewed the guidance we recently published for [ISV considerations for ALZ](https://aka.ms/alz/isv)?

It's absolutely possible to achieve the above, but we would recommend considering whether the recommendations from the ISV guidance would result in a preferable architecture.

Answering your question, we have a number of options.

Assuming the `root` Management Group in the above diagram is not the `Tenant Root Group`, I think the best approach would be to deploy the `root` Management Group first, following the guidance officered in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/113#issuecomment-847280289

I would then configure multiple [nested deployments](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Using-Module-Nesting) to create the custom hierarchies under `root` that you mention, following the configuration pattern mentioned in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/126#issuecomment-866718410

If you are happy to include the full recommended set of Management Groups from ALZ, you could just deploy the "out of the box" settings using `deploy_core_landing_zones = true` (_default setting when not specified_) and just run the deployment with `root_parent_id` set to the ID of your custom `root` Management Group, but you may then want to update some of the archetypes to change where policies are deployed.

**Comment by mlomat** [comment]
Hi @krowlandson, 
I am still testing a few things. Please keep it open for few more days, I will close it soon if no question occurs.

**Comment by mlomat** [comment]
I think we can close this one :) I have bugs reported which I found when testing, your example helped me. Thanks!

**Comment by krowlandson** [comment]
Great to hear, thank you for the update. Hopefully we can help with your other questions too!
