### ISSUE TITLE
BGP configuration on VPN gateways

### ISSUE THREAD

**Issue by dan-dimitrov** [Azure/terraform-azurerm-caf-enterprise-scale#334]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can we request for BGP parameters to be exposed on the VPN gateways please. These currently have to be configured through the advanced configuration as per the example below.

```hcl
  advanced = {
    custom_settings_by_resource_type = {
      azurerm_virtual_network_gateway = {
        connectivity = {
          vpngw = {
            (var.connectivity_resources_location) = {
              enable_bgp    = true
              bgp_settings = [{
                asn               = "65515"
                peering_addresses = ["xx.xx.xx.xx"]
              }]
            }
          }
        }
      }
    }
  }
```

**Comment by krowlandson** [comment]
Thank you for logging this @dan-dimitrov

Adding this to the input variable schema will be a breaking change so I will try to include this on the `v1.2.0` release where we will be introducing other breaking changes.
