### ISSUE TITLE
Feature Request - Add AZ Support for Azure Firewall in Secure vHub Model

### ISSUE THREAD

**Issue by jtracey93** [Azure/terraform-azurerm-caf-enterprise-scale#336]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

No

**Describe the solution you'd like**

AZs are now supported for Azure Firewalls deployed in the Secure vHub model (Virtual WAN) as per https://azure.microsoft.com/en-us/blog/boost-your-network-security-with-new-updates-to-azure-firewall & https://docs.microsoft.com/en-us/azure/virtual-wan/virtual-wan-faq#how-are-availability-zones-and-resiliency-handled-in-virtual-wan

This change looks to be to add the zones property to the Azure Firewall in the secure VWAN hub and expose as a variable and default to a sensible value (TBD). This is already done as part of the hub & spoke azure firewall so should be a simple addition before VWAN release.

**Additional context**

**Comment by krowlandson** [comment]
Evidence for incoming fix:

![image](https://user-images.githubusercontent.com/12268562/162942184-17a85351-9751-400a-841b-d5974a66974b.png)

Will not be leaving the Azure Firewall enabled for `westeurope` in test framework though.
