### ISSUE TITLE
Feature Request: Assigning Policies to Subscriptions (roadmap query)

### ISSUE THREAD

**Issue by rfk-nc** [Azure/terraform-azurerm-caf-enterprise-scale#337]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<p>Hi, </p>
<p>We are using the caf-es module for a large UK public sector customer as part of a standardised landing zone deployment that they will use for internal and &quot;internal customer&quot; projects. </p>
<p>One requirement we need to meet is assigning policies to subscriptions (in addition to management groups), and can see that this is work in progress in the current module. </p>
<p>Is there any indication when this functionality will be completed, or any good suggestions on applying the existing policy definition files to subscriptions? </p>
<p>Thanks!
Richard </p>

**Comment by rfk-nc** [comment]
Hi Kevin,

Many thanks for getting back to me, appreciate the response. 

The reason we are interested in this functionality is due to the distributed nature of our customer's environment, with a central IT team delegating many responsibilities to a departmental level.  Some departments will only have one or two applications within a single subscription, but others are much larger and will have multiple subscriptions across multiple management groups.

In fact, we envision the Landing Zone MG structure to look something like this, eventually with 50+ subscriptions in place:

-Org Root
 - Landing Zones
   - Dev
   - Test
   - Prod
     - Dept A
       - Subscription A1
       - Subscription A2
     - Dept B
       - Subscription B1
       - Subscription B2
         - Application C (management group)
           - Subscription C1
           - Subscription C2
  ...

The issue is that, as mentioned, some applications will be comprised of five or six subscriptions, so while we can locate these within their own MG, the subscriptions themselves may still have divergent policy requirements, as some will contain e.g. public vs private connectivity, or different resource types.

We are still just about within the limit of six MG levels, so if we have to use additional layers of those, that could be a possible solution for us, but I thought it worth checking on applying policies directly to subscriptions as well as we'd seen the initial work you've done on this :)

Would be happy to hear any other recommendations you might have as this could help us steer the conversation with the customer.

As an aside, we have done quite a lot of other customisation on top of the es-caf module that I'm sure you would be interested in seeing too (e.g. defining our Management Groups fully within the json archetype files and loading these as custom landing zones, so we have separation between logic and config, but can also dynamically add new MGs by simply dropping a new archetype file into the repo).

We'd be happy to share this with you, when we have it polished up a bit better!

Thanks,
Richard

**Comment by matt-FFFFFF** [comment]
Thanks for your detailed use case information @rfk-nc

We will keep this issue open to track the request and prioritize accordingly.

**Comment by MarcelHeek** [comment]
Also interested, as we could drop additional layer of MG's if this were possible

**Comment by rfk-nc** [comment]
Hi @krowlandson @MarcelHeek 
The point about subscription owners removing the assignments is a really good one I think, and we have also been able to persuade our customer that applying all policies at MG level rather than a mix of MG and subscription is simply more transparent.

We have therefore settled on a management group structure along the following lines:
![image](https://user-images.githubusercontent.com/98461689/170022336-62d2611c-f726-4c1c-9368-36564190e105.png)

.. and will add additional MGs at the lowest level of the hierarchy on a case by case basis if required.

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by Eslam10** [comment]
Hello,
I have the same use case.
In our case we have some custom child MGs under LandingZones MG, some of the subscriptions require additional policies (subscription specific), for instance some subscriptions are used for a certain application on which we need to limit the resource types that will be created on these subscriptions using Azure policy.
Such policy can not be applied on the MG level, and it is different for each subscription.

**Comment by krowlandson** [comment]
Thank you for the additional support on this item @Eslam10 👍🏻 

The voice of our community is important and helps us to prioritize these items, however from a technical perspective this will actually be challenging to implement due to the provider authentication model which links it to a single Subscription for resource creation.

We are evaluating the [AzApi provider](https://registry.terraform.io/providers/Azure/azapi/) to see whether we could integrate this to overcome the scoping challenge but there's still the bigger question around whether this is something we would implement in the module as this approach technically falls outside of the ALZ recommendations.

Please also note @jtracey93's point above around the implications in regard to enforcing governance.

**Comment by Eslam10** [comment]
@krowlandson, Thanks for the feedback. I did a simple test maybe it will help in the case evaluation.

I tested the `azurerm_subscription_policy_assignment` resource with only one provider authentication to one subscription and apply the code to two different subscriptions.

Since this resource has an argument `subscription_id`, it successfully applied the policy to the two different subscriptions, without using `provider alias` in the TF resource.  
For sure, the used SPN should have access to all the subscriptions that this resource will be applied to, which is in my case I applied the permission on the MG level.

**Comment by krowlandson** [comment]
Thank you @Eslam10 ... will definitely check this out as I hadn't appreciated this resource was an exception to the "normal" rule of Subscription scoped resources 😄 

However, we still need to validate the business benefit of adding this to the module, and how it aligns with the broader ALZ guidance so cannot make any promises to add this just yet.

Of course, community contributions are also welcome 😉

**Comment by matt-FFFFFF** [comment]
Hi, after discussion we cannot add this feature to this module. However we do have a sibling module that we may be more suitable for this ask.

Please check out https://github.com/Azure/lz-vending for more info

**Comment by matt-FFFFFF** [comment]
See Azure/terraform-azurerm-lz-vending#117
