### ISSUE TITLE
How can I disable gateway transit on peered networks?

### ISSUE THREAD

**Issue by cn-dylan** [Azure/terraform-azurerm-caf-enterprise-scale#339]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:  v1.1.6

**azure provider**: 2.99.0

**module**: 1.1.4

### Description

We are deploying an environment using this module that has an NVA in place, this is why we want gateway transit to be disabled on the peered VNET's from the hub. How can I disable this?
We are already using custom_settings_by_resource_type to alter the VPN Gateway settings but I can't seem to figure out what the syntax is for the Peerings.

**Comment by jtracey93** [comment]
Hey @cn-dylan,

Thanks for raising this.

I assume this is a requirement from a security perspective, as this setting isn't preventing anything from technically working, right?

Also, just to call out this setting prevents the spokes from being advertised via BGP from the Gateways to on-prem.

As it is today, it is not possible to disable/change the VNET peering setting we set on the Hub VNET side only in this module via a variable or advanced block as seen here:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/0b343c6ba9ce4595a0e494f97d2a439845a1cb2a/modules/connectivity/locals.tf#L1227-L1230

Therefore, our suggestion today would be to handle the peering's outside of the module to handle this scenario.

However, there is value to specify the spoke VNETs still in the module as below:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/0b343c6ba9ce4595a0e494f97d2a439845a1cb2a/variables.tf#L243

If you are planning to use the following setting for DNS as below

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/0b343c6ba9ce4595a0e494f97d2a439845a1cb2a/variables.tf#L359

### Looking ahead

We are currently thinking about our story for custom NVA users/customers and what that means. However, this is in very early phases.

**Comment by krowlandson** [comment]
> ### Looking ahead
> We are currently thinking about our story for custom NVA users/customers and what that means. However, this is in very early phases.

Just to add, it would be great to have your feedback on this point to help us shape this requirement. Thank you!
