### ISSUE TITLE
Ability to rename ASC export resource group name

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/terraform-azurerm-caf-enterprise-scale#342]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Discussed with Kevin to have the ability to rename ASC export resource groups names for a customer deployment, submitting this feature request per discussion

**Additional context**

**Comment by krowlandson** [comment]
Thank you @mbilalamjad

Will address this as part of the next release.

**Comment by krowlandson** [comment]
Adding this in an upcoming PR using an optional input under `configure_management_resources.advanced`, which allows us to set this value using the following configuration setting:

```hcl
  configure_management_resources = {

    # ...

    advanced = {
      asc_export_resource_group_name = "${var.root_id}-security-logs-export"
    }
  }

```

This allows setting the value to whatever you want it to be in the managed Policy Assignment input parameter:

![comparison of pre and post change values for the ascExportResourceGroupName parameter](https://user-images.githubusercontent.com/12268562/164031593-d2b86295-1208-4c15-8d29-b17dc491542e.png)

I've considered whether a more generic approach would add value elsewhere, but this is the only parameter value for policies currently managed by the module which makes sense to be able to customise in this way.
