### ISSUE TITLE
Ability to rename PIP assigned to VPN/ER Gateway

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/terraform-azurerm-caf-enterprise-scale#343]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Discussed with Kevin to have the ability to rename PIP assigned to VPN/ER Gateway for a customer deployment, submitting this feature request per discussion

**Additional context**

**Comment by krowlandson** [comment]
Thank you @mbilalamjad

Should already be addressed within #331 and will be included in our upcoming release.
