### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tpatrizio** [Azure/terraform-azurerm-caf-enterprise-scale#344]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

I cannot find a way to enforce a centralyzed management of private DNS Zones for private links created in the landing zones. Even if I can apply the custom policy **Deny-Private-DNS-Zones** to prevent the creation of DNS zones, I cannot find a DINE policy to automatically create the **privateDNSZoneGroup** in the DNS zone created int the connectivity subscription, as documented in the CAF article: [Private Link and DNS integration at scale](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)

**Describe the solution you'd like**

I'd like to have more information on how to realize what is mentioned in the description of the aforementioned Deny policy: "used in combination with policies that create centralized private DNS in connectivity subscription"

**Additional context**

I'm using the 1.1.4 of the module

**Comment by jtracey93** [comment]
Hey @tpatrizio,

Thanks for raising this. 

Have you seen the policy set definition we include as part of the module called `Deploy-Private-DNS-Zones`?

The definition can be found here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_private_dns_zones.tmpl.json 

This can then be assigned, to an archetype, and parameters provided to help achieve the CAF article you referenced 👍

cc: @krowlandson for any further inputs he may have on this topic 👍

**Comment by tpatrizio** [comment]
> Hey @tpatrizio,
> 
> Thanks for raising this.
> 
> Have you seen the policy set definition we include as part of the module called `Deploy-Private-DNS-Zones`?
> 
> The definition can be found here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_private_dns_zones.tmpl.json
> 
> This can then be assigned, to an archetype, and parameters provided to help achieve the CAF article you referenced 👍
> 
> cc: @krowlandson for any further inputs he may have on this topic 👍

Hi @jtracey93 thanks for pint me to this policy definition. Does it means that applying this policy at the landing zone scope A records are automatically created in the corresponding private DNS zone in the connectivity subscrption? in aother words, does this policy implies that a privateDnsZoneGroups resource is providioned or I need to add another DINE polycy for this to happen?

**Comment by jtracey93** [comment]
Hi @tpatrizio,

Correct this policy set will create the `privateDnsZoneGroups` on private endpoints created and link them to the specified DNS zone, as per the input parameter values you set.

There may be some missing services from the policy set as there may not be a built-in policy for the service at this time, but you can always create a custom one and update the policy set definition with it. However, may be easier to create your own custom policy set definition for this to help you stay up-to-date with module version releases going forward 👍

Hope this helps, let us know

**Comment by tpatrizio** [comment]
> `privateDnsZoneGroups`

That's great! does this means that I have to create my own policy definitions, include all of them into a custom policy set and assign it to the landig zones artifact ? For instance, assuming that a privateDNSZoneGroup should be created for the private endpoint of storage blob, I have to create a policy starting from the ESLZ one **Deploy-DNSZoneGroup-For-Blob-PrivateEndpoint** and assign it to the landing zones management group? Thanks for the clarification

**Comment by jtracey93** [comment]
Hey @tpatrizio,

Today that is correct you would need to create a custom policy set to wrap them all together (custom and built-in). The policy set we provide only groups together the built-in ones today.

Thanks

**Comment by tpatrizio** [comment]
> 
Hi @jtracey93,

I ended up with creating three files in the lib directory: 

- a DINE policy_definition to deploy __privateDNSZoneGroup__ for storage blob as documented [here](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale) at point 3
- a policy_set_definition with the same content of  __policy_set_definition_es_deploy_private_dns_zones.tmpl.json__ plus a reference to the custom policy I created
- a policy_assignment with the same content of __policy_assignment_es_deploy_private_dns_zones.tmpl.json__ plus a reference to my custom policy. 

With all of these in place, I added the __"Deny-Private-DNS-Zones"__ and __"Deploy-Private-DNS-Zones"__ assignments to the custom archetype of the corporate landing zone. Does this makes sense? 
Sorry for asking such trivial questions but I'm newby to Terraform ESLZ and I'm trying to learn by doing with the help of your precious suggestions

**Comment by jtracey93** [comment]
That all sounds correct to me from a high level. 

Just need to ensure it's assigned to an archetype definition or via an extension. 

There are docs for this in the wiki in level 200 and 300

**Comment by tpatrizio** [comment]
> That all sounds correct to me from a high level.
> 
> Just need to ensure it's assigned to an archetype definition or via an extension.
> 
> There are docs for this in the wiki in level 200 and 300

Thanks @jtracey93 it worked perfectly!
