### ISSUE TITLE
Duplicate Role Assignment

### ISSUE THREAD

**Issue by niksheridan** [Azure/terraform-azurerm-caf-enterprise-scale#346]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.0

**azure provider**: 2.70.0

**module**: 0.0.8

### Description

**Describe the bug**

During a complete recreation of management groups, policies and role mapping, an intermittent issue is encountered regarding duplicate role assignments.  Whilst inspecting the values created by the locals in generating the role mapping the following behavior has been observed, an example can be seen below:

```bash
{
  "/providers/Microsoft.Authorization/policySetDefinitions/1a5bb27d-173f-493e-9568-eb56638dde4d" = tolist([])
  "/providers/Microsoft.Authorization/policySetDefinitions/3937f550-eedd-4639-9c5e-294358be442e" = tolist([
    "/providers/microsoft.authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
  ])
  "/providers/Microsoft.Authorization/policySetDefinitions/55f3eceb-5573-4f18-9695-226972c6d74a" = tolist([
    "/providers/Microsoft.Authorization/roleDefinitions/92aaf0da-9dab-42b6-94a3-d43ce8d16293",   <<<<<<< duplicate (LA contrib.)
    "/providers/microsoft.authorization/roleDefinitions/92aaf0da-9dab-42b6-94a3-d43ce8d16293",
  ])
  "/providers/Microsoft.Authorization/policySetDefinitions/e77fc0b3-f7e9-4c58-bc13-cb753ed8e46e" = tolist([
    "/providers/microsoft.authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
  ])
}
```

The resource ID appears to have a difference in case - and only regarding one section of it - which is affecting the distinct functions ability to de-duplicate the list used in the for_each loop and a resulting error in the role assignment as it is being attempted more than once.  In the test environment, oddly there appears to be a degree of tolerance to this that does in some instances work, and continue to do so reliably, and errors only appear during change at high volume.  Role Assignment is the only problem observed. 

Historical issues have been searched, and I could not find a similar problem.  The example above, is not consistent and the nature of this error can affect other roles.  

**Steps to Reproduce**

  Destroy environment
  Reapply environment

**Comment by krowlandson** [comment]
> **module**: 0.0.8

Thank you for logging this @niksheridan ... are you aware of whether this is an issue in newer releases of the module?

Unfortunately, `0.0.8` is quite old now and we are unable to resolve issues in previous releases due to our approach to release management.

We have also done a lot of code changes in this area since this early release so I would not expect this problem to still exist.

**Comment by niksheridan** [comment]
I'll organise an upgrade.  Very grateful for the quick reply. Many thanks.

**Comment by krowlandson** [comment]
Please review the release notes and upgrade guides in the wiki, as there will have been quite a few changes since `v0.0.8` 😄
