### ISSUE TITLE
'Module-managed' Private DNS Zones - Add capability to selectively configure auto-registration on VNET links

### ISSUE THREAD

**Issue by kahawai-sre** [Azure/terraform-azurerm-caf-enterprise-scale#348]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The module does a great job of simplifying & expediting delivery of Platform & Application Landing Zones mapped to defined archetypes, with defaults aligned to reference architecture (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/#azure-landing-zone-conceptual-architecture).

For the Connectivity archetype, under "hub_networks" or "vwan_hub_networks", we can add "spoke_virtual_network_resource_ids". When we do this, the Private DNS Zone VNET links are created/managed automatically as part of the module which is great. This applies to Private DNS Zones created for Azure default private link DNS domains or PaaS services, and also custom Private DNS Zones which can also be enabled in settings under "dns" => "private_dns_zones". This means that most aspects of DNS can be easily managed by the module centrally as part of the Connectivity archetype.

However, for custom Private DNS Zones, one aspect is currently missing: the ability to selectively enable auto-registration on VNET links.

Currently we have to manage DNS Auto-registration on VNET links outside of the module, which is cumbersome, and it really should be a core capability to make centralized management of DNS a more complete feature.

Request: 
Provide a feature to selectively enable DNS auto-registration on VNET links per Private DNS Zone that is managed by the module. 
This could potentially be achieved by mapping a single Private DNS Zone defined in "private_dns_zones", to a particular spoke defined in "spoke_virtual_network_resource_ids" in some way.

Many thanks for all the great work.

**Comment by matt-FFFFFF** [comment]
Hi @kahawai-sre,

Thanks for raising this. I am looking into whether this is a bug or an enhancement.

**Comment by matt-FFFFFF** [comment]
Hi @kahawai-sre,

The auto-registration feature is not implemented yet. We will consider this for a future release.

**Comment by KahawaiMSFT** [comment]
Many thanks @matt-FFFFFF, that would be great. As above if we are going to manage Private DNS centrally with the module, auto-registration would be required.

In the interim, is there a way that auto_registration can be enabled on a given vnet link via "advanced" configuration?
Could you provide an example if possible?

**Comment by kahawai-sre** [comment]
Many thanks @matt-FFFFFF, that would be great. As per above if we are going to manage Private DNS centrally with the module, auto-registration feature would be required.

In the interim, would it be possible to provide an example of how to enable auto-registration on a given vnet link using the "advanced" capability?

**Comment by matt-FFFFFF** [comment]
Hi @kahawai-sre 

We currently do not support the configuration of `azurerm_private_dns_zone_virtual_network_link` resources using the advanced block.

I will create a hotfix release to address this

**Comment by matt-FFFFFF** [comment]
To clarify,

We will use a patch release to implement the advanced variable changes to allow configuration of auto registration.

If there is sufficient evidence to surface this configuration option within 'configure_connectivity_resources', we will use a minor release (at least) with accompanying documentation. Until Terraform provides a stable mechanism for implementing optional properties within complex objects, we disrupt the upgrade experience with every change to the variable input schema.

We will keep this issue open to track this feature request.

**Comment by kahawai-sre** [comment]
Thanks very much @matt-FFFFFF.
Is there scope for the Advanced settings for private DNS zone vnet link config could enable auto-reg based on inputs of (i) Private DNS Zone name & (ii) VNET Resource Id?
i.e. can it be done that way vs having to specify the Resource Id/name of the VNET link itself?

That way we can configure auto-registration on a unique PDNS Zone Name <=> VNET combination in advance, vs hard coding completely based on an existing VNET link deployment.

**Comment by matt-FFFFFF** [comment]
Release v2.0.1 now completed, contains the fix for `custom_settings_by_resource_type`.

You can see testing evidence in #361 

Please let us know if this provides a workable interim solution in lieu of this becoming a "1st class" input variable

Thank you!
