### ISSUE TITLE
Error: Provider configuration not present

### ISSUE THREAD

**Issue by VRThompson** [Azure/terraform-azurerm-caf-enterprise-scale#352]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

### Description

**Describe the bug**

Cloned the GitHub Repo for CAF as I wanted to deploy this into my test subscription using Cloud Shell.

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 3.0.2"...
- Finding hashicorp/time versions matching ">= 0.7.0"...
- Finding hashicorp/random versions matching ">= 3.1.0"...
- Installing hashicorp/azurerm v3.3.0...
- Installed hashicorp/azurerm v3.3.0 (signed by HashiCorp)
- Installing hashicorp/time v0.7.2...
- Installed hashicorp/time v0.7.2 (signed by HashiCorp)
- Installing hashicorp/random v3.1.3...
- Installed hashicorp/random v3.1.3 (signed by HashiCorp)

1. Run Terraform init from VS Code
Terraform has been successfully initialized!
2. Run Terraform Plan from VS Code and I get the following set of errors : 

Error: Provider configuration not present
│
│ To work with azurerm_firewall.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it   
│ has been removed. This occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider
│ configuration to destroy azurerm_firewall.virtual_wan, after which you can remove the provider configuration again.
╵

Plus about 10 more.

![image](https://user-images.githubusercontent.com/104138152/165549071-cf684ce5-58da-4903-8a02-65c4f87e4d8b.png)

**Additional context**

I am new to terraform and unsure how to resolve this.  Please advise.

**Comment by matt-FFFFFF** [comment]
Hi @VRThompson,

Which repo did you clone, can you supply the URL?

If you want to learn how to use this module, Hashicorp have created a learning resource, available here:

https://learn.hashicorp.com/tutorials/terraform/microsoft-caf-enterprise-scale?in=terraform/azure

Let me know if this is useful

**Comment by VRThompson** [comment]
Hi @matt-FFFFFF 

Thank you for getting back to me so quickly.  I cloned : https://github.com/Azure/terraform-azurerm-caf-enterprise-scale.git

Then just tried to run it.

Will also take a look at the URL you provided me.  Just a bit unsure what to do next.

**Comment by VRThompson** [comment]
Matt,

This is a screenshot of what I see in VS Code :

***@***.***

Thanks,
Vince

**Comment by krowlandson** [comment]
Hi @VRThompson 

The module isn't designed to be cloned and run like this. Instead, please follow the guidance provided in [our Wiki](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki).

This will give you the most up to date guidance.

**Comment by matt-FFFFFF** [comment]
Adding: needs author feedback label

Please comment further if assistance is required.
