### ISSUE TITLE
Feature Request: document policy/iniative definitions and assignments

### ISSUE THREAD

**Issue by JasperCodes** [Azure/terraform-azurerm-caf-enterprise-scale#358]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<p>We are using the enterprise-scale module to leverage the recommended set of policies and iniatives that it defines, . </p>
<p>However, it is quite difficult to get an overview of all the policies that the module defines and/or assigns to what scope, you have to match to different policy definition and assignment files to the archetype definition files. As there isn't a specific wiki entry that describes this (or I am unable to find it), I started looking at tools that can do this for me. </p>
<p>That is when I found the <a href="https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md">Enterprise Scale</a> repository, with a document that describes all policy and iniative definitions and default assignments. It seems to be based on the same Enterprise-Scale reference architecture from Microsoft and when I scan table I see the same policy definition names in the table as I see them in enterprise-scale definition files. </p>
<p><strong>Describe the solution you'd like</strong> </p>
<p>I'd like to use the table as documentation source, but first I'd like to be sure that it describes the same policies and assignments as defined in the enterprise-scale module. Can you verifiy this? Maybe that table could be referenced and/or included in the enterprise-scale wiki. </p>
<p>If not, are there any plans to document the policy definitions and assignments of the enterprise-scale module? </p>

**Comment by matt-FFFFFF** [comment]
Hi @JasperCodes 

You are correct in your deduction that this module sources its policies from the upstream Enterprise-Scale repo.

The process of pulling the policy definitions is automated (see the update-policies.yml workflow), and the archetype definitions are updated using pull requests.

Currently we have no plans to duplicate the documentation in this repository but we can certainly link to the upstream document to improve  traceability. Would this be satisfactory?

**Comment by JasperCodes** [comment]
That's great to hear. I understand you would not want to duplicate documentation. Adding a link to the upstream document would help others in the future make the same connection.

Where you also aware that the enterprise scale policy set is advertised on [azadvertizer.net](https://www.azadvertizer.net/azpolicyadvertizer_all.html#%7B%22col_10%22%3A%7B%22flt%22%3A%22ESLZ%22%7D%7D)?

**Comment by matt-FFFFFF** [comment]
Hey @JasperCodes, I was aware of azadvertizer, yes.

I use it regularly 😄 

We could link to it, however it's a third-party service so would need to discuss internally to see if this is something we wanted to do.

We will make the documentation changes in the wiki. Keeping this open to track.

**Comment by jtracey93** [comment]
Linking this to https://github.com/Azure/Enterprise-Scale/issues/980 where we will be making this a lot better hopefully very soon 👍

**Comment by krowlandson** [comment]
Thinking we could use the archetype definition files to auto-generate a Wiki page for this on each release?

**Comment by JasperCodes** [comment]
The documentation as provider by https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md is now much improved. For my purposes it is now easy to understand and use. 

A link to above document and short explanation what the relationship is between the policies implemented by the this module and enterprise-scale repo would suffice for me, like in [this document](https://github.com/Azure/ALZ-Bicep/wiki/PolicyDeepDive) for AZL-Bicep module. Saves you the trouble of writing it yourself.

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by matt-FFFFFF** [comment]
This now exists upstream here: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies

Assuming this can be closed now @JasperCodes
