### ISSUE TITLE
Specifying parameters in policy assignment loses Log Analytics ID

### ISSUE THREAD

**Issue by adhodgson1** [Azure/terraform-azurerm-caf-enterprise-scale#359]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: 1.1.7 </p>
<p><strong>azure provider</strong>: 3.0.2 </p>
<p><strong>module</strong>: 2.0.0 </p>
<h3 id=description>Description </h3>
<p><strong>Describe the bug</strong> </p>
<p>I'm trying to set a parameter on a policy to disable logging of Azure Firewalls to the Log Analytics resource as per a company requirement. I'm not sure whether I am adding the parameter to the correct place in the policy but I am configuring the following set of locals in my code: </p>
<pre><code>locals {
  archetype_config_overrides = {
    root = {
      archetype_id   = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;es_root&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
      parameters     = {
        Deploy-Resource-Diag = {
          FirewallLogAnalyticsEffect = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;Disabled&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
        }
      }
      access_control = local.empty_map
    }
  }
}
</code></pre>
<p>This creates the following change in Terraform: </p>
<pre><code>module.enterprise_scale.azurerm_management_group_policy_assignment.enterprise_scale[&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;/providers/Microsoft.Management/managementGroups/[correct-mg]/providers/Microsoft.Authorization/policyAssignments/Deploy-Resource-Diag&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;] will be updated in-place
  ~ resource &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;azurerm_management_group_policy_assignment&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;enterprise_scale&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; {
        id                   = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;/providers/Microsoft.Management/managementGroups/[correct-mg]/providers/Microsoft.Authorization/policyAssignments/Deploy-Resource-Diag&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
        name                 = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;Deploy-Resource-Diag&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
      ~ parameters           = jsonencode(
          ~ {
              + FirewallLogAnalyticsEffect = {
                  + value = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;Disabled&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
                }
              ~ logAnalytics               = {
                  ~ value = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;/subscriptions/[correct-id]/resourceGroups/[correct-rg]/providers/Microsoft.OperationalInsights/workspaces/[correct-workspace]&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; -&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;gt; &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/[correct-rg]/providers/Microsoft.OperationalInsights/workspaces/[correct-workspace]&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
                }
            }
        )
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
</code></pre>
<p>Is this even the correct way of disabling the functionality of that policy (by sending in the parameter into the policy assignment) and if so what is causing the additional parameter to cause the subscription ID to be lost? </p>

**Comment by adhodgson1** [comment]
Based on further research (#207) I figure I need to specify the loganalytics parameter in the archetype configuration as I am overriding the parameters. I have done this and it has resolved the issue. Are the details in the linked issue still valid (i.e, if I add another value to the policy parameter it loses the subscription_id on the LA instance in the policy)?

**Comment by krowlandson** [comment]
Hi @adhodgson1. Thank you for logging this issue and following up with your further findings.

As you've discovered, we currently only set parameters based on what you provide in the parameter input object. i.e. We don't merge individual parameter inputs per assignment. 

This means as soon as you set one parameter value for a specified assignment, you need to set all which don't have a (suitable) default value.

We took this approach to avoid unpredictable results.

As such I don't believe this is something that we would want to change, but I can see this would benefit from greater clarity on the Wiki page for [archetype_config_overrides](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-archetype_config_overrides) but also with a dedicated example page so I'll keep this issue open to track this update.

Would you be happy that updating the Wiki with clearer guidance would resolve your issue?

Thank you

**Comment by adhodgson1** [comment]
Happy with your resolution here.

**Comment by krowlandson** [comment]
Trigger ADO Sync
