### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ahmetsyildirim** [Azure/terraform-azurerm-caf-enterprise-scale#366]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 2.203.0

**azure provider**: 

**module**: azure/caf-enterprise-scale/azurerm  v:2.0.0

### Description

**Describe the bug**
When following the "[Examples] Deploy Connectivity Resources With Custom Settings" document 
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings

 and using all the provided code as described in the example, I found that terraform validate command is returning the error below:

"**_Starting: Terraform Validate

Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
Version      : 2.203.0
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AAf0uqr)

/opt/hostedtoolcache/terraform/1.1.9/x64/terraform validate
╷
│ Error: Invalid value for module argument
│ 
│   on main.tf line 27, in module "enterprise_scale":
│   27:   configure_connectivity_resources = local.configure_connectivity_resources
│ 
│ The given value is not suitable for child module variable
│ "configure_connectivity_resources" defined at
│ .terraform/modules/enterprise_scale/variables.tf:203,1-44: attribute
│ "settings": attribute "hub_networks": element 0: attribute "config":
│ attribute "virtual_network_gateway": attribute "config": attribute
│ "advanced_vpn_settings" is required.
╵
##[error]Error: The process '/opt/hostedtoolcache/terraform/1.1.9/x64/terraform' failed with exit code 1
Finishing: Terraform Validate_**"

I believe that the root cause of the problem is the document is not synced with the latest changes in the https://github.com/Azure/terraform-azurerm-caf-enterprise-scale repository.

The provided settings.connectivity.tf provided in the "[Examples] Deploy Connectivity Resources With Custom Settings" page is missing the "advanced_vpn_settings".

The bug can be remediated by updating the settings.connectivity.tf snippet in the document page by adding the below block under  gateway_sku_vpn line for all occurrences.

advanced_vpn_settings = {
                  enable_bgp                       = null
                  active_active                    = null
                  private_ip_address_allocation    = ""
                  default_local_network_gateway_id = ""
                  vpn_client_configuration         = []
                  bgp_settings                     = []
                  custom_route                     = []
                }

**Steps to Reproduce**

1. step 1: Follow the steps in the https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings page
2. step 2: Run terraform validate command
3. you get it...

**Screenshots**

![image](https://user-images.githubusercontent.com/1262423/167063875-20b7f799-aaa1-40d6-8f0e-5fcb41eb79d3.png)
![image](https://user-images.githubusercontent.com/1262423/167064023-4bfd0854-631a-4ae0-a41e-df4b3c686b58.png)

**Additional context**

**Comment by jtracey93** [comment]
Thanks @ahmetsyildirim for raising this.

#356 this is being fixed here. cc @matt-FFFFFF

**Comment by matt-FFFFFF** [comment]
fixed by #356
