### ISSUE TITLE
Unable to exclude Azure resource from deploy-resource-diag policy assignment

### ISSUE THREAD

**Issue by adhodgson1** [Azure/terraform-azurerm-caf-enterprise-scale#368]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.7

**azure provider**: 2.99.0

**module**: 1.1.3

### Description

I wish to set the parameter on the Deploy-Resource-Diag policy assignment so it doesn't apply the default Log Analytics diagnostic settings to any Azure firewall created in the management group structure. I did this by updating the archetype overrides as follows:

```
locals {
  archetype_config_overrides = {
    root = {
      archetype_id = "es_root"
      parameters = {
        Deploy-Resource-Diag = {
          logAnalytics               = "/subscriptions/${var.management_subscription_id}/resourceGroups/${var.root_id}-mgmt/providers/Microsoft.OperationalInsights/workspaces/${var.root_id}-la"
          # We want to use custom log settings for the firewalls as we don't want to log all network traffic to Log Analytics
          FirewallLogAnalyticsEffect = "Disabled"
        }
      }
      access_control = {}
    }
  }
}
```

I applied this setting and it went through without errors but still get the policy applied diagnostic settings on my newly created firewall.

I have tried the following:
- Tainting and re-applying the relevant policy assignments in Terraform so the whole policy assignment gets re-created.
- Setting the FirewallLogAnalyticsEffect parameter to an invalid value, this returned an error from Azure with an explanation of the values I can set for that parameter which are the values I was expecting.
- Excluding the Deploy-Resource-Diag policy assignment from the es_root archetype definition. This removed the assignment from the management group structure but firewalls I was creating still had the policy assigned LA diagnostic settings applied.

**Comment by matt-FFFFFF** [comment]
Hi @adhodgson1 

Thanks for logging this issue!

Once you make this change in the archetype configuration, can you confirm in the Azure portal that the `Deploy-Resource-Diag` policy has its effect set to `Disabled` for the firewall policy?

![image](https://user-images.githubusercontent.com/16320656/168166597-cf8fc7c7-d1e2-4a6a-be7d-4218ac7c1531.png)

DeployIfNotExists policies will only remediate resources when they are newly created, or when a remediation task is subsequently created for a resource that in non-compliant. We can see them working by examining the ARM deployments to the scope of the DINE deployment.

If you look at the resource group of the Azure Firewall, in the Deployments view. Can you see the Azure Policy ARM deployments in there?

![image](https://user-images.githubusercontent.com/16320656/168167276-e407b7d4-e94f-46a9-8020-db7d4f6805b9.png)

**Comment by adhodgson1** [comment]
Sorry it isn't a screenshot, I am visually impaired and don't like sending out screenshots in case it sends out sensitive info.Hi. Here is the policy definition in the Azure CLI if that helps.

az policy assignment show --scope /providers/Microsoft.Management/managementGroups/[...] --name Deploy-Resource-Diag
{
  "description": "Ensures that Azure resources are configured to forward diagnostic logs and metrics to an Azure Log Analytics workspace.",
  "displayName": "Deploy-Resource-Diag",
  "enforcementMode": "Default",
  "id": "/providers/Microsoft.Management/managementGroups/[...]/providers/Microsoft.Authorization/policyAssignments/Deploy-Resource-Diag",
  "identity": {
    "principalId": "[...]",
    "tenantId": "[...]",
    "type": "SystemAssigned",
    "userAssignedIdentities": null
  },
  "location": "uksouth",
  "metadata": {
    "createdBy": "[...]",
    "createdOn": "2022-05-09T10:10:59.652327Z",
    "updatedBy": null,
    "updatedOn": null
  },
  "name": "Deploy-Resource-Diag",
  "nonComplianceMessages": null,
  "notScopes": null,
  "parameters": {
    "FirewallLogAnalyticsEffect": {
      "value": "Disabled"
    },
    "logAnalytics": {
      "value": "/subscriptions/[...]/resourceGroups/[...]/providers/Microsoft.OperationalInsights/workspaces/[...]"
    }
  },
  "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/[...]/providers/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics",
  "scope": "/providers/Microsoft.Management/managementGroups/[...]",
  "systemData": {
    "createdAt": "2022-05-09T10:10:59.002329+00:00",
    "createdBy": "[...]",
    "createdByType": "Application",
    "lastModifiedAt": "2022-05-09T10:10:59.002329+00:00",
    "lastModifiedBy": "[...]",
    "lastModifiedByType": "Application"
  },
  "type": "Microsoft.Authorization/policyAssignments"
}

**Comment by matt-FFFFFF** [comment]
Hey @adhodgson1

As per our conversation offline, I think the module is working correctly here so I think the next course of action is to take the policy definition and assign it singularly, with the effect parameter set to Disabled.

I will then deploy an Azure Firewall within the scope of that policy. The policy compliance and the resource group deployments can then be monitored to see if the policy created an ARM deployment.

**Comment by krowlandson** [comment]
Hi @adhodgson1... Do you still require assistance with this?

Just to provide some additional information regarding the policy in question. When you set the effect to `Disabled` it should make the policy effectively "do nothing" however any resources which were previously remediated will not have any settings reverted.

As such, the settings will likely have been applied almost as soon as the resource was created if you deployed the Azure Firewall with this policy in its default configuration.

With the policy set to `Disabled` via the input parameter on the Policy Assignment, you should be able to remove these settings from your firewall and it will still report as compliant. Any newly created firewalls should also retain their default configuration.

Be careful to ensure you correctly set the `logAnaytics` value if using our OOTB policy templates though as we only set this dynamically with the module if you don't provide your own parameters. We can help with this if needed.

**Comment by adhodgson1** [comment]
Ok sorry for this one being open for longer than it should have been. I believe I have it working now with the current firewall with the parameters intact. I am due to create another firewall in a few weeks and if I get a similar behaviour I will get back in touch.

**Comment by krowlandson** [comment]
No worries @adhodgson1... hopefully the above proves useful and you have no further issues but please do reach out again if further assistance is needed.

If you do open a new issue, please try to link back to this one to remind us of the context though.

Thank you
