### ISSUE TITLE
bug: copy paste err: peer_weight vs private_ip_address_allocation

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-caf-enterprise-scale#370]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

2.0.1

**terraform**:NA

**azure provider**: NA

**module**: this

### Description

**Describe the bug**

This seems like a copy paste error: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/246cf7de44369b2a40a1b07fafdd8b8b792e7c35/resources.connectivity.tf#L209

**Steps to Reproduce**

NA

**Screenshots**

NA
**Additional context**
Just browsed some code.

**Comment by matt-FFFFFF** [comment]
Thanks @davidkarlsen for raising this - it indeed does look like a bug.

Let me look into creating a hotfix for it

**Comment by matt-FFFFFF** [comment]
Hi @davidkarlsen 

I have staged this change as a PR into the v2.0.2 release branch

#375
