### ISSUE TITLE
Bug Report: avoid caf moduile version in label

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-caf-enterprise-scale#371]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.1.9

**azure provider**: 3.0.x

**module**: caf 2.0.1

### Description

**Describe the bug**
rather than having the label versioned, like it is today:
`deployedBy : terraform/azure/caf-enterprise-scale/v2.0.1`

it would suffice to tag with:
`deployedBy : terraform/azure/caf-enterprise-scale``

that way you can avoid a gazillion changes on module upgrade, and it is easier to track the relevant changes.

**Steps to Reproduce**

1. run with a caf module version
2. upgrade
3. se a bunch of changes that only touch the label

**Screenshots**
N/A

**Additional context**

N/A

**Comment by matt-FFFFFF** [comment]
Agreed it's a fair point and it would be very distracting when trying to work with a module version upgrade and trying to make sure there were no unwanted changes.

**Comment by matt-FFFFFF** [comment]
Hi @davidkarlsen 

I have staged this change into the release branch for v2.0.2

See #374
