### ISSUE TITLE
Feature Request - Azure AD diagostics to LAW

### ISSUE THREAD

**Issue by rhyspaterson** [Azure/terraform-azurerm-caf-enterprise-scale#372]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<p><strong>Is your feature request related to a problem?</strong> </p>
<p>Not sure if this is a bug or a feature request - and ultimately it is terraform agnostic - but figured I would start here. </p>
<p>When deploying the es module resources, there does not appear to be an automatic integration of the Azure AD diagnostic logs into the management LAW. I assumed - perhaps incorrectly - that this would be a crucial element in the CAF, particularly given the cap on retention for those logs within AAD itself. Maybe there is an asumption that the Sentinel configuration <a href="https://docs.microsoft.com/en-us/azure/sentinel/connect-azure-active-directory">sorts this out for you</a> if you were to deploy it at a later date, or maybe that you're streaming that information elsewhere? </p>
<p>There's a <a href="https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_aad_diagnostic_setting">terraform resource for it</a> in the azurerm provider, which makes it a trivial implementation step. </p>
<p><strong>Describe the solution you'd like</strong> </p>
<p>The optional ability to include aad diagnostic settings as part of the CAF module, and pump it to the LAW created as part of the <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5bUser-Guide%5d-Management-Resources">management and monitoring resources</a>. Something like <code>enable_aad_diagnostics = true</code> in <code>settings.management.tf</code>. </p>
<p>Happy to have a crack at a PR. </p>
<p><strong>Additional context</strong> </p>
<p>None. </p>

**Comment by matt-FFFFFF** [comment]
Hi @rhyspaterson 

Thanks for logging this request!

Initial investigation seems like this could be challenging because of the constraint on the API authentication for the `monitor_aad_diagnostic_setting` resource.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/16320656/167844643-67e66f1d-515f-4934-9f25-0175de5182ef.png">

This would break usage for customers using this in a CI/CD scenario.

We will add it to the backlog as an enhancement and consider for a future release.

In the meantime, this could be configured outside the scope of this module, using the outputs.

**Comment by rhyspaterson** [comment]
Thanks for the quite reply! Yeah I did notice that. 

I guess another option might be to just add a policy under the [Deploy-Resource-Diag](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_resource_diag.tmpl.json) / [Deploy-Diagnostics-LogAnalytics](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json) initative to at least identity via `AuditIfNotExists` the potential non-compliance? Either way, backlog sounds great,

As for accessing the module output, do you suggest something like this? I'm unsure the best way to grab that single attribute from what seems like a complex output. This seems somewhat brittle, but I'm not an expert in HCL.

```hcl
resource "azurerm_monitor_aad_diagnostic_setting" "management_law" {
  name                       = "diagnosticsToLa"
  log_analytics_workspace_id = [for x in module.enterprise_scale.azurerm_log_analytics_workspace.management : x.id][0]
  ...
}
```



Cheers.

**Comment by matt-FFFFFF** [comment]
Hi,

You can use the resource id to access the value in the map. This is knowable as you have used the subscription id as an input to the module (as you should have in the `subscription_id_management` variable)

`module.enterprise_scale.azurerm_log_analytics_workspace.management[/subscriptions/${local.sub_id_mgmt}/resourceGroups/${local.root_id}-mmgt/providers/Microsoft.OperationalInsights/workspaces/${local.root_id}-la]`

You can also use the for loop method, there will either be zero or one items in the map.

**Comment by rhyspaterson** [comment]
That's much better - exactly what I was looking for. Here's the final code for anyone else.

```hcl
resource "azurerm_monitor_aad_diagnostic_setting" "management_law" {
  name                       = "diagnosticsToLa"
  log_analytics_workspace_id = module.enterprise_scale.azurerm_log_analytics_workspace.management["/subscriptions/${var.management_subscription_id}/resourceGroups/${var.root_id}-mgmt/providers/Microsoft.OperationalInsights/workspaces/${var.root_id}-la"].id
  ...
}
```

Thanks mate!

**Comment by matt-FFFFFF** [comment]
Glad to help - I will leave this open to track

**Comment by krowlandson** [comment]
You may also want to consider whether this is something you want to manage within the same deployment (terraform state) or independently?

Regardless, [dependency inversion](https://www.terraform.io/language/modules/develop/composition#dependency-inversion) techniques in Terraform can also be useful.

To do this, you can use a data resource to lookup the LAW (ensure you correctly set dependencies too) and then reference this in your additional code:

```hcl
data "azurerm_log_analytics_workspace" "management" {
  provider = azurerm.management # Set to the required provider to target your Management Subscription

  name                = "${var.root_id}-la"
  resource_group_name = "${var.root_id}-mgmt"

  depends_on = [
    module.enterprise_scale # Assuming you have within the same deployment
  ]
}

resource "azurerm_monitor_aad_diagnostic_setting" "management_law" {
  name                       = "diagnosticsToLa"
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.management.id
  ...
}
```

**Comment by rhyspaterson** [comment]
Thanks mate! Yeah I've not yet come to a conclusion on splitting it out yet. Thanks for pointing out the dependency inversion techniques with the module, I'm familiar with the data elements but, using them with modules and providers is newer to me. This approach does align more with how we surface other Terraform components - looks like a ripper. Thanks!

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by matt-FFFFFF** [comment]
Can't implement so closing for now
