### ISSUE TITLE
Feature Request - Pricing/costing estimates

### ISSUE THREAD

**Issue by rhyspaterson** [Azure/terraform-azurerm-caf-enterprise-scale#378]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<p><strong>Is your feature request related to a problem?</strong> </p>
<p>It's unclear what the potential cost implications are when deploying the CAF, either directly or indirectly. </p>
<p><strong>Describe the solution you'd like</strong> </p>
<p>It would be beneficial to call out the potential cost implications when deploying services into this architecture as configured in its default state. For example, the management subscription punches out a LAW, which I'll admit is a mostly trivial cost. But taking something like the <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_assignments/policy_assignment_es_enable_ddos_vnet.tmpl.json">Enable-DDos-VNET</a> assignment, my reading is if a virtual network is deployed then the recommendation is Azure DDoS Standard (I think it is audit only, but I am not game to test it out), which is currently sitting at over $4,000 AUD per month flat fee. Looking closer, this is called out <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5bExamples%5d-Deploy-Connectivity-Resources">to an extent in the wiki</a>, but cost is not mentioned and rather implied. </p>
<p>Perhaps it might be prudent to be a bit more upfront about cost implications associated with this best practice, even as a warning? If it is indeed mostly policy related, it could be an idea to have somewhere in the repo or wiki a dump of all the policy assignments, even a table to reference, and what is enforced and what is not. Maybe they could even be tagged as ones expected to incur costs, so people can cater for that. I'm sure there is some fun once could have with CI/CD to sort that! That all said, even something in the front page that called out an indicative cost impact would be really beneficial. </p>
<p>Thank you. </p>
<p><strong>Additional context</strong> </p>

**Comment by krowlandson** [comment]
Thank you for logging this @rhyspaterson... this was something which was discussed at length within the team and had a mixed opinion on what we should do.

Within the Terraform module we opted to set the defaults to minimise the risk of "bill shock" by disabling high-cost resource types. But ultimately, we want to ensure that customers are led by the recommended practices rather than costs alone and we would always recommend using the [Azure pricing calculator](https://azure.microsoft.com/en-gb/pricing/calculator/) to understand costs before deploying resources to Azure.

You can also monitor costs using [Cost Management + Billing](https://docs.microsoft.com/en-us/azure/cost-management-billing/cost-management-billing-overview), and implement budgets to help reduce your risk.

I will raise this question again with the team to see whether this is something we can incorporate into our documentation.

**Comment by krowlandson** [comment]
Also, does the following provide sufficient information if we cross link to this from our Wiki?

https://github.com/Azure/Enterprise-Scale/wiki/What-is-Enterprise-Scale#pricing

**Comment by rhyspaterson** [comment]
Thanks for the reply!

Appreciate the cost management and pricing calculator approach, in fact I cross-referenced each policy being deployed and that was what surfaced some of the significant costings associated with them. That the customer/end-user is ultimately responsible for costing is true, but I think being clear that deploying the CAF best practice architecture in its default state will absolutely incur non-insignificant additional cost would be beneficial - particularly if concepts such as DDoS plans are new to them.

> Also, does the following provide sufficient information if we cross link to this from our Wiki?
> 
> https://github.com/Azure/Enterprise-Scale/wiki/What-is-Enterprise-Scale#pricing

I think that would be great! I definitely missed it and read the wiki quite a few times unpicking the what and the how, policies and configuration options. Sorry I missed it though, it does seem fairly clear, and thanks for pointing it out. 

I guess for me a good example of a concerning one is the DDoS plan, just because I believe all you need is a vnet which itself is a 'free' resource and usually considered fairly benign. This approach could also help partners or professional services - who are helping customers adopt best practice, such as CAF - be aware they likely need to forecast CAF induced costings.

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync
