### ISSUE TITLE
Unable to add `azurerm_local_network_gateway` and `azurerm_virtual_network_gateway_connection` resources

### ISSUE THREAD

**Issue by tpatrizio** [Azure/terraform-azurerm-caf-enterprise-scale#380]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

I've deployed the connectivity resources with a VPN gateway but it is still missing the local gateway and the related connection.
Is there a way to add those resources to the same resource group where other connectivity resources are located (firewall, 
virtual network gateway, ...)? I tried to create the `azurerm_local_network_gateway` and `azurerm_virtual_network_gateway_connection` resources after the `enterprise_scale` modue, but I'm not sure how to get access to the resource goup name and location. This attempt was not successfull:

`location                         = module.enterprise_scale.azurerm_resource_group.connectivity.default_location`
`resource_group_name  = module.enterprise_scale.azurerm_resource_group.connectivity.name`

I got the error:

`Error: Unsupported attribute
on main.tf line 223, in resource "azurerm_local_network_gateway" "onpremise-network":
223:   location            = module.enterprise_scale.azurerm_resource_group.connectivity.location
module.enterprise_scale.azurerm_resource_group.connectivity is object with 3 attributes
This object does not have an attribute named "location".`

**Describe the solution you'd like**

Can you point me to the right way to complete the configuration of the VPN gateway ?

Thanks a lot!

**Additional context**

**Comment by krowlandson** [comment]
Thank you for logging your question @tpatrizio 

If I'm correct in my understanding of your question, I believe you are trying to identify the correct reference to use when addressing the resource outputs from the module?

As you have correctly identified, we do not provision `azurerm_local_network_gateway` and `azurerm_virtual_network_gateway_connection` resources using the module so these must be done seperately.

Usually, we recommend using [dependency inversion](https://www.terraform.io/language/modules/develop/composition#dependency-inversion) techniques in Terraform to reference resources created by the module. This makes it much cleaner and easier to read the code.

For an example of this, please see the following comment from a similar issue:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/372#issuecomment-1127539466

If you still want to extract these values from the module, you need to use the following format, ensuring you use the correct Resource ID for the Resource Group (which can also be determined from the module output):

```hcl
  location            = module.enterprise_scale.azurerm_resource_group.connectivity["<resource ID of the Resource Group>"].location
  resource_group_name = module.enterprise_scale.azurerm_resource_group.connectivity["<resource ID of the Resource Group>"].name
```

As you can see, this isn't very friendly, hence our recommendation above.

Please let me know if this helps.

**Comment by tpatrizio** [comment]
Hi @krowlandson, thanks a lot for your suggestion! I ended upt writing this piece of Terraform code to complete the VPN gateway configuration in the same deployment (terraform state). Does it make sense or is there a better way?

```
locals {
  connectivity_rg_name = "${var.root_id}-connectivity-${var.connectivity_resources_location}"
}
data "azurerm_resource_group" "connectivity-rg" {
  provider = azurerm.connectivity 
  name                = local.connectivity_rg_name
  depends_on = [
    module.enterprise_scale 
  ]
}

data "azurerm_virtual_network_gateway" "vpngw" {
  provider = azurerm.connectivity 
  name = "${var.root_id}-vpngw-${var.connectivity_resources_location}"
  resource_group_name =  local.connectivity_rg_name
  depends_on = [
    module.enterprise_scale 
  ]
}

resource "azurerm_local_network_gateway" "lgw" {
  provider            = azurerm.connectivity
  count               = var.deploy_connectivity_resources ? 1 : 0
  name                = "${var.root_id}-lgw-network"
  location            = data.azurerm_resource_group.connectivity-rg.location
  resource_group_name = local.connectivity_rg_name
  gateway_address     = "53.52.51.50"
  address_space = [
    "10.0.0.0/8",
    "192.168.0.0/16"
  ]
}

resource "azurerm_virtual_network_gateway_connection" "vpn-connection" {
  provider                   = azurerm.connectivity
  count                      = var.deploy_connectivity_resources ? 1 : 0
  name                       = "${var.root_id}-vgw-connection"
  location                   = data.azurerm_resource_group.connectivity-rg.location
  resource_group_name        = local.connectivity_rg_name
  local_network_gateway_id   = azurerm_local_network_gateway.lgw[count.index].id
  type                       = "IPsec"
  virtual_network_gateway_id = data.azurerm_virtual_network_gateway.vpngw.id
  shared_key                 = "mysupersecretkey"
}
```

**Comment by krowlandson** [comment]
Great stuff, thank you for the update @tpatrizio
