### ISSUE TITLE
How the ESLZ policy Deploy-VNET-HubSpoke is supposed to work?

### ISSUE THREAD

**Issue by tpatrizio** [Azure/terraform-azurerm-caf-enterprise-scale#381]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi All,

I was looking for way to automate the vNet peering in a Hub and Spoke topology and I found the custom policy `Deploy-VNET-Hub` Spoke that looks promising. However I'm not sure how it is supposed to work. Should I first create the resource group required by the `vNetRgName` parameter? Is it possible to attach the policy to each landing zone defined in custom archetypes? or is it only made available for subsequent deployments, when the hub and spoke vNets are in place?

I'd like to have an example in the documentation that could help to understand how a complete hub-spoke topology could be realized with the enterprise_scale module.

Thanks a lot for your help

**Additional context**

**Comment by jtracey93** [comment]
Hey @tpatrizio you can find information on this policies usage here: https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/deploy-lz-vnet.md

However, as the `azurerm` provider operates today you have to declare a provider block for each subscription you wish to manage. Therefore, it isn't possible with the module today to assign this policy as we only manage the platform subscriptions and not landing zone subscriptions.

I know we have been talking about Landing Zone subscription resource creation in this module but will leave @krowlandson and @matt-FFFFFF to provide an update/insight into this as they are closer to it than myself 👍

**Comment by matt-FFFFFF** [comment]
Thanks @jtracey93,

I agree this is a missing area we need to document better.

At the moment it's non-trivial but to do have long term plans for another module to simplify things.

Will add it to the wiki.

**Comment by tpatrizio** [comment]
Thanks a lot for the clarifications on this matter. I'll give a try to the AzApi provider but in the meanwhile I opted for creating the peering using a different plan, keeping the state of updated/created resources separate from the one related to the ESLZ module. This could be an acceptable compromise, given we dont have so many vNet to peer with the Hub.

**Comment by krowlandson** [comment]
Sounds good @tpatrizio, thank you for the update.

I will close this issue as I believe this is resolved, but please feel free to re-open if you require further assistance.
