### ISSUE TITLE
Add documentation for deploying across multiple Terraform workspaces (Terraform state file segregation)

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#392]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<p><strong>Is your feature request related to a problem?</strong> </p>
<p>No, this is a documentation request. </p>
<p><strong>Describe the solution you'd like</strong> </p>
<p>As described in #391, some customers would like to know how to implement the platform components of ALZ using multiple instances of this module to allow segregation of resources across multiple Terraform workspaces. </p>
<p>This helps to reduce the number of resources within a single Terraform state file, but also allows more granular RBAC to be applied to pipelines. </p>
<p>For example, a common scenario might be to have the following workspaces configured: </p>
<p>| Workspace / Module | Description |
| :--- | :--- |
| alz<em>core | Implementation of the core Management Group Hierarchy, including all base policies and IAM settings. This workspace will have high privileges across the resource hierarchy but can be under strict change control as changes are rare. |
| alz</em>landing<em>zones | Implementation of additional custom Management Groups under the <code>landing_zones</code> Management Group implemented by <code>alz_core</code>. Changes will be more common under this scope, as new landing zone Subscriptions are regularly added to the environment. This workspace can be run under an identity with permissions delegated to the <code>landing_zones</code> Management Group only, reducing attack surface area. |
| alz</em>connectivity | Implementation of the <code>connectivity</code> resources into the corresponding Azure subscription. Permissions for this workspace are only needed on the target Azure subscription, reducing attack surface area. |
| alz_management | Implementation of the <code>management</code> resources into the corresponding Azure subscription. Permissions for this workspace are only needed on the target Azure subscription, reducing attack surface area. | </p>
<p>This is already possible with the module, but documentation needs to be created so customers know how to implement this pattern (or similar) in their environments. </p>
<p>This issue is being raised to request and track addition of documentation for the above to the Wiki. </p>
<p><strong>Additional context</strong> </p>
<ul>
<li>Please refer to #391 </li>
</ul>

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync
