### ISSUE TITLE
Bug Report - How to change parameter of policy set assignment

### ISSUE THREAD

**Issue by DevSecNinja** [Azure/terraform-azurerm-caf-enterprise-scale#394]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**: 2.0.1

### Description

I was looking at the documentation for excluding policy assignments here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-archetype_config_overrides

Let's say I want to change the policy that blocks ACR public access to "Audit", I was expecting to do something like this:

```` terraform
  archetype_config_overrides = {
    landing-zones = {
      archetype_id = "es_landing_zones"
      parameters = {
        # This currently doesn't work. Param not populated in policy definition set
        Deny-Public-Endpoints = {
          ACRPublicIpDenyEffect = "Audit"
        }
      }
      access_control = {}
    }
````

But that doesn't seem to trigger anything. Could that be because the parameters are not specified here? https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/e4019d8f8943cc341ba8fd13ba29c105d48031d1/modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_public_endpoints.tmpl.json

**Steps to Reproduce**

1. Add the config overrides block.
2. Run terraform plan
3. No action will be taken.

**Screenshots**

**Additional context**

**Comment by krowlandson** [comment]
@DevSecNinja, in order for the parameters to do anything, they must map to a valid Policy Assignment.

In this instance, the `Deny-Public-Endpoints` Policy Assignment isn't applied at the `landing-zones` scope as this is only applied at the `corp` scope within the ALZ reference architecture.

For this to work, you can either set `deploy_corp_landing_zones = true` and use the same approach to set this parameter on this Policy Assignment, or you can use the [archetype extensions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions) capability to add this Policy Assignment to the `landing-zones` scope.

Please let me know if you require further guidance on this.

**Comment by krowlandson** [comment]
Incidentally, you can also set parameter values within the archetype definition files, including within an [archetype extension](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions). For this type of scenario, that may work better for you as it would allow you to both enable the Policy Assignment and set custom parameter values within a single place, potentially negating the need for setting `archetype_config_overrides`.
