### ISSUE TITLE
Feature Request: Add option to add Identity block to an Automation Account.

### ISSUE THREAD

**Issue by ofbjansen** [Azure/terraform-azurerm-caf-enterprise-scale#398]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

We would like to be able to add an Identity on at least the Automation Account resource in the management. At this point we can only change the name, but it is not possible to set the identity an Automation Account is run. I think the best location would be in the advanced part of the configure_management_resources variable.

**Describe the solution you'd like**

```
configure_management_resources = {
    "advanced" = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          management = {
            name = "management"
          }
        }
        azurerm_automation_account = {
          management = {
            name = "management"
            identity = {
               type = "SystemAssigned, UserAssigned"
               identity_ids = "identity ID"
           }
          }
        }
        azurerm_log_analytics_workspace = {
          management = {
            name = "management"
          }
        }
      }
    }
    "location" : "west...........

```
**Additional context**

**Comment by krowlandson** [comment]
Thank you for your request @ofbjansen... Seems a reasonable ask and one we should be able to add with no customer impact.

I'll get this prioritized and added to our backlog, unless you would be happy to submit a PR for this yourself? Happy to provide a few pointers on where the updates are needed if that helps?
