### ISSUE TITLE
How to disable default policies?

### ISSUE THREAD

**Issue by binaryPUNCH** [Azure/terraform-azurerm-caf-enterprise-scale#400]
First of all. I absolutely love this project. It is a godsend!

Now I need to disable a few of the default policies that come in the baseline. How do I go about doing that? Some are assigned on the Landing Zones mgmt group, other are on the root. How does one disable some of the defaults? E.g. `Deploy-Linux-Arc-Monitoring` & `Auditing on SQL server should be enabled`

Also, is there a way to add a default `nonComplianceMessages` to all the default policies?

I will happily make a PR to add these userguides if I can get some initial help on figuring it out. Thanks!

**Comment by krowlandson** [comment]
Thank you for the great feedback @binaryPUNCH, and of course your two questions.

Please let us know whether the following helps...

### Question 1

Have you seen the examples on [Expand built in archetype definitions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions)? This also includes guidance on how to [enable the exclusion function](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions#to-enable-the-exclusion-function) which should cover what you're trying to achieve with disabling policies.

You will need to create an exclusion for the archetype at each scope where it's references, but to give an example for `Deploy-Linux-Arc-Monitoring` at the `root` scope, you would create the following:

File name `${custom-lib-path}/archetype_exclusion_es_root.json`
```hcl
{
    "exclude_es_root": {
        "policy_assignments": [
            "Deploy-LX-Arc-Monitoring"
        ],
        "policy_definitions": [],
        "policy_set_definitions": [],
        "role_definitions": [],
        "archetype_config": {
            "parameters": {},
            "access_control": {}
        }
    }
}
```

You can also see an example of this exact example in the [test framework](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/292314eafb63d2142693d832a7ad0ddd8d607dbd/tests/modules/test_lib/archetype_exclusions/archetype_exclusion_es_root.json).

Just for clarity, you can only modify the presence of a Policy Assignment at the scope of where the assignment is created. If you want to actually exclude a Policy Assignment from applying to a lower scoped resource you need to either add a policy exclusion using the [notScopes](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/scope#assignment-scopes) value, or to create [Policy Exemptions](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/exemption-structure).

### Question 2

> Also, is there a way to add a default nonComplianceMessages to all the default policies?

Unfortunately we haven't added support for this yet but we are tracking this in the following issue:
- #67 

We've been discussing this recently and have added it to our backlog for the next minor release. We were planning to provide a new input variable to allow specifying an optional "generic" non-compliance message which would be used unless a more specific one was added in the Policy Assignment template. Hopefully this will offer what you're looking for once implemented, but we would greatly appreciate your feedback on this.

**Comment by binaryPUNCH** [comment]
Thank you thank you! I missed that part of the documentation. Great solution for doing the exclusions.

Aha, #67! We will really look forward to it. I believe that approach would be perfect. Just make sure it is optional for those who prefer not to use it, but we definitely will :)

**Comment by krowlandson** [comment]
Awesome, glad this helps.

> Aha, #67! We will really look forward to it. I believe that approach would be perfect. Just make sure it is optional for those who prefer not to use it, but we definitely will :)

And yes, will definitely make this optional... plan is if `var.default_non_compliance_message = ""` _(Actual variable name TBC)_ we will effectively "do nothing".
