### ISSUE TITLE
Feature Request - Cloud Scale Analytics Landing Zones

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-caf-enterprise-scale#404]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<p>Are there any plans to incorporate the Cloud Scale Analytics Landing Zones into these modules capabilities? </p>
<p><strong>Describe the solution you'd like</strong> </p>
<p>Microsoft have recently provided guidance on Data Management and Data Landing Zones. They have provided ARM Templates and Bicep Modules for these scenarios but for consistency it would be good to see these available for deployment via Terraform. </p>
<p>https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/architectures/overview-architectures
https://github.com/Azure/data-management-zone </p>
<p><strong>Additional context</strong>
I understand this a probably a considerable amount of work but have to ask. </p>

**Comment by matt-FFFFFF** [comment]
Hi @birdnathan 

Thanks for raising this issue!

Workloads such as cloud scale analytics are things that **integrate into** the ALZ conceptual architecture that is provided by this module, but are not **deployed by** this module.

Workload subscriptions are placed underneath the Landing Zones management group, or its children.

Typically we would see each of the workloads being deployed by a different repo/pipeline/spn then the platform components.

Does this answer your question?

**Comment by birdnathan** [comment]
Thanks @matt-FFFFFF Understood. Suppose I was coming at it as adding functionality to optionally deploy data spokes/resources as you already do with Connectivity and Management resources, reason being the data LZ code overlaps (it can also deploy firewalls and DNS Private Zones etc for example)

**Comment by krowlandson** [comment]
@birdnathan, our colleague @tschwarz01 is currently working on a Terraform implementation for Cloud-scale Analytics so I'm bringing this to his attention.

I'll be working with him to review this in the coming weeks so hopefully we can provide some better guidance around the integration points.

Just to ensure we bring all the right pieces together, please can you confirm which "data LZ code" you are currently using?

**Comment by birdnathan** [comment]
@krowlandson We are using the Data Management Landing Zone - https://github.com/Azure/data-management-zone
and Data Landing Zone - https://github.com/Azure/data-landing-zone examples. The Data Management Landing Zone is a pre-req to the Data Landing Zone......yes its a bit confusing until your read the guidance a few times 😊

**Comment by tschwarz01** [comment]
@birdnathan - I have a functional pre-release version completed.  It has not gone through rigorous testing, and we're still debating internally whether or not we should release these in their current form (a point-in-time example implementation) or structure and release it as a module.  These tasks will have to be completed prior to publishing them in a repo within the github.com/Azure organization.

With that said, if you'd be interested in evaluating the current templates, I'd certainly be interested in any feedback or suggestions you may have.  

Data Management Landing Zone - https://github.com/tschwarz01/cloud-scale-analytics-management-zone
Data Landing Zone - https://github.com/tschwarz01/cloud-scale-analytics-landing-zone
Example Data Product - https://github.com/tschwarz01/cloud-scale-analytics-example-data-product

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
As we are not going to be implementing this within this module and have provided visibility of the relevant project, I am closing this issue.
