### ISSUE TITLE
Feature Request: Simplify output for azurerm_log_analytics_workspace.management

### ISSUE THREAD

**Issue by adhodgson-wpp** [Azure/terraform-azurerm-caf-enterprise-scale#406]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Right now the output is a map with a single instance, the key being the management Log Analytics ID. Is there any reason why this couldn't be in the same format as the other outputs? Its not straightforward to get data from this output from for example remote state, as you have to lookup the key using an exact value from the map.

**Comment by krowlandson** [comment]
We've been having a lot of discussions around this and I think we have a good solution for this so will add this to the backlog.

In the meantime, do you have a preferred format for how to handle this?

I was thinking to mirror the scoping standards used for the `advanced.custom_settings_by_type` inputs for management and connectivity configuration...

**Comment by adhodgson-wpp** [comment]
Main issue for me with the current output is that its difficult to refer to it in Terraform as the index of the map is currently the full workspace ID. Personally I don't see why this needs to be any different from say the automation account output.

**Comment by adhodgson-wpp** [comment]
Sorry for the confusion I believed incorrectly that the output for the automation account was less complex than the log analytics resource. I am happy to close this issue.

**Comment by krowlandson** [comment]
No worries @adhodgson-wpp... we are still actively looking into how we can simplify both the input and output options for the module so would always welcome feedback.

We are largely tied by the fact that ALZ is a large and complex deployment so will always require some degree of complexity in what is effectively an "orchestration module". One option we are considering is whether to create smaller modules for specific components which can be consumed independently if a customer prefers that approach, but we also need to consider the impact such changes would have on existing consumers of the module.

Thank you for your response and support.
