### ISSUE TITLE
Feature Request -  Private DNS Zone logic needs changed for a select few zones

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-caf-enterprise-scale#412]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Private DNS Zone creation logic needs amended for some zones.

As per your example - https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings#resource-group-myorg-dns when creating region specific Private DNS Zones you are taking the full name of the location and creating the DNS Zone - i.e privatelink.uksouth.backup.windowsazure.com

However backup zones expect the region code not the fullname of the region - https://docs.microsoft.com/en-us/azure/backup/private-endpoints#for-the-backup-service

So should be privatelink.uks.backup.windowszure.com

In your above example you state siterecovery is a region specific zone, it is not. The region specific code gets added within the a record on creation of the private endpoint - https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-how-to-enable-replication-private-endpoints#create-private-endpoints-for-the-recovery-services-vault.

I wont comment on the AKS setup as i've never attempted to configure private endpoints on them so for now assuming that is correct.

1. Remove region specific deployments of siterecovery private dns zones, they arent required (to my knowledge)
Remove
```
azure_site_recovery = [
      for location in local.private_link_locations :
      "${location}.privatelink.siterecovery.windowsazure.com"
    ]
```
Replace with
azure_azure_site_recovery       = ["privatelink.siterecovery.windowsazure.com"]

2. Replace the logic on the creation of the backup.windowsazure.com private zone to incorporate the region prefix not full region name.
```
azure_backup = [
      for location in local.private_link_locations :
      "privatelink.${location}.backup.windowsazure.com"
    ] 
```
Perhaps use this [module ](https://registry.terraform.io/modules/claranet/regions/azurerm/latest) to pull the short format for each region replacing the ${location} with the result based on a region parameter from settings.connectivity.tf 

**Additional context**

**Comment by krowlandson** [comment]
Apologies for the slow pick up on this one... not forgotten, but needs some validation on our side as we need to consider the impact of this across our non-Terraform implementations of ALZ.

Thank you for raising awareness. We will update here again soon.
