### ISSUE TITLE
Can't create a custom archetype when the `root_id` had an uppercase character.

### ISSUE THREAD

**Issue by fgauna12** [Azure/terraform-azurerm-caf-enterprise-scale#415]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:  v1.1.5

**azure provider**: 2.99.0

**module**: 1.1.4

#### Describe the bug

When choosing a `root_id` with an uppercase character, one can't define custom archetypes that include the `root_id` like in the other built-in archetypes. 

#### Steps to Reproduce

1. Set `root_id` to "Canary" or something with upper case.
2. Define a custom archetype file with the ID of "my_archetype"
3. Try to create a custom archetype by adding to the `custom_landing_zone`. 
``` hcl
  custom_landing_zones = {
    "${var.root_id}-my-archetype" = {
      display_name               = "My Archetype"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "my_archetype"
        parameters     = {}
        access_control = {}
      }
    }
  }
```
4. Terraform fails to plan because the key to the map, in this case, "Canary-my-archetype" has an upper case character.

#### Screenshots

![2022-06-29_13-40-28](https://user-images.githubusercontent.com/1071270/176501230-cdf27c5c-9bc3-46b0-abae-02def35af8ef.png)

#### Additional context

I would expect the `root_id` to be more strict, requiring all lowercase characters.

Right now, I can create by using `lower`, but then it's inconsistent with the other archetypes.

``` hcl
  custom_landing_zones = {
    "${lower(var.root_id)}-my-archetype" = {
      display_name               = "My Archetype"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "my_archetype"
        parameters     = {}
        access_control = {}
      }
    }
  }
```

**Comment by krowlandson** [comment]
Thank you for raising this @fgauna12.

By design, we originally limited the inputs to lowercase, but in v0.1.0 we updated this. As you rightly pointed out, we appear to still have some inconsistencies in the validation rules and this should be an easy fix with no downstream customer impact.

I'll get this reviewed and added to our backlog. Please be aware that this fix will be applied to the latest version only, so you may need to upgrade.
