### ISSUE TITLE
Bug Report - Destroy fails - Error: deleting Policy Set Definition

### ISSUE THREAD

**Issue by dewhurstwill** [Azure/terraform-azurerm-caf-enterprise-scale#419]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

Terraform v1.1.7 on darwin_arm64

**azure provider**:

+ provider registry.terraform.io/hashicorp/azuread v2.25.0
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2
+ provider registry.terraform.io/hashicorp/random v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.7.2

**module**: 

Azure/caf-enterprise-scale/azurerm 2.1.0

#### Describe the bug

After running terraform destroy of caf-enterprise-scale, the destroy fails at;
│ Error: deleting Policy Set Definition "Deploy-Private-DNS-Zones": policy.SetDefinitionsClient#DeleteAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDeletePolicySetDefinitionRequest" Message="The policy set definition 'Deploy-Private-DNS-Zones' cannot be deleted. It is referenced by the policy assignment '/providers/Microsoft.Management/managementGroups/ans-corp/providers/Microsoft.Authorization/policyAssignments/Deploy-Private-DNS-Zones'. Please delete all policy assignments referencing the policy."
│
│
╵
╷
│ Error: deleting Policy Set Definition "Enforce-EncryptTransit": policy.SetDefinitionsClient#DeleteAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDeletePolicySetDefinitionRequest" Message="The policy set definition 'Enforce-EncryptTransit' cannot be deleted. It is referenced by the policy assignment '/providers/Microsoft.Management/managementGroups/ans-landingzones/providers/Microsoft.Authorization/policyAssignments/Enforce-TLS-SSL'. Please delete all policy assignments referencing the policy."
│
│
╵
╷
│ Error: deleting Policy Set Definition "Deny-PublicPaaSEndpoints": policy.SetDefinitionsClient#DeleteAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDeletePolicySetDefinitionRequest" Message="The policy set definition 'Deny-PublicPaaSEndpoints' cannot be deleted. It is referenced by the policy assignment '/providers/Microsoft.Management/managementGroups/ans-corp/providers/Microsoft.Authorization/policyAssignments/Deny-Public-Endpoints'. Please delete all policy assignments referencing the policy."

#### Steps to Reproduce

1. Run terraform apply
2. Run terraform destroy

#### Additional context

Workaround - manually destroy management groups

**Comment by MarcelHeek** [comment]
I prefer removing the entries (assignments / definition (sets)) from the archetype definitions, so they get removed from the Azure policy context in a working fashion.

**Comment by krowlandson** [comment]
@dewhurstwill are you able to provide anymore context around the scenario in which you're seeing this?

Is this on a vanilla implementation, or are you making changes to an existing implementation?

We run a full end-to-end test on all releases which confirms that the module is able to successfully create all the resources, and then destroy them.

We do sometimes observe failures, but these are usually on resource creation and are down to eventual consistency delays on Azure, rather than a problem with the module or Azure provider for Terraform. In most cases, a simple re-run of the `apply` or `destroy` will resolve the issue. It's relatively rare that we have to manually interact with any resources created by the module.

**Comment by dewhurstwill** [comment]
Hi @krowlandson

This is a vanilla implementation. We are attempting to build out using the ESLZ module what our consultants perform manually from which we can wrap with a module so it can be consumed in larger pieces of terraform.

I have attempted doing apply and destroy's and even blowing the entire environment away and running an apply/destroy again. Apply seems to work, we are only seeing issues when we run destroy.

**Comment by krowlandson** [comment]
Thank you for the additional information @dewhurstwill

Do you have any custom policy assignments being created outside of the module? This sounds like a dependency issue, but the module already handles this for all internally created/managed resources.

**Comment by dewhurstwill** [comment]
Inside the archetype extension we have;

```json
"policy_assignments": [  
           "Deny-Resource-Locations",
           "Deny-RSG-Locations"
      ],
  ```
  
  Other than that non that I am aware of

**Comment by dewhurstwill** [comment]
Update: Removing Deny-Resource-Locations and Deny-RSG-Locations from policy_assignments in archetypes extension still results in the same error message

**Comment by krowlandson** [comment]
@dewhurstwill are you able to provide a minimal example code sample which would allow us to reproduce this issue? As mentioned above, all of our testing (plus our own personal use of the module) hasn't shown this to be a problem.

Thank you

**Comment by dewhurstwill** [comment]
@krowlandson Thank you for you support so far, I have invited you to a private github repo where the source can be found. I am currently running the module from ./examples/

**Comment by krowlandson** [comment]
Great stuff, thank you. Will check it out and let you know if I find anything. Might be in the next couple of days though as have a few other commitments to work through. Hope that's OK?

**Comment by dewhurstwill** [comment]
Hi @krowlandson

I appreciate your help and that you have other higher priority commitment. Have you managed to get time to take a look into this?

Many thanks in advance

**Comment by krowlandson** [comment]
@dewhurstwill do you have a valid `tfvars` file I can use as a starting point for my testing please? There are a LOT of variables with invalid default values which need setting to something before the base deployment will work. Thanks

**Comment by dewhurstwill** [comment]
OK, leave it with me I will collect some more info

**Comment by dewhurstwill** [comment]
As with all things tech the issue appears to have resolved itself without any code change. Thank you for your time and support on this it has been appreciated.

**Comment by krowlandson** [comment]
Very odd... but glad to hear this is resolved.

Thank you for confirming and best of luck with your project.
