### ISSUE TITLE
Error: Provider configuration not present

### ISSUE THREAD

**Issue by vrrasann** [Azure/terraform-azurerm-caf-enterprise-scale#421]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:
Azure provider configruation are failed 

**module**:

Terraform init is showing no issues

### Description

terraform plan its error message

#### Describe the bug

azure provider configuration not found , multiple providers are missing so this code are not working properly

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

#### Additional context

<!-- Add any other context about the problem here.

**Comment by krowlandson** [comment]
Hi @vrrasann ... are you able to provide some more information so we can try to reproduce this problem?

How have you configured the module? Did you follow one of our [examples](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/Examples) on the Wiki?

**Comment by vrrasann** [comment]
on main.tf line 13:
│   13: module "enterprise_scale" {
│
│ Configuration required for module.enterprise_scale.provider["registry.terraform.io/hashicorp/azurerm"].connectivity.
│ Add a provider named azurerm.connectivity to the providers map for module.enterprise_scale in the root module.

i have checked the teraform.tf

for each and every subscription its all same code will be working formultiple subscirption , however iam searching for options to enter the custom ipaddress or it has to cuztomized by our own

**Comment by krowlandson** [comment]
@vrrasann... Just to confirm, are you trying to use the module by cloning from this repository and then trying to run `terraform apply` from the root directory?

If so, the module isn't designed to be used like this.

Instead, please follow the guidance provided in our [wiki](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki) and let us know if you continue to have this problem.

**Comment by krowlandson** [comment]
Further to the above @vrrasann, this is what I believe you are seeing when you try to use the module by cloning from this repository and then trying to run `terraform plan` or `terraform apply` from the module root directory:

```shell
PS ~/terraform-azurerm-caf-enterprise-scale> terraform init
Initializing modules...
- connectivity_resources in modules/connectivity
- identity_resources in modules/identity
- management_group_archetypes in modules/archetypes
- management_resources in modules/management
- role_assignments_for_policy in modules/role_assignments_for_policy

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/time versions matching ">= 0.7.0"...
- Finding hashicorp/random versions matching ">= 3.1.0"...
- Finding hashicorp/azurerm versions matching ">= 3.0.2"...
- Installing hashicorp/time v0.7.2...
- Installed hashicorp/time v0.7.2 (signed by HashiCorp)
- Installing hashicorp/random v3.3.2...
- Installed hashicorp/random v3.3.2 (signed by HashiCorp)
- Installing hashicorp/azurerm v3.12.0...
- Installed hashicorp/azurerm v3.12.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
PS ~/terraform-azurerm-caf-enterprise-scale> terraform plan
var.root_parent_id
  The root_parent_id is used to specify where to set the root for all Landing Zone deployments. Usually the Tenant ID when deploying the core Enterprise-scale Landing Zones.

  Enter a value: test

╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_private_dns_zone.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_private_dns_zone.connectivity, after which you can remove the provider configuration
│ again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_automation_account.management its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].management is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_automation_account.management, after which you can remove the provider configuration
│ again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_dns_zone.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider configuration
│ is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_dns_zone.connectivity, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_resource_group.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_resource_group.connectivity, after which you can remove the provider configuration
│ again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_resource_group.management its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].management is required, but it has been removed. This occurs when a provider configuration
│ is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_resource_group.management, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_resource_group.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_resource_group.virtual_wan, after which you can remove the provider configuration
│ again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_firewall.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider configuration is
│ removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_firewall.virtual_wan, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_virtual_wan.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider configuration
│ is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_virtual_wan.virtual_wan, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_public_ip.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider configuration
│ is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_public_ip.connectivity, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_private_dns_zone_virtual_network_link.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs
│ when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_private_dns_zone_virtual_network_link.connectivity, after which you
│ can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_log_analytics_solution.management its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].management is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_log_analytics_solution.management, after which you can remove the provider
│ configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_log_analytics_workspace.management its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].management is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_log_analytics_workspace.management, after which you can remove the provider
│ configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_log_analytics_linked_service.management its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].management is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_log_analytics_linked_service.management, after which you can remove the provider
│ configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_firewall.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider configuration
│ is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_firewall.connectivity, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_firewall_policy.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_firewall_policy.virtual_wan, after which you can remove the provider configuration
│ again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_virtual_network_peering.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_virtual_network_peering.connectivity, after which you can remove the provider
│ configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_firewall_policy.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_firewall_policy.connectivity, after which you can remove the provider configuration
│ again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_virtual_hub.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider configuration
│ is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_virtual_hub.virtual_wan, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_network_ddos_protection_plan.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a
│ provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_network_ddos_protection_plan.connectivity, after which you can remove the
│ provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_subnet.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider configuration is
│ removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_subnet.connectivity, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_virtual_hub_connection.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_virtual_hub_connection.virtual_wan, after which you can remove the provider
│ configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_express_route_gateway.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_express_route_gateway.virtual_wan, after which you can remove the provider
│ configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_subscription_template_deployment.telemetry_management its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].management is required, but it has been removed. This occurs
│ when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_subscription_template_deployment.telemetry_management, after which
│ you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_virtual_network_gateway.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_virtual_network_gateway.connectivity, after which you can remove the provider
│ configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_virtual_network.connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_virtual_network.connectivity, after which you can remove the provider configuration
│ again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_subscription_template_deployment.telemetry_connectivity its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This
│ occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_subscription_template_deployment.telemetry_connectivity, after
│ which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with azurerm_vpn_gateway.virtual_wan its original provider configuration at provider["registry.terraform.io/hashicorp/azurerm"].connectivity is required, but it has been removed. This occurs when a provider configuration
│ is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy azurerm_vpn_gateway.virtual_wan, after which you can remove the provider configuration again.
╵
PS ~/terraform-azurerm-caf-enterprise-scale> 
```

Is this correct?

**Comment by vrrasann** [comment]
You are 100% right, this is the same issue iam experience,

As per the wiki instructions , i started creating the new file with deployment and iam able to create the custom deployment

Level300 partially successfull

**Comment by vrrasann** [comment]
As Per the documentations, how do i create the vnet and snet related entries or iptables where to create and setup the custom ipranges on the modules

its only setting up the connectivity, management and identity subscription

**Comment by vrrasann** [comment]
Please provide iam refering the examples to use the connectivity settings and subscription

**Comment by krowlandson** [comment]
> You are 100% right, this is the same issue iam experience,
> 
> As per the wiki instructions , i started creating the new file with deployment and iam able to create the custom deployment
> 
> Level300 partially successfull

Great stuff, glad you have managed to progress, and I hope our documentation is useful and easy to understand?

> As Per the documentations, how do i create the vnet and snet related entries or iptables where to create and setup the custom ipranges on the modules
> 
> its only setting up the connectivity, management and identity subscription

> Please provide iam refering the examples to use the connectivity settings and subscription

Regarding both of the above, please see the following:

- [\[User Guide\] Module Permissions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Module-Permissions) should give you guidance on how to ensure your identity has the permissions needed to deploy resources, although it's worth noting that when using the same identity to deploy core resources (i.e the Management Group hierarchy) as other resources, this identity will have sufficient permissions due to the high privilege needed to move Subscriptions into the Management Groups.
- [\[User Guide\] Provider Configuration](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Provider-Configuration) provides information on how to ensure you have the required providers configured to allow the module to deploy connectivity and management resources into the correct target Subscriptions. Note that you must do this in addition to specifying the Subscription ID for [subscription_id_connectivity](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-subscription_id_connectivity) and [subscription_id_management](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-subscription_id_management) input variables.
- [\[Variables\] configure_connectivity_resources.settings.hub_networks](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks) provides all the information you should need to configure your hub networks and to [add custom subnets](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks#configsubnets) within your hub network if needed (also equivalent docs for if you are [using virtual WAN](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.vwan_hub_networks) instead of traditional hub & spoke).
- Assuming you mean `iptables` in the context of Azure Firewall, we only deploy the firewall and link it to a default firewall policy. You have [configuration options for the firewall and firewall policy](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks#configazure_firewallconfig) surfaced through the input variables. For any other firewall configuration settings such as Firewall rules, we recommend using the dedicated provider resources to add them, such as:
  - [firewall_application_rule_collection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_application_rule_collection)
  - [firewall_nat_rule_collection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_nat_rule_collection)
  - [firewall_network_rule_collection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_network_rule_collection)

If you want to create spoke virtual networks in your landing zones, you need to do this outside the module. but we have some options to simplify [peering](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks#configenable_outbound_virtual_network_peering) and linking [DNS](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.dns#configenable_private_dns_zone_virtual_network_link_on_spokes) / [DDoS](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks#configlink_to_ddos_protection_plan) for [specified spoke networks](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks#configspoke_virtual_network_resource_ids). You'll find information about this in the connectivity guides mentioned above.

Hope this helps?

**Comment by vrrasann** [comment]
Thanks for making me further progress, please provide one more help on this situation. if iam getting an error on specific module how to ignore or skip those specific modules that would help me to enable other features


Example:
level1: ./terraform/modules/module.enterprise_scale/resource.management.group.tf

so if you could help me how to skip this module i can proceed further with this code

**Comment by vrrasann** [comment]
Thanks kevin , for your help on setting up the vwan with custom settings , iam able to create vwan however i have management
i have identity and core subscriptions . they are all on different subscription . please share me any options or settings file to enable the peering between multiple subsciprtion between vwan hub and each spoke,

I have a sample code also provided below whether it can be deployed seperately , kindly help each spokes are in different subscription.

[Using Azure Vnet Peerings across subscriptions - Terraform · Issue #5843 · hashicorp/terraform-provider-azurerm (github.com)](https://github.com/hashicorp/terraform-provider-azurerm/issues/5843)


================================================================


I am using the below code to peer my created vnet with an existing Vnet in a separate subscription.

provider "azurerm" {
alias = "core"
subscription_id = "REMOTESUBID"
tenant_id = "CurrentTenantID"
client_id = "ClientIDConstant"
client_secret = "ClientIDConstant"
}

data "azurerm_virtual_network" "remotevnet" {
provider = "azurerm.core"
name = "co-np-eastus-core1-vnet"
resource_group_name = "co-np-eastus-core1-rg"
}

module "applicationrg"
{
source = "../modules/resource_group"
resource_group_name = "${var.applicationrg_name}"
resource_group_location = "${var.application_rg_location}"

tags = "${var.tags}"
}
module "applicationvnet"{
source="../modules/virtual_network"
virtual_network_name="${var.virtual_network_name}"
resource_group_location = "${module.applicationrg.resource_group_location}"
resource_group_name ="${module.applicationrg.resource_group_name}"
address_space = "${var.address_space}"
dns_server = "${var.dns_server}"
tags = "${var.tags}"
}

resource "azurerm_virtual_network_peering" "CreatedVnetToRemoteVnet" {
name = "CreatedVnettoRemoteVnet"
virtual_network_name = "${module.applicationvnet.virtual_network_name}"
resource_group_name = "${module.applicationrg.resource_group_name}"
remote_virtual_network_id = "${data.azurerm_virtual_network.remotevnet.id}"
allow_virtual_network_access = true
allow_forwarded_traffic = true
}

resource "azurerm_virtual_network_peering" "RemoteVnetToCreatedVnet" {
name = "RemoteVnettoCreatedVnet"
virtual_network_name = "${data.azurerm_virtual_network.corevnet.name}"
resource_group_name = "${data.azurerm_virtual_network.corevnet.resource_group_name}"
remote_virtual_network_id = "/subscriptions{module.applicationrg.resource_group_name}/providers/Microsoft.Network/virtualNetworks/${module.applicationvnet.virtual_network_name}"
allow_virtual_network_access = true
allow_forwarded_traffic = true
}

**Comment by krowlandson** [comment]
> Thanks for making me further progress, please provide one more help on this situation. if iam getting an error on specific module how to ignore or skip those specific modules that would help me to enable other features
> 
> Example: level1: ./terraform/modules/module.enterprise_scale/resource.management.group.tf
> 
> so if you could help me how to skip this module i can proceed further with this code

To specifically disable deployment of the core landing zones (i.e. the default Management Group hierarchy and associated policies/roles) you would set `deploy_core_landing_zones = false`.

As it sounds like you are trying to configure quite a few settings, I would strongly recommend reading through the examples in the Wiki and the docs for each input variable to better understand how you can configure the module. If you can then come back with more specific questions around areas which aren't clear in the docs so we know which need improving, that would be really helpful for us. 

> please share me any options or settings file to enable the peering between multiple subsciprtion between vwan hub and each spoke

We are currently working on a new module to help with "Subscription vending" which will cover the creation of Subscriptions and platform managed resources, such as spoke virtual networks (with peering). Unfortunately, this isn't ready yet.

As you are using Virtual WAN to create your network topology, you should need to simply specify each spoke virtual network resource ID in the []() input.

> Note that the module doesn't currently support using references to other resources due to the way the data model works (we are looking at options to resolve this, but it will require a major refactor) so you will need to input a list of virtual network IDs. Resource IDs in Azure can be determined fairly easily though, as long as you know the Subscription ID, Resource Group name, and resource name.
