### ISSUE TITLE
vpn point to site new configuration

### ISSUE THREAD

**Issue by vrrasann** [Azure/terraform-azurerm-caf-enterprise-scale#428]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

#### We are trying to custom configuration of vpn point to site on the enterprise scale using the vwan , is it the feature exists to configure or the custom code should be build by our self , if the point to site vpn can be enabled on the enterprise scale or not 

if yes, please share the details link , because i have checked the custom variable documentations link but those are giving plenty of code which is not clear to configure vpn gateway 

Thanks

**Comment by matt-FFFFFF** [comment]
Hi @vrrasann, have you seen the documentation in the wiki here:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks#configvirtual_network_gatewayconfigadvanced_vpn_settingsvpn_client_configuration

**Comment by matt-FFFFFF** [comment]
Hi @vrrasann,

Currently the module does not deploy [azurerm_vpn_site](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vpn_site) resources, thes emust be created outside the module. You can use the dependency inversion technique and use the `azurerm_vwan_hub` as a data source and deploy the configuration that way.
