### ISSUE TITLE
root_parent_id validation for Management Group ID

### ISSUE THREAD

**Issue by n-sandstrom-flysas** [Azure/terraform-azurerm-caf-enterprise-scale#43]
Hi.
I am trying to use an existing Management Group as root_parent_id.
This group has an id that contains an underscore, causing the validation to fail.

According to variables.tf: "The root_parent_id value must be a valid GUID, or Management Group ID."

According to Azure Portal, the id can contain: `ASCII letter, digit, -, _, (, ), .`
However, that is not matched by the regex in variables.tf, which only allows for letters, numbers and hyphen.

Is this an intended limitation?

/Niklas

**Comment by krowlandson** [comment]
This was by design as it matches what we were considering "supported characters" within the Enterprise-scale naming, but agree this isn't that useful so will include this update in our next release. Thank you for raising this.
