### ISSUE TITLE
Not clear how to configure firewall with forced tunneling

### ISSUE THREAD

**Issue by tpatrizio** [Azure/terraform-azurerm-caf-enterprise-scale#432]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<h4 id=isyourfeaturerequestrelatedtoaproblem>Is your feature request related to a problem? </h4>
<p>Hi All, afer enabling  Express Route and advertised a default route on it I'm no longer able to create Azure Firewall. </p>
<h4 id=describethesolutionyoudlike>Describe the solution you'd like </h4>
<p>I'd like to configure forced tunneling as documented <a href="https://docs.microsoft.com/en-us/azure/firewall/forced-tunneling">here</a>. I found that the connectivity configuration object expose the object <code>management_ip_configuration</code> but I was not able to find relevant documentation on its usage. Is it supposed to create a subnet named AzureFirewallManagementSubnet and a management public IP as a prerequisite to the Terraform ES automation? </p>
<h4 id=additionalcontext>Additional context </h4>
<p>I'm using the following module: </p>
<pre><code>  source  = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;Azure/caf-enterprise-scale/azurerm&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
  version = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;2.0.1&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
</code></pre>
<p>Thanks a lot for your attention </p>

**Comment by krowlandson** [comment]
Hi @tpatrizio... thank you for your patience on our response.

> I found that the connectivity configuration object expose the object management_ip_configuration but I was not able to find relevant documentation on its usage.

I assume you mean within the firewall resource, rather than via the input variables?

I've not personally configured the option you are requesting, but the `management_ip_configuration` setting would be set by the `configure_connectivity_resources.advanced` block. This is why it is undocumented, as we plan to expose these in release `v3.0.0` when we are able to support `optional()` input types with the GA release of this functionality in Terraform `v1.3.x`.

To configure this setting, your input would look something like the following:

```hcl
  configure_connectivity_resources = {
    # other attributes removed for brevity
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_firewall = {
          connectivity = {
            (var.location) = {
              management_ip_configuration = [
                {
                  name = "" # (Required)
                  subnet_id = "" # (Required) The Management Subnet used for the Firewall must have the name AzureFirewallManagementSubnet and the subnet mask must be at least a /26.
                  public_ip_address_id = "" # (Required) The Public IP must have a Static allocation and Standard SKU.
                }
              ]
            }
          }
        }
      }
    }
  }
```

All entries to this should match those documented on the Terraform docs for the [azurerm_firewall | management_ip_configuration](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#management_ip_configuration) resource attribute.

> Is it supposed to create a subnet named AzureFirewallManagementSubnet and a management public IP as a prerequisite to the Terraform ES automation?

You will need to provision these resources yourself and then provide the relevant IDs into the above configuration.

**Comment by tpatrizio** [comment]
> Hi @tpatrizio... thank you for your patience on our response.
> 
> > I found that the connectivity configuration object expose the object management_ip_configuration but I was not able to find relevant documentation on its usage.
> 
> I assume you mean within the firewall resource, rather than via the input variables?
> 
> I've not personally configured the option you are requesting, but the `management_ip_configuration` setting would be set by the `configure_connectivity_resources.advanced` block. This is why it is undocumented, as we plan to expose these in release `v3.0.0` when we are able to support `optional()` input types with the GA release of this functionality in Terraform `v1.3.x`.
> 
> To configure this setting, your input would look something like the following:
> 
> ```terraform
>   configure_connectivity_resources = {
>     # other attributes removed for brevity
>     advanced = {
>       custom_settings_by_resource_type = {
>         azurerm_firewall = {
>           connectivity = {
>             (var.location) = {
>               management_ip_configuration = [
>                 {
>                   name = "" # (Required)
>                   subnet_id = "" # (Required) The Management Subnet used for the Firewall must have the name AzureFirewallManagementSubnet and the subnet mask must be at least a /26.
>                   public_ip_address_id = "" # (Required) The Public IP must have a Static allocation and Standard SKU.
>                 }
>               ]
>             }
>           }
>         }
>       }
>     }
>   }
> ```
> 
> All entries to this should match those documented on the Terraform docs for the [azurerm_firewall | management_ip_configuration](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#management_ip_configuration) resource attribute.
> 
> > Is it supposed to create a subnet named AzureFirewallManagementSubnet and a management public IP as a prerequisite to the Terraform ES automation?
> 
> You will need to provision these resources yourself and then provide the relevant IDs into the above configuration.

Thanks for the clarification, I didn't considered the possibility to leverage the advanced feature of the module. I will give it a try in the next days. Do you have any outlook on when the es module will officially support the management interface configuration?

**Comment by tpatrizio** [comment]
Thanks for the clarification, I didn't considered the possibility to leverage the advanced feature of the module. I will give it a try in the next days. Do you have any outlook on when the es module will officially support the management interface configuration?

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
> Do you have any outlook on when the es module will officially support the management interface configuration?

I assume you're actually asking when we will add this to the main schema using `optional()` as mentioned previously?

If so, we have no firm commitment on this yet and we won't be removing the advanced block support immediately to minimise the transition so hopefully that should give reassurance on this approach.

**Comment by krowlandson** [comment]
Did you manage to get this working as required @tpatrizio?

**Comment by tpatrizio** [comment]
Hi @krowlandson, I was able to overcome the problem by leveraging the advanced configuration in the configure_connectivity_resources settings, after manually creating the /26 management subnet and a static public IP
Thanks a lot for your support!

**Comment by krowlandson** [comment]
That's great to hear, thank you for confirming @tpatrizio 

If there's anything else we can help with, please let us know.

**Comment by krowlandson** [comment]
Trigger ADO Sync
