### ISSUE TITLE
Feature Request: Investigate subnet with no NSG policy Terraform usage

### ISSUE THREAD

**Issue by adhodgson1** [Azure/terraform-azurerm-caf-enterprise-scale#434]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I had an issue today deploying production workloads into a subscription under the landing zone MG. My test workload was in a subscription under the sandbox MG. I found out the hard way that the landing zone MG had a policy assigned to block subnets without NSGs, running into the Terraform issue/workaround: https://github.com/hashicorp/terraform-provider-azurerm/issues/9022

Although I have got through using the workaround in my use case its not ideal to use the subnets block inline on the vnet resource as it supports a lot less features than the subnet resource does.

My questions relating to the CAF module are:
1. Should my test workload have been in a subscription under the sandboxes MG? If so, would it be appropriate to have the same policies there as well so I can be confident my code will work in the production subscriptions which I have under the landing zones MG?
2. Does anyone have any ideas about generating more Terraform friendly policies which we can use instead given our IAC choice is Terraform going forward?

**Comment by heintonny** [comment]
Hi @adhodgson1 

We have solved this by changing the effect from Deny to Audit for the landingzone assignment.

Create a file with name

"configuration/level1/alz/lib/archetype_extension_es_landing_zones.tmpl.json"

Insert the code below and run a new rover apply for the azlz state:

{
  "extend_es_landing_zones": {
    "policy_assignments": ["Deny-Subnet-Without-Nsg"],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {
        "Deny-Subnet-Without-Nsg": {
          "effect": "Audit",
          "excludedSubnets": ["GatewaySubnet","AzureFirewallSubnet","AzureFirewallManagementSubnet"]
        }
      },
      "access_control": {}
    }
  }
}

**Comment by matt-FFFFFF** [comment]
Hi @adhodgson1 

Agree with the recommendation to move the NSG policy to Audit. You can do this using `archetype_config_overrides` or using archetype extensions.

The above example from @heintonny comes from using this module withing CAF Terraform Landing Zones. If you are using the module standalone, then the file paths will be different. See the wiki for examples.
