### ISSUE TITLE
Deployment of Arc policies is not in the default CAF accelerators

### ISSUE THREAD

**Issue by anwather** [Azure/terraform-azurerm-caf-enterprise-scale#436]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Terraform v1.2.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.17.0
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.7.2

**module**: root module

### Description

The default deployment deploys 2 extra policy assignments to the management group in the root id - they are defined in the root archetype.

```
"policy_assignments": [

      
      "Deploy-LX-Arc-Monitoring",

      "Deploy-WS-Arc-Monitoring"
    ]
```

#### Describe the bug

The CAF landing zone accelerators e.g. portal deployment, Bicep deployment do not deploy these Arc monitoring policies as they pull policies definitions from the main ESLZ repository.

Just wondering if these should be removed from this deployment - or added to the other accelerator deployments?

**Comment by krowlandson** [comment]
Thank you for logging this @anwather 

All of the policies implemented in this module are pulled from the upstream Azure/Enterprise-Scale repository, but we do still observe some subtle differences.

We have an outstanding piece of work to complete "feature parity" and "consistency" between these (ARM for Portal, Bicep and Terraform) so I will get this added to the backlog.

Assuming you are not facing any issues with these policies, I don't think we will look to remove these from the Terraform module.

**Comment by anwather** [comment]
As discussed offline - looks like the Terraform solution is actually ahead of the others - closing
