### ISSUE TITLE
Upgrade from v0.0.8 to v0.1.2

### ISSUE THREAD

**Issue by lintaonz** [Azure/terraform-azurerm-caf-enterprise-scale#441]
### Versions

**terraform**: 1.0.5

**azure provider**: 2.65

**module**: 0.0.8

### Description

I try to upgrade the `caf-enterprise-scale` from v0.0.8 to the latest v2+. So I follow the doc user guide to [upgrade from v0.0.8 to v0.1.x](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v0.0.8-to-v0.1.0) first.

My landing zone has some custom archetypes:

* archetype_definitions
* policy_assignments
* policy_definitions
* role_assignments

When I run the TF plan, TF shows `Plan: 97 to add, 113 to change, 91 to destroy.` 

I can see the upgrade will recreate lots of `azurerm_role_assignment` and `azurerm_policy_assignment` resources.

My question: 

* Because we only use `caf-enterprise-scale` to deploy archetypes, not other Azure resources such as VNet etc. Is it safe to do the upgrade? Do I need to verify the other resources such as VNet or VMs in the landing zones after the upgrade?
* Do I need to follow the [User Guide](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v1.1.4-to-v2.0.0) to upgrade `caf-enterprise-scale` step by step? Or can I upgrade from 0.0.8 -> 0.1.x -> 1.1.x -> 2.x directly?

Thanks,

Tao

**Comment by krowlandson** [comment]
Hi @lintaonz

I've been testing this today and whilst I believe your configuration should be a relatively simple upgrade path, you may want to go in stages anyway.

I just tested going from a simple working example using `0.0.8` to `v2.3.0` and `terraform plan` throws the following error:

```shell
╷
│ Error: no schema available for module.test_core.azurerm_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/abc/providers/Microsoft.Authorization/policyAssignments/ES-Allowed-Locations"] while reading state; this is a bug in Terraform and should be reported
│
│
╵
```

This is not a module issue, but rather is related to the updated provider and Terraform versions needed.

We did not observe this during any of the staged upgrades (which continues to be a part of our manual testing) so I would advise that you go in stages, ensuring you also iterate the provider and Terraform versions incrementally.

If you hit any specific problems, please let us know and we will help where we can.

**Comment by lintaonz** [comment]
Hi @krowlandson,

I followed your suggestion to do the upgrade by stage. I have upgraded successfully for:
1.   0.0.8 -> 0.1.2
2.  0.1.2 -> 0.3.3

But when I try to upgrade from `0.3.3` to `0.4.0`, the plan is OK: `402 to create, 402 to destroy`. But the application is failed because `policyAssignments/Git-Repo-Tags" already exists`. 

```shell
Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/brands-sandbox/providers/Microsoft.Authorization/policyAssignments/Git-Repo-Tags" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
with module.enterprise_scale.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/brands-sandbox/providers/Microsoft.Authorization/policyAssignments/Git-Repo-Tags"]
on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 1, in resource 
"azurerm_management_group_policy_assignment" "enterprise_scale":

resource "azurerm_management_group_policy_assignment" "enterprise_scale" {

A resource with the ID "/providers/Microsoft.Management/managementGroups/brands-sandbox/providers/Microsoft.Authorization/policyAssignments/Git-Repo-Tags" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
```

Here is the `policy_assignment_require_git_repo_tags.json`

```json
{
  "name": "Git-Repo-Tags",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Audit existence of a tag. Does not apply to resource groups.",
    "displayName": "Git-Repo-Tags",
    "notScopes": [],
    "parameters": {
      "tagName": {
        "value": "git_repo"
      }
    },
    "policyDefinitionId": "${current_scope_resource_id}/providers/Microsoft.Authorization/policyDefinitions/Tag-Audit-Policy",
    "scope": "${current_scope_resource_id}"
  },
  "location": "${default_location}",
  "identity": {
    "type": "SystemAssigned"
  }
}

```

Why the `policyAssignments` cannot destroy/create correctly?

Thanks

**Comment by krowlandson** [comment]
@lintaonz ... this sounds like Terraform has somehow dropped a previously deployed resource from the state file. Whilst rare, I have seen similar behaviour previously.

In this instance my recommendation would be to either import the item into state, or delete the Policy Assignment so Terraform will recreate it.

Unfortunately, there isn't much we can do about this in the module.

**Comment by lintaonz** [comment]
Hi @krowlandson 

Thanks for the advice. Yes, I have to import `213 policyAssignments` back into the state. Then I can successfully upgrade from `0.3.3` to `0.4.0` and `1.1.4`.

When I try to upgrade from `1.1.4` to the latest `2.3.1`, the TF plan shows `Plan: 101 to add, 0 to change, 99 to destroy.`

It seems `resource "time_sleep" "after_azurerm_role_assignment"` remove all the `roleAssignments` with  `policyAssignments`. 

Is this by design?

Thanks,

```
  # module.enterprise_scale.time_sleep.after_azurerm_role_assignment must be replaced
-/+ resource "time_sleep" "after_azurerm_role_assignment" {
      ~ id               = "2022-08-21T03:33:47Z" -> (known after apply)
      ~ triggers         = { # forces replacement
          - "azurerm_policy_assignment_enterprise_scale"  = jsonencode([]) -> null
          - "azurerm_policy_assignment_policy_assignment" = jsonencode(
                [
                  - "/providers/Microsoft.Management/managementGroups/brands-non-prod/providers/Microsoft.Authorization/roleAssignments/15d29bfb-75e4-53c6-a05b-f140ddffe9f6",
...
                ]
            ) -> null
          + "azurerm_role_assignment_enterprise_scale"    = jsonencode([])
          + "module_role_assignments_for_policy"          = jsonencode(
                [
                  + "/providers/Microsoft.Management/managementGroups/brands-non-prod/providers/Microsoft.Authorization/policyAssignments/Backup-Tags",
                  + "/providers/Microsoft.Management/managementGroups/brands-non-prod/providers/Microsoft.Authorization/policyAssignments/Cost-Center-Tags",
```

**Comment by krowlandson** [comment]
Hi @lintaonz ... interesting that you had an issue with so many policy assignments. This is usually a sign that a Terraform run failed and these weren't committed to the state file. I've only personally seen this happen at this scale when running Terraform in a pipeline which then terminates due to hitting the run time limit. This also leaves a lock on the state file.

Regarding your question about the Role Assignments... this was an update designed to address the issue where all Role Assignments would be recreated when only a single Policy Assignment was modified. Hopefully this should be the last time you see this.

In the future you should only see Role Assignments updated on a per-policy basis when that Policy Assignment needs to be recreated, resulting in a new System Assigned Managed Identity being created.
