### ISSUE TITLE
 root_parent_id not switching to secondary tenant

### ISSUE THREAD

**Issue by frankscalzo** [Azure/terraform-azurerm-caf-enterprise-scale#443]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: 1.2.7 </p>
<p><strong>azure provider</strong>: 3.19.1 </p>
<p><strong>module</strong>: main deploy </p>
<h3 id=description>Description </h3>
<h4 id=describethebug>Describe the bug </h4>
<p>i am trying to deploy a full deployment form here and see i cant just download and deploy so i am working through the demos  and the first issue is that i need to deploy in a secondary tenant </p>
<p>I added the root tenant info in variables and Main  it asks for it but still put in primary tenant </p>
<h4 id=stepstoreproduce>Steps to Reproduce </h4>
<ol>
<li>step 1 </li>
<li>step 2 </li>
<li>you get it… </li>
</ol>
<h4 id=screenshots>Screenshots </h4>
<h4 id=additionalcontext>Additional context </h4>

**Comment by frankscalzo** [comment]
i was able to work around it i think by adding 
subscription_id = "XXXXXX" (billing account)
tenant_id              = "XXXXXXXX" 
to the azure provider in Main 

provider "azurerm" {
  tenant_id              = "XXXXX"
  subscription_id = "XXXXX"
  features {}
}

i was hoping to be able to do a full deploy from the pull but i will just work through the levels of the example until i get what i need.

**Comment by krowlandson** [comment]
Hi @frankscalzo... thank you for raising this here. An interesting ask.

We don't explicitly cover configuration for a "cross Tenant deployment" as this isn't strictly a module concern.

As you have already identified, the module will deploy resources based on the specified authentication settings set in the `provider` configuration blocks. As the Azure provider for Terraform is designed to work against a single Subscription per `provider` declaration, we currently need 3 `provider` blocks mapped to the module for `core`, `connectivity`, and `management` resources. Each of these will also therefore map to the Tenant associated with the identity and Subscription specified.

More details of [Provider Configuration](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Provider-Configuration) for the module can be found on our Wiki.

We would be interested to get further details from you to better understand your deployment scenario and to see if there's anything we can do to make this easier or clearer in the future.

Thank you.

**Comment by frankscalzo** [comment]
@krowlandson 

Thanks for getting back to me.

For my current internal needs we needed to build a demo environment that did not tie to our main tenant for testing and segregation purposes. I have a demo tenant we use for our 365 and Azure env that is Air-gapped for this purpose but some users have cross tenant access and permissions such as my main user.

At the same time we have customers that 
A. instead of granting local user access they request to add an external user as a guest with escalated privileges
B. have multiple tenant due to corporate isolation needs they have a desire to mimic each environment with in each tenant.

I was following this article to quickly switch as needed

https://jeffbrown.tech/terraform-azure-multiple-subscriptions/

hope that helps 

Frank

**Comment by krowlandson** [comment]
OK, that makes sense so thank you for confirming @frankscalzo 

So if I understand this correctly, I don't think there is anything for us to "fix" in the module as this is a provider configuration scenario?

**Comment by frankscalzo** [comment]
@krowlandson im trying to get the connectivity and management providers to work 

when i run the init and plan all works but in the apply i get an error

creating Linked Service 'es-la/Automation' (Resource Group "es-mgmt"): operationalinsights.LinkedServicesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Automation/automationAccounts/read' on scope '/subscriptions/XXXXXXXX-6527-XXXXX-9dc4-fa514c5209c9/resourcegroups/es-mgmt/providers/Microsoft.OperationalInsights/workspaces/es-la/linkedServices/Automation', however the linked subscription '00000000-0000-0000-0000-000000000000' was not found. "

after investigating i see that the automation deployed in ths main tenant not the other tenant 

my provider.tf looks like below 

provider "azurerm" {
  tenant_id = "XXXXXX-9d29-XXXX-915d-c67edf4dcf4e"
  subscription_id = "07f192e5-05e9-4c31-91a4-eabbd2be9099"
  features {}
}

provider "azurerm" {
  alias = "connectivity"
  tenant_id = "XXXXX-9d29-XXXX-915d-c67edf4dcf4e"
  features {}

  subscription_id = local.subscription_id_connectivity
}

provider "azurerm" {
  alias = "management"
  tenant_id = "XXXXX-9d29-XXXX-915d-c67edf4dcf4e"
  features {}

  subscription_id = local.subscription_id_management
}

**Comment by frankscalzo** [comment]
I guess i missed the step where you need to pre create the 3 subscriptions i assumed it created them during deployment

if thats the case i think this will run just fine if i pre create them

**Comment by frankscalzo** [comment]
@kevdhowell so even after trying to use a local account and creating the additional subscriptions i get the error did i miss a step where i have to add a variable or change info in a file

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
@frankscalzo just wanted to see whether you've had any luck with this?

Just looking back at the last detail you provided (apologies for not getting back to you sooner) I can see a reference to subscription ID `00000000-0000-0000-0000-000000000000` was not found.

This is usually an indication that you haven't correctly configured the input for [subscription_id_management](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-subscription_id_management).

Please can you check this and let me know? Thank you

**Comment by krowlandson** [comment]
Trigger ADO Sync
