### ISSUE TITLE
Error received when running custom network connectivity deployment

### ISSUE THREAD

**Issue by ATuckwell** [Azure/terraform-azurerm-caf-enterprise-scale#444]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: v1.1.2 </p>
<p><strong>azure provider</strong>: 3.0.2 </p>
<p><strong>module</strong>: 2.3.1 </p>
<h3 id=description>Description </h3>
<p>Error received when using the &quot;Deploy Connectivity Resources With Custom Settings&quot; configuration guide. Specific error received is: &quot;The given value is not suitable for child module variable &quot;configure<em>connectivity</em>resources&quot; defined at .terraform\modules\enterprise<em>scale\variables.tf:224,1-44: attribute &quot;settings&quot;: attribute      
│ &quot;hub</em>networks&quot;: element 0: attribute &quot;config&quot;: attribute &quot;<strong>enable<em>hub</em>network<em>mesh</em>peering</strong>&quot; is required.&quot; </p>
<h4 id=describethebug>Describe the bug </h4>
<p>The bug appears to be relating to new functionality within the terraform module for hub network mesh peering, which has a mandatory attribute missing from the <strong>settings.connectivity.tf</strong> </p>
<h4 id=stepstoreproduce>Steps to Reproduce </h4>
<p>Following the &quot;Deploy Connectivity Resources with Custom Settings&quot; guide reproduces the error.
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings </p>
<p>As above, by following the guide here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings </p>
<h4 id=screenshots>Screenshots </h4>
<p><img src="https://user-images.githubusercontent.com/106317528/186480513-ed23aff6-4178-4ae0-b63b-b1e5904c5a91.png" alt=image> </p>
<h4 id=additionalcontext>Additional context </h4>
<p>I believe adding this line resolves the issue:
<img src="https://user-images.githubusercontent.com/106317528/186480612-6b7a62fe-806a-4aed-9a48-ded844cd23a0.png" alt=image> </p>

**Comment by krowlandson** [comment]
Great catch @ATuckwell ... thank you!

**Comment by cbezenco** [comment]
Not sure it is only a doc issue. 
I am seeing same error when trying to deploy hub and spoke config and for me adding "enable_hub_network_mesh_peering" in the   

            spoke_virtual_network_resource_ids      = []
            enable_outbound_virtual_network_peering = true
            enable_hub_network_mesh_peering         = false

Gives the same error even through the attribute is there....

╵
PS E:\ado\tf-eslz\terraform> terraform validate
╷
│ Error: Invalid value for input variable
│
│   on main.tf line 77, in module "caf-enterprise-scale":
│   77:   configure_connectivity_resources = local.configure_connectivity_resources
│
│ The given value is not suitable for module.caf-enterprise-scale.var.configure_connectivity_resources declared at .terraform\modules\caf-enterprise-scale\variables.tf:224,1-44: attribute
│ "settings": attribute "hub_networks": element 0: attribute "config": attribute "enable_hub_network_mesh_peering" is required.

PS E:\ado\tf-eslz\terraform> terraform version
Terraform v1.2.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.21.0
+ provider registry.terraform.io/hashicorp/random v3.4.1
+ provider registry.terraform.io/hashicorp/time v0.8.0

**Comment by ATuckwell** [comment]
Hi Christian, just to double check but did you add enable_hub_network_mesh_peering for both Hub networks within settings.connectivity.tf ?

Regards
Ad

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Closing as this should now be resolved by PR #496
