### ISSUE TITLE
azurerm v4 compatibility

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azurerm-caf-enterprise-scale#445]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: 1.2.x </p>
<p><strong>azure provider</strong>: 3.x </p>
<p><strong>module</strong>: 2.3.1 </p>
<h3 id=description>Description </h3>
<h4 id=describethebug>Describe the bug </h4>
<p>AzureRM provider v4 is making changes and has deprecation warnings: </p>
<pre><code class="text language-text">│ Warning: Argument is deprecated
│ 
│   with module.alz.azurerm_subnet.connectivity,
│   on .terraform/modules/alz/resources.connectivity.tf line 58, in resource &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;azurerm_subnet&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;connectivity&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;:
│   58:   enforce_private_link_endpoint_network_policies = each.value.template.enforce_private_link_endpoint_network_policies
│ 
│ `enforce_private_link_endpoint_network_policies` will be
│ removed in favour of the property
│ `private_endpoint_network_policies_enabled` in version 4.0
│ of the AzureRM Provider
│ 
│ (and one more similar warning elsewhere)
</code></pre>
<h4 id=stepstoreproduce>Steps to Reproduce</h4>
<ol>
<li>Deploy module with default configuration</li>
</ol>
<h4 id=screenshots>Screenshots</h4>
<p><img width=684 alt=image src="https://user-images.githubusercontent.com/16320656/186640702-675eb179-fe77-430c-b58d-7579548bfe55.png"></p>
<h4 id=additionalcontext>Additional context</h4>

**Comment by birdnathan** [comment]
Just about to log this myself. Warning came in with version 3.18.0 of the provider - https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.18.0

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
As mentioned by @birdnathan, this was introduced in [v3.18.0](https://registry.terraform.io/providers/hashicorp/azurerm/3.18.0/docs/resources/subnet#private_endpoint_network_policies_enabled) of the provider as part of commit [d0269ae463502e3c097c42ddc95429262d182eb7](https://github.com/hashicorp/terraform-provider-azurerm/commit/d0269ae463502e3c097c42ddc95429262d182eb7)

I would suggest on our next major or minor release we make this change and bump the minimum supported provider version to `v3.18.0`, rather than waiting for `v4.0.0` to be released and bumping to that. Gets us one step ahead then.

Thoughts please?

**Comment by krowlandson** [comment]
Trigger ADO Sync
