### ISSUE TITLE
Incorrect automation region mapping for Log Analytics workspace in East US regions

### ISSUE THREAD

**Issue by autocloudarc** [Azure/terraform-azurerm-caf-enterprise-scale#449]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: </p>
<p>PS [08/29/2022 17:54:49]&gt; terraform -version
Terraform v1.1.2 on windows_amd64 </p>
<p><strong>azure provider</strong>: </p>
<ul>
<li>provider registry.terraform.io/hashicorp/azurerm v3.20.0 </li>
</ul>
<p><strong>module</strong>:
azurerm 2.3.1 </p>
<h3 id=description>Description </h3>
<p>When selecting either eastus or eastus2 for the management<em>resources</em>location variable in variables.tf file, we can't link the log analytics workspace to the automation account. </p>
<h4 id=describethebug>Describe the bug </h4>
<p>This is because these resources cannot be both in the same region at the same time. One has to be in eastus and the other in eastus2. See: https://docs.microsoft.com/en-us/azure/automation/how-to/region-mappings </p>
<h4 id=stepstoreproduce>Steps to Reproduce </h4>
<ol>
<li>step 1: Assign the management<em>resources</em>location variable value to either &quot;eastus&quot; or &quot;eastus2&quot; </li>
<li>step 2: Attempt to link the log analytics workspace to the automation account from Update Management to enable the solutions. </li>
<li>you get it…See screenshot below. </li>
</ol>
<h4 id=screenshots>Screenshots </h4>
<p><img src="https://user-images.githubusercontent.com/15109536/187307359-a263702e-b666-4d88-8a96-225023a6fca8.png" alt=image> </p>
<h4 id=additionalcontext>Additional context </h4>
<p>Same issue with ARM template deployment: </p>
<p>Possibility to choose region for Log Analytics / Automation Account resource deployment #244 </p>

**Comment by krowlandson** [comment]
Great catch @autocloudarc... I'll see if we can get this added as a quick bugfix as shouldn't be too hard to address.

Will also talk to the team about how we address this in the ARM and Bicep implementations.

**Comment by autocloudarc** [comment]
Thanks @krowlandson , for your quick response. :-) It may be worthwile to note that the Bicep implementation works as intended and this isn't an issue because I've had to use it as a workaround for the ARM issue. This is because in Bicep, we can specify the regions for both resources independently (automatioon account and log analytics workspace), so the issue only occurs for the portal experience and Terraform so far.

**Comment by krowlandson** [comment]
Cool... thank you for confirming. I'll address the Portal experience too when fixing this then 👍🏻 

For now (as a tactical work-around), you can actually override the automation account locations using the `advanced` block. To solve this issue for either location, add the following to your `configure_connectivity_settings` input variable and the module should utilise the correct location when specifying either `eastus` or `eastus2` as the desired region:

```hcl
  configure_connectivity_settings = {
    # other settings removed for brevity
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_automation_account = {
          management = {
            eastus = {
              location = "eastus2"
            }
            eastus2 = {
              location = "eastus"
            }
          }
        }
      }
    }
  }
```

The relevant code in the module where this is applied can be seen here:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/8cd6f249e5396d505ce59c07c74fd68016c68a4f/modules/management/locals.tf#L157

**Comment by krowlandson** [comment]
@autocloudarc... Please test the above and let me know if this works as expected. I will then apply this logic to the module so you don't need to do this manually.

**Comment by krowlandson** [comment]
@autocloudarc I can also see this was "addressed" in the Bicep module in https://github.com/Azure/ALZ-Bicep/pull/97 so thank you for confirming.

**Comment by autocloudarc** [comment]
Thanks again @krowlandson for being so responsive. I copied/pasted these advanced settings into my configure_management_resources input variable (you suggested configure_connectivity_settings input variable, but I believe that may have just been a typo, since these resources are in the management and not the connectivity subscription. The results unfortunately, did not change and both resources were still placed in the eastus2 region. 

![image](https://user-images.githubusercontent.com/15109536/187404919-ad69448e-8c2d-4c42-bdf1-017098058779.png)

![image](https://user-images.githubusercontent.com/15109536/187404945-c0be4e03-9d1d-4c41-9fa9-f9c2f171033c.png)

![image](https://user-images.githubusercontent.com/15109536/187404978-c69139af-3fab-4dfa-8e52-fa9cec2d6fcf.png)

**Comment by krowlandson** [comment]
Yes, you're correct... that was a typo! I'll also double check the syntax provided above and come back to you later.

**Comment by krowlandson** [comment]
@autocloudarc

Actually, not such a difficult one for me to verify... In the `connectivity` data module we standardised on including the location of the target resource(s) within the map when defining overrides. Within the `management` data module we didn't.

I've corrected the example above but sadly you will need to correctly specify the pairing as I cannot (at this level) determine how an end user would specify the primary management location to determine this programmatically like I will within the module when implementing a fix.

**Comment by autocloudarc** [comment]
@krowlandson Thank you! The updated code above works for me now. :-) Made my day!!

**Comment by krowlandson** [comment]
Awesome, glad this helped @autocloudarc... will keep this issue open until we implement a more permanent fix.

Thank you for confirming that the above worked as a tactical work-around 👍🏻

**Comment by jtracey93** [comment]
Trigger ADO Sync

**Comment by krowlandson** [comment]
Trigger ADO Sync
