### ISSUE TITLE
Subnets still created when configuration scope set to `enabled = false`

### ISSUE THREAD

**Issue by ATuckwell** [Azure/terraform-azurerm-caf-enterprise-scale#450]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.1.2

**azure provider**: 3.0.2

**module**: 2.3.1

#### Describe the bug

During a recent customer deployment there was some confusion created when the VNG and AF config was set to **enabled = false**, but the module still attempted to deploy these subnets, i.e. The CIDR ranges that were left within the VNG and AF address prefix still showed up within a terraform plan. Only when the address prefix was removed did the module stop trying to create these subnets.

#### Steps to Reproduce

Within the advanced configuration of a Virtual network using the **settings.connectivity.tf** (as per guide [here](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings)), the hub network is configured with the required address space.

**Example hub network config**
![image](https://user-images.githubusercontent.com/106317528/187454317-b2794ba6-76ab-4663-81e2-a6e733644de0.png)

If **virtual network gateway** or **azure firewall** config is set to **enabled = false**, but has address prefix configured, the module will try to create this subnet within the hub virtual network. 

![image](https://user-images.githubusercontent.com/106317528/187454913-38e33883-08fe-43eb-8b71-932285126631.png)

If the address prefix is a valid address range within the virtual network address space the subnet will be created, even though **enabled = false**. This has been confirmed for both the VNG and AF subnets. 

![image](https://user-images.githubusercontent.com/106317528/187455015-c4d11eb0-0ec7-4263-b82e-b58a3e25a600.png)

![image](https://user-images.githubusercontent.com/106317528/187455041-a1a0a2f4-aaed-4261-ac44-bee7ef15d551.png)

If the Address prefix is **NOT** a valid address range within the virtual network address space, then it will show on the **terraform plan**, but will error upon **terraform apply** (as expected as this is not a valid prefix).

![image](https://user-images.githubusercontent.com/106317528/187455093-3cc01145-6655-4610-8bf5-a6435be3e8f1.png)
![image](https://user-images.githubusercontent.com/106317528/187455106-d7d7e6bc-fc7e-4d5f-aee9-028977331ed0.png)

#### Screenshots

Screenshots added above.

#### Additional context

- This may not be a bug, and is potentially expected behaviour, but this issue caused issues during a customer deployment using the advanced deployment guidance.
- This has only been tested within the first hub network, but assumption is that the second hub network will use the same logic.

**Comment by krowlandson** [comment]
Thank you for logging this @ATuckwell... as discussed online, this should be a relatively simple fix and the outcome you describe was the original intent of the logic.

I also don't feel this should have a negative impact on existing customers once implemented so we should be able to add this under a minor release.

Will speak to the team to get this appropriately prioritised on our backlog.

**Comment by ATuckwell** [comment]
@JamJarchitect , FYI as per proposal of updating logic within module.

**Comment by krowlandson** [comment]
Trigger ADO Sync
