### ISSUE TITLE
Exclude archetype not working for management, connectivity or sandbox

### ISSUE THREAD

**Issue by owejak** [Azure/terraform-azurerm-caf-enterprise-scale#451]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.8

**azure provider**: 3.0.2

**module**: 2.3.1

#### Describe the bug
We are trying to disable some azure policies using the exclude archetype, this applies to the root or our custom landing zones, but doesn't apply to management, connectivity, decommissioned or sandbox
#### Steps to Reproduce
File is called "archetype_exclusion_decommissioned.json"
```
{
"exclude_es_decommissioned": {
    "policy_assignments": [
        "Deploy-ASC-Monitoring",
        "Deploy-AzActivity-Log",
        "Deploy-LX-Arc-Monitoring",
        "Deploy-MDFC-Config",
        "Deploy-Resource-Diag",
        "Deploy-VM-Monitoring",
        "Deploy-VMSS-Monitoring",
        "Deploy-WS-Arc-Monitoring"
    ],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
    "parameters": {},
    "access_control": {}
    }
}
}
```
This file with Terraform plan 

#### Screenshots
This is what we get when se do exclude_es_root:
![image](https://user-images.githubusercontent.com/112624741/187898659-7036778b-dd7c-4274-a78c-e308c1059f8c.png)

This is what we get when planning with exclude_es_decommissioned:
![image](https://user-images.githubusercontent.com/112624741/187895656-0043e586-f987-4433-aae7-4ed90b2b82f4.png)

**Comment by jtracey93** [comment]
Hi @owejak,

These polices are assigned at the intermediate root management group "es_root" so you would need to exclude them from there. 

Or use the "notScopes" to exclude those policies from taking effect on the decommissioned management group. 

Hope that helps

Thanks

Jack

**Comment by jtracey93** [comment]
This has been handled over email

**Comment by krowlandson** [comment]
Trigger ADO Sync
