### ISSUE TITLE
Question - How to exclude inheritance of Deploy-Resource-Diag initiative?  

### ISSUE THREAD

**Issue by cmohams9** [Azure/terraform-azurerm-caf-enterprise-scale#466]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=description>Description </h3>
<h4 id=isyourfeaturerequestrelatedtoaproblem>Is your feature request related to a problem? </h4>
<p>I would like to exclude sandbox MG inheriting Deploy-Resource-Diag and some other initiatives. What is the best practice to achieve this? </p>
<h4 id=describethesolutionyoudlike>Describe the solution you'd like </h4>
<p>Exclude Sandbox MG from certain policy inheritance </p>
<h4 id=additionalcontext>Additional context </h4>

**Comment by krowlandson** [comment]
Thank you for the question @cmohams9 

We generally advise that the top-level Policy Assignments should be applied consistently across all Subscriptions, but to achieve the above we would recommend using [policy exemptions](https://learn.microsoft.com/azure/governance/policy/concepts/exemption-structure).

This won't be possible with the module alone, but can be created in Terraform using the [azurerm_management_group_policy_exemption](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_policy_exemption) resource assigned to your `sandbox` management group.

I think this is a better approach than removing the assignments at the intermediate root, and then having to re-assign to the `platform`, `landing-zones` and `decommissioned` management groups.

Hope this helps, but please let us know if you have any further questions regarding this.

**Comment by cmohams9** [comment]
Thanks , I will try out the exemption option and get back to you if any questions.

Sujith



From: Kevin Rowlandson ***@***.***>
Date: Monday, 26 September 2022 at 2:16 PM
To: Azure/terraform-azurerm-caf-enterprise-scale ***@***.***>
Cc: Sujith Mohammed ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/terraform-azurerm-caf-enterprise-scale] Question - How to exclude inheritance of Deploy-Resource-Diag initiative? (Issue #466)

Thank you for the question @cmohams9<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmohams9&data=05%7C01%7CSujith.Mohammed%40jci.com%7Cd73ea2ef69694e22031e08da9fa81d47%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637997841636426313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GCN%2Bh3YusgclQjX%2F81z7OdlMxNNiOqS%2FTUCT%2FkL6Upg%3D&reserved=0>

We generally advise that the top-level Policy Assignments should be applied consistently across all Subscriptions, but to achieve the above we would recommend using policy exemptions<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fazure%2Fgovernance%2Fpolicy%2Fconcepts%2Fexemption-structure&data=05%7C01%7CSujith.Mohammed%40jci.com%7Cd73ea2ef69694e22031e08da9fa81d47%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637997841636426313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aYyDCtD4F6aT6SGQa8je9UTRUy6ErktPQlqv5z7kn94%3D&reserved=0>.

This won't be possible with the module alone, but can be created in Terraform using the azurerm_management_group_policy_exemption<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Fazurerm%2Flatest%2Fdocs%2Fresources%2Fmanagement_group_policy_exemption&data=05%7C01%7CSujith.Mohammed%40jci.com%7Cd73ea2ef69694e22031e08da9fa81d47%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637997841636426313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p27jIEJh%2FzCeiNHb0bE518uK4MWe6wDQ4Pg0ISa1UHQ%3D&reserved=0> resource assigned to your sandbox management group.

I think this is a better approach than removing the assignments at the intermediate root, and then having to re-assign to the platform, landing-zones and decommissioned management groups.

Hope this helps, but please let us know if you have any further questions regarding this.

**Comment by krowlandson** [comment]
Trigger ADO Sync
