### ISSUE TITLE
Error: A resource with the ID "/providers/Microsoft.Authorization/roleDefinitions/...managementGroups/xxxxx" already exists - to be managed via Terraform this resource needs to be imported into the State

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#467]
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: </p>
<p>```terraform -v </p>
<p>Terraform v1.2.9
on darwin_amd64 </p>
<ul>
<li>provider registry.terraform.io/hashicorp/azurerm v3.24.0 </li>
<li>provider registry.terraform.io/hashicorp/random v3.4.3 </li>
<li>provider registry.terraform.io/hashicorp/time v0.8.0 </li>
</ul>
<p>Your version of Terraform is out of date! The latest version
is 1.3.0. You can update by downloading from https://www.terraform.io/downloads.html </p>
<pre><code>**azure provider**:
</code></pre>
<h1 id=configuretheminimumrequiredproviderssupportedbythismodule>Configure the minimum required providers supported by this module </h1>
<p>terraform {
  required<em>providers {
    azurerm = {
      source  = &quot;hashicorp/azurerm&quot;
      version = &quot;&gt;= 3.0.2&quot;
      configuration</em>aliases = [
        azurerm.connectivity,
        azurerm.management,
      ]
    }
    time = {
      source  = &quot;hashicorp/time&quot;
      version = &quot;&gt;= 0.7.0&quot;
    }
    random = {
      source  = &quot;hashicorp/random&quot;
      version = &quot;&gt;= 3.1.0&quot;
    }
  } </p>
<p>required_version = &quot;&gt;= 0.15.1&quot;
} </p>
<pre><code>**module**:
</code></pre>
<p>v2.3.1 </p>
<pre><code>### Description

#### Describe the bug

After cloning down the latest version, providing minimal default configuration, successful plan and then trying to apply the deployment fails with these errors indicating resources which have been created and are somehow out of the state (this is odd because the resources were never created outside of the provided code!):
</code></pre>
<p>│ Error: A resource with the ID &quot;/providers/Microsoft.Management/managementGroups/engeneon/providers/Microsoft.Authorization/policyDefinitions/Deploy-DDoSProtection&quot; already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for &quot;azurerm<em>policy</em>definition&quot; for more information.
│ 
│   with module.enterprise<em>scale.azurerm</em>policy<em>definition.enterprise</em>scale[&quot;/providers/Microsoft.Management/managementGroups/engeneon/providers/Microsoft.Authorization/policyDefinitions/Deploy-DDoSProtection&quot;],
│   on .terraform/modules/enterprise<em>scale/resources.policy</em>definitions.tf line 1, in resource &quot;azurerm<em>policy</em>definition&quot; &quot;enterprise<em>scale&quot;:
│    1: resource &quot;azurerm</em>policy<em>definition&quot; &quot;enterprise</em>scale&quot; {
│ 
╵ </p>
<p>``` </p>
<p>This happens despite no code changes to the current latest code and minimal default code configuration. </p>
<p>1) Complete apply fail is here: https://gist.github.com/archmangler/91898a65f5e66eac90f42e484196d55a
2) Complete plan is here: https://gist.github.com/archmangler/da0de1be87b825c0c7834df3772c9b5d
3) Complete code: https://github.com/engeneon/terraform-azurerm-caf-enterprise-scale </p>
<h4 id=stepstoreproduce>Steps to Reproduce </h4>
<p>Minimal default configuration of v2.3.1 is required to reproduce the issue: </p>
<ol>
<li>git clone https://github.com/Azure/terraform-azurerm-caf-enterprise-scale.git </li>
<li>configure as per: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Provider-Configuration#multi-subscription-deployment </li>
<li>terraform init </li>
<li>terraform plan -out terraform.plan </li>
<li>terraform apply terraform.plan </li>
</ol>
<h4 id=screenshots>Screenshots </h4>
<h4 id=additionalcontext>Additional context </h4>
<p>One would expect this to work off the bat with default config as documented in the wiki. The weird  out of state errors are especially difficult to troubleshoot because the resource configuration is not static - it's either created by iterating blocks through loops or templated - so <code>terraform import</code> doesn't fix here. </p>

**Comment by krowlandson** [comment]
Hi @archmangler, thank you for your interest in our module.

I think the issue is due to you cloning the module.

The code you've added to `main.tf` looks OK but you need to do this in your own root module. Terraform will download the module and other dependencies for you.

**Comment by archmangler** [comment]
Hi @krowlandson  - thanks for your response.

As far as I'm aware I haven't cloned the module at all, just the example code at the repo:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale.git

As I understand it, this code consumes the Azure CAF enterprise module?

Perhaps I am unclear as to what you mean by "you need to do this in your own root module. "  Is there perhaps a step by step guide on how to do this ?

**Comment by archmangler** [comment]
Thanks @krowlandson  - it's clear this is a module, not a blueprint.

**Comment by krowlandson** [comment]
Great stuff... glad you managed to sort this out.

In general, most common scenarios are covered in the Wiki, but for any other questions please feel free to raise a new issue and we'll do our best to help.
