### ISSUE TITLE
Documentation Request: Spoke VNET configuration in terraform to complete connectivity to Hub VNET

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#472]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

While the hub-spoke peering configuration on the hub side appears to be well documented, there is no example of the configuration on the spoke side.

#### Describe the solution you'd like

A terraform example of the spoke VNET configuration required to complete the sync and initiation for spoke peering to the hub vnet.

#### Additional context

Overall, there needs to be an example of complete hub-spoke buildout.

**Comment by jtracey93** [comment]
@matt-FFFFFF is this somewhere TF LZ Vending can help @archmangler here do you think?

**Comment by matt-FFFFFF** [comment]
Hi @archmangler 

See the LZ vending module for examples, it will manage both sides of the peering or vWAN connection.

https://github.com/Azure/terraform-azurerm-lz-vending/wiki/Examples

**Comment by archmangler** [comment]
Thanks @jtracey93  @matt-FFFFFF !

**Comment by krowlandson** [comment]
Trigger ADO Sync
