### ISSUE TITLE
Documentation Request: How to configure Azure Firewall Policies (or Rules) using the module?

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#475]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

There are no examples in the documentation or indications in the default configuration on how to add Azure Firewall Policies or Rules. This leaves the user wondering if policies should be managed by the module or outside of it. However, the module code does suggest policies are somehow to be included in the connectivity configuration ...

#### Describe the solution you'd like

Examples from basic to advanced on Azure Firewall configuration in the module. Specifically:

- Creation of custom firewall policies
- Creation of rules

#### Additional context

Using v2.4.0 of the module

**Comment by archmangler** [comment]
This bloc of code in `locals.connectivity.tf ` suggests that `azurerm_firewall_policy` is a bloc of configuration that should be defined in the variables.tf of the root module:

```
# The following locals are used to build the map of Azure
# Firewall Policies to deploy.
locals {
  azurerm_firewall_policy_connectivity = {
    for resource in module.connectivity_resources.configuration.azurerm_firewall_policy :
    resource.resource_id => resource
    if resource.managed_by_module &&
    resource.scope == "connectivity"
  }
}
```
However, I can't infer the configuration of the `azurerm_firewall_policy` bloc from this.

**Comment by krowlandson** [comment]
@archmangler we currently assign a default `azurerm_firewall_policy` to the firewall as this allows us to control settings like setting the [DNS configuration](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy#dns) for the firewall through the module.

For the default `azurerm_firewall_policy` you can configure it using the [`config.azure_firewall.config`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks#configazure_firewallconfig) settings, which is documented in our Wiki.

We have included the ability to use the [rule hierarchy](https://docs.microsoft.com/azure/firewall-manager/rule-hierarchy) option by setting [`config.azure_firewall.config.base_policy_id`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.hub_networks#configazure_firewallconfig) and you can add your own rules to the Azure Firewall Policy using the [`azurerm_firewall_policy_rule_collection_group`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy_rule_collection_group).

Again, we will look to triage this for adding more details to the Wiki in due course.

> There is equivalent content in the Wiki for if you are using Secure Virtual WAN

**Comment by archmangler** [comment]
Thanks @krowlandson  - this works.

**Comment by krowlandson** [comment]
Trigger ADO Sync
