### ISSUE TITLE
Documentation Request/Feature Request: Private Link Configuration for each subnet in spoke VNET 

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#477]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

It's not clear in the documentation how  the module can be used to manage Azure Private Links in each subnet (for spoke or hub vnets). The documentation refers to Private DNS Zone Links for Private Links, but not actually how to configure Azure Private Links for subnets via the module.

#### Describe the solution you'd like

Desired solution:

- Module configuration and documentation for creating private links for each subnet (spoke or hub)

Alternatively:

- Indication in the documentation if Private Links are to be maintained outside the module or not.

**Comment by krowlandson** [comment]
Hi @archmangler ... thank you for this question.

We have documented our recommendations for Private Endpoints here:
[Azure Private Link in a hub-and-spoke network](https://learn.microsoft.com/azure/architecture/guide/networking/private-link-hub-spoke-network)

As you have already realised, we don't actually create these with the module and recommend deploying them outside this module.

The module instead focuses on creation of the centralized DNS zones, and includes an [example policy assignment](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/cc22c56ed6849ef900b02c6f538fdfa266368fc5/modules/archetypes/lib/archetype_definitions/archetype_definition_es_corp.tmpl.json#L5) on the `corp` scope to ensure private endpoints are correctly configured.

I will discuss this with the team to see whether we can improve the documentation around this across our implementation options.

cc: @jtracey93 @matt-FFFFFF @jfaurskov

**Comment by archmangler** [comment]
Thanks. I've implemented this with a separate module.

**Comment by krowlandson** [comment]
Trigger ADO Sync
