### ISSUE TITLE
Using the uuid function in Custom RBAC Role definition

### ISSUE THREAD

**Issue by Duchynko** [Azure/terraform-azurerm-caf-enterprise-scale#479]
### Versions

**terraform**: 1.3.1

**azure provider**: 3.8.0

**module**: Azure/caf-enterprise-scale/azurerm

#### Describe the bug

I can't figure out how to use the `uuid` function in a custom RBAC Role definition—as described on the documentation page [[Examples] Create and Assign Custom RBAC Roles](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-and-Assign-Custom-RBAC-Roles). In the documentation it's stated 

> We need to ensure that every custom role we create has a unique value for "name". To do that, there are a number of tooling options we can use, including:
>
> The New-Guid PowerShell cmdlet
> The *nix tool uuidgen
> The uuidv5 function that is built-in to Terraform.

I'm trying to deploy the custom role to multiple management groups (Dev, Test, Prod) so that I have three separate roles in each MG. In other words, I'm trying to deploy `[Custom Dev] Contributor` to the `Dev` Management Group, `[Custom Test] Contributor` to the `Test` Management Group, and so on.

For that, every role definition must have a unique UUID. What I've tried to do is to inject the UUID to the definition template as a variable but Terraform complains with the following error.

```
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/caf-enterprise-scale/resources.role_definitions.tf line 2, in resource "azurerm_role_definition" "enterprise_scale":
│    2:   for_each = local.azurerm_role_definition_enterprise_scale
│     ├────────────────
│     │ local.azurerm_role_definition_enterprise_scale will be known only after apply
│ 
│ The "for_each" map includes keys derived from resource attributes that
│ cannot be determined until apply, and so Terraform cannot determine the
│ full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map
│ keys statically in your configuration and place apply-time results only in
│ the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply
│ only the resources that the for_each value depends on, and then apply a
│ second time to fully converge.
╵
```

#### Steps to Reproduce

```
// lib/role_definitions/custom_role

{
    "name": "${custom_uuid}",
    "type": "Microsoft.Authorization/roleDefinitions",
    "apiVersion": "2021-06-01",
    "scope": null,
    "properties": {
       // ...
    }
}
```

```hcl
// main.tf

module "caf-enterprise-scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "2.3.1"

  template_file_variables = {
    custom_uuid = uuid()
  }

 # ...
}
```

#### Additional context

How do I dynamically inject a custom UUID into a Custom RBAC role definition?

**Comment by Duchynko** [comment]
Okay, I figured it out. The documentation clearly mentions using `uuidv5` while I was using `uuid` function instead. I didn't assume the former one would work while the later doesn't. 

The following works as expected.
```hcl
// main.tf

module "caf-enterprise-scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "2.3.1"

  template_file_variables = {
    custom_uuid = uuidv5("namespace", "name")
  }

 # ...
}
```

**Comment by krowlandson** [comment]
Trigger ADO Sync
