### ISSUE TITLE
Log Analytics solution provider error

### ISSUE THREAD

**Issue by DevOpsStyle** [Azure/terraform-azurerm-caf-enterprise-scale#480]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "1.1.3"
}

**terraform**:

**azure provider**:

providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
   }
**module**:

azurerm

### Description

After deployng CAF Terraform show up the following error:
"When applying changes to
│ module.enterprise_scale.azurerm_log_analytics_solution.management["/subscriptions/c1984e1a-e223-4422-81cd-e05e3ce595c1/resourceGroups/Cetesting-mgmt/providers/Microsoft.OperationsManagement/solutions/AgentHealthAssessment(Cetesting-la)"],
│ provider "provider[\"registry.terraform.io/hashicorp/azurerm\"].management" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker."

#### Steps to Reproduce

Deploy the CAF landing zone

#### Screenshots

![image](https://user-images.githubusercontent.com/93210452/194374255-0cfdac5a-922c-4370-ac74-a25ae8deda11.png)

**Comment by krowlandson** [comment]
Trigger ADO Sync
