### ISSUE TITLE
Feature Request - configure automation account in management subscription 

### ISSUE THREAD

**Issue by prjelesi** [Azure/terraform-azurerm-caf-enterprise-scale#492]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

There is no possibility to configure automation account network integration that is deployed as part of management environment.  

#### Describe the solution you'd like

Would be great to have parameter in settings.management.tf like:

aa_public_network_access_enable=true/false

**Comment by krowlandson** [comment]
Thank you for logging this @prjelesi ... we will look to triage this as agree this would be a useful feature to add.

**Comment by krowlandson** [comment]
Need to add the following attributes for this resource:

- [public_network_access_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account#public_network_access_enabled)
- [local_authentication_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account#local_authentication_enabled)
