### ISSUE TITLE
Feature Request: avoid deprecated enforce_private_link_endpoint_network_policies attribute

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-caf-enterprise-scale#495]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Avoid

```
Warning: Argument is deprecated

  with module.caf-enterprise-scale.azurerm_subnet.connectivity,
  on .terraform/modules/caf-enterprise-scale/resources.connectivity.tf line 58, in resource "azurerm_subnet" "connectivity":
  58:   enforce_private_link_endpoint_network_policies = each.value.template.enforce_private_link_endpoint_network_policies

`enforce_private_link_endpoint_network_policies` will be removed in favour of
the property `private_endpoint_network_policies_enabled` in version 4.0 of
the AzureRM Provider
```

#### Is your feature request related to a problem?

no, preventive to ensure smooth transition to future provider version

#### Describe the solution you'd like

avoid deprecated attrib and use suggested alternative.

**Comment by krowlandson** [comment]
Hi @davidkarlsen ... this has already been addressed in #489 

As this will be a breaking change, we are just agreeing on when to release this.
