### ISSUE TITLE
Question - private_dns_zone_prefix - Locals in connectivity module

### ISSUE THREAD

**Issue by Schillman** [Azure/terraform-azurerm-caf-enterprise-scale#497]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Related to _Add additional resource types to variable validation_ #361  & [[Variables] template_file_variables](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-template_file_variables)

I've chosen not to deploy the connectivity module because the support for Virtual WAN wasn't available back when we started.

We have deployed private DNS zones in a spoke and want to utilize the ES CAF built-in initiative "Deploy-Private-Dns-Zones" but point the _private_dns_zone_prefix_  to our spoke Vnet. 

I've tried to utilize the template variable **private_dns_zone_prefix** however, it doesn't pick that up. So I went with trying to do some advanced configuration for the connectivity module without deploying any of its resources. But it didn't solve my issue either. It still uses some default values. : "/subscriptions/xxx-xxx-xxx-xxxx/resourceGroups/es-dns/providers/Microsoft.Network/privateDnsZones/ 
 I'm not able to decipher the advanced input for connectivity.

I found that hardcoding the following locals **private_dns_zone_prefix** solves my problem.
"/subscriptions/xxxx-xxx-xxx-xxxx/resourceGroups/rg-dns-prod/providers/Microsoft.Network/privateDnsZones/"

[/modules/connectivity/locals.tf](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/connectivity/locals.tf#L1280f)

private_dns_zone_prefix        = "${local.resource_group_config_by_scope_and_location["dns"][local.dns_location].resource_id}/providers/Microsoft.Network/privateDnsZones/"

So my question follows, how would I go about specifying the advanced block to be able to use the actual value for this parameter?
Below is the block I tried. It's somewhat based on #361. I'm by no means a pro at interpreting code 😄

```hcl
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_private_dns_zone = {
          dns = {
            westeurope = {
              resource_id = var.privateendpoint_resource_base_id
            }
          }
        }
      }
    }
```
I really appreciate any help you can provide.

**Comment by krowlandson** [comment]
Thank you for your question @Schillman 

If I have understood correctly, you are trying to ensure that the correct value is parsed into the `Deploy-Private-Dns-Zones` Policy Assignment without using the module to deploy the DNS zones?

Currently we only create this Policy Assignment on the `corp` Management Group. Depending on how you are implementing this Policy Assignment, there are a few options for how to overcome this and interestingly we have literally just adde some guidance for this.

We don't quite have it published to the Wiki yet, but please can you check out the content here:
[[Examples] Set parameter values for Policy Assignments](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/docs/wiki/%5BExamples%5D-Set-parameter-values-for-Policy-Assignments.md)

This should hopefully give you the guidance you need to set the required parameter values as part of creating a Policy Assignment.

Also a massive thank you to @DevSecNinja who helped with this timely content!!

**Comment by krowlandson** [comment]
Just to add, you may or may not be able to use `template_file_variables` as an alternative to declaring each of the parameters, depending on where you are using this assignment.

In theory, you would add the following to your module declaration to enable this:

```hcl
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "2.4.1"

  # additional config and input variables removed for brevity

  template_file_variables = {
    private_dns_zone_prefix = "/subscriptions/xxxx-xxx-xxx-xxxx/resourceGroups/rg-dns-prod/"
  }

}

```

However this is a "managed Policy Assignment" so the connectivity module will override whatever is being inherited from the template if assigned at the `corp` scope.

**Comment by Schillman** [comment]
Hi,

First of all, thank you for your answer, and yes, you understood me correctly. Unfortunately, I didn't have time to check this yesterday.

However, Today I tried the above suggestions without success. I even tried the following:

```hcl
advanced = {
      custom_settings_by_resource_type = {
        azurerm_private_dns_zone = {
          dns = {
            westeurope = {
              resource_id = "/subscriptions/xxxx-xxx-xxx-xxxx/resourceGroups/rg-dns-prod/"
            }
          }
        }
      }
    }
```
So I created my definition, initiative, and assignment, along with archetype_config and template_file_variables.
```json
"Deploy-Dns-Records": {
          "privatednszoneprefix": "${dns_zone_prefix}"
}
```

The reason I wanted to utilize the built-in assignment was that I didn't want to have to update our definitions manually. But as a colleague told me, a Private-link resource is not often added.

Again, Thank you for your answer. Greatly appreciate it.

**Comment by krowlandson** [comment]
Glad you managed to find a solution to this @Schillman although I'm still not completely sure why you were not able to use assignment. If you think something is missing in the guidance I have shared, please let me know so we can work on improving it for greater clarity.

Also, as an FYI, please see the following issues which may be of interest to you:

- https://github.com/Azure/Enterprise-Scale/issues/1097
- https://github.com/Azure/Enterprise-Scale/issues/725

This is now being actively worked on so we should be shipping updated policy files for this soon.

**Comment by Schillman** [comment]
Hi @krowlandson,

I'd gladly take a meeting where we can discuss this further. So I would be looking forward to that.
Topics to be discussed:
Our particular problem and the potential solution. But if there already is a way of solving it, then you could probably explain to me how one should go about setting a custom privateDnsZoneId. Then, I could make a draft/PR, for example, using it.
