### ISSUE TITLE
Feature Request: How to Configure Additional Subnets in Hub? Managed Externally?

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#502]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

- Hub VNET configuration seems to indicate the format for specifying additional subnets in the VNET (see below) however the module doesn't prescribe any solution for creating those subnets.
- Ideally, the module should include configuration for adding new subnets including their route tables and NSGs, or recommend modules for doing this:

```
variable "configure_connectivity_resources" {
  type = object({
    settings = object({
      hub_networks = list(
        object({
.
.
.            subnets = list(
              object({
                name                      = string
                address_prefixes          = list(string)
                network_security_group_id = string
                route_table_id            = string
              })
            )
.
.
.
```

#### Describe the solution you'd like

- Configuration and examples for creating additional subnets (including their associated NSGs and UDRs) which can be referenced in the hub configuration.
- Ideally the the caf module allows definition of subnet plus associated udrs and nsg in once unified configuration
- Alternatively a single module which packages the subnet,udr and NSG configuration into one configuration scheme ready to be consumed by the hub subnet configuration .
- Least desireable: Hub Subnets, UDRs, NSGs need to be managed using  a completely separate module, and need to be created first in Azure and then added in the hub configuration post-creation.

Alternatively:

Terraform module managing subnets in a standalone way and integrated with the CAF module configuration.

#### Additional context

- The documentation provides no examples or details on using the subnets parameter to the hub module:

`https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Module-Variables`

**Comment by krowlandson** [comment]
Thank you for your question @archmangler.

Although we don't provide any official guidance around adding Subnets to the hub in ALZ, we added this capability to provide flexibility for exactly this.

Currently we only support adding subnets, and the entries for `network_security_group_id` and `route_table_id` are placeholders for further work which hasn't been completed yet. In an ideal world, `optional()` types would have made this unnecessary but they only became GA in Terraform v1.3, long after this was added to prevent breaking changes.

As such, you can add subnets to each hub network using the code example below but will need to associate NSGs or Route Tables using native Terraform:

```hcl
  # Additional settings removed for brevity
  configure_connectivity_resources = {
    settings = {
      hub_networks = [
        {
          enabled = true
          config = {
            address_space                = ["10.100.0.0/22", ]
            location                     = var.primary_location
            # Additional settings removed for brevity
            subnets                      = [
              {
                name                      = "mySubnet"
                address_prefixes          = ["10.101.2.0/24", ]
                network_security_group_id = null
                route_table_id            = null
              }
            ]
            # Additional settings removed for brevity
      ]
      # Additional settings removed for brevity
  }
```

Does this help?

**Comment by archmangler** [comment]
Thanks, @krowlandson  - we will use a separate module to manage subnets and update as recommended above.

**Comment by krowlandson** [comment]
OK thanks for confirming. Are you happy to share why you went with the decision to fully manage the subnets outside the module? Hopefully this will help us make decisions on how to improve moving forward 👍🏻

**Comment by archmangler** [comment]
Hi @krowlandson  - as follows:

- We have better control over automating the naming convention of the subnet name
- we may need to specify the NSG in detail which is attached to the subnet
- we may need to specify the routing table in detail associated with the subnet

It's not clear how the configuration in the example caters to all these items ...
