### ISSUE TITLE
Feature Request: Parameterise VNET Gateway ipConfiguration Name

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-caf-enterprise-scale#503]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The ipConfiguration > Name value for Virtual Network Gateways (VPN and ExpressRoute) deployed by the connectivity module currently takes the associated PIP name as the value.

azurerm_virtual_network_gateway_vpn = [
    for location, hub_network in local.hub_networks_by_location :
    {
      # Resource logic attributes
      resource_id       = local.vpn_gateway_resource_id[location]
      managed_by_module = local.deploy_virtual_network_gateway_vpn[location]
      # Resource definition attributes
      name                = local.vpn_gateway_name[location]
      resource_group_name = local.resource_group_names_by_scope_and_location["connectivity"][location]
      location            = location
      type                = "Vpn"
      sku                 = hub_network.config.virtual_network_gateway.config.gateway_sku_vpn
      ip_configuration = try(
        local.custom_settings.azurerm_virtual_network_gateway["connectivity_vpn"][location].ip_configuration,
        concat(
          [
            {
              **name = local.vpn_gateway_pip_name[location]**
              private_ip_address_allocation = (
                contains(
                  local.private_ip_address_allocation_values,
                  hub_network.config.virtual_network_gateway.config.advanced_vpn_settings.private_ip_address_allocation
                )
                ? hub_network.config.virtual_network_gateway.config.advanced_vpn_settings.private_ip_address_allocation
                : null
              )
              subnet_id            = "${local.virtual_network_resource_id[location]}/subnets/GatewaySubnet"
              public_ip_address_id = local.vpn_gateway_pip_resource_id[location]
            }
          ],

#### Describe the solution you'd like

Can we parametrise this value? Make it a declarable value in the config settings for the gateway? Post deployment you cannot change the name of the ipConfiguration due to its dependencies so if a Gateway has been created outside of this module and the ipConfiguration is left as default or given a custom name I cannot import the gateway into state and have the modules manage as its will want to change the name all the time and this action fails.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/42775203/200528353-cabb8bfb-5270-4e2c-b589-1b05af84e354.png">

**Comment by krowlandson** [comment]
This is an interesting ask and something I was looking at just last week whilst troubleshooting another issue related to the Virtual Network gateways (_not a problem with the module I must add!_).

The best way to handle this right now is to use the `advanced` object within the `configure_connectivity_settings` input variable. This currently means defining the entire `ip_configuration` block for each instance needed.

To do this, add the following to your input:

```hcl
  configure_connectivity_settings = {
    # additional attributes removed for brevity
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_virtual_network_gateway = {
          connectivity_vpn = {
            eastus = {                                  # replace eastus with the location you are using
              ip_configuration = [
                # insert configuration based on provider docs to match your actual settings
              ]
            }
          }
        }
      }
    }
  }
```

Hope this helps, but please let me know if you need any further support with this.

**Comment by birdnathan** [comment]
Thanks @krowlandson. I overlooked the fact the whole ip_configuration block can be configured by advanced settings.

**Comment by krowlandson** [comment]
Awesome, thanks for confirming @birdnathan

I'll close this issue, but please re-open if you require further support on this.
