### ISSUE TITLE
Bug Report:  Azure Private DNS Resolver: ` Error: updating Subnet: ... Original Error: Code="SubnetMissingRequiredDelegation"`

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#505]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

 `0.15.1`

**azure provider**:

`3.29.0`

**module**:

azurecaf `2.0.0-preview-3`

#### Describe the bug

Summary:

Azure CAF Terraform module tries to delete any service endpoints configured on subnets in the hub VNET.

Detail:

- This issue occurs when  trying to implement Azure DNS Private Resolver (https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-overview)
- When subnets are configured (using an external module or process) in the Azure CAF Hub with Azure Private DNS Resolver service endpoints and links are created as described here:

`https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-overview`

- However, when terraform is re-run to apply the azure caf enterprise module and update the hub vnet, the module wants to remove any service delegations it finds on any new subnets added to the hub vnet.

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.subnet_privatedns_dnsinbound.azurerm_subnet.main will be updated in-place
  ~ resource "azurerm_subnet" "main" {
        id                                             = "/subscriptions/319b5c03-aac1-4f4b-a8ed-1d722d02d814/resourceGroups/hkjc-connectivity-eastasia/providers/Microsoft.Network/virtualNetworks/hkjc-hub-eastasia/subnets/inbound-dns-ea-nprd-snet-hub00-net00"
        name                                           = "inbound-dns-ea-nprd-snet-hub00-net00"
        # (9 unchanged attributes hidden)

      - delegation {
          - name = "Microsoft.Network.dnsResolvers" -> null

          - service_delegation {
              - actions = [
                  - "Microsoft.Network/virtualNetworks/subnets/join/action",
                ] -> null
              - name    = "Microsoft.Network/dnsResolvers" -> null
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

- When terraform tries to apply this change, it fails as follows:

```
╷
│ Error: updating Subnet: (Name "inbound-dns-ea-nprd-snet-hub00-net00" / Virtual Network Name "hkjc-hub-eastasia" / Resource Group "hkjc-connectivity-eastasia"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SubnetMissingRequiredDelegation" Message="Subnet /subscriptions/319b5c03-aac1-4f4b-a8ed-1d722d02d814/resourceGroups/hkjc-connectivity-eastasia/providers/Microsoft.Network/virtualNetworks/hkjc-hub-eastasia/subnets/inbound-dns-ea-nprd-snet-hub00-net00 requires any of the following delegation(s) [Microsoft.Network/dnsResolvers] to reference service association link /subscriptions/319b5c03-aac1-4f4b-a8ed-1d722d02d814/resourceGroups/hkjc-connectivity-eastasia/providers/Microsoft.Network/virtualNetworks/hkjc-hub-eastasia/subnets/inbound-dns-ea-nprd-snet-hub00-net00/serviceAssociationLinks/dnsResolverLink." Details=[]
│ 
│   with module.subnet_privatedns_dnsinbound.azurerm_subnet.main,
│   on ../modules/azurerm-caf-subnet/main.tf line 10, in resource "azurerm_subnet" "main":
│   10: resource "azurerm_subnet" "main" {
│ 

```

 NOTE: In this case, subnets are not being managed in the azure CAF module, they're being added to the caf module-managed hub vnet using an external deploy pipeline.

#### Steps to Reproduce

1. add one or more subnets to the azure caf-module-managed hub VNET via the Azure portal
2. Create an Azure DNS Private Resolver using the created hub subnets using the example code here: https://raw.githubusercontent.com/Azure/terraform-provider-azapi/main/examples/Microsoft.Network/dnsResolvers/main.tf 
3.  Re-apply the hub VNET terraform using the azure caf enterprise module to check if  it tries to remove service association links from the subnets ...

#### Screenshots

```
│ Error: updating Subnet: (Name "inbound-dns-ea-nprd-snet-hub00-net00" / Virtual Network Name "hkjc-hub-eastasia" / Resource Group "hkjc-connectivity-eastasia"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SubnetMissingRequiredDelegation" Message="Subnet /subscriptions/319b5c03-aac1-4f4b-a8ed-1d722d02d814/resourceGroups/hkjc-connectivity-eastasia/providers/Microsoft.Network/virtualNetworks/hkjc-hub-eastasia/subnets/inbound-dns-ea-nprd-snet-hub00-net00 requires any of the following delegation(s) [Microsoft.Network/dnsResolvers] to reference service association link /subscriptions/319b5c03-aac1-4f4b-a8ed-1d722d02d814/resourceGroups/hkjc-connectivity-eastasia/providers/Microsoft.Network/virtualNetworks/hkjc-hub-eastasia/subnets/inbound-dns-ea-nprd-snet-hub00-net00/serviceAssociationLinks/dnsResolverLink." Details=[]
│ 
│   with module.subnet_privatedns_dnsinbound.azurerm_subnet.main,
│   on ../modules/azurerm-caf-subnet/main.tf line 10, in resource "azurerm_subnet" "main":
│   10: resource "azurerm_subnet" "main" {
│ 


```

#### Additional context

- We need to be able to implement AZure DNS Private Resolver service in the hub vnet, ideally using terraform. 
- Perhaps a switch could be implemented to disable the azure caf module's removal of the service association from externally managed subnets?

**Comment by krowlandson** [comment]
This is an interesting issue, so thank you for raising this @archmangler 

> the module wants to remove any service delegations it finds on any new subnets added to the hub vnet

In this case, this appears to not be our module (I don't know what you mean by `azurecaf 2.0.0-preview-3`), however I'm happy to offer some advice on this to help you.

I think this less of a "bug" and more a matter of mismatched configuration, the workaround is to add the missing delegation settings to your code following the guidance in the AzureRM docs for the [subnet delegation block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#delegation). If it's not possible to set this in the `azurecaf 2.0.0-preview-3` module, I would suggest raising an issue with the author of that module.

I don't believe there is anything for us to do regarding this in our module as you are managing these subnets outside of the module (but presumably within the same Terraform workspace?)

As such I will close this issue but please feel free to re-open if I have misunderstood the ask or you require further assistance.

**Comment by archmangler** [comment]
Hi @krowlandson - apologies, I have corrected the module version (I pasted the wrong module details in the ticket - it should be v2.4.0)

The subnets are being managed by a separate module, however even if we were to manage the subnets within the `terraform-azurerm-caf-enterprise-scale` module, there is no indication in the documentation on how to configure subnets for the case of Azure DNS Private Resolver.

To illustrate, the following configuration doesn't indicate how/where we'd add the necessary configuration:


```
  default = {
    settings = {
      hub_networks = [
        {
          enabled = true
          config = {
            address_space                = ["10.101.0.0/16", ]
            location                     = "eastasia"
            link_to_ddos_protection_plan = false
            dns_servers                  = []
            bgp_community                = ""
            subnets = [
              {
                name                      = "lol-ea-hub00-sbt-shared00"
                address_prefixes          = ["10.101.2.0/24"]
                network_security_group_id = null
                route_table_id            = null
              }
            ]
            virtual_network_gateway = {

```

Does `terraform-azurerm-caf-enterprise-scale` currently support Azure Private DNS Resolution as configured here:

`https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-overview`

Alternatively, can you perhaps provide some guidance on how to integrate Azure Prive DNS Resolution service with VNETs deployed by `terraform-azurerm-caf-enterprise-scale` module ?

**Comment by archmangler** [comment]
Note: 

Even for subnets managed using `terraform-azurerm-caf-enterprise-scale v2.4.0` module, we encounter the same problem when configuring Azure DNS Resolver.

It seems there needs to be some development required on `terraform-azurerm-caf-enterprise-scale` to ensure either:

a) Co-existence with Azure DNS Private Resolver - OR - 
b) Support for configuring Azure DNS Private resolver within the module itself.

References:

1. https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-overview
2. https://raw.githubusercontent.com/Azure/terraform-provider-azapi/main/examples/Microsoft.Network/dnsResolvers/main.tf

**Comment by krowlandson** [comment]
OK, I understand.

Right now this would be via the advanced input and is applicable to all subnets created by the module, regardless of how they are defined.

The general format should be as follows (_I haven't tested this exact code so please let me know if any issues_):

```hcl
  configure_connectivity_settings = {
    # additional attributes removed for brevity
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_subnet = {
          connectivity = {
            eastus = { # replace eastus with the location you are using
              subnet_name = { # replace subnet_name with the name of the subnet you want to configure
                {
                  delegation = [
                    {
                      name = "Microsoft.Network.dnsResolvers"
                      service_delegation = [
                        {
                          name    = "Microsoft.Network.dnsResolvers"
                          actions = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
                        }
                      ]
                    }
                  ]
                }
              } # repeat this block for each subnet you need to configure
            }
          }
        }
      }
    }
  }
```

Am I correct to assume that you are providing this as feedback rather than need this feature right now? Either way, I will link this to the work we are doing to refactor the module with `optional()` input type support as this will be easier for us to add without causing the inputs to become unmanageable for those who don't want to configure this.

**Comment by krowlandson** [comment]
> It's a feature request: Update documentation to clarify this area of subnet configuration.

This should form part of the updates I mentioned so will be covered then.

Thank you for the valuable feedback! 👍🏻

**Comment by archmangler** [comment]
Hi @krowlandson - this works quite fine. Thanks for the help!
