### ISSUE TITLE
Feature Request: Specify Regulatory Standards to include in Microsoft Defender Configuration

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#510]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

While the `terraform-azurerm-caf-enterprise-scale` allows enabling Microsoft Defender for some services, it doesn't seem to allow specifying one or more regulatory compliance standards eg `CIS 1.4`. 

Usually this has to be done via the portal using the following manual procedure:

1. From Defender for Cloud's menu, select Regulatory compliance to open the regulatory compliance dashboard. Here you can see the compliance standards currently assigned to the currently selected subscriptions.
2. From the top of the page, select Manage compliance policies. The Policy Management page appears.
3. Select the subscription or management group for which you want to manage the regulatory compliance posture.
4. To add the standards relevant to your organization, expand the Industry & regulatory standards section and select Add more standards.
5. From the Add regulatory compliance standards page, you can search for any of the available standards e.g: 

![image](https://user-images.githubusercontent.com/3898404/201306515-0c3d0bbc-f2b0-4773-be1e-ea21ed855d23.png)

(Note: Many enterprises on Azure require the regulatory package `CIS 1.4` to be included at least to pass a compliance review)

#### Describe the solution you'd like

What is desired is:

The global configuration for the module should allow enabling one or more of the following regulatory standards to be included in the configuration:

```
Azure CIS 1.1.0
Azure CIS 1.3.0
Azure CIS 1.4.0
Australian Government ISM PROTECTED
CMMC Level 3
Canada Federal PBMM
FedRAMP H
FedRAMP M
HIPAA HITRUST
ISO 27001:2013
NIST SP 800 171 R2
NIST SP 800-53 R4
NIST SP 800-53 R5
New Zealand ISM Restricted
New Zealand ISM Restricted v3.5
PCI DSS 4
RMIT Malaysia
Reserve Bank of India IT Framework for NBFC
SOC 2
SWIFT CSP CSCF v2020
SWIFT CSP CSCF v2022
UKO and UK NHS
```

Alternatives considered: Managing the Defender configuration in a separate custom module such as described here:

https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/deploy-microsoft-defender-for-cloud-via-terraform/ba-p/3563710

#### Additional context

Currently, the `terraform-azurerm-caf-enterprise-scale` module is used as-is, and the regulatory standards are configured using a separate, manual workflow in the portal as described here:

`https://awesomeopensource.com/project/Azure/regulatory-compliance-initiatives`

Naturally, this is difficult to manage in a scenario where landing zones are expected to be automated.

**Comment by archmangler** [comment]
Additional related  request:

Ability to select the default regulatory standards from a range of options to change the default one included in the module, which is:

 modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json:    

```
"policyDefinitionId": "/providers/Microsoft.Authorization/policySetDefinitions/1f3afdf9-d0c9-4c3d-847f-89da613e70a8",
```

**Comment by archmangler** [comment]
Quick note: To change the default regulatory policy to something else I've had to change the policy definition Id and updated the parameters accordingly in the template in the module:

```
"policyDefinitionId": "/providers/Microsoft.Authorization/policySetDefinitions/1f3afdf9-d0c9-4c3d-847f-89da613e70a8",
```

This is  fine for selection of on regulatory standard.

**Comment by krowlandson** [comment]
Thank you for this interesting request @archmangler

We don't currently configure any MDFC settings with Terraform, and only enable the preferred SKU using Azure Policy (if not already configured) however this raises an interesting question as to whether we should expand our capabilities (across all of our implementation options) to explicitly configure MDFC as DINE is really intended to catch and resolve non-compliance, rather than to be used as an alternative to managing resources with proper IaC.

cc: @jtracey93 for further discussion internally.

We will hopefully come back to you soon on this one 👍🏻

**Comment by matt-FFFFFF** [comment]
Can assign policy through existing functionality
