### ISSUE TITLE
Update policy assignment for deny public IP

### ISSUE THREAD

**Issue by jfaurskov** [Azure/terraform-azurerm-caf-enterprise-scale#512]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

On the Enterprise scale repo a [PR](https://github.com/Azure/Enterprise-Scale/pull/1103) changes the policy and assignment for deny public ip. Please modify ALZ-Terraform to reflect this change.

#### Describe the solution you'd like

N/A

**Comment by krowlandson** [comment]
- Closed by #523
