### ISSUE TITLE
Pass boolean parameter to archetype_config_overrides

### ISSUE THREAD

**Issue by florentvaldelievre** [Azure/terraform-azurerm-caf-enterprise-scale#517]
Terraform version v1.1.7
hashicorp/azurerm v2.93.1
registry.terraform.io/Azure/caf-enterprise-scale/azurerm 1.1.3 

I am trying to pass a boolean parameter to a built-in policy, but it seems to be passed as a string

```
archetype_config_overrides = {
  root = {
    archetype_id = "root"
    parameters = {
      "Deploy-Azure-Monitor-AMA" = {
        "bringYourOwnUserAssignedManagedIdentity" = {
          value = false
        }
      }
   }
}
```

Here is the plan

```
# module.enterprise_scale.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/xxx/providers/Microsoft.Authorization/policyAssignments/Deploy-Azure-Monitor-AMA"] will be created
+ resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
    + description          = "Enable Azure Monitor for the virtual machines (VMs) with AMA. Takes Log Analytics workspace as parameter and asks for an option to enable Processes and Dependencies."
    + display_name         = "[Preview]: Enable Azure Monitor for VMs with Azure Monitoring Agent(AMA)"
    + enforce              = true
    + id                   = (known after apply)
    + location             = "canadacentral"
    + management_group_id  = "/providers/Microsoft.Management/managementGroups/xxx"
    + metadata             = (known after apply)
    + name                 = "Deploy-Azure-Monitor-AMA"
    + not_scopes           = []
    + parameters           = jsonencode(
          {
            + bringYourOwnUserAssignedManagedIdentity = {
                + value = "false"
              }
          }
      )
    + policy_definition_id = "/providers/Microsoft.Authorization/policySetDefinitions/9dffaf29-5905-4145-883c-957eb442c226"

    + identity {
        + principal_id = (known after apply)
        + tenant_id    = (known after apply)
        + type         = "SystemAssigned"
      }
  }
```

Error when applying:
2022-11-17T13:51:33.3680532Z Error: creating Policy Assignment ID: (Assignment Name "Deploy-Azure-Monitor-AMA" / Scope "/providers/Microsoft.Management/managementGroups/xxx"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicyParameterType" Message="The policy parameter 'bringYourOwnUserAssignedManagedIdentity' does not match the expected parameter type defined in the policy definition '9dffaf29-5905-4145-883c-957eb442c226'. Details 'The expected policy parameter type: 'Boolean'. The actual policy parameter type 'String'.'."

```
{
  "name": "Deploy-Azure-Monitor-AMA",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Enable Azure Monitor for the virtual machines (VMs) with AMA. Takes Log Analytics workspace as parameter and asks for an option to enable Processes and Dependencies.",
    "displayName": "[Preview]: Enable Azure Monitor for VMs with Azure Monitoring Agent(AMA)",
    "notScopes": [],
    "parameters": {},
    "policyDefinitionId": "/providers/Microsoft.Authorization/policySetDefinitions/9dffaf29-5905-4145-883c-957eb442c226",
    "scope": "${current_scope_resource_id}",
    "enforcementMode": null
  },
  "location": "${default_location}",
  "identity": {
    "type": "SystemAssigned"
  }
}
```

Full Stack error:

```
Error: creating Policy Assignment ID: (Assignment Name "Deploy-Azure-Monitor-AMA" / Scope "/providers/Microsoft.Management/managementGroups/xxx"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicyParameterType" Message="The policy parameter 'bringYourOwnUserAssignedManagedIdentity' does not match the expected parameter type defined in the policy definition '9dffaf29-5905-4145-883c-957eb442c226'. Details 'The expected policy parameter type: 'Boolean'. The actual policy parameter type 'String'.'."

  with module.enterprise_scale.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/xxx/providers/Microsoft.Authorization/policyAssignments/Deploy-Azure-Monitor-AMA"],
  on /home/vsts_azpcontainer/xxx/rover_jobs/20221117134534169382894/modules/enterprise_scale/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
   1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {

creating Policy Assignment ID: (Assignment Name "Deploy-Azure-Monitor-AMA" /
Scope "/providers/Microsoft.Management/managementGroups/xxx"):
policy.AssignmentsClient#Create: Failure responding to request:
StatusCode=400 -- Original Error: autorest/azure: Service returned an error.
Status=400 Code="InvalidPolicyParameterType" Message="The policy parameter
'bringYourOwnUserAssignedManagedIdentity' does not match the expected
parameter type defined in the policy definition
'9dffaf29-5905-4145-883c-957eb442c226'. Details 'The expected policy
parameter type: 'Boolean'. The actual policy parameter type 'String'.'."
Terraform apply return code: 1
```
Am I missing something in the parameter ?

**Comment by florentvaldelievre** [comment]
Hi @krowlandson Yes, I did, the plan fails with the following error
```
The given value is not valid for variable "archetype_config_overrides":
element "root": attribute "parameters": element "Deploy-Azure-Monitor-AMA":
element "bringYourOwnUserAssignedManagedIdentity": object required.
```

**Comment by krowlandson** [comment]
This is interesting @florentvaldelievre... As you can see from our test framework, we use the pattern you mention above ourselves:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/40c89bee7a21bd4c4f063223795f11897079ff70/tests/modules/settings/settings.core.tf#L100-L143

I have also just tested this by adding it to our test framework config and it works as expected.

Here are the amendments I made to the code:

- Added the policy assignment template (copied from above) to the custom `lib` folder
  ![image](https://user-images.githubusercontent.com/12268562/203809182-223bd084-f3c4-4255-8941-b92405650a90.png)

- Added the policy assignment to the `es_root` archetype using the archetype extension capability
  ![image](https://user-images.githubusercontent.com/12268562/203809282-40322bcb-6e50-4b8a-ba34-eb6f68dbae34.png)

- Added the parameter configuration to the `archetype_config_overrides` input (_I had to map the `logAnalyticsWorkspace` ID into the `settings` module due to the way we built the test framework_)
  ![image](https://user-images.githubusercontent.com/12268562/203809962-6504a102-be1c-4710-9c6a-6aceddba4188.png)

- I was then able to successfully run `terraform plan`
  ![image](https://user-images.githubusercontent.com/12268562/203813343-313de59e-65c6-4072-8fe6-100ee449ab29.png)

- And the assignment was correctly created as expected
  ![image](https://user-images.githubusercontent.com/12268562/203813819-f711cd60-44ec-441c-8d48-dbcb100cec54.png)

Please check your configuration against the above and let me know how you get on.

**Comment by florentvaldelievre** [comment]
Thanks for testing, that's interesting. The only difference I see between your test and mine is the archetype_config_overrides object. You are manipulating .tf file. On my side, I am manipulating .tfvars as I am using caf-terraform-landingzones wrapper (2203.1)

https://github.com/Azure/caf-terraform-landingzones/blob/2203.1/caf_solution/add-ons/caf_eslz/archetype_config_overrides.tf

So, I believe the issue is on their side, I'll open a ticket

Thank you for testing

**Comment by krowlandson** [comment]
Thank you for the additional information @florentvaldelievre... hopefully you can find a resolution for this.

I will close this issue for now, but please re-open if there's any reason to believe this is still an issue with our module.
