### ISSUE TITLE
Feature Request - ExpressRoute Gateway VPN_Type is Hardcoded, parameterise.

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-caf-enterprise-scale#521]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Just discovered that the vpn_type for an ExpressRoute Virtual Network Gateway is hardcoded to "RouteBased" within https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/connectivity/locals.tf 
They can also be "PolicyBased" nowadays, i think this is the case when a VPN Gateway is also added to the same GatewaySubnet. I definitely have an example where this is the case and I cant manage the already manually gateway with the module at the moment.
![image](https://user-images.githubusercontent.com/42775203/203511478-6d9557f3-40ba-45e4-9908-1ff4cc3b08a2.png)

#### Describe the solution you'd like

Can this value be parametrised so we can make it a declarable value in the config settings / advanced settings for the gateway?
#### Additional context
![image](https://user-images.githubusercontent.com/42775203/203511225-9d7c0d36-afec-4493-afbb-55b015cd3f8d.png)

**Comment by sitarant** [comment]
@birdnathan Route base and policy base only apply for VPN gateways, not for ExpressRoute

**Comment by birdnathan** [comment]
> @birdnathan Route base and policy base only apply for VPN gateways, not for ExpressRoute

@sitarant As you'll see from the screenshot above (this template is from a deployed and active ExpressRoute Gateway) the value is "PolicyBased"

**Comment by sitarant** [comment]
@birdnathan, yes you are right, thanks for checking, we should delete line 51 @krowlandson?

**Comment by gbr759** [comment]
I'm confused on this one.  Isn't it the case that if the gateway type is set to "ExpressRoute", then the VPN options (vpnType, enableBgp, and activeActive in the above example) are ignored?  So, they'll appear in the config, but they aren't used and active anywhere?  For example, the "enableBgp" setting cannot be an option for ExpressRoute gateways (even though it's set to false) as ERs cannot exist without BGP, and they are also always configured with active/active, which cannot be disabled.  Another point that makes me feel this is the case is that policy-based VPNs don't have the option to use BGP.

**Comment by krowlandson** [comment]
I think you are correct @gbr759 - we stripped out most of the settings due to these differences but left this one as ExpressRoute gateways use BGP based routing. We can probably remove this too, although I'm not sure this addresses the question raised by @birdnathan.

In theory, we believe that the `vpnType` will be ignored regardless of the setting on this particular value.

We are not aware of any issues as a result of this, and have many customers running ExpressRoute and VPN gateways together using this module, to support encryption (using VPN) over ExpressRoute scenarios.

@birdnathan are you able to confirm whether you have identified this setting as causing an unexpected behaviour on the platform?

**Comment by birdnathan** [comment]
@krowlandson there is no unexpected behaviour as far as i know. The example in my screenshot is the deployed expressroute gateway which you can see from the gatewayType parameter, I want to manage this gateway with the modules but it wants to change the vpn_type to RouteBased, you can clearly see its currently "PolicyBased". I have no idea what that impact would be if we changed it or indeed if it would even let you. To be honest its not a massive issue to exclude the gateway from terraform state but be nice to get all angles covered, saves questions further down the line which is why i've raised this. Hope that helps.

**Comment by krowlandson** [comment]
Got it, thank you @birdnathan.

I think it's reasonable to add this into the `advanced` config so you can manage this scenario, but I will also investigate the option of simply removing this setting (or rather, set to `null`) as that may be a better option for your import scenario.

We are due to make a new release shortly so will see if we can validate the approach and add this in time for that.

**Comment by birdnathan** [comment]
> Got it, thank you @birdnathan.
> 
> I think it's reasonable to add this into the `advanced` config so you can manage this scenario, but I will also investigate the option of simply removing this setting (or rather, set to `null`) as that may be a better option for your import scenario.
> 
> We are due to make a new release shortly so will see if we can validate the approach and add this in time for that.

Thanks for looking at this @krowlandson, appreciated

**Comment by krowlandson** [comment]
@birdnathan... it looks like changing `vpn_type` to `null` doesn't cause any issues for previously deployed `azurerm_virtual_network_gateway` instances for ExpressRoute so I think this is the way to go.

Given this doesn't appear to be a valid setting when `type = "ExpressRoute"` I would even suggest this could be raised as a bug on the provider so they ignore this (and other irrelevant settings) based on the specified type.

**Comment by krowlandson** [comment]
@birdnathan and @sitarant ... I've done some further testing this morning and found the following.

- If I deploy the ExpressRoute gateway with `vpn_type` set to `null` using Terraform, it creates with it with the value set to `RouteBased`. I can then import this resource into the module and it works fine with no changes proposed.
- If I deploy the ExpressRoute gateway through the Portal, it creates it with `vpn_type` set to `PolicyBased`. I can still import this into the module, but then on the next plan, Terraform wants to change it to `RouteBase` despite being set to `null` in the config.

Looking at the provider source code, this appears to be why:

![image](https://user-images.githubusercontent.com/12268562/203937236-d8c0d898-0034-41f0-a8dd-f88b13163130.png)

_src: https://github.com/hashicorp/terraform-provider-azurerm/blob/104992dab799f384149d865e3f73234be70f40e5/internal/services/network/virtual_network_gateway_resource.go#L74_

As such, it appears our only way to resolve this is to provide an advanced override.

I think we also need to verify whether there's actually a preferred configuration setting for this which differs from what we believed to be the case.

**Comment by krowlandson** [comment]
## Evidence for the above

### ARM deployment template

```json
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "String"
        },
        "location": {
            "type": "String"
        },
        "gatewayType": {
            "defaultValue": "Vpn",
            "allowedValues": [
                "Vpn",
                "ExpressRoute"
            ],
            "type": "String"
        },
        "sku": {
            "type": "String"
        },
        "subnetId": {
            "type": "String"
        },
        "publicIpAddressId": {
            "type": "String"
        }
    },
    "resources": [
        {
            "type": "Microsoft.Network/virtualNetworkGateways",
            "apiVersion": "2020-11-01",
            "name": "[parameters('name')]",
            "location": "[parameters('location')]",
            "dependsOn": [],
            "tags": {
                "deployedBy": "terraform/azure/caf-enterprise-scale/test_framework"
            },
            "properties": {
                "gatewayType": "[parameters('gatewayType')]",
                "ipConfigurations": [
                    {
                        "name": "default",
                        "properties": {
                            "privateIPAllocationMethod": "Dynamic",
                            "subnet": {
                                "id": "[parameters('subnetId')]"
                            },
                            "publicIpAddress": {
                                "id": "[parameters('publicIpAddressId')]"
                            }
                        }
                    }
                ],
                "sku": {
                    "name": "[parameters('sku')]",
                    "tier": "[parameters('sku')]"
                }
            }
        }
    ]
}
```

### ARM resource template

```json
{
    "name": "12345-ergw-westeurope",
    "id": "/subscriptions/fa2fa118-a60d-4700-9ef1-fa02beeaaea5/resourceGroups/12345-connectivity-westeurope/providers/Microsoft.Network/virtualNetworkGateways/12345-ergw-westeurope",
    "etag": "W/\"f1b0eb9e-08fa-4673-92ed-da5ae6e5211f\"",
    "type": "Microsoft.Network/virtualNetworkGateways",
    "location": "westeurope",
    "tags": {
        "deployedBy": "terraform/azure/caf-enterprise-scale/test_framework"
    },
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "b96bdd2b-baf6-48f0-bf85-93626284c0ca",
        "packetCaptureDiagnosticState": "None",
        "enablePrivateIpAddress": false,
        "isMigrateToCSES": false,
        "ipConfigurations": [
            {
                "name": "default",
                "id": "/subscriptions/fa2fa118-a60d-4700-9ef1-fa02beeaaea5/resourceGroups/12345-connectivity-westeurope/providers/Microsoft.Network/virtualNetworkGateways/12345-ergw-westeurope/ipConfigurations/default",
                "etag": "W/\"f1b0eb9e-08fa-4673-92ed-da5ae6e5211f\"",
                "type": "Microsoft.Network/virtualNetworkGateways/ipConfigurations",
                "properties": {
                    "provisioningState": "Succeeded",
                    "privateIPAllocationMethod": "Dynamic",
                    "publicIPAddress": {
                        "id": "/subscriptions/fa2fa118-a60d-4700-9ef1-fa02beeaaea5/resourceGroups/12345-connectivity-westeurope/providers/Microsoft.Network/publicIPAddresses/12345-ergw-westeurope-pip"
                    },
                    "subnet": {
                        "id": "/subscriptions/fa2fa118-a60d-4700-9ef1-fa02beeaaea5/resourceGroups/12345-connectivity-westeurope/providers/Microsoft.Network/virtualNetworks/12345-hub-westeurope/subnets/GatewaySubnet"
                    }
                }
            }
        ],
        "natRules": [],
        "virtualNetworkGatewayPolicyGroups": [],
        "enableBgpRouteTranslationForNat": false,
        "disableIPSecReplayProtection": false,
        "sku": {
            "name": "ErGw1AZ",
            "tier": "ErGw1AZ",
            "capacity": 2
        },
        "gatewayType": "ExpressRoute",
        "vpnType": "PolicyBased",
        "enableBgp": false,
        "activeActive": false,
        "vpnGatewayGeneration": "None",
        "allowRemoteVnetTraffic": false,
        "allowVirtualWanTraffic": false
    }
}
```

### Terraform plan (post import)

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.test_connectivity.azurerm_virtual_network_gateway.connectivity["/subscriptions/fa2fa118-a60d-4700-9ef1-fa02beeaaea5/resourceGroups/12345-connectivity-westeurope/providers/Microsoft.Network/virtualNetworkGateways/12345-ergw-westeurope"] must be replaced
-/+ resource "azurerm_virtual_network_gateway" "connectivity" {
      ~ active_active              = false -> (known after apply)
      ~ enable_bgp                 = false -> (known after apply)
      ~ generation                 = "None" -> (known after apply)
      ~ id                         = "/subscriptions/fa2fa118-a60d-4700-9ef1-fa02beeaaea5/resourceGroups/12345-connectivity-westeurope/providers/Microsoft.Network/virtualNetworkGateways/12345-ergw-westeurope" -> (known after apply)     
        name                       = "12345-ergw-westeurope"
      - private_ip_address_enabled = false -> null
        tags                       = {
            "deployedBy" = "terraform/azure/caf-enterprise-scale/test_framework"
        }
      ~ vpn_type                   = "PolicyBased" -> "RouteBased" # forces replacement
        # (4 unchanged attributes hidden)

      + bgp_settings {
          + asn         = (known after apply)
          + peer_weight = (known after apply)

          + peering_addresses {
              + apipa_addresses       = (known after apply)
              + default_addresses     = (known after apply)
              + ip_configuration_name = (known after apply)
              + tunnel_ip_addresses   = (known after apply)
            }
        }

      ~ ip_configuration {
          ~ name                          = "default" -> "12345-ergw-westeurope-pip"
            # (3 unchanged attributes hidden)
        }

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by krowlandson** [comment]
@birdnathan this is now available through [release v3.0.0](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases/tag/v3.0.0).

For now, to set this please use the `advanced` block in `configure_connectivity_settings`:

```hcl
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_virtual_network_gateway = {
          connectivity_expressroute = {
            eastus = { # Replace 'eastus' with the location you are deploying this resource to
              vpn_type = "PolicyBased"
            }
          }
        }
      }
    }
```

Hopefully this allows you to import and manage this resource as requested, but please let us know 😄

**Comment by birdnathan** [comment]
Thanks for this @krowlandson. Been out for a few days so will get to upgrading a couple of environments today/tomorrow and feedback.

**Comment by birdnathan** [comment]
Works great @krowlandson - Thanks for turning that one round so quickly.
