### ISSUE TITLE
Missing documentation - and comprehension

### ISSUE THREAD

**Issue by MaxiPalle** [Azure/terraform-azurerm-caf-enterprise-scale#53]
Hi Kevin,

thanks for the great piece of software you created with this module!

Having the need to deploy CAF Landing Zones with Terraform in my current project I was happy, when a colleague pointed me to this module.
I read the 'Getting started', deployed the default confuguration - and succeed within the first try.

I know quite much about Terraform, Azure CAF, Landing Zones, Management Groups and Policies.
But to be honest: I hardly have a clue, how this module is working 'under the hood'.
So I'm missing a lot of documentation.

As a non-developer, I would like to understand things like 
- How can I customize this module?
- Where is the entry point?
- Where are configurable values?
- How to use the /test folder? 
- ...

I would like to support with contributing documentation. So just let me know, whether this is requested and if yes, how to start.

Cheers,
Jens

**Comment by krowlandson** [comment]
Hi @MaxiPalle... thank you for the great feedback.

Have you seen our documentation on the wiki?
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki

It's still a work in progress but starts to show some of what is possible through the module variables and using the custom library to really add your own stamp.

**Comment by krowlandson** [comment]
Also, to answer your question specifically about the `/test` folder, this is just our test suite for ensuring the module works as expected when we make updates. Although not officially part of the functionality of the module that you would use directly, you may find it useful to look in this to understand how we run Terraform in a pipeline if that's also something you want to do.

**Comment by MaxiPalle** [comment]
Sure. But it isn't (yet) sufficient (at least from my point of view).
maybe this will change, when I will have a successful 'terraform graph' output :-)

**Comment by krowlandson** [comment]
Are you able to identify something specific I can help you with at this point, beyond the initial examples?

i.e. is there a particular item you wish to customize but are unsure how to do this?

The [Deploy Custom Landing Zone Archetypes](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes) example and [Archetype Definitions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions) pages gives a reasonable level of information about how to do some of the more advanced customization options, but I think you may find it easier to understand once I get a chance to update the individual variable pages. Hopefully you should see this improve over the next couple of months.

**Comment by MaxiPalle** [comment]
OK, let's start. :-)

We would like to implement and assign a given policy initiative like "Azure Security Benchmark" to dedicated management groups.
I haven't identified the way how to adapt this i.e. for the level 1 management group. 

I'm willing and able to document this in the wiki, but have to understand it.

**Comment by krowlandson** [comment]
@MaxiPalle, apologies for not responding sooner. We've been busy working on some new features for an up-coming release, but are also actively working on the examples section within the Wiki to improve this content.

I've added this to our list of examples and hope to have an update for you soon.

If you have some other scenarios you would find useful, please provide a list and we will triage them for our backlog.

In the meantime, please try the following for your mentioned scenario:

1. Firstly, ensure you have a custom library configured in your root module (e.g. `./lib/`) and have set yourself up with a custom `archetype definition` as documented in our [Deploy Custom Landing Zone Archetypes](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes)
2. Within the library, save a `Policy Assignment` template for the "Azure Security Benchmark" policy as per those included in the module, taking note of the required [File Name Pattern](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions#working-with-archetype-definitions-and-the-custom-library) for the module to detect this correctly.
3. Ensure you include the value of the `name` for your custom `Policy Assignment` in the `policy_assignments` section of your custom archetype definition.
4. You can associate the custom archetype definition with any `custom_landing_zones` as per the [Deploy Custom Landing Zone Archetypes](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes) example, or to override the archetype_definition for one of the core landing zones, you use the `archetype_config_overrides` variable when configuring the module.

The following example files shows how you could set the "landing-zones" management group to use a custom archetype definition called `customer_landing_zones`, based on the built-in archetype with an additional `Policy Assignment` called `Azure-Security-Benchmark`:

**`main.tf`**
```hcl
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.1.2"

  root_parent_id = data.azurerm_client_config.current.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.root}/lib"

  custom_landing_zones = {
    <redacted>
  }

  # The following var provides an example for how to specify
  # custom archetypes for the connectivity Landing Zones
  archetype_config_overrides = {
    #------------------------------------------------------#
    # This variable is used to configure the built-in
    # Enterprise-scale Management Groups with alternate
    # (or custom) name and parameters.
    # Simply uncomment the one(s) you want to modify and
    # provide the required values.
    #------------------------------------------------------#
    # root = {
    #   archetype_id   = "es_root"
    #   parameters     = {}
    #   access_control = {}
    # }
    # decommissioned = {
    #   archetype_id   = "es_decommissioned"
    #   parameters     = {}
    #   access_control = {}
    # }
    # sandboxes = {
    #   archetype_id   = "es_sandboxes"
    #   parameters     = {}
    #   access_control = {}
    # }
    # landing-zones = {
    #   archetype_id   = "es_landing_zones"
    #   parameters     = {}
    #   access_control = {}
    # }
    # platform = {
    #   archetype_id   = "es_platform"
    #   parameters     = {}
    #   access_control = {}
    # }
    # connectivity = {
    #   archetype_id   = "es_connectivity_foundation"
    #   parameters     = {}
    #   access_control = {}
    # }
    # management = {
    #   archetype_id   = "es_management"
    #   parameters     = {}
    #   access_control = {}
    # }
    # identity = {
    #   archetype_id   = "es_identity"
    #   parameters     = {}
    #   access_control = {}
    # }
    #------------------------------------------------------#
    landing-zones = {
      archetype_id = "customer_landing_zones"
      parameters = {
        Azure-Security-Benchmark = {
          param_name_1 = param_value_1
          param_name_2 = param_value_2
          param_name_3 = param_value_3
        }
      }
      access_control = {}
    }
  }
}
```

**`lib/archetype_definition_customer_landing_zones.json`**
```json
{
    "customer_landing_zones": {
        "policy_assignments": [
            "Deny-IP-Forwarding",
            "Deny-RDP-From-Internet",
            "Deny-Storage-http",
            "Deny-Subnet-Without-Nsg",
            "Deploy-AKS-Policy",
            "Deploy-SQL-DB-Auditing",
            "Deploy-VM-Backup",
            "Deploy-SQL-Security",
            "Deny-Priv-Escalation-AKS",
            "Deny-Priv-Containers-AKS",
            "Deny-http-Ingress-AKS",
            "Azure-Security-Benchmark" // This is the reference to your additional Policy Assignment (by name)
        ],
        "policy_definitions": [],
        "policy_set_definitions": [],
        "role_definitions": [],
        "archetype_config": {
            "parameters": {}, // You can add default values for any Policy Assignments here, or within the archetype_config block where the archetype is being used
            "access_control": {}
        }
    }
}
```

**`lib/policy_assignment_azure_security_benchmark.json`**
```json
{
  "name": "Azure-Security-Benchmark",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Assigns the built-in Azure Security Benchmark initiative.",
    "displayName": "Azure Security Benchmark",
    "notScopes": [],
    "parameters": {
        // Ensure you include any mandatory parameters here, but also any you want to control the values for
    },
    "policyDefinitionId": "/providers/Microsoft.Authorization/policySetDefinitions/1f3afdf9-d0c9-4c3d-847f-89da613e70a8",
    "scope": "${current_scope_resource_id}"
  },
  "location": "${default_location}",
  "identity": {
    "type": "None"
  }
}
```

> NOTE: The `jsondecode()` function in Terraform does not support comments in JSON files, so please don't include these if copying the examples above.

As a general best practice, we would also advise copying the original corresponding archetype definition from the module as above to ensure you retain the original settings intended as per the Enterprise-scale reference architecture.

Hope this helps.

**Comment by MaxiPalle** [comment]
Hi Kevin,
this helped me a lot.
Thanks!
Jens
