### ISSUE TITLE
Unable to configure `service_endpoints` on `AzureFirewallSubnet` using `advanced` settings

### ISSUE THREAD

**Issue by hungbui78** [Azure/terraform-azurerm-caf-enterprise-scale#539]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

Terraform v1.3.5
on linux_amd64

**azure provider**:
hashicorp/azurerm v3.34.0

**module**:

source  = "Azure/caf-enterprise-scale/azurerm"
  version = "3.0.0"

### Description

Trying to use advanced settings to set AzsureFirewallSubnet service endpoint but not success. I can use it to set azurerm_firewall_policy settings but when I tried to set azurerm_subnet settings it does nothing.

#### Describe the bug

Trying to use advanced settings to set AzsureFirewallSubnet service endpoint but not success. I can use it to set azurerm_firewall_policy settings but when I tried to set azurerm_subnet settings it does nothing.

The working code when settings azurerm_firewall_policy settings is 

```hcl
location = null
tags     = null
    advanced = {custom_settings_by_resource_type = {
         azurerm_firewall_policy = {
          connectivity = {
            ("swedencentral") = {
              sql_redirect_allowed = false
            }
          }
        }
      }
}
```
And when I tried to sets service endpoints for AzureFirewallSubnet  on same way it does nothing
 Here is the code I use to try to set service endpoints

```hcl
location = null
tags     = null
advanced = {custom_settings_by_resource_type = {
           azurerm_subnet = {
           connectivity = {
            ("swedencentral") = { 
            ("AzureFirewallSubnet") = {
               service_endpoints = ["Microsoft.AzureActiveDirectory", "Microsoft.KeyVault", "Microsoft.Storage"]
               }
             }
          }
      }
   }
}
```

#### Steps to Reproduce

1. step 1
Terraform init
2. step 2
Terraform apply
3. you get it...

**Comment by krowlandson** [comment]
Hi @hungbui78 - is this request related to #538?

**Comment by krowlandson** [comment]
OK great, thank you for confirming.

I've validated the module capability in this regard and am able to get it to work as expected using your sample code, slightly adapted to our test environment.

Please see the following based on modifying our working baseline from the test modules:

### Code changes

![Code changes on test module](https://user-images.githubusercontent.com/12268562/206423083-772146a8-e80d-4b92-8f04-252a310a8ad2.png)

### Terraform apply

![console output showing successful Terraform apply](https://user-images.githubusercontent.com/12268562/206423476-2ad0d74e-0d28-4e67-9069-1e3bb65cb874.png)

### Changes in Portal

![Portal blade showing updated changes to the subnet configuration](https://user-images.githubusercontent.com/12268562/206423718-73108fb3-a9f9-42ba-acb2-fefab801e0cc.png)

Are you able to provide more information about what you mean by "it does nothing"? Are you not seeing the plan change, or does the plan reflect the code change, but the changes are not applied in Azure?

**Comment by hungbui78** [comment]
> OK great, thank you for confirming.
> 
> I've validated the module capability in this regard and am able to get it to work as expected using your sample code, slightly adapted to our test environment.
> 
> Please see the following based on modifying our working baseline from the test modules:
> 
> ### Code changes
> ![Code changes on test module](https://user-images.githubusercontent.com/12268562/206423083-772146a8-e80d-4b92-8f04-252a310a8ad2.png)
> 
> ### Terraform apply
> ![console output showing successful Terraform apply](https://user-images.githubusercontent.com/12268562/206423476-2ad0d74e-0d28-4e67-9069-1e3bb65cb874.png)
> 
> ### Changes in Portal
> ![Portal blade showing updated changes to the subnet configuration](https://user-images.githubusercontent.com/12268562/206423718-73108fb3-a9f9-42ba-acb2-fefab801e0cc.png)
> 
> Are you able to provide more information about what you mean by "it does nothing"? Are you not seeing the plan change, or does the plan reflect the code change, but the changes are not applied in Azure?

Ty Krow.

I will try your example in our enviroment and let you know the result.

Regarding the "it does nothing" is the terraform output not show any changes.

BR

Hung

**Comment by hungbui78** [comment]
Ty Krow.

It is working as aspected now.

BR

Hung

**Comment by krowlandson** [comment]
Great stuff... thank you for confirming and closing the issue @hungbui78 👍🏻
