### ISSUE TITLE
Bug Report - enable_private_dns_zone_virtual_network_link_on_hubs   = true failing on disabled hub

### ISSUE THREAD

**Issue by cbezenco** [Azure/terraform-azurerm-caf-enterprise-scale#542]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.5

**azure provider**: 3.34.0

**module**: 3.0.0

### Description
enable_private_dns_zone_virtual_network_link_on_hubs   = true is failing when trying to deploy "azurerm_private_dns_zone_virtual_network_link" on disabled hub. 

#### Describe the bug

As part of dev, qa, prod, hierarchy approach I am maintaining different connectivity configurations. In my env, I maintain config for northeurope and westeurope. I disable westeurope hub with 

   settings = {
      hub_networks = [
        {
          enabled = false

I expect that private DNS zone will not be deployed on the disabled hub when enable_private_dns_zone_virtual_network_link_on_hubs   = true but this is not happening and Terraform apply tries and fails to deploy "azurerm_private_dns_zone_virtual_network_link" 

I tried to force  the private link location to include only the enabled hub using private_link locations but module still try to deploy  "azurerm_private_dns_zone_virtual_network_link" in westeurope but module still try to deploy in westeurope disabled hub.

          private_link_locations = [
            "northeurope"
          ]
          public_dns_zones                                       = []
          private_dns_zones                                      = []
          enable_private_dns_zone_virtual_network_link_on_hubs   = true
          enable_private_dns_zone_virtual_network_link_on_spokes = false

#### Steps to Reproduce

1. configure 2 hub 
2. disable one of the hub
3. enable_private_dns_zone_virtual_network_link_on_hubs   = true

You get the error below when applying

#### Screenshots
╷
│ Error: creating/updating Virtual Network Link (Subscription: "e4f86ded-632e-46f0-9d88-56cf56ee72c0"
│ Resource Group Name: "dev-dns"
│ Private Zone Name: "privatelink.blob.core.windows.net"
│ Virtual Network Link Name: "e4f86ded-632e-46f0-9d88-56cf56ee72c0-3d70942d-9305-5ebb-8687-99bf65bdb0a7"): polling after CreateOrUpdate: Code="BadRequest" Message="Virtual network resource not found for '/subscriptions/e4f86ded-632e-46f0-9d88-56cf56ee72c0/resourceGroups/dev-connectivity-westeurope/providers/Microsoft.Network/virtualNetworks/dev-hub-westeurope'"
│
│   with module.caf-enterprise-scale.azurerm_private_dns_zone_virtual_network_link.connectivity["/subscriptions/e4f86ded-632e-46f0-9d88-56cf56ee72c0/resourceGroups/dev-dns/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net/virtualNetworkLinks/e4f86ded-632e-46f0-9d88-56cf56ee72c0-3d70942d-9305-5ebb-8687-99bf65bdb0a7"],
│   on .terraform\modules\caf-enterprise-scale\resources.connectivity.tf line 492, in resource "azurerm_private_dns_zone_virtual_network_link" "connectivity":
│  492: resource "azurerm_private_dns_zone_virtual_network_link" "connectivity" {
│
│ Virtual Network Link Name: "e4f86ded-632e-46f0-9d88-56cf56ee72c0-3d70942d-9305-5ebb-8687-99bf65bdb0a7"): polling after CreateOrUpdate: Code="BadRequest" Message="Virtual network resource not found for '/subscriptions/e4f86ded-632e-46f0-9d88-56cf56ee72c0/resourceGroups/dev-connectivity-westeurope/providers/Microsoft.Network/virtualNetworks/dev-hub-westeurope'"
│
│   with module.caf-enterprise-scale.azurerm_private_dns_zone_virtual_network_link.connectivity["/subscriptions/e4f86ded-632e-46f0-9d88-56cf56ee72c0/resourceGroups/dev-dns/providers/Microsoft.Network/privateDnsZones/privatelink.file.core.windows.net/virtualNetworkLinks/e4f86ded-632e-46f0-9d88-56cf56ee72c0-3d70942d-9305-5ebb-8687-99bf65bdb0a7"],│   on .terraform\modules\caf-enterprise-scale\resources.connectivity.tf line 492, in resource "azurerm_private_dns_zone_virtual_network_link" "connectivity":
│  492: resource "azurerm_private_dns_zone_virtual_network_link" "connectivity" {

**Comment by krowlandson** [comment]
Thank you for logging this @cbezenco and providing the context around why this is an issue for you... we have also observed this and weren't sure whether this would be a problem for customers or not.

I will get this added to our backlog and prioritised 👍🏻

**Comment by krowlandson** [comment]
Whilst working on this and creating the test coverage, I've realised that the logic for `enable_hub_network_mesh_peering` results in similar behaviour:

![terraform plan showing rogue resources](https://user-images.githubusercontent.com/12268562/207714793-2a88bea6-175b-484e-8a12-5dcfd4881857.png)

This results in the following errors as would be expected:

![terraform apply errors for rogue resources](https://user-images.githubusercontent.com/12268562/207714895-cb9f157a-eaa4-41a0-a393-cefc77e343b9.png)

This requires a similar fix.

cc: @matt-FFFFFF

**Comment by krowlandson** [comment]
@cbezenco... whilst working on this I thought I would also comment on the following statement:

> I tried to force the private link location to include only the enabled hub using private_link locations

This particular setting is to enable creation of region-bound DNS zones [as documented in our wiki](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-configure_connectivity_resources.settings.dns#configprivate_link_locations), hence why this didn't help.
