### ISSUE TITLE
Deploying a policy set or a policy assignment errors in 404 not found when following the tutorial

### ISSUE THREAD

**Issue by TerraformNovice** [Azure/terraform-azurerm-caf-enterprise-scale#543]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:Terraform v1.3.2

**azure provider**:azurerm v3.33.0

**module**:"Azure/caf-enterprise-scale/azurerm 2.4.1"

#### Following the guide from https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy-Sets-and-Assignments my deployment errors when I try to deploy policy assignments or policy sets. Policy definitions are working corrrectly. 

This is the error when trying to deploy a policy set: Error: reading Policy Set Definition "Enforce-Mandatory-Tags": policy.SetDefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error.

│ Error: reading Policy Set Definition "Enforce-Mandatory-Tags": policy.SetDefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicySetDefinitionNotFound" Message="The policy set definition 'Enforce-Mandatory-Tags' could not be found."
│
│   with module.enterprise_scale.data.azurerm_policy_set_definition.external_lookup["/providers/Microsoft.Management/managementGroups/FCS/providers/Microsoft.Authorization/policySetDefinitions/Enforce-Mandatory-Tags"],
│   on .terraform\modules\enterprise_scale\locals.policy_assignments.tf line 98, in data "azurerm_policy_set_definition" "external_lookup":
│   98: data "azurerm_policy_set_definition" "external_lookup" {

The corresponding json files are just copied into the right folder under /lib and the archetype is a custom definition with only the policies from the tutorial. I tried this multiple times and also a collegue of mine did too and got the same error. 

#### Steps to Reproduce

1. Follow the guide above and create the files under /lib
2. Add the policies definitions, set and assignments to the archetype definition
3. Run terraform plan
4. When adding an assignment or a set, the plan will fail:  Status=404 Code="PolicySetDefinitionNotFound" Message="The policy set definition 'Enforce-Mandatory-Tags' could not be found."

#### Additional context

I created custom_landing_zones in my main.tf file.

Thank you in advance!

**Comment by TerraformNovice** [comment]
I also tried updating my terraform binary to Terraform v1.3.6, but that did not help either.

**Comment by TerraformNovice** [comment]
Hi @krowlandson, thank you for the reply! Really appreciate it. 
So I looked at the file which is mentioned in the error: 

 on .terraform\modules\enterprise_scale\locals.policy_assignments.tf line 98, in data "azurerm_policy_set_definition" "external_lookup":
│ 98: data "azurerm_policy_set_definition" "external_lookup" {

After looking at the file locals.policy_assignments.tf I came to the conclusion, that this command performs an external lookup for the policy definition in my azure tenant, but does not find it, because it does not exist yet. 


.terraform\modules\enterprise_scale\locals.policy_assignments.tf line 98 looks like this: 

# Perform a lookup of the Policy Set Definitions not deployed by this module.
data "azurerm_policy_set_definition" "external_lookup" {
  for_each = local.azurerm_policy_set_definition_external_lookup

  name                  = each.value.name
  management_group_name = each.value.management_group_id
}

I already looked in my archetype extension json file and the policy set is referenced there, just as descibed in the tutorial. The policy assignment and policy set json files exist within the lib folder. 

So my question is why does this module errors at the lookup of the policy definition before it is created in my tenant and what steps can I take to fix this?

**Comment by cveld** [comment]
Can you create a small repro? I.e. set up a small folder inside a github repo and when running terraform plan this should yield the reported error.

**Comment by TerraformNovice** [comment]
Hey @krowlandson,
I figured it out, I did not quite understand the scopes of the policies, but I could solve it with your help.

Thank you for your time and advice, keep the great work going!
