### ISSUE TITLE
Missing assignment parameter values for "Configure Azure PaaS services to use private DNS zones"

### ISSUE THREAD

**Issue by anwarnk** [Azure/terraform-azurerm-caf-enterprise-scale#544]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.6

**azure provider**: 3.34.0

**module**: 3.0.0

### Description

Configure Azure PaaS services to use private DNS zones not passing all parameter values with the subscription details of where central private DNS is located.

#### Steps to Reproduce

1. Assign "Deploy-Private-DNS-Zones" to a landing zone 
2. View Assignment properties 
and a lot of the Parameter ID's entries have no value.

#### Screenshots

![image](https://user-images.githubusercontent.com/105373983/206729354-0a4ef39b-3c81-4d63-bcd3-a93f5b0569fa.png)

**Comment by krowlandson** [comment]
Thank you for logging this... should be relatively quick fix so I will get this prioritised.
