### ISSUE TITLE
Feature Request: Deploy private dns zones and link them to an existing vnet

### ISSUE THREAD

**Issue by cveld** [Azure/terraform-azurerm-caf-enterprise-scale#549]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the module requires one to specify a "hub vnet" that is created and used by the module to link the deployed private dns zones.
In our situation we only have one subscription. Therefore it would be great just to be able to deploy the private dns zone connections to an existing vnet in this subscription.

Current configuration:
```terraform
hub_networks = [{config = {
        location = "westeurope"
        address_space = ["10.0.0.0/16"]
        spoke_virtual_network_resource_ids = [
          "/subscriptions/<redacted>/resourceGroups/rg-shared-local/providers/Microsoft.Network/virtualNetworks/my-existing-vnet-001"
        ]
      }}]
dns = {
        enabled = true
        config = {
          location = "westeurope"
          enable_private_link_by_service = {
            ...
          }
          private_link_locations                                 = []
          public_dns_zones                                       = []
          private_dns_zones                                      = []
          enable_private_dns_zone_virtual_network_link_on_hubs   = true
          enable_private_dns_zone_virtual_network_link_on_spokes = true
        }
      }
```

Desired situation with which not a new vnet is created, but an existing vnet can be included for private dns zone vnet connections:
```terraform
hub_networks = []
existing_networks = ["/subscriptions/<redacted>/resourceGroups/rg-shared-local/providers/Microsoft.Network/virtualNetworks/my-existing-vnet-001"]
dns = ...
```

**Comment by krowlandson** [comment]
Seems a reasonable ask. The current module logic actually allows this already, as the DNS config can read the list of spoke virtual network IDs even when the hub is disabled, but someone else has recently raised this as a bug. Please see:

- #542 

As such, we are considering closing that logic and this would be a good addition to replace that logic 👍🏻 I'll get this added to our backlog and linked to #542.

**Comment by krowlandson** [comment]
@cveld - if you have some time, I would appreciate your thoughts on the above mentioned commit which includes my initial thoughts on how to fix this issue.

**Comment by krowlandson** [comment]
Populated with the following test configuration:

![example code](https://user-images.githubusercontent.com/12268562/207722508-05fc2831-5f44-468a-bdd7-095533c7e69d.png)

You can see that the DNS links are created as desired:

![configured links](https://user-images.githubusercontent.com/12268562/207722689-a97a61a7-3ef9-4806-b4ec-0f5b20e4d691.png)
