### ISSUE TITLE
Feature Request: Multiple Hub scenario, 2 VWANS are getting deployed

### ISSUE THREAD

**Issue by sudhir-ops** [Azure/terraform-azurerm-caf-enterprise-scale#552]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
2 VWAN resources are getting created when deploying 2 hubs in same region. But expectation is that 1 VWAN and 2 hub resources should be created. Also 2 resource groups are being deployed since we are creating 2 modules. But ideally, all the vwan hub needs to be in  single resource group as per microsoft recommendation
#### Is your feature request related to a problem?
Yes

#### Describe the solution you'd like
There is a need in my project to create 2 hubs in same region. I went through issue https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/328
and the below documentation which mentioned that it is possible to create 2 hubs in same region.

![2 hub in same region](https://user-images.githubusercontent.com/55252751/207232691-8e5eb36f-a904-489e-90bd-31be8631e232.png)

But when I created another module with unique root id, the module is creating a VWAN hub as well as a VWAN resource. This is a problem as we need only one VWAN resource and we will be connecting  multiple hub to one VWAN.

Please let me know if there is any way to create only the hub without VWAN for the 2nd hub.

**Comment by krowlandson** [comment]
Yes, we already have this covered but not documented due to the advanced nature of this scenario.

To do this, you need to add the following to the `configure_connectivity_resources` input for your module config on the secondary instance (and subsequent):

```hcl
  configure_connectivity_resources = {
    # additional setting removed for brevity
    advanced = {
      custom_settings_by_resource_type = {
        existing_virtual_wan_resource_id= "" # Add you Virtual WAN resource ID here
      }
    }
  }
```

> **NOTE:** Due to the way resource keys are currently generated, you may have to set this as a string input rather than linking modules together if you are creating within a single Terraform workspace.

**Comment by sudhir-ops** [comment]
Thank you for prompt response. But when I tried the above code, terraform was still creating the new VWAN resource.

I went through the CAF modules and found that the below code works.


  _configure_connectivity_resources = {
    # additional setting removed for brevity
    advanced = {
        existing_virtual_wan_resource_id= "" # Add you Virtual WAN resource ID here
    }
  }_


But still I'm not able to find how to deploy this VWAN hub and associated resource in existing resource group. As per Microsoft recommendation, all the VWAN and hub resources needs to be created in the same resource group.
I tried the below code but this did not work either 
  _configure_connectivity_resources = {
    # additional setting removed for brevity
    advanced = {
        custom_settings_by_resource_type = { azurerm_resource_group = "/subscriptions/XXXX"} 
        existing_virtual_wan_resource_id = "/subscriptions/XXXX" # Add you Virtual WAN resource ID here
    }
  }_

Kindly let me know if there is any way to deploy the 2nd VWAN hub to existing resource group

**Comment by sudhir-ops** [comment]
I believe its a great idea to allow specifying existing_virtual_wan_resource_group_id so that there will be more leniency on controlling the deployment. 
If not, based on the existing_virtual_wan_resource_id field, it should automatically deploy the VWAN hub resources in that resource group which has the VWAN. But this would limit the flexibility of providing the resource group as per user need.

But thank you for letting me know that currently its not possible to deploy the 2nd VWAN hub in existing resource group.

**Comment by krowlandson** [comment]
@sudhir-ops... I've put together an initial solution as per the linked PR.

This uses a new `configure_connectivity_resources.advanced.existing_virtual_wan_resource_group_name` which will apply at the module scope (not per Virtual Hub) on the basis that this feature is intended to allow you to deploy all Virtual WAN resources into a single resource group.

I went with resource group name rather than ID as this is an easier input to specify and would only work when the target resource is in the same Subscription as all of the resources being created.

Does this meet your expectations, or would it make more sense to implement this option on a per virtual hub basis?

**Comment by sudhir-ops** [comment]
Hi Kevin, Yes this satisfies my requirement. Thank you for considering the change.

**Comment by krowlandson** [comment]
Great, thank you for confirming
