### ISSUE TITLE
Unexpected behaviour: Radius IP required when using AAD for VPN gateway

### ISSUE THREAD

**Issue by geertklop** [Azure/terraform-azurerm-caf-enterprise-scale#556]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.5

**azure provider**: 3.33.0

**module**: 3.0.0

#### Describe the bug

When setting the VPN gateway in my hub network, when setting `vpn_aut_types` to `"AAD"` only, then I get an error on `terraform apply` with the following message:
```
expected vpn_client_configuration.0.radius_server_address to contain a valid IPv4 address, got:
```

Expected behaviour would be to not having to setup RADIUS server when using AAD.

#### Steps to Reproduce

1. Setup hub according to [Wiki Example](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings)
2. Setup Enterprise App for VPN according to [Docs](https://learn.microsoft.com/en-gb/azure/vpn-gateway/openvpn-azure-ad-tenant-multi-app)
3. Change settings for `virtual_network_gateway` to:
```terraform
virtual_network_gateway = {
              enabled = true
              config = {
                address_prefix           = "10.100.1.0/24"
                gateway_sku_expressroute = ""
                gateway_sku_vpn          = "VpnGw1AZ"
                advanced_vpn_settings = {
                  enable_bgp                       = null
                  active_active                    = null
                  private_ip_address_allocation    = ""
                  default_local_network_gateway_id = ""
                  vpn_client_configuration = [
                    {
                      address_space        = ["10.10.10.0/24"]
                      vpn_client_protocols = ["OpenVPN"]
                      vpn_auth_types       = ["AAD"]
                      aad_tenant   = "https://login.microsoftonline.com/${data.azurerm_client_config.core.tenant_id}"
                      aad_audience = "41b23e61-6c1e-4545-b367-cd054e0ed4b4"
                      aad_issuer   = "https://sts.windows.net/${data.azurerm_client_config.core.tenant_id}"
                    }
                  ]
                  bgp_settings = []
                  custom_route = []
                }
              }
            }
```
4. Run `terraform apply`

#### Screenshots
<img width="2017" alt="image" src="https://user-images.githubusercontent.com/34519549/207542720-7e71c646-b479-4b16-94d8-2d37c98dc5de.png">

#### Additional context

If I comment out the radius lines in `caf_enterprise_scale/resources.connectivity.tf:181-182`, then everything works as expected and I can create my VPN P2S config as required.

**Comment by krowlandson** [comment]
Thank you for logging this @geertklop... this looks like a genuine issue introduced as part of the addition of default values within the new `optional()` schema updates.

As you can see, the following are setting a default value of `""` when it should actually be `null`:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/72e149f1bdc95d9a4d07c61df66e04f83529049f/variables.tf#L268-L269

As you can see in the resource config, we default these to `null` but the above is now overriding these with the `optional()` defaults:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/72e149f1bdc95d9a4d07c61df66e04f83529049f/resources.connectivity.tf#L181-L182

I will look to get this resolved ASAP and review the others.

**Comment by geertklop** [comment]
Not sure if it helps, but I get the same error by setting the RADIUS settings explicitly to `null` in my config. 

```terraform
vpn_client_configuration = [
  {
    address_space        = ["10.10.10.0/24"]
    vpn_client_protocols = ["OpenVPN"]
    vpn_auth_types       = ["AAD"]
    aad_tenant           = "https://login.microsoftonline.com/${data.azurerm_client_config.core.tenant_id}"
    aad_audience         = "41b23e61-6c1e-4545-b367-cd054e0ed4b4"
    aad_issuer           = "https://sts.windows.net/${data.azurerm_client_config.core.tenant_id}/"
  
    radius_server_address = null
    radius_server_secret  = null
  }
]
```

**Comment by krowlandson** [comment]
Thank you for following up @geertklop

I'm not too worried about that, as Terraform treats a `null` input as if it hasn't been specified. You can prove this with the following simple module:

```hcl
variable "input" {
  type = object({
    name = optional(string, "default")
  })
}

output "output" {
  value = var.input.name
}
```

Which gives the following outpus:

![image](https://user-images.githubusercontent.com/12268562/207808932-8330cb5c-9ae9-4dbe-8608-e9c54eceff07.png)

As you can see, a `null` input results in Terraform using the default value specified in the `optional()` input. If we set the default to `null` within the `optional()` it will then pass through as `null` through the module.
