### ISSUE TITLE
Bug Report : An argument named "sandboxes" is not expected here for variable "subscription_id_overrides"

### ISSUE THREAD

**Issue by Karni-G** [Azure/terraform-azurerm-caf-enterprise-scale#557]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.6

**azure provider**: 3.35.0

**module**: 3.0.0

#### Describe the bug

Unable to map subscription to MG. Reopening because I have got question about mapping - will this variable still work if I have used below mentioned custom-landing-zone deployment ?? If not, how can I make it work. Thanks!

#### Steps to Reproduce

Since we needed to follow naming convention for our customer, I have used custom_landing_zone to achieve this including creation of platform and rest of the MG structure (struggling to get rid of "decomissioned" mg). Sample below :

   custom_landing_zones = {
    "${var.root_id}-platform" = {
      display_name               = "${lower(var.root_id)}-platform"
      parent_management_group_id = "${var.root_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "es_platform"
        parameters     = {}
        access_control = {}
      }
    }
}

**Comment by Karni-G** [comment]
please ignore this. I have found the cause. Thanks!

**Comment by krowlandson** [comment]
hi @Karni-G - just to check, did you mean to re-open this?

If not, great that you managed to work out a resolution for your issue, but if you have any other questions please feel free to add them to this issue.

**Comment by Karni-G** [comment]
H

> hi @Karni-G - just to check, did you mean to re-open this?
> 
> If not, great that you managed to work out a resolution for your issue, but if you have any other questions please feel free to add them to this issue.

@krowlandson - Yes, I was able to use the block in custom landing zone today which I missed the first time and it worked.

**Comment by krowlandson** [comment]
> Yes, I was able to use the block in custom landing zone today which I missed the first time and it worked.

That's great, thank you for confirming.

Regarding your other questions:

1. To remove `decommissioned` from the core hierarchy, the only way currently is to disable `deploy_core_landing_zones` and manually redefine the structure you want using `custom_landing_zones`. We are looking at options to make this easier, but no ETA on this yet.
2. We have a dedicated module for [lz-vending](https://registry.terraform.io/modules/Azure/lz-vending/azurerm/latest) which I would highly recommend checking out. @matt-FFFFFF is also working on some documentation which will hopefully help to better explain how to integrate the two modules as this isn't well covered today. For now, I would suggest experimenting with what you feel is the best way to populate these values. One option could be to read the state from your subscription creation process (assuming this is also with Terraform) and using this to populate the MGs, but you need to have a way of knowing which management group to place the subscription in.

Hope this helps?

**Comment by Karni-G** [comment]
@krowlandson  - Thank you for prompt responses! :)

For point 1 then I just need to disable the switch as I'm already using custom_landing_zones variable. 

For point 2, I will check lz-vending option to see what I can include. I had added a subscription.tf so it is part of same state file now and making any changes in terms of separating it will disrupt the setup as subscriptions get disabled. It somehow isn't able to identify the already created subscription with alias and creates a new one instead. 
I was trying to use data and depends_on to do this mapping in custom_landing_zone block and that worked wonderfully for one subscription (sample below) BUT failed terribly with multiple subscriptions (error below). I'm assuming it is because it cannot read multiple data blocks for subscriptions but I'm not entirely sure. High chances of it being an amateur mistake but do you have any thoughts on this or suggested fix ?

resource "azurerm_subscription" "sandbox1" {
  alias = "xxxxxxxxxxx"
  subscription_name = "xxxxxxxxxxxx"
  billing_scope_id  = data.azurerm_billing_enrollment_account_scope.billing.id
}

data "azurerm_subscription" "sandbox1" {
  subscription_id = azurerm_subscription.sandbox1.id
}


****error with multiple similar blocks******

│ Error: retrieving Subscription (Subscription: "/providers/Microsoft.Subscription/aliases/n-sub-arc712-sandbox-01"): subscriptions.Client#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidSubscriptionId" Message="The provided subscription identifier 'providers' is malformed or invalid."
│
│   with data.azurerm_subscription.sandbox1,
│   on subscription.tf line 14, in data "azurerm_subscription" "sandbox1":
│   14: data "azurerm_subscription" "sandbox1" {

**Comment by Karni-G** [comment]
Adding for point 1, I tried following the custom landing zone deployment guide and I'm running into error while deploying it. It is strange because same setup ran successfully when I had added it in enterprise_scale module block directly. Can you pls help with this too ? Thanks in advance!

 Below is the sample and error -

Sample  Code-

  root_parent_id            = "${var.root_id}"
  root_id                   = var.root_id
  deploy_core_landing_zones = false
  library_path              = "${path.root}/lib"

  custom_landing_zones = {
     "${var.root_id}-landing-zones" = {
       display_name               = "${lower(var.root_id)}-landing-zones"
       parent_management_group_id = "${var.root_id}"
       subscription_ids           = []
       archetype_config = {
         archetype_id   = "es_landing_zones"
         parameters     = {}
         access_control = {}
       }
     }
   "${var.root_id}-platform" = {
      display_name               = "${lower(var.root_id)}-platform"
      parent_management_group_id = "${var.root_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "es_platform"
        parameters     = {}
        access_control = {}
      }
    }
}
Error -

│   on .terraform\modules\enterprise_scale_nested_landing_zone\modules\role_assignments_for_policy\main.tf line 2, in resource "azurerm_role_assignment" "for_policy":
│    2:   for_each = local.azurerm_role_assignments
│     ├────────────────
│     │ local.azurerm_role_assignments will be known only after apply
│
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot     
│ determine the full set of keys that will identify the instances of this resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place
│ apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and   
│ then apply a second time to fully converge.
╵

**Comment by krowlandson** [comment]
I'm also going to link this to the following issue as evidence:

- #115

**Comment by Karni-G** [comment]
Thank you for getting back to me on this. I will go through the link to understand what I was missing for the dependencies.

Just additional information - for time-being, I have made the deployment work by including the custom_landing_zone directly in the enterprise-scale module instead of using the nested module.

**Comment by Karni-G** [comment]
**Elaborating on previous comment as to what I have done and works.** 

In below main.tf, you will notice that I use different archetypes for different landing zones (also creating root with it) but all of this is part module "enterprise_scale" and not module "enterprise_scale_nested_landing_zone".
And even though this configuration works perfectly fine today, I want to understand what difference using nesting module provides and if doing below prevents some things or will cause a possible error/complexity in future from CAF module perspective. 
Looking forward to hear from you.

_-----main.tf--------
# Get the current client configuration from the AzureRM provider.
# This is used to populate the root_parent_id variable with the
# current Tenant ID used as the ID for the "Tenant Root Group"
# Management Group.

data "azurerm_client_config" "core" {}

# Obtain client configuration from the "management" provider
# data "azurerm_client_config" "management" {
#   provider = azurerm.management
# }

# Declare the Azure landing zones Terraform module
# and provide a base configuration.

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "3.0.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.root}/lib"

  custom_landing_zones = {
    "${var.root_id}" = {
      display_name               = "${lower(var.root_id)}"
      parent_management_group_id = "${data.azurerm_client_config.core.tenant_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "es_root"
        parameters     = {}
        access_control = {}
      }
    }   
    ##### SandBox #####
    "${var.root_id}-sandboxes" = {
      display_name               = "${lower(var.root_id)}-sandboxes"
      parent_management_group_id = "${var.root_id}"
      # subscription_ids           = [data.azurerm_subscription.sandbox1.subscription_id]
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "es_sandboxes"
        parameters     = {}
        access_control = {}
      }
      # depends_on= [azurerm_subscription.sandbox1]
    }
  }
}_

**Comment by krowlandson** [comment]
Hi @Karni-G... the primary purpose of using the module to created nested deployments in the management group hierarchy is when a customer wants different pipelines to be responsible for different parts of the hierarchy. The nesting approach allows different credentials to be used for the nested deployments. It's not a common scenario though.

Does this help?

**Comment by Karni-G** [comment]
This helps. I will investigate a bit more and get back to you if needed. Thanks! I
