### ISSUE TITLE
Question - how to configure Azure Firewall with existing public IP resource

### ISSUE THREAD

**Issue by hungbui78** [Azure/terraform-azurerm-caf-enterprise-scale#559]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

terraform:

Terraform v1.3.5
on linux_amd64

azure provider:
hashicorp/azurerm v3.34.0

module:

source = "Azure/caf-enterprise-scale/azurerm"
version = "3.0.0"

#### Describe the bug

Hi.

This is not a bug more of a question of a setting. We have our public ip  that we want to use instead of a public ip that gett created by the module while we deploy the hub firewall.

We cant find anywhere in the wiki guide how to do that. The question is how to we use our own static public IP (created outside the module) for the hub firewall with the module ? This is because we want to have same public IP for the FW even if we redploy the FW due to FW öppnings in onprem firewalls.

BR 

Hung

#### Steps to Reproduce

Hi.

This is not a bug more of a question of a setting. We have our public ip that we want to use instead of a public ip thats got created by the module while we deploy the hub firewall.

We cant find anywhere in the wiki guide how to do that. The question is how to we use our own static public IP for the hub firewall with the module ?

BR 

Hung

**Comment by krowlandson** [comment]
Thank you for the question @hungbui78 

Assuming you are using `hub_networks` (this isn't possible with Virtual WAN), you should be able to do this using the advanced input as follows:

```hcl
  configure_connectivity_resources = {
    # additional settings removed for brevity
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_firewall = {
          connectivity = {
            eastus = { # replace `eastus` with the location you are deploying to
              ip_configuration = [
                {
                  name                 = "" # set as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#name
                  public_ip_address_id = "" # set as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#public_ip_address_id
                  subnet_id            = "" # set as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#subnet_id
                }
              ]
            }
          }
        }
      }
    }
  }
```

The presence of this setting should stop the module from creating the corresponding public IP resource, and attach the specified public IP to the Azure Firewall.

For more information on these settings, please refer to the [azurerm_firewall](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall) documentation.

**Comment by hungbui78** [comment]
> Thank you for the question @hungbui78
> 
> Assuming you are using `hub_networks` (this isn't possible with Virtual WAN), you should be able to do this using the advanced input as follows:
> 
> ```terraform
>   configure_connectivity_resources = {
>     # additional settings removed for brevity
>     advanced = {
>       custom_settings_by_resource_type = {
>         azurerm_firewall = {
>           connectivity = {
>             eastus = { # replace `eastus` with the location you are deploying to
>               ip_configuration = [
>                 {
>                   name                 = "" # set as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#name
>                   public_ip_address_id = "" # set as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#public_ip_address_id
>                   subnet_id            = "" # set as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#subnet_id
>                 }
>               ]
>             }
>           }
>         }
>       }
>     }
>   }
> ```
> 
> The presence of this setting should stop the module from creating the corresponding public IP resource, and attach the specified public IP to the Azure Firewall.
> 
> For more information on these settings, please refer to the [azurerm_firewall](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall) documentation.

Hi Kevin.

Thx for the help and it works like a charm :)

BR

Hung
