### ISSUE TITLE
"ES-Deny-VMIPForwarding" does not deny IP Forwarding

### ISSUE THREAD

**Issue by WilliamDahlen** [Azure/terraform-azurerm-caf-enterprise-scale#56]
Hi

We can't get "ES-Deny-VMIPForwarding" policy assignment to deny VM ip forwarding.

The policy assigment uses a build in definition, so it might be something wrong upstream.

```JSON
{
  "name": "ES-Deny-VMIPForwarding",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Deny IP Forwarding on Virtual Machines.",
    "displayName": "ES-Deny-IP-Forwarding-On-VM",
    "notScopes": [],
    "parameters": {
      "effect": {
        "value": "Disabled"
      }
    },
    "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/bd352bd5-2853-4985-bf0d-73806b4a5744",
    "scope": "${current_scope_resource_id}"
  },
  "sku": {
    "name": "A0",
    "tier": "Free"
  },
  "location": "${default_location}",
  "identity": {
    "type": "None"
  }
}
```

The policy assignment has set "Disabled" as its default value in the parameters section. The only option i can see in the azure portal is AuditIfNotExists or Disabled. i would expect Deny to be a option here? I have tried it with both, but i have yet to try and set "Deny" through the main.tf file.

![es_deny_ip_forwarding](https://user-images.githubusercontent.com/36991168/111642888-c155ca00-87fe-11eb-8699-6d7b015e9dc1.png)

In the complience reason details blade we get this error. So it has identified that the VM is breaking the policy, but no remediation tasks are available and i still get to turn on and off the VM IP Forwarding.

> Reason for non-compliance
> No related resources match the effect details in the policy definition. (Error code: AssessmentNotFound)
> Existence condition
> Type
> Microsoft.Security/assessments
> Name
> c3b51c94-588b-426b-a892-***

Are we missing something?
Any suggestions are appreciated.

**Comment by krowlandson** [comment]
Hi @WilliamDahlen... I appreciate this will require a bit of additional work on your part, but I would highly recommend updating to the latest release as I know this policy has been updated and may resolve your problem.

Please take a look at the [upgrade guide](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v0.0.8-to-v0.1.0) but note that we've already released `v0.1.1` which includes a further bugfix relating to Role Assignments for policies with Managed Identity.

**Comment by WilliamDahlen** [comment]
Hi, thanks! 

Ill update the issue when we get the new version rolling and can test if the policy is fixed.

**Comment by krowlandson** [comment]
Closing as I believe this is no longer relevant.

This Policy Assignment has now been replaced by [`Deny-IP-Forwarding`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_ip_forwarding.tmpl.json) which uses a new built-in Policy Definition `/providers/Microsoft.Authorization/policyDefinitions/88c0b9da-ce96-4b03-9635-f29a937e2900`

Hopefully this addresses the original problem, but please feel free to raise a new issue if the updated Policy Assignment doesn't achieve the desired outcome.
