### ISSUE TITLE
Feature Request - Videos to Assist Written Documentation

### ISSUE THREAD

**Issue by oZakari** [Azure/terraform-azurerm-caf-enterprise-scale#567]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Had request from customer that they would appreciate additional videos that could cover the following:

-  Videos that would walk through some of the [examples](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/Examples).
-  Videos that could assist with giving a deeper look at how the module is designed and correlates to the different configurations available.
- Videos talking through some of the limitations as well as some of the things to watch out for.

**Comment by jtracey93** [comment]
Hey @oZakari,

Have you/they seen the recent Azure Enablement Show videos @krowlandson and @matt-FFFFFF have made? 

They are available here via the AAC page: https://learn.microsoft.com/azure/architecture/landing-zones/terraform/landing-zone-terraform

**Comment by oZakari** [comment]
Thanks @jtracey93, wasn't aware of these!

**Comment by krowlandson** [comment]
This is a great ask @oZakari so also adding these to the Wiki as part of some other updates I'm making today. Thank you! 👍🏻
