### ISSUE TITLE
Bug Report : terraform commands caused azure request limit exceeded

### ISSUE THREAD

**Issue by johnnylintwn** [Azure/terraform-azurerm-caf-enterprise-scale#570]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

![image](https://user-images.githubusercontent.com/46800056/209316586-0ec8250f-1c13-483e-b7ed-5cb6bd883f55.png)

  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "2.3.1"

### Description

We have created several level 3, 4 management groups, and imported some subscriptions, and we have also done a lot of peering for the connectivity of many vnets by landing zone code in these subscriptions, but since this morning can't execute teffaform plan and apply, the error message is error429, after researching we found that because azure detected the read request behavior of terraform, the azure limit was exceeded, and **then stopped all terraform commands**

Since we have added vnets peering to vwan by terraform, caf terraform will automatically link these vnets to link private dns zone, But when we execute the terraform plan/apply command, the behavior of terraform is to update the status of read private dns zone virtual network link, which will trigger the access restriction of azure, but we can't do anything about this..

May Microsoft adjust the azure request limit? 
Or how to make the behavior of terraform conform to the azure request limit?

#### Describe the bug

{"error":{"code":"ResourceRequestsThrottled","message":"Number of requests for action 'Microsoft.Network/privateDnsZones/virtualNetworkLinks/read' exceeded the limit of '500' for time interval '00:05:00'. Please try again after '307' seconds."}}: timestamp=2022-12-23T05:21:29.864Z
2022-12-23T05:26:29.601Z [ERROR] provider.terraform-provider-azurerm_v3.23.0_x5: Response contains error diagnostic: diagnostic_severity=ERROR diagnostic_summary="reading Virtual Network Link (Subscription: "a7f7f0ad-f6ba-4a65-995f-d991597db09c"

#### Screenshots

![image](https://user-images.githubusercontent.com/46800056/209318379-71386c90-fbe0-481a-beec-60510f5ef71e.png)

**Comment by krowlandson** [comment]
Thank you for the question @johnnylintwn... can I just check, do you manually increase the number of parallel resources being created by Terraform using the [`-parallelism`](https://developer.hashicorp.com/terraform/cli/commands/apply#parallelism-n) option?

If you have increased this from the default (`10`) it might be worth trying to reduce this.

Unfortunately we don't have control over the API limits imposed by the platform, and the behaviour you are observing is more likely a provider or Terraform bug, where it isn't backing off the request rate quickly enough.

If you continue to observe this issue, I would strongly recommend logging this as [an Azure support request](https://learn.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). If you have an assigned CSAM, you can also ask them to escalate this ticket.

Hope this helps.

**Comment by yuanzhang9** [comment]
@krowlandson referring to the following link, can we add support to the module to allow overriding the default TIMEOUT value? Will that help solving this issue?
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_a_record

Or, @johnnylintwn , it also worth trying to decrease the terraform parallel level to number lower than default (10), 5 for example.

**Comment by johnnylintwn** [comment]
@krowlandson
Thank you for the suggestion, but we did not set parallelism, or try to change the limit the number of concurrent operation defined .
In fact, we have also submitted a level A support ticket on Azure, and the supprot engineer told us it was because terraform's behavior triggered Azure's request limit.
they assume that due to the automation packaged by terraform caf, too many requests to azure are generated. 
in our case, in connectivity.tf, connecting a vent peering to vwan will cause more than 40 private dns zone virtual network links to be added.
PS: The proportion of project connected caf-landing zone is less than one-tenth..

**Comment by johnnylintwn** [comment]
I tried to execute the command "terraform plan -parallelism=5", but still because of a large number of reading and refreshing state behaviors, the result is conext deadline exceeded

<img width="322" alt="螢幕擷取畫面 2022-12-25 085957" src="https://user-images.githubusercontent.com/46800056/209454390-a34d0810-6a86-4163-b7c7-4c729baa804d.png">

<img width="1025" alt="螢幕擷取畫面 2022-12-25 091429" src="https://user-images.githubusercontent.com/46800056/209454447-cca3f8b4-144b-4480-a2b3-ebfde55964d4.png">

**Comment by krowlandson** [comment]
Thank you for the additional information @johnnylintwn... I completely understand the challenge you are facing.

Increasing the timeout in the module is a possible option but we also need to consider the broader impact these limits have on customers trying to manage environments at scale.

I am discussing with @yuanzhang9 offline and we will try to find a suitable resolution to this 👍🏻

**Comment by johnnylintwn** [comment]
thanks for youall helps @krowlandson @yuanzhang9
the issue has be resolved currently, we add "time out=60ms" under code block of private dns zone and private dns zone virtual network links in resource.connectivity.tf in the modules, so even azure deny over 500 request in 5 mins, terraform still run requests after 5 mins.

**Comment by matt-FFFFFF** [comment]
resolved above
