### ISSUE TITLE
Bug Report: NSG Flow Logs policy not assigned

### ISSUE THREAD

**Issue by DevSecNinja** [Azure/terraform-azurerm-caf-enterprise-scale#579]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: latest

**azure provider**: latest

**module**: v3.1.0

#### Describe the bug

The deprecation warning in the ES module mentions the deprecation of the NSG Flow Logs policy **in favor of a built-in one**: https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/ALZ-Deprecated-Services.md#deprecated-policies. It seems this one was deprecated in this module as well, but the built-in policy was never assigned: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/e6da921369d90aa38bd2ece1dfb8e81f55cf8cfe/docs/wiki/%5BUser-Guide%5D-Upgrade-from-v2.4.1-to-v3.0.0.md#resource-type-azurerm_policy_definition

Should this policy be assigned?

#### Steps to Reproduce

1. Deploy the Enterprise Scale environment
2. Check the built-in NSG flow log policy.
3. Confirm the built-in policy doesn't have any assignments.

**Comment by jtracey93** [comment]
Hey @DevSecNinja,

This policy was never assigned. We just provided it as a definition as it didn't exist as a built in. We are currently reviewing the default ALZ policy assignments, but we are not going to add this one at this time as it can increase costs considerably for customers with additional logging.

**Comment by DevSecNinja** [comment]
Thanks for your reply @jtracey93! Understood, but shouldn't it be assigned considering that it's a best practice in the Azure Review checklist?

`Enable NSG flow logs and feed them into Traffic Analytics to gain insights into internal and external traffic flows.`

In my opinion, we shouldn't exclude features because they could potentially increase costs. Services like DDoS Protection, Azure Firewall and Sentinel can also cause cost increases. Enabling NSG Flow logs by default is definitely a topic for a discussion and I would agree that it's up to discretion of the user to enable it.

Considering it's part of the Azure Review checklist, could we give this one a spot on the roadmap?

Thanks.

**Comment by jtracey93** [comment]
Hey @DevSecNinja,

I hear you. The checklist is currently being updated. 

We will consider it in the current round of policy updates again, and it is also on the roadmap under some work we are tracking with the PG for flow log enhancements and network watcher 👍

**Comment by DevSecNinja** [comment]
Thanks, appreciate it @jtracey93!
