### ISSUE TITLE
Feature Request - How to use configure_connectivity_resources variable in a custom landing zone

### ISSUE THREAD

**Issue by sudhir-ops** [Azure/terraform-azurerm-caf-enterprise-scale#580]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
How to use configure_connectivity_resources variable in a custom landing zone.
#### Is your feature request related to a problem?
Yes

#### Describe the solution you'd like
I'm creating a custom landing zones for core management groups. So I have set "deploy_core_landing_zones = false".

I would like to use the configure_connectivity_resources variable for creating and configuring VWAN resources for the custom connectivity landing zone I have created.

Kindly let me know if this is possible.

#### Additional context

**Comment by sudhir-ops** [comment]
This can be closed, as I got to know that even though custom landing zones are present its not related to deploying connectivity resources since , just enabling the below in the correct connectivity subscription will deploy the resources in them and  we can move the connectivity subscription into custom landingzone we created

  deploy_connectivity_resources    = true
  subscription_id_connectivity     = data.azurerm_client_config.connectivity.subscription_id
  configure_connectivity_resources = local.configure_connectivity_resources

**Comment by krowlandson** [comment]
Glad you found a solution to this, and thank you for closing this.

You may find the following Wiki guidance useful as this shows using the connectivity capability independently as I believe you are trying to do:
[[Examples] Deploy using multiple module declarations with remote state](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-remote-state)
