### ISSUE TITLE
How to deploy landing zone subscriptions?

### ISSUE THREAD

**Issue by chanakanissanka** [Azure/terraform-azurerm-caf-enterprise-scale#589]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is not really an issue and more of seeking direction towards "landing zone subscription deployment". We have tried out this repo and successfully deployed related components. Before we go ahead and create our own modules on top of this for landing zone components, where we can actually vend out to LZ consumers, do we have any pre-work done on this so far ? Any recommendation or direction on this is much appreciated. 

#### Is your feature request related to a problem?

No

#### Describe the solution you'd like

Sample next steps for "Landing zone subscription" vending out part

**Comment by krowlandson** [comment]
@chanakanissanka are you aware of our [lz-vending](https://registry.terraform.io/modules/Azure/lz-vending/azurerm/latest) module?

You can find [examples](https://github.com/Azure/terraform-azurerm-lz-vending/wiki/Examples) on how to use this on the wiki, including an [Example of how to integrate this module with the ALZ Terraform module](https://github.com/Azure/terraform-azurerm-lz-vending/wiki/Example-4-Integration-with-ALZ-module).

cc: @matt-FFFFFF

**Comment by krowlandson** [comment]
Thanks @chanakanissanka... I'll close the issue for now, but please re-open and let us know if you need any further information.

**Comment by chanakanissanka** [comment]
@krowlandson Apologies if I'm barking the wrong tree here, we are in the middle of deploying a LZ and we want it to be aligned with 100% CAF and got really confused with this two repos provided by MS. 
This repo ( Enterprise Landing Zone ) works fine and vending module is easy to implement tat has all these initial information. 
Then, this CAF super module comes with all goodies but no any MGMT group or Policy .  
Deployed connectivity module both into  test subscriptions and looks same.  Any idea why MS has these two repos and what we ( As customers ) should be  start using ?

**Comment by chanakanissanka** [comment]
> Thanks @chanakanissanka... I'll close the issue for now, but please re-open and let us know if you need any further information.

@krowlandson Apologies if I'm barking the wrong tree here, we are in the middle of deploying a LZ and we want it to be aligned with 100% CAF and got really confused with this two repos provided by MS.
This repo ( Enterprise Landing Zone ) works fine and vending module is easy to implement tat has all these initial information.
Then, this CAF super module comes with all goodies but no any MGMT group or Policy .
Deployed connectivity module both into test subscriptions and looks same. Any idea why MS has these two repos and what we ( As customers ) should be start using ?

**Comment by krowlandson** [comment]
@chanakanissanka have you seen the following guidance on the CAF docs?
[Deploy Azure landing zones by using Terraform](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/deploy-landing-zones-with-terraform)

Does this help?

**Comment by chanakanissanka** [comment]
@krowlandson , Thanks again and really don't want to waste your time anymore. quick update/background, 
we have seen this page multiple times (All honesty) and doubt we had was, we will have to maintain pipeline consists of both repos as upstream which has different level of provider dependency for our landing zone. Keep maintaining those levels as explained here- https://aztfmod.github.io/documentation/docs/fundamentals/lz-intro could be somewhat challenging. Not saying we can’t, it just that lots of moving parts. More than happy to be wrong here and pick your brain for the last time. Do you have any thoughts or possible approach that can be shared. Specific to our scenario we need obviously both platform and application component.   
Irrelevant, many thanks for your direction so far. Cheers mate
