### ISSUE TITLE
Bug Report - resource_prefix / resource_suffix

### ISSUE THREAD

**Issue by diegosrp** [Azure/terraform-azurerm-caf-enterprise-scale#596]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**source = "Azure/caf-enterprise-scale/azurerm"**: version = "3.1.2"

**terraform**: v1.3.7

**azure provider**: v3.39.1

**module**: management 

#### I checked here https://registry.terraform.io/modules/Azure/caf-enterprise-scale/azurerm/latest/submodules/management?tab=inputs 
about resource_prefix / resource_suffix but when I try to use with the parameter I receive error.
I don't found example how can I use this parameters: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/examples

#### Steps to Reproduce

I added the source module and required inputs and the optional input and receive the message: 
 Error: Unsupported argument
│ 
│   on caf.tf line 39, in module "enterprise_scale":
│   39:   resource_prefix = "123-"
│ 
│ An argument named "resource_prefix" is not expected here.

│ Error: Unsupported argument
│ 
│   on caf.tf line 40, in module "enterprise_scale":
│   40:   resource_suffix = "-test"
│ 
│ An argument named "resource_suffix" is not expected here.

#### Screenshots

 https://postimg.cc/hfzVYyGH

**Comment by krowlandson** [comment]
Thank you for the ask @diegosrp... 

To use this feature, you would use the following code block in your configuration:

```hcl
  configure_management_resources = {
    # other attributes removed for brevity
    advanced = {
      resource_prefix = "myString"
      resource_suffix = "myString"
    }
  }
```

Please let me know if this helps?

**Comment by diegosrp** [comment]
Oh yeah!
Thank you so much @krowlandson
