### ISSUE TITLE
Feature flag not working for Azure Activity solution

### ISSUE THREAD

**Issue by prjelesi** [Azure/terraform-azurerm-caf-enterprise-scale#599]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
Terraform v1.3.6

**azure provider**:
- Using previously-installed hashicorp/azurerm v3.40.0
- Using previously-installed hashicorp/random v3.4.3
- Using previously-installed hashicorp/time v0.9.1
- 
**module**:
 version = "3.1.2"

#### Describe the bug

changing value for enable_solution_for_azure_activity in settings.management.tf file does not create solution in LAWS.   

#### Steps to Reproduce

change value from false to tru and apply configuration. 

#### Screenshots
current confirguration

<img width="848" alt="image" src="https://user-images.githubusercontent.com/5805065/214868461-ffec1aaa-464a-4204-9ea4-81694d353f10.png">

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/5805065/214868125-0358696e-c1e5-49fa-bddc-9becfaabfe13.png">

**Comment by krowlandson** [comment]
@prjelesi, this feature was removed in [release v3.1.0](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases/tag/v3.1.0).

Are you seeing this somewhere in our documentation, or have you just observed this elsewhere whilst upgrading from an earlier version?
