### ISSUE TITLE
Feature Request: Improve access_control plan output

### ISSUE THREAD

**Issue by bob-rohan** [Azure/terraform-azurerm-caf-enterprise-scale#605]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`access_control` enables us to maintain role assignement, however the Terraform plan output is quite opaque. The reason for Terraform provider alignment are justified in the README, so IDs are provided. But either meta data (user principal name, group name) could be retried from data source or provided as optional additional meta data by the developer.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/28977803/216984999-f6f047d0-173d-428b-9df7-27149d2dce22.png">

#### Is your feature request related to a problem?

Can see this being a problem for plan reviewers / approvers.

#### Describe the solution you'd like

To show the user principal name or some other user friendly name in the terraform output

**Comment by krowlandson** [comment]
Thank you for the feature request @bob-rohan. I can completely understand your ask here.

The output above will always look like the above due to this being controlled by the provider.

It may be possible to create a custom `output` to perform this conversion using the Azure AD provider, but this may be better handled by the customer by reversing this logic.

What I mean by this, is for the customer to provide a series of inputs which represent the users, groups or SPN/MIs to be assigned. These can be converted dynamically to the required object ID for input to the module using the relevant Azure AD data resource. Reviewers/approvers can then validate the source code, rather than the Terraform plan.

Please let me know your thoughts.

**Comment by bob-rohan** [comment]
Thanks @krowlandson. That would certainly improve the review process by removing the need to validate the supplied ID. The code would certainly be clearer.

However as you point out the plan would not improve. By computing the value for attribute `azurerm_role_assignment.name`, something like "<scope>-<role>-<object-displayname>"  i.e "CIT-Reader-BobRohan". The object displayname could be pulled from `azuread_provider` or provided by the user as additional optional input.

I had suggested use of optional input data in reluctance to avoid direct dependency on `azuread_provider`.  

> - `access_control` provides the option to add user-specified Role Assignments which will be added to the specified Management Group.
>To avoid a direct dependency on the [Azure Active Directory Provider][azuread_provider], this module requires the input to >be a list of Object IDs for each Azure AD object you want to assign the specified permission.

The use of `azuread_provider` would presumably require the entity executing Terraform to hold some additional azure ad permissions?

**Comment by krowlandson** [comment]
> The use of `azuread_provider` would presumably require the entity executing Terraform to hold some additional azure ad permissions?

That's correct, which is the primary reason why we opted to exclude the Azure AD provider from the module.

The approach I describe above makes this 100% a customer decision which can be made once they are comfortable with the additional complexity required to achieve this.

One point to watch out for is ensuring the correct object ID is referenced when looking up SPNs (App Registrations), as Azure actually needs the object ID of the associated Enterprise Application when creating role assignments using the `azurerm_role_assignment` Terraform resource.

**Comment by matt-FFFFFF** [comment]
Due to constraints above, closing this as won't fix
