### ISSUE TITLE
Bug Report: No corresponding policy_assignment for `Enforce-Encryption-CMK`

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#609]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:  any

**azure provider**: any

**module**: `enterprise-scale-2.4.1`

#### Describe the bug

When creating policy configuration for landing zones it appears there is no corresponding `policy assignment` for the policyset definition "Enforce-Encryption-CMK", as shown below:

```
{
  "customer_000": {
    "policy_assignments": ["?????", "Enforce-TLS-SSL","Deny-Subnet-Without-Nsg","Deny-Resource-Locations","Deny-RSG-Locations","Deny-Public-Endpoints","Deny-RDP-From-Internet","Deny-Public-IP"],
    "policy_definitions": [],
    "policy_set_definitions": ["Enforce-Encryption-CMK", "Enforce-EncryptTransit"],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {
        "Deny-Resource-Locations": {
          "listOfAllowedLocations": [
            "eastasia",
            "southeastasia"
          ]
        },
        "Deny-RSG-Locations": {
          "listOfAllowedLocations": [
            "eastasia",
            "southeastasia"
          ]
        },
        "Deny-Subnet-Without-Nsg": {
           "effect": "Audit"
        }
      },
      "access_control": {}
    }
  }
}
```
 
While there are references to assignments for other policy definitions there does not seem to be one in the code or documentation for "Enforce-Encryption-CMK".

This means there is no way to specify an assignment to enforce CMK on storage accounts and VM  disks.

Ideally, there should be a policy assignment to add to the following list in order to specify CMK encryption enforcement.

```
  "policy_assignments": ["?????", "Enforce-TLS-SSL","Deny-Subnet-Without-Nsg","Deny-Resource-Locations","Deny-
```

#### Steps to Reproduce

n/a

#### Screenshots

n/a

#### Additional context

An assignment is needed to enforce the policy/set definition "Enforce-Encryption-CMK". 
While we can deploy the "Enforce-Encryption-CMK". definition to the landing zone we cannot create an assignment using an assignment configured in the module.

**Comment by archmangler** [comment]
Any update on this?

**Comment by krowlandson** [comment]
@archmangler, we only create policy assignments for policies which are included as part of the reference implementation. In many cases, our custom policy definitions are bundled within an initiative and we only have an assignment for the initiative. As such, there are some policies which don't have a corresponding assignment.

There are also scenarios where a policy was included for optional assignment, to help with testing, or has been deprecated. In these cases, we haven't included the corresponding policy assignment template.

For this particular initiative, I'm not aware that we have ever assigned it by default so you would make it accessible by adding your own policy assignment template to your custom lib folder.

We are also currently working on a policy refresh for ALZ all-up. We can add this policy for review/discussion as part of that if it isn't already.

@jtracey93, do you know the status of this particular policy?

**Comment by archmangler** [comment]
@krowlandson  - thanks for the feedback. 

An example in this case would be good for those of us struggling to navigate the implementation of the module code. Perhaps a small guide on creating assignments for existing definitions that may not have them ?

**Comment by krowlandson** [comment]
Agreed @archmangler... I'll discuss with the team.

**Comment by jtracey93** [comment]
This policy will be staying as is today as per: https://aka.ms/alz/policies as not all customers require CMK.

As for the documentation, does this not cover it off? https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy-Sets-and-Assignments#create-custom-policy-assignment-files

**Comment by krowlandson** [comment]
@jtracey93... if we are classifying this as a "recommended, but optional" policy, would it make sense to add a template for this one to simplify creating the assignment?

I'd even suggest it justifies a `bool` input to control it being created or not, but I actually prefer the archetype extension mechanism, as it gives far greater long-term flexibility.

**Comment by jtracey93** [comment]
If we want to add an example to the lib then I have no issues with that, but ideally the wiki docs should be sufficient for creating this. So if they aren't, I think we should fix that.

**Comment by matt-FFFFFF** [comment]
@archmangler Does the above wiki article cover you needs for creating new policy assignment files?
