### ISSUE TITLE
Policy Definition Deploy-Diagnostics-VNetGW contains duplicate Log Property - fails on remediation

### ISSUE THREAD

**Issue by XristophD** [Azure/terraform-azurerm-caf-enterprise-scale#611]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
v1.3.6
**azure provider**:
v3.42.0
**module**:
3.1.2

#### Describe the bug

Policy Definition Deploy-Diagnostics-VNetGW contains a duplicate log property _RouteDiagnosticLog_ that prevents the policy executing the deployment template on e.g. remediation. 

Remediation fails with the following error: 

> BadRequest
> Detected duplicated Log settings 'GatewayDiagnosticLog | IKEDiagnosticLog | P2SDiagnosticLog | RouteDiagnosticLog | RouteDiagnosticLog | TunnelDiagnosticLog'.

#### Steps to Reproduce

1. Deploy Virtual Network Gateway
2. Remediate Policy Assignment for definition Deploy-Diagnostics-VNetGW
3. An error as described above during remediation

#### Screenshots

![image](https://user-images.githubusercontent.com/10231267/218049768-a8ec5ca9-4730-47ea-bdab-7810e1a9501b.png)

![image](https://user-images.githubusercontent.com/10231267/218050088-79383d59-e289-4412-93ad-34f6ed4d0a00.png)

**Comment by jtracey93** [comment]
Thanks @XristophD, we are tracking and resolving this in the ALZ upstream repo, where all the policies are sourced, here: https://github.com/Azure/Enterprise-Scale/issues/1190

Will close this as duplicate :)
