### ISSUE TITLE
Feature Request: Make it possible to import role assignments by allowing the name property to be changed

### ISSUE THREAD

**Issue by adhodgson1** [Azure/terraform-azurerm-caf-enterprise-scale#614]
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'm importing some existing management groups to this module that contain some role assignments that were created outside of Terraform. I can successfully import the existing role assignment objects into the state, however when I do this the entries need to be re-created because the Name property doesn't match that used by the module. Looking at the code I don't believe the module allows the Name property to be specified on the access_control property:

```
  # Special handling of OPTIONAL name to ensure consistent and correct
  # mapping of Terraform state ADDR value to Azure Resource ID value.
  name = basename(each.key)
```

While I like the way this works now it does mean we can't import existing entries. I haven't ruled out importing all the entries and allowing Terraform to re-create them on the next run, worse case scenario is we use the module to assign new entries and leave the old ones as is.

**Comment by krowlandson** [comment]
Thank you for the question @adhodgson1... whilst this would be technically possible, I think the additional logic (and customer inputs) to make this possible would add too much complexity for limited value.

As Role Assignments will have no impact on the Policy Assignment (specifically compliance history), I would probably recommend letting the module create the new Role Assignments needed (as the module also handles ensuring unique naming) and then manually removing the old assignments.

**Comment by matt-FFFFFF** [comment]
@adhodgson1 

Do you need to import the role assignments here? Can you leave them as managed outside the existing terraform state?

Otherwise as @krowlandson says this will be very complex to implement.

**Comment by adhodgson1** [comment]
Yeah will be handling this by having them unmanaged outside of this code and going through a migration process. The client wants to actually change some of these now to make them more uniform anyhow.
