### ISSUE TITLE
Deploy-Private-DNS-Zones permission error

### ISSUE THREAD

**Issue by skiddder** [Azure/terraform-azurerm-caf-enterprise-scale#615]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.6

**azure provider**: 3.37.0

**module**: 3.1.2

#### Describe the bug

When creating an Azure Key Vault with a private endoint within my landing zone subscription, the policy assignment "Deploy-Private-DNS-Zones" triggers the creation of an A Record in the corresponding privatelink DNS Zone in the connectivity subscription. But the deployment of the private DNS zone integration fails due to missing permissions of the service principal.

here is the error message - in my case I tried to create a keyvault with private endpoint:

`
The client '18df6054-f3cb-478d-a732-7b24834cfecd' with object id '18df6054-f3cb-478d-a732-7b24834cfecd' has permission to perform action 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups/write' on scope '/subscriptions/<my-landing-zone-sub-id>/resourcegroups/dns-test/providers/Microsoft.Network/privateEndpoints/pe-kv-dnstest2/privateDnsZoneGroups/deployedByPolicy'; however, it does not have permission to perform action 'Microsoft.Network/privateDnsZones/join/action' on the linked scope(s) '/subscriptions/<my-connectivity-sub-id>/resourceGroups/es-dns/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net' or the linked scope(s) are invalid.
`

#### Steps to Reproduce

here are my connectivity settings:

`
locals {
  configure_connectivity_resources = {
    settings = {
      hub_networks = [
        {
          enabled = true
          config = {
            address_space                = ["10.101.0.0/16", ]
            location                     = "westeurope"
            link_to_ddos_protection_plan = false
            dns_servers                  = []
            bgp_community                = ""
            subnets                      = []
            virtual_network_gateway = {
              enabled = true
              config = {
                address_prefix           = "10.101.1.0/24"
                gateway_sku_expressroute = ""
                gateway_sku_vpn          = "VpnGw1" #"VpnGw2AZ"
                advanced_vpn_settings = {
                  enable_bgp                       = null
                  active_active                    = null
                  private_ip_address_allocation    = ""
                  default_local_network_gateway_id = ""
                  vpn_client_configuration         = []
                  bgp_settings                     = []
                  custom_route                     = []
                }
              }
            }
            azure_firewall = {
              enabled = true
              config = {
                address_prefix                = "10.101.2.0/24"
                enable_dns_proxy              = true
                dns_servers                   = []
                sku_tier                      = ""
                base_policy_id                = ""
                private_ip_ranges             = []
                threat_intelligence_mode      = ""
                threat_intelligence_allowlist = []
                availability_zones = {
                  zone_1 = true
                  zone_2 = true
                  zone_3 = true
                }
              }
            }
            spoke_virtual_network_resource_ids      = [
              "/subscriptions/<my-connectivity-sub-id>/resourceGroups/es-network/providers/Microsoft.Network/virtualNetworks/es-vnet-spoke-eslz-a"
            ]
            enable_outbound_virtual_network_peering = true
            enable_hub_network_mesh_peering         = false
          }
        },
      ]
      vwan_hub_networks = []
      ddos_protection_plan = {
        enabled = false
        config = {
          location = "northeurope"
        }
      }
      dns = {
        enabled = true
        config = {
          location = null
          enable_private_link_by_service = {
            azure_api_management                 = true
            azure_app_configuration_stores       = true
            azure_arc                            = true
            azure_automation_dscandhybridworker  = true
            azure_automation_webhook             = true
            azure_backup                         = true
            azure_batch_account                  = true
            azure_bot_service_bot                = true
            azure_bot_service_token              = true
            azure_cache_for_redis                = true
            azure_cache_for_redis_enterprise     = true
            azure_container_registry             = true
            azure_cosmos_db_cassandra            = true
            azure_cosmos_db_gremlin              = true
            azure_cosmos_db_mongodb              = true
            azure_cosmos_db_sql                  = true
            azure_cosmos_db_table                = true
            azure_data_explorer                  = true
            azure_data_factory                   = true
            azure_data_factory_portal            = true
            azure_data_health_data_services      = true
            azure_data_lake_file_system_gen2     = true
            azure_database_for_mariadb_server    = true
            azure_database_for_mysql_server      = true
            azure_database_for_postgresql_server = true
            azure_digital_twins                  = true
            azure_event_grid_domain              = true
            azure_event_grid_topic               = true
            azure_event_hubs_namespace           = true
            azure_file_sync                      = true
            azure_hdinsights                     = true
            azure_iot_dps                        = true
            azure_iot_hub                        = true
            azure_key_vault                      = true
            azure_key_vault_managed_hsm          = true
            azure_kubernetes_service_management  = true
            azure_machine_learning_workspace     = true
            azure_managed_disks                  = true
            azure_media_services                 = true
            azure_migrate                        = true
            azure_monitor                        = true
            azure_purview_account                = true
            azure_purview_studio                 = true
            azure_relay_namespace                = true
            azure_search_service                 = true
            azure_service_bus_namespace          = true
            azure_site_recovery                  = true
            azure_sql_database_sqlserver         = true
            azure_synapse_analytics_dev          = true
            azure_synapse_analytics_sql          = true
            azure_synapse_studio                 = true
            azure_web_apps_sites                 = true
            azure_web_apps_static_sites          = true
            cognitive_services_account           = true
            microsoft_power_bi                   = true
            signalr                              = true
            signalr_webpubsub                    = true
            storage_account_blob                 = true
            storage_account_file                 = true
            storage_account_queue                = true
            storage_account_table                = true
            storage_account_web                  = true
          }
          private_link_locations = [
            #"northeurope",
            "westeurope",
          ]
          public_dns_zones                                       = []
          private_dns_zones                                      = []
          enable_private_dns_zone_virtual_network_link_on_hubs   = true
          enable_private_dns_zone_virtual_network_link_on_spokes = false
          virtual_network_resource_ids_to_link                   = []
        }
      }
    }
    location = var.connectivity_resources_location
    tags     = var.connectivity_resources_tags
    advanced = null
  }
}
`

Because I only have one subscription directly below management group "landing_zones", I did the following archetype_extension on my landing_zones in order to assign "Deploy-Private-DNS-Zones" on that scope instead of "corp":

`{
    "extend_es_landing_zones": {
      "policy_assignments": ["Deploy-Private-DNS-Zones"],
      "policy_definitions": [],
      "policy_set_definitions": [],
      "role_definitions": [],
      "archetype_config": {
        "parameters": {},
        "access_control": {
        }
      }
    }
  }`

#### Additional context

I did not test to create other resource types with private endpoints. But I assume that all the individual subscriptions use the same service principal with the same permissions. So I assume that other resource types will probably also fail due to the same error message.

I worked around the problem by manually assigning the contributor permission for the service principal to the resource group 'es-dns'.

**Comment by matt-FFFFFF** [comment]
Hi @skiddder 

Thanks for raising this. Can you be specific about which service principal you are talking about? Is this the one created by the policy assignment, or the one that you are using to deploy the KV?

**Comment by matt-FFFFFF** [comment]
@skiddder for now please make the role assignment manually, we have a item to track permissions at these scopes using the assignPermissions metadata property.

see #439

**Comment by skiddder** [comment]
Sorry for the delay! The specific service principal is mentioned in the error message:

`'18df6054-f3cb-478d-a732-7b24834cfecd' with object id '18df6054-f3cb-478d-a732-7b24834cfecd'`

The display name is 'Deploy-Private-DNS-Zones'.
