### ISSUE TITLE
Feature Request: Documentation Request - Custom Auto-Remediation

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#618]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Not clear from available documentation and code how to implement an Azure resource Auto-remediation.

#### Describe the solution you'd like

Documented example(s) of configuring a custom Auto-remediation using the `terraform-azurerm-caf-enterprise-scale` module

#### Additional context

This is a requested feature from enterprise customers running landing zones on azure.

**Comment by matt-FFFFFF** [comment]
Hi @archmangler 

Can you be more specific on the ask here, are you talking about automatic remediation via Azure policy remediation tasks?
