### ISSUE TITLE
Feature Request / Question | Allow additional Azure Monitoring Solutions to be deployed easily

### ISSUE THREAD

**Issue by XristophD** [Azure/terraform-azurerm-caf-enterprise-scale#619]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently, within the configuration of management resources, we can define if Log Analytics Workspace is deployed, and can (de-)select from a predefined list of monitoring solutions. 
Adding additional monitoring solutions that are not defined within the template to the central Log Analytics workspace is currently not easily possible or documented (maybe possible via the advanced property?). 

#### Is your feature request related to a problem?
No, more an inconvenience.

#### Describe the solution you'd like
Beside the predefined list of Solutions to be deployed, an optional array to define solutions that should be deployed.

**Comment by matt-FFFFFF** [comment]
Hi @XristophD 

Thanks for the request, we will consider it for a future release.

In the mean time you can implement this now using the [dependency inversion](https://developer.hashicorp.com/terraform/language/modules/develop/composition#dependency-inversion) technique using the module outputs. Does this help?

**Comment by XristophD** [comment]
@matt-FFFFFF , thank you for your input here. This helps, I already used dependency inversion to reach my desired goal.

**Comment by matt-FFFFFF** [comment]
Thanks @XristophD
