### ISSUE TITLE
Feature Request: Centralised Backup within a Landing Zone Subscription using single Recovery Vault

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#620]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

- The current backup policy included in the module (`Deploy-VM-Backup`) will configure new VMs to use a new recovery services vault in the same subscription.
- This means every single VM in the subscription will be assigned a unique recovery services vault, which is a nightmare from an operations point of view (backups need to be piecemeal located for each vm in it's own dedicated recovery vault)
- In addition, the current backup policy in the module doesn't allow customisation of the backup schedule on a per VM basis (or at least, this is not clear in the documentation)

#### Describe the solution you'd like

Ideally: 

1. Each newly created subscription should have a single recovery services vault created (perhaps by policy) for purpose of backup. 
2. Backup policy should then automatically configure each newly deployed VM in the subscription to use this recovery vault, along with a default policy.
3. There should be clear documentation in the wiki and examples on how to configure or enforce custom backup schedules on a per VM basis using tags to specify which backup-policy (schedule) is applied to a given vm.

Alternatives considered:

- Custom implemented terraform and backup solution design.
- Veeam backup solution for azure cloud

#### Additional context

- Enterprises usually require centralised management of backups. 
- In the context of Azure, few enterprise Cloud Operations teams would accept anything more than one Azure Recovery Services Vault in a subscription due to the management complexity. 
- Given this, the policy `Deploy-VM-Backup` should be optimised to use a single , ideally existing RSV. Moreover, this policy doesn't allow the user to specify a custom schedule in the `terraform-azurerm-caf-enterprise-scale` in the root module configuration (or at least there is no indication in the documentation on how this is done).
- The following policy might be a better fit if it can be included by default in the `terraform-azurerm-caf-enterprise-scale` module:

- Azure Policy Name:

"Configure backup on virtual machines with a given tag to an existing recovery services vault in the same location"

- Azure Policy Id:

`/providers/Microsoft.Authorization/policyDefinitions/345fa903-145c-4fe1-8bcd-93ec2adccde8`

**Comment by matt-FFFFFF** [comment]
Hi @archmangler 

We take the policy definitions from upstream in [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale). Please consider raising an issue there if you would like the policies changing.

In the mean time, you can implement this yourself by deploying a recovery services vault centrally and then adapting the policy definition. However you should be aware that the you will need multiple assignments for each location.

> Region: Select the geographic region for the vault. For you to create a vault to help protect any data source, the vault must be in the same region as the data source.

From https://learn.microsoft.com/en-us/azure/backup/backup-create-recovery-services-vault

Does this help?
