### ISSUE TITLE
Bug Report - Documentation issue on Module Variables link inner components

### ISSUE THREAD

**Issue by juvenalguevara** [Azure/terraform-azurerm-caf-enterprise-scale#625]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
v3.2.0

**terraform**: NA

**azure provider**: NA

**module**: NA

### Description
Inner links on https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/User-Guide are redirecting to the main page https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/

#### Describe the bug
If you want to check variable documents inside of https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/User-Guide, all inner links are redirecting to https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/

#### Steps to Reproduce

1. Go to https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/User-Guide
2. Click on any of the Modules Variables links. For instance: [archetype_config_overrides](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-archetype_config_overrides) 
3. You will get redirected to Home https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/

#### Screenshots
![Screenshot 2023-02-23 at 12 00 09](https://user-images.githubusercontent.com/69692129/220991196-c9cad4b0-8017-410d-ac78-be83190a61a3.png)

**Comment by matt-FFFFFF** [comment]
Thanks for the report, we will fix this
