### ISSUE TITLE
Deploy diagnostics policy assignment per subscription specific log analytics workspace

### ISSUE THREAD

**Issue by cveld** [Azure/terraform-azurerm-caf-enterprise-scale#626]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Our solution is deployed to four environments:
* dev
* test
* qa
* prod

Every environment has its own spoke subscription with its own dedicated log analytics workspace.

What is the easiest way to deploy the diagnostics policy definition set four times? Is that possible with this module with some configuration? 

Or should we just declare separate policy assignment resources. Is this even possible or would it conflict with the central log analytics workspace target in the management subscription.

**Comment by matt-FFFFFF** [comment]
Hi @cveld

Please can you explain a little further about your management group hierarchy?

The policy supplied with the module will create a diagnostic setting resource with a well-known name, therefore you can't assign it twice within the same scope unless you change the profile name property.

It is possible to send data from a resource to two different workspaces, but the diagnostic setting extension resources must have unique names.

Therefore assignming the same policy multiple times, with different parameters could be a solution here.

**Comment by matt-FFFFFF** [comment]
Hi @cveld

We do not plan to support subscription scope policy assignments in this module. We do have https://github.com/Azure/terraform-azurerm-lz-vending, where we have this on our backlog and is the most appropriate place to do this.

You can use that module with existing subscriptions or to vend new ones.
