### ISSUE TITLE
Broken links in Terraform Registry in release `v3.2.0`

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#637]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: n/a

**azure provider**: n/a

**module**: v3.2.0

#### Describe the bug

Since the latest release, links from [README.md](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/README.md) are no longer correctly rendering / working in the [Terraform Registry](https://registry.terraform.io/modules/Azure/caf-enterprise-scale/azurerm/latest).

This appears to be due to the addition of escaping for underscore `_` characters introduced in PR #624

#### Steps to Reproduce

1. Browse to [https://registry.terraform.io/modules/Azure/caf-enterprise-scale/azurerm/latest](https://registry.terraform.io/modules/Azure/caf-enterprise-scale/azurerm/latest) being sure to select release `v3.2.0` in the version dropdown.
2. Note that all links on the `Readme` tab are not working
3. Switch to a previous release and verify that they are OK
4. See changes implemented in PR #624

#### Screenshots

![image](https://user-images.githubusercontent.com/12268562/223543436-653b2fc2-36f9-4bff-8785-9f930d8cc01b.png)

#### Additional context

I'm not sure why, but native Github doesn't seem to suffer the same issue.

**Comment by matt-FFFFFF** [comment]
Thanks Kevin!

I think the registry has issues with the terraform-docs escaping. Will fix.
