### ISSUE TITLE
Bug Report (more of a question/observation than a bug) - Deploy-ASC-Monitoring Assignment

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-caf-enterprise-scale#640]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.9

**azure provider**: 3.47.0

**module**: 3.3.0

#### Describe the bug

Not so much a bug i dont think but more an observation
Every subsequent plan/apply following upgrade to 3.2.0/3.3.0 detects changes to the "Deploy-ASC-Monitoring" Policy Assignment due the jsonencoding of the Parameters.

It doesnt cause any problems as nothing is technically changing but be ideal if it can be overridden/removed.

#### Steps to Reproduce

1. any terraform plan or apply

#### Screenshots

<img width="618" alt="image" src="https://user-images.githubusercontent.com/42775203/224290719-05ce8dbc-0f95-429c-bc04-9f16b9435da0.png">

#### Additional context

I've done some searching around and I cant personally find a way of resolving this, any ideas?

**Comment by matt-FFFFFF** [comment]
I noticed this too today. Will research!

**Comment by matt-FFFFFF** [comment]
AB#27337

**Comment by birdnathan** [comment]
Strangely I can no longer replicate this behaviour. I thought perhaps a newer version of the azurem provider and or terraform had resolved it but seems not.

**Comment by matt-FFFFFF** [comment]
Thanks for reporting back @birdnathan 

/cc @jaredfholgate
