### ISSUE TITLE
Feature Request: Include policy changes in the next release of the module

### ISSUE THREAD

**Issue by chrholt** [Azure/terraform-azurerm-caf-enterprise-scale#642]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- In the policy for setting diagnostic settings on Databricks there is always non-compliance due to missing log categories.
  - [terraform-azurerm-caf-enterprise-scale/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_databricks.json](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_databricks.json)
- Include support for Flexible server in the policy for setting diagnostic settings on PostgreSQL
  - [terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_postgresql.json](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_postgresql.json)

#### Is your feature request related to a problem?

The policy for Databricks diagnostics is always non-compliant because the `existenceCondition` checks if all logs are enabled. The deployment of the diagnostic setting is missing the 5 latest log categories:
- Databricks Serverless Real-Time Inference
- Databricks Cluster Libraries
- Databricks Partner Hub
- Databricks Clam AV Scan
- Databricks Capsule8 Container Security Scanning Reports

#### Describe the solution you'd like

Include [these changes from the Enterprise-Scale project](https://github.com/Azure/Enterprise-Scale/issues/1221) in the next release of the module.

**Comment by matt-FFFFFF** [comment]
Hi @chrholt our policy update workflow is broken at the moment - we are fixing it!

Once we get the new definitions from upstream then we will create a minor release to fix this

@jtracey93

**Comment by matt-FFFFFF** [comment]
This is fixed now and the next major release will contain the new policies
