### ISSUE TITLE
Feature Request: Add  settings for configuring own RCG and rules in FW policy

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/terraform-azurerm-caf-enterprise-scale#643]
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Documentation on how to edit the default Firewall Policy so Rule Collection Groups etc... can be created
#### Is your feature request related to a problem?

Its currently unclear how to add RCG to FW policy that get created when you deploy the Firewall

#### Describe the solution you'd like

Update documentation or file/setting added to be able to update RCG in FW policy

**Comment by ricardoklein** [comment]
I am also trying to figure out how to link firewall rules to the spokes, specially to avoid them talking to each other (even if using a gateway for that).
From @matt-FFFFFF 's comment, I understand that the actual firewall rules should be managed outside this module, and I can totally agree with that. My question is how do I link the firewall with the subnets, is that also something that needs to be done completely outside the module? Or there are ways to do this link? Will that be done by just enforcing the security group into the subnets?

**Comment by matt-FFFFFF** [comment]
Hi @ricardoklein 

In order to configure the spoke virtual networks then you can use the [lz-vending](https://github.com/Azure/terraform-AzureRM-lz-vending) module.

This allows you to configure peering and will in the future allow you to create a route table.

Is this what you mean?
