### ISSUE TITLE
Feature Request: how to add subscriptions to Sandbox and Decomissioned MGs

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/terraform-azurerm-caf-enterprise-scale#644]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Update Documentation on where and how to add Subscription IDs for Sandbox and Decommissioned MGs so subscriptions are auto placed in MG. Currently have this for Landing Zone MG but not For Sandbox and Decommissioned

#### Is your feature request related to a problem?

Its currently unclear on where to put config for subscription ids that need to go under Sandbox and Decommissioned

#### Describe the solution you'd like

Update documentation and/or code that explain where and how this should be one

**Comment by matt-FFFFFF** [comment]
Hi @ashley-kainos 

See this comment
