### ISSUE TITLE
Feature Request: to add option to deploy Sentinel if required

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/terraform-azurerm-caf-enterprise-scale#645]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add Option to Deploy Sentinel with some basic Data Connectors

#### Describe the solution you'd like

To add an option to install Sentinel if user wishes, but can can be set not to install in not required

**Comment by matt-FFFFFF** [comment]
Hi @ashley-kainos

Have you seen this variable?

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale#-configure_management_resources

You can use the module outputs to deploy the sentinel data connectors outside the module
