### ISSUE TITLE
Unable to change policy assignment parameters

### ISSUE THREAD

**Issue by ptsouk** [Azure/terraform-azurerm-caf-enterprise-scale#648]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.4.2

**azure provider**: 3.45.0

**module**: 3.3.0

### Description

Unable to change policy assignment parameters using an archetype extension.

#### Describe the bug

I am following the doc here: [expand an existing archetype](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions#to-enable-the-extension-function) to set parameter values for Policy Assignments, via expanding an existing archetype.
The archetype I am expanding is the [`es_identity`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/archetype_definitions/archetype_definition_es_identity.tmpl.json) and I am using the following `archetype_extension_es_identity.json` file in `archetype_extensions` folder :

```json
{
    "extend_es_identity": {
        "policy_assignments": [],
        "policy_definitions": [],
        "policy_set_definitions": [],
        "role_definitions": [],
        "archetype_config": {
          "parameters": {
            "Deny-Subnet-Without-Nsg": {
              "effect": "Audit"
            }
          },
          "access_control": {}
        }
      }
}
```

The policy assignment [`Deny-Subnet-Without-Nsg`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deny_subnet_without_nsg.json) is a custom policy included in the built-in archetype definition [`es_identity`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/archetype_definitions/archetype_definition_es_identity.tmpl.json).

> **NOTE:** I am using the `custom_landing_zones` block to define subscription placements :
>
```hcl
"${local.root_id}-identity" = {
      display_name               = "Identity"
      parent_management_group_id = "${local.root_id}-platform"
      subscription_ids = [
        local.subscription_id_identity1,
        local.subscription_id_identity2
      ]
      archetype_config = {
            archetype_id = "es_identity"
            parameters = {}
        }
        access_control = {}
      }
```

The workaround I have is to use the `custom_landing_zones` block to also define the parameter :

```hcl
    "${local.root_id}-identity" = {
      display_name               = "Identity"
      parent_management_group_id = "${local.root_id}-platform"
      subscription_ids = [
        local.subscription_id_identity1,
        local.subscription_id_identity2
      ]
      archetype_config = {
        archetype_id = "es_identity"
        parameters = {
          Deny-Subnet-Without-Nsg = {
            effect = "Audit"
           }
        }
        access_control = {}
      }
    }
```

I would expect that extending the archetype would suffice, and have one place to declare the policy assignments.

#### Steps to Reproduce

1. use `custom_landing_zones` using an archetype_id without any policy assignment parameters
2. extend the archetype to input policy assignment parameters
3. the parameter remains the policy default

#### Screenshot

![Screenshot1](https://user-images.githubusercontent.com/22319275/225958560-fb4f14da-ee02-499d-9bd3-997b5fce2b38.png)

#### Additional context

I tried to remove the archetype_id block in `custom_landing_zones`, but it errors out:

![Screenshot2](https://user-images.githubusercontent.com/22319275/225959553-15576f5b-7eb5-424e-afcf-6f48a9569938.png)

**Comment by luke-taylor** [comment]
Hey @ptsouk, thank you for bringing this to our attention using the `archetype_extension` should work as is detailed here [[Examples] Set parameter values for Policy Assignments](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Set-parameter-values-for-Policy-Assignments). Running the `archetype_extension` case myself I have noticed that using your example for `es_landing_zones` (Also contains that specific policy) works fine, but using `es_identity` fails. 

In the mean time, it will be best to use the `archetype_config_overrides` parameter since the `identity` archetype already exists by default. Try this instead:
```hcl
  archetype_config_overrides = {
  
   identity = {
      archetype_id = "es_identity"
      parameters = {
        Deny-Subnet-Without-Nsg = {
          effect = "Audit"
        }
      }
      access_control = {
      }
    }
  }
```

**Comment by ptsouk** [comment]
Hi @luke-taylor , thank you for the reply. I can confirm in my case that using the `archetype_config_overrides` option is also not working.

**Comment by ptsouk** [comment]
The proposed workaround with the `archetype_config_overrides` actually worked after removing the identity block from the `custom_landing_zones`. 
Thx!
