### ISSUE TITLE
custom_settings_by_resource_type issue when renaming vpn/expressroute gateways

### ISSUE THREAD

**Issue by gbr759** [Azure/terraform-azurerm-caf-enterprise-scale#649]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

3.3.0

**terraform**: 1.4.1

**azure provider**:  3.35.0

**module**: 3.3.0

#### Describe the bug

I'm definitely missing something here but I'm going a little blind looking at this now.  I have the `custom_settings_by_resource_type` settings configured for my connectivity resources, they are as follows:

```
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          connectivity = {
            (var.primary_region) = {
              name = "rg-connectivity-${var.environment}-${var.primary_region}-01"
            }
          }
          dns = {
            (var.primary_region) = {
              name = "rg-dns-${var.environment}-${var.primary_region}-01"
            }
          }
        },
        azurerm_firewall = {
          virtual_hub = {
            (var.primary_region) = {
              name = "fw-hub-${var.environment}-${var.primary_region}-01"
            }
          }
        },
        azurerm_virtual_network_gateway = {
          expressroute = {
            (var.primary_region) = {
              name = "ergw-hub-${var.environment}-${var.primary_region}-01"
            }
          }
          vpn = {
            (var.primary_region) = {
              name = "vpngw-hub-${var.environment}-${var.primary_region}-01"
            }
          }
        },
        azurerm_virtual_network = {
          connectivity = {
            (var.primary_region) = {
              name = "vnet-hub-${var.environment}-${var.primary_region}-01"
            }
          }
        }
      }
    }
```
The issue I have is that the custom names work fine for the resources groups and the VNET, the VPN and ExpressRoute gateways have their default names allocated by the module, even though I double-checked that the advanced settings do support custom naming for these resources, and I've copied the code from #332 with no joy.

I'm sure it's something simple that I'm missing, any help is appreciated.

**Comment by birdnathan** [comment]
You advanced block should read:

connectivity_vpn = {
            (var.primary_region) = {
              name = "vpngw-hub-${var.environment}-${var.primary_region}-01"
            }
          }

**Comment by matt-FFFFFF** [comment]
Hi @gbr759 has this solved your issue?

**Comment by gbr759** [comment]
That works great, thanks for that @birdnathan
