### ISSUE TITLE
Bug Report: Clarification on expected behavior of policy "Deploy-Private-DNS-Zones"

### ISSUE THREAD

**Issue by kevinmccurdybrd** [Azure/terraform-azurerm-caf-enterprise-scale#650]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.4.0

**azure provider**: 3.43

**module**: 3.3.0

#### Describe the bug

First of all thank you so much for this module as well as the lz-vending module. Super grateful these resources exist. Well done.

Our scenario is as follows:

- Existing tenant that had no CAF implementation. We've gone ahead and provisioned the tenant using mostly defaults. We're using all of Connectivity, Management and Identity. (our baseline was based off of your 400-Orchestration example). Env uses Azure vWAN w/ firewall. We're also using the lz-vending module, so we've disabled strict subscription association.
- We're using private endpoints per recommendation, however we're not seeing the records deployed as expected by the DINE  policies defined in "Deploy-Private-DNS-Zones" initiative.
- Checking the initiative, I see it is set to enforcementType: DoNotEnforce. (screenshot attached) This is the unexpected bit, as I would have expected this to evaluate to enforce to properly deploy the A records for PE's defined in the landing zones. If this is expected by design, please provide insight as to how this is designed, and best mechanism to overcome (I would expect via archetype override?)
- If I change the initiative to enforce, as one would expect the next time the CAF is applied it wants to revert this change, so it's clearly operating either mostly or completely as intended.

Thanks in advance for your help, again our organization appreciates your efforts here.

#### Steps to Reproduce

1. Apply CAF Terraform
2. Observe that  Deploy-Private-DNS-Zones is set to DoNotEnforce

#### Screenshots

![image](https://user-images.githubusercontent.com/101918588/226720653-819b72e0-367f-4d43-9cea-172757391d1e.png)

#### Additional context

I apologize if this submission is incomplete, but hopefully a good starting point. If additional information is required please advise and I will get back to you as soon as possible.

**Comment by kevinmccurdybrd** [comment]
I also should add that I had to manually assign DNS role as I had a similar experience to #615. I doubt it's related, but figured I'd mention it as well.

**Comment by matt-FFFFFF** [comment]
Hi @kevinmccurdybrd 

Looking at this we expect the default effect to be DeployIfNotExists.

Can you post your module config so that we can see why this might be happening?

**Comment by kevinmccurdybrd** [comment]
When I manually flip the slider on the initiative, and then run a tf plan, i see this:

module.core.module.alz.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/bird-corp/providers/Microsoft.Authorization/policyAssignments/Deploy-Private-DNS-Zones"] will be updated in-place  ~ resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
      ~ enforce              = true -> false

Hopefully this will help narrow down where this is coming from. Just to reiterate, we're basically using the 400-orch example mostly as-is.

**Comment by matt-FFFFFF** [comment]
Hi @kevinmccurdybrd I have had a look into this and you need to enable the DNS setting for the connectivity module that is responsible for deploying the Azure policy.

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/779bf6a5d450bc20179d2d9e9af33bc1002b1a65/modules/connectivity/locals.tf#L159

**Comment by matt-FFFFFF** [comment]
and here, sorry:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/779bf6a5d450bc20179d2d9e9af33bc1002b1a65/modules/connectivity/locals.tf#L1779-L1782

**Comment by kevinmccurdybrd** [comment]
Here's our current settings.connectivity.tf for the connectivity module. 

```
# Configure custom connectivity resources settings
locals {
  configure_connectivity_resources = {
    settings = {
      # Create two hub networks with hub mesh peering enabled
      # and link to DDoS protection plan if created
      hub_networks = [
      ]
      #create an Virtual WAN resources
      vwan_hub_networks = [
        {
          enabled = true
          config = {
            address_prefix = "10.128.0.0/23"
            location       = var.primary_location
            sku            = "Standard"
            routes         = []
            expressroute_gateway = {
              enabled = false
              config = {
                scale_unit = 1
              }
            }
            vpn_gateway = {
              enabled = true
              config = {
                bgp_settings       = []
                routing_preference = "Microsoft Network"
                #initial scale units to get to 1Gbps traffic.
                scale_unit = 2
              }
            }
            azure_firewall = {
              enabled = true
              config = {
                enable_dns_proxy              = true
                dns_servers                   = []
                sku_tier                      = "Standard"
                base_policy_id                = ""
                private_ip_ranges             = []
                threat_intelligence_mode      = "Alert"
                threat_intelligence_allowlist = []
                availability_zones = {
                  zone_1 = true
                  zone_2 = true
                  zone_3 = true
                }
              }
            }
            spoke_virtual_network_resource_ids        = []
            secure_spoke_virtual_network_resource_ids = []
            enable_virtual_hub_connections            = false
          }
        },
      ]
      # Enable DDoS protection plan in the primary location
      ddos_protection_plan = {
        enabled = var.enable_ddos_protection
      }
      # DNS will be deployed with default settings
      dns = {
        enabled = true
        config = {
          location = ""
          enable_private_link_by_service = {
            azure_api_management                 = true
            azure_app_configuration_stores       = true
            azure_arc                            = true
            azure_automation_dscandhybridworker  = true
            azure_automation_webhook             = true
            azure_backup                         = true
            azure_batch_account                  = true
            azure_bot_service_bot                = true
            azure_bot_service_token              = true
            azure_cache_for_redis                = true
            azure_cache_for_redis_enterprise     = true
            azure_container_registry             = true
            azure_cosmos_db_cassandra            = true
            azure_cosmos_db_gremlin              = true
            azure_cosmos_db_mongodb              = true
            azure_cosmos_db_sql                  = true
            azure_cosmos_db_table                = true
            azure_data_explorer                  = true
            azure_data_factory                   = true
            azure_data_factory_portal            = true
            azure_data_health_data_services      = true
            azure_data_lake_file_system_gen2     = true
            azure_database_for_mariadb_server    = true
            azure_database_for_mysql_server      = true
            azure_database_for_postgresql_server = true
            azure_digital_twins                  = true
            azure_event_grid_domain              = true
            azure_event_grid_topic               = true
            azure_event_hubs_namespace           = true
            azure_file_sync                      = true
            azure_hdinsights                     = true
            azure_iot_dps                        = true
            azure_iot_hub                        = true
            azure_key_vault                      = true
            azure_key_vault_managed_hsm          = true
            azure_kubernetes_service_management  = true
            azure_machine_learning_workspace     = true
            azure_managed_disks                  = true
            azure_media_services                 = true
            azure_migrate                        = true
            azure_monitor                        = true
            azure_purview_account                = true
            azure_purview_studio                 = true
            azure_relay_namespace                = true
            azure_search_service                 = true
            azure_service_bus_namespace          = true
            azure_site_recovery                  = true
            azure_sql_database_sqlserver         = true
            azure_synapse_analytics_dev          = true
            azure_synapse_analytics_sql          = true
            azure_synapse_studio                 = true
            azure_web_apps_sites                 = true
            azure_web_apps_static_sites          = true
            cognitive_services_account           = true
            microsoft_power_bi                   = true
            signalr                              = true
            signalr_webpubsub                    = true
            storage_account_blob                 = true
            storage_account_file                 = true
            storage_account_queue                = true
            storage_account_table                = true
            storage_account_web                  = true
          }
          private_link_locations                                 = []
          public_dns_zones                                       = []
          private_dns_zones                                      = []
          enable_private_dns_zone_virtual_network_link_on_hubs   = true
          enable_private_dns_zone_virtual_network_link_on_spokes = true
          virtual_network_resource_ids_to_link                   = []
        }
      }
    }
    # Set the default location
    location = var.primary_location
    # Create a custom tags input
    tags = var.connectivity_resources_tags
  }
}

```

First off, I apologize if I didn't provide enough detail, if there is a better mechanism to share our config with you, by all means I am open to it, there's a lot of config for this module and I wasn't quite sure what you needed. 

With regards to what you've indicated, is this in addition to what we've already set above? I would expect dns enablement to be handled by the above? I see all the policies in azure,  and I see a policy initiative that contains all the Private DNS DINE policies. Everything looks right, it's just the initiative is set to DoNotEnforce instead of Enforce. Apologies in advance if I'm off base here, I'm still pretty new to TF.

**Comment by kevinmccurdybrd** [comment]
Hi Matt,

Appreciate your patience as we work through this. 

Just to re-iterate, we've used your 400 - Orchestration github example [here](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-orchestration) exactly.

Our orchestration terraform main.tf looks like this:

<pre>
# Get the current client configuration from the AzureRM provider

data "azurerm_client_config" "current" {}

# Logic to handle 1-3 platform subscriptions as available

locals {
  subscription_id_core         = coalesce(var.subscription_id_core, local.subscription_id_management)
  subscription_id_connectivity = coalesce(var.subscription_id_connectivity, local.subscription_id_management)
  subscription_id_identity     = coalesce(var.subscription_id_identity, local.subscription_id_management)
  subscription_id_management   = coalesce(var.subscription_id_management, data.azurerm_client_config.current.subscription_id)
}

# The following module declarations act to orchestrate the
# independently defined module instances for core,
# connectivity and management resources

module "connectivity" {
  source = "./modules/connectivity"

  deploy_connectivity_resources = var.deploy_connectivity_resources

  connectivity_resources_tags  = var.connectivity_resources_tags
  enable_ddos_protection       = var.enable_ddos_protection
  default_location             = var.default_location
  primary_location             = var.primary_location
  root_id                      = var.root_id
  secondary_location           = var.secondary_location
  subscription_id_connectivity = local.subscription_id_connectivity
}

module "management" {
  source = "./modules/management"

  deploy_management_resources = var.deploy_management_resources

  email_security_contact     = var.email_security_contact
  log_retention_in_days      = var.log_retention_in_days
  management_resources_tags  = var.management_resources_tags
  default_location           = var.default_location
  primary_location           = var.primary_location
  root_id                    = var.root_id
  subscription_id_management = local.subscription_id_management
}

module "core" {
  source = "./modules/core"

  deploy_identity_resources = var.deploy_identity_resources

  <b>configure_connectivity_resources = module.connectivity.configuration
  configure_management_resources   = module.management.configuration</b>
  default_location                 = var.default_location
  primary_location                 = var.primary_location
  root_id                          = var.root_id
  root_name                        = var.root_name
  secondary_location               = var.secondary_location
  subscription_id_core             = local.subscription_id_core
  subscription_id_connectivity     = local.subscription_id_connectivity
  subscription_id_identity         = local.subscription_id_identity
  subscription_id_management       = local.subscription_id_management
  deploy_online_landing_zones      = var.deploy_online_landing_zones
  deploy_corp_landing_zones        = var.deploy_corp_landing_zones
  strict_subscription_association  = var.strict_subscription_association
  archetype_config_overrides       = var.archetype_config_overrides
}
</pre>

If I'm understanding the flow of resources correctly, the output of the connectivity module should be ingested by the core module via the bolded code above. Is further duplication of the connectivity resources config required? Again, my apologies for the repetition in my questioning and perhaps my overall clarity, but I feel like we're following the example precisely, and not seeing the desired outcome.

Thanks again in advance for your assistance.

**Comment by matt-FFFFFF** [comment]
Hi @kevinmccurdybrd,

It does seem to look ok, however I'd still recommend setting the deploy DNS settings in a new object for the core module, just to rule anything out.
