### ISSUE TITLE
"local.azurerm_role_assignment_enterprise_scale will be known only after apply" when assigning roles with "access_control"

### ISSUE THREAD

**Issue by sjovang** [Azure/terraform-azurerm-caf-enterprise-scale#651]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

```
➜ terraform --version
Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/azure/azapi v1.4.0
+ provider registry.terraform.io/hashicorp/azuread v2.36.0
+ provider registry.terraform.io/hashicorp/azurerm v3.48.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
```
v.3.3.0 of terraform-azurerm-caf-enterprise-scale

#### Describe the bug

Not sure if this is a bug, a limitation in Terraform, or an issue that is better suited for a feature request. The use case is that we have split the deployment of ALZ into two separate Terraform deployments:
1. Deploy the core architecture (management groups, platform components, policy definitions etc.)
2. Deploy an arbitrary number of custom landing zones under the <root_id>-landing-zones management group

To deploy these custom landing zones we also wish to create groups in Azure AD and assign built-in roles to the management group. This fails with the following error message when running terraform plan/apply:

```
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/example_landing_zones.azure_landing_zones/resources.role_assignments.tf line 2, in resource "azurerm_role_assignment" "enterprise_scale":
│    2:   for_each = local.azurerm_role_assignment_enterprise_scale
│     ├────────────────
│     │ local.azurerm_role_assignment_enterprise_scale will be known only after apply
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of
│ this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
```

I am curious if this is a limitation in Terraform itself, a bug, or if there exist some nice examples on how to get this working? (without  running terraform apply -target first or splitting the group creation out to a different deployment and either hardcoding object_ids or read them with `data "azuread_group" "example" [}`

#### Steps to Reproduce

```
resource "azuread_group" "owner" {
  display_name     = "${var.landing_zone_name}-owner"
  description      = "Grant Owner role on ${var.landing_zone_name} environment"
  security_enabled = true
}

module "azure_landing_zones" {
  source                    = "Azure/caf-enterprise-scale/azurerm"
  version                   = "3.3.0"
  [...]

  custom_landing_zones = {
    "${var.root_id}-${lower(var.landing_zone_name)}" = {
      display_name               = "${var.root_name} - ${var.landing_zone_name}"
      parent_management_group_id = var.parent_management_group_id
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "custom_landingzone"
        parameters     = {}
        access_control = {
          Owner = [ azuread_group.owner.object_id ]
        }
      }
    }
}
```

**Comment by sjovang** [comment]
Thanks for the quick response and clarifications. Using the outputs and do role assignments outside of the module was my backup plan as well, so good to know I was on the right track =)

**Comment by matt-FFFFFF** [comment]
Closing for now but tagging as enhancement to track in v.next
