### ISSUE TITLE
Bug Report - Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by ctahok** [Azure/terraform-azurerm-caf-enterprise-scale#652]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.3.7

**azure provider**: >= 3.19.0

**module**: 3.2.0

#### Describe the bug

**c:\TFS\terraform-azurerm-caf-enterprise-scale-1\examples\400-multi-with-orchestration>terraform init>** throws an "**Error: Failed to query available provider packages**"

#### Steps to Reproduce

1. Clone the repo
2. Run C:\TFS\terraform-azurerm-caf-enterprise-scale-1\examples\400-multi-with-orchestration> terraform init
3. Error: Failed to query available provider packages

#### Screenshots

![image](https://user-images.githubusercontent.com/17162642/226953672-d9b1d119-1517-47e3-a0ef-eb8e7de3f977.png)

#### Additional context

Trying to deploy \400-multi-with-orchestration scenario and when running _terraform init_ it errors:

`C:\TFS\terraform-azurerm-caf-enterprise-scale-1\examples\400-multi-with-orchestration> terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 3.19.0, 3.19.0, >= 3.35.0"...
- Finding hashicorp/random versions matching ">= 3.1.0"...
- Finding azure/azapi versions matching ">= 1.3.0"...
- Finding hashicorp/time versions matching ">= 0.7.0"...
- Installing hashicorp/random v3.4.3...
- Installed hashicorp/random v3.4.3 (signed by HashiCorp)
- Installing azure/azapi v1.4.0...
- Installed azure/azapi v1.4.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
- Installing hashicorp/time v0.9.1...
- Installed hashicorp/time v0.9.1 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/azurerm: no available releases match the given constraints >= 3.19.0, 3.19.0, >= 3.35.0`

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by matt-FFFFFF** [comment]
Thanks. We recently raised the minimum provider version and need to update the example.

If you change the required providers for AzureRM to >= 3.35.0 and remove the static constraint of 3.19.0 then it should work

**Comment by matt-FFFFFF** [comment]
Fixed in all examples
