### ISSUE TITLE
Feature Request - Parameterize notScopes or loosen array restriction at template file

### ISSUE THREAD

**Issue by jckeme-rs** [Azure/terraform-azurerm-caf-enterprise-scale#654]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Add a way to parameterize notScopes for policy assignments
This request is related to the following issue:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/96

At the moment, in order to accommodate more than a single resource exclusion from a policy assignment, the policy assignment template json will need to have these entries included in the template json file: 

example from issue#96:
```
"notScopes": [
      "${root_scope_resource_id}-platform",
      "${root_scope_resource_id}-sandboxes"
    ],
```

If we were to leverage template_file_variables, notScopes within the template file must be in the following state:
```
"notScopes": ["${variable_for_substitution"],
```
however the variable_for_substitution can only be defined as a single string. 

i.e.
```
template_file_variables = {
    variable_for_substitution = "${var.my_string_variable}",
}
```

Anything outside of a single string will need a data type that can act as a wrapper around the information being passed in, and this doesn't work with notScopes because the notScopes will end up like this:

for example, a list of string
```
"notScopes": [["list","of","string"]],
```

#### Describe the solution you'd like

Is it possible to loosen the requirement to enable a notScope list be passed in from the core module, similar to how policy parameters are being passed?

Hence we might be able to leverage terraform [for] loops or create a notScopes array outside the template and then pass that into the template as a variable.

i.e.
```
"notScopes": "${some_list_of_scopes_to_be_excluded_from_policy}",
```

By doing this, it will now be possible to fulfill the list of strings requirement. 

On a side note, is it also possible to use template_file_variables to pass in other data types? e.g. a list of string? It would definitely be helpful in a situation like this.

**Comment by matt-FFFFFF** [comment]
Thank you for reporting this - we will add it to the backlog for the next version

**Comment by jckeme-rs** [comment]
Hi @krowlandson , thank you for the feedback. 
I'll give this a try in the coming week and will let you know what the outcome is.

**Comment by jckeme-rs** [comment]
Hi @krowlandson 

Thanks for verifying how this should work. 

We have applied the policy in this manner and it worked as expected. 

As you suggested, we made the policy assignment a template in itself and then created a notScopes loop. 

FileName: **policy_assignment_policy_name.json.tftpl**
```
${jsonencode({
  "name": "Policy-Name",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2021-06-01",
  "properties": {
    "description": "Policy-Description-Here",
    "displayName": "Policy-DisplayName-Here",
    "notScopes": [for notscope in "${template_file_variable_with_list_of_strings}" : "${notscope}"],
    "parameters": {
      "SomeFancyParameter": {
        "value": null
      }
    },
    "policyDefinitionId": "/providers/Microsoft.Authorization/policySetDefinitions/<policy-set-definition-id>",
    "scope": "${current_scope_resource_id}",
    "enforcementMode": null
  },
  "location": "${default_location}",
  "identity": {
    "type": "SystemAssigned"
  }
})}
```

And in this case, the template file variable is a list being passed in from a local

```
template_file_variables = {
    template_file_variable_with_list_of_strings = "${local.list_of_string_with_nonscopes}"
}
```

```
locals {
  provider_path = {
    management_groups = "/providers/Microsoft.Management/managementGroups/"
    role_assignment   = "/providers/Microsoft.Authorization/roleAssignments/"
  }

  list_of_string_with_nonscopes = [
        "${local.provider_path.management_groups}lz-sandbox",
        "${local.provider_path.management_groups}lz-connectivity",
    ]
}
```
