### ISSUE TITLE
Terraform plan shows "Error: Provider configuration not present"

### ISSUE THREAD

**Issue by airwalk-neilashbysenior** [Azure/terraform-azurerm-caf-enterprise-scale#656]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.1

**azure provider**: 3.35.0

**module**: 3.3.0

### Summary

Once `terraform init` is successful, the first plan results in the error below for lots of different modules/resources.

####
```
Error: missing provider provider["registry.terraform.io/hashicorp/azurerm"]
```

`terraform providers` shows the below
```
Providers required by configuration:
.
└── module.caf-enterprise-scale
    ├── provider[registry.terraform.io/hashicorp/time] >= 0.7.0
    ├── provider[registry.terraform.io/hashicorp/random] >= 3.1.0
    ├── provider[registry.terraform.io/azure/azapi] >= 1.3.0
    ├── provider[registry.terraform.io/hashicorp/azurerm] >= 3.35.0
    ├── module.management_resources
    ├── module.role_assignments_for_policy
    │   └── provider[registry.terraform.io/hashicorp/azurerm] >= 3.19.0
    ├── module.connectivity_resources
    ├── module.identity_resources
    └── module.management_group_archetypes
```

#### Steps to Reproduce

1. Run `terraform init`
2. Run `terraform plan`

**Comment by matt-FFFFFF** [comment]
Hi @airwalk-neilashbysenior 

I cannot re-produce this, can you give more information on your setup? Proxies, TF Cloud, etc.
