### ISSUE TITLE
Documentation Request: Better explanation of the archetype_extension_es_* files

### ISSUE THREAD

**Issue by tlfzhylj** [Azure/terraform-azurerm-caf-enterprise-scale#657]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

I'd wish the documentation explained the files `archetype_extension_es_landing_zones.tmpl.json` and `archetype_extension_es_root.tmpl.json` and had a dedicated page for that in the Wiki. These two files are mentioned in the Wiki

Also, if I want to assign a policy to the platform management group, is the file it's looking for `archetype_extension_es_platform.tmpl.json`? I see no mention of other archetype_extension_es_* files in the documentation.

#### Describe the solution you'd like

A dedicated Wiki page explaining all the posibilities with the archetype_extension_es_* files.

**Comment by tlfzhylj** [comment]
After a little troubleshooting I see that the files also have values in the json file called "extend_es_landing_zones" and "extend_es_root". Does it matter at all what the files are actually called?

**Comment by jtracey93** [comment]
Hey @tlfzhylj,

Please review the following existing docs and let us know if these cover your questions:

- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions
- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions

Thanks

**Comment by tlfzhylj** [comment]
Yes, it does. Thank you for pointing me to the correct documentation.
