### ISSUE TITLE
VPNGW1 doesn't get deployed with static PIP

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/terraform-azurerm-caf-enterprise-scale#661]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.4.2

**azure provider**: 3.49.0

**module**: 3.3.0

#### Describe the bug

Customer is running into a challenge while deploying with vpngw1 selected as the sku for the vpn gateway, in turn the public ip getting configured is with Basic SKU and dynamic allocation, customer wants the PIP to be static regardless of whether the sku is basic or standard, all the while keeping the gateway sku to vpngw1, it seem the code self determines this (screen shot#1) and doesn't have a parameter to specify otherwise unless it could be done through the advance block on which guidance would be appreciated. It seems this is achievable through Portal
#### Steps to Reproduce

1. Set gateway_sku_vpn = "vpngw1" in settings.connectivity.tf

#### Screenshots

![MicrosoftTeams-image](https://user-images.githubusercontent.com/79409563/228060836-99c5ef19-bdbf-48a1-a506-d6b65ddb26fb.png)

**Comment by matt-FFFFFF** [comment]
Hi @mbilalamjad 

What's the Terraform resource reference for the public IP? I can then help guide the use of the advanced block
