### ISSUE TITLE
Bug Report: Security Center settings in management really applies to core

### ISSUE THREAD

**Issue by tlfzhylj** [Azure/terraform-azurerm-caf-enterprise-scale#664]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**module**: 3.3.0

#### Describe the bug

If I split the module in three different Terraform projects, like you describe in [Deploy using multiple module declarations with remote state](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-remote-state), the settings under `security_center` for the Management part in the don't apply.

These settings needs to be set under the Core part, because these settings are policies and nothing to do with Management.

#### Steps to Reproduce

1. Call the module with `deploy_core_landing_zones = false` and `deploy_management_resources = true`.
2. Try to set the following:
    ```hcl
      configure_management_resources = {
        settings = {
          security_center = {
            config = {
              email_security_contact = "mail@mail.com"
            }
          }
        }
    ```
3. Try to plan, and you can see that no email address is planned set.
4. If you do the same where you deploy core landing zones where `deploy_core_landing_zones = true` and the Azure policies are set, you can see that the email address will be set in a Azure policy.
5. The same is true for the other Defender for cloud settings under `security_center` like `enable_defender_for_app_services`, `enable_defender_for_key_vault` and so on.

**Comment by luke-taylor** [comment]
Hello @tlfzhylj! 

In [this](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-remote-state#managementsettingsmanagementtf) section from the document you mentioned, it is highlighted that management configuration is shared by the core module:

 _This ensures that managed parameters for policies deployed by the core module instance are configured with values correctly reflecting the resources deployed by this module instance._
 
 As you can see for the example from the core module:
 ```
 module "alz" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "<version>" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  # Base module configuration settings
  root_parent_id = data.azurerm_client_config.current.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.module}/lib"

  # Enable creation of the core management group hierarchy
  # and additional custom_landing_zones
  deploy_core_landing_zones = true
  custom_landing_zones      = local.custom_landing_zones

  # Configuration settings for identity resources is
  # bundled with core as no resources are actually created
  # for the identity subscription
  deploy_identity_resources    = true
  configure_identity_resources = local.configure_identity_resources
  subscription_id_identity     = var.subscription_id_identity

  # The following inputs ensure that managed parameters are
  # configured correctly for policies relating to connectivity
  # resources created by the connectivity module instance and
  # to map the subscription to the correct management group,
  # but no resources are created by this module instance
  deploy_connectivity_resources    = false
  configure_connectivity_resources = data.terraform_remote_state.connectivity.outputs.configuration
  subscription_id_connectivity     = data.terraform_remote_state.connectivity.outputs.subscription_id

  # The following inputs ensure that managed parameters are
  # configured correctly for policies relating to management
  # resources created by the management module instance and
  # to map the subscription to the correct management group,
  # but no resources are created by this module instance
  deploy_management_resources    = false
  configure_management_resources = data.terraform_remote_state.management.outputs.configuration
  subscription_id_management     = data.terraform_remote_state.management.outputs.subscription_id

}
```
The same data from the management module (Assumed to have been deployed before the core module) for the `configure_management_resources` parameter is passed into to core module.

**Comment by tlfzhylj** [comment]
Ah ok, I missed that one. Thank you.
