### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jkatergaris** [Azure/terraform-azurerm-caf-enterprise-scale#665]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?
No. More of a question about how to do things correctly for spoke vnets. The deploy connectivity with custom settings has a hub_networks block that does this for the hub vnet. Let's say you also deploy the corp landing zone, how would you create a spoke vnet there?

#### Describe the solution you'd like

A documented example of how to get this done in a similar manner as the hub_network

I suspect assigning the "Deploy vnet and peer to hub" policy to the corp lz, by extending the definition, will get this done, but I'm not sure I like this as much. I am confused about how it would work if you need 3 environments/subscriptions in corp and all of them need a different vnet

#### Additional context
Ultimately, I'd like to achieve the below setup with a spoke vnet for each subscription/environment or app 
![image](https://user-images.githubusercontent.com/17388323/229051052-67ac9766-94ee-45c5-8737-864ff6675bbc.png)

**Comment by birdnathan** [comment]
@jkatergaris - With the subscription vending module.
https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-our-new-subscription-vending-iac-modules-for-bicep/ba-p/3770617
https://github.com/Azure/terraform-azurerm-lz-vending

**Comment by matt-FFFFFF** [comment]
Hi @jkatergaris  - yes we would recommend looking at subscription vending modules. Does this answer your issue?

**Comment by jkatergaris** [comment]
Thanks for the pointer. From a quick first look, I believe this will be the way to go.

**Comment by matt-FFFFFF** [comment]
Thanks. Closing for now
