### ISSUE TITLE
Remove Owner access on unmanged subscriptions? Minimum privileges needed for deployment.

### ISSUE THREAD

**Issue by binaryPUNCH** [Azure/terraform-azurerm-caf-enterprise-scale#668]
Hi. 

Is it possible to ensure the service principal needed for enterprise-scale does not have Owner privileges over all subscriptions? We use `strict_subscription_association = false` as we use Azure Functions to provision subscriptions, so we only use this module for the management group hierarchy and policy assignments.

The service principal is protected by our CI/CD, GitHub Actions with federated credentials to only run on the right branch, but it would be better if we can unassign it entirely as Owner from all our downstream subscriptions. It is currently inherited from the root management group so is there a clever way to reduce the needed permissions to operate our landingzones?

[Module permissions documentation](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Module-Permissions)

**Comment by matt-FFFFFF** [comment]
Hi, unfortunately there is no was to prevent permission inheritance from MG to sub.

**Comment by matt-FFFFFF** [comment]
> > Hi, unfortunately there is no was to prevent permission inheritance from MG to sub.
> 
> 
> 
> Hi Matt! Thanks for the feedback. That’s what I thought. Is it possible to remove Owner access from the root after it has been deployed? Enterprisescale “just” needs access to write policies and Contributor on the management subscription, no?

It depends what you use the module for. In order to create new MGs we need management group contributor. This will effectively grant write access to all management groups.

**Comment by binaryPUNCH** [comment]
We will rarely create new management groups. It is only policy creation and assignments at this point. 

So should we be able to limit the access to `Resource Policy Contributor` and `Management Group Contributor`?

**Comment by matt-FFFFFF** [comment]
Hi @binaryPUNCH 

The issue you will find is that policy assignments also require the ability to create role assignments.

This means that you have to grant the identity user access administrator, which is effectively owner anyway as you can grant yourself a role assignment.

The MG contributor works because the identity that creates the MG is the owner of it.

**Comment by binaryPUNCH** [comment]
Thanks for the feedback this is very helpful and will save me time from coming to the same conclusion by trial and error. This is a bit tricky. I believe switching to User Access Administrator is still an improvement, as it can at least protect us against faulty code that could cause tenant-wide issues. But ofc a malicious user could still use the service principal to assign themself Contributor. For that, we have SIEM and activity log monitoring.

Thanks for the input once again, we will do some small adjustments and update our documentation.
