### ISSUE TITLE
Bug Report: deploy_diagnostics_for_mg variable does not trigger diagnostics deployment

### ISSUE THREAD

**Issue by MarcelHeek** [Azure/terraform-azurerm-caf-enterprise-scale#672]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.9

**azure provider**: 3.50.0

**module**: 3.3.0

#### Describe the bug

Although bumped up to module version 3.3.0 and AzureRM version 3.50.0 and adding the variable to the enterprise_scale.tfvars the plan show no changes to be made that reflect the enabling of diagnostics on Management Groups

#### Steps to Reproduce

Up the version of the terraform-azurerm-caf-enterprise-scale module in our workflow (Rover based), see screenshot
![image](https://user-images.githubusercontent.com/84451910/230330818-43047c2e-ad10-4321-ac02-10124fbeb6c4.png)

 The plan output only show 1 outside changes and 1 policy assignments change, thats are both non-related to enabling diagnostics on Management Groups

#### Additional context

Please advice.....

**Comment by MarcelHeek** [comment]
@lachaves Do you perhaps have an idea why this is not working for me?

**Comment by matt-FFFFFF** [comment]
Hi @MarcelHeek 

The MG diag settings are deployed by the AzAPI provider. Can you confirm this is being used?

We do not test this module with Rover and the aztfmod caf supermodule. You should raise an issue on that repo as well.

**Comment by MarcelHeek** [comment]
Hi @matt-FFFFFF,

How can I confirm whether this is being used? I am not that much into TF and merely a consumer. I can (at this point) only see that the azure/azapi module v1.5.0 is being loaded through the enterprise-scale module load in the Azure/caf-terraform-landingzone logic

And I will look into raising this issue as well in the Azure/caf-terraform-landingzone repo which calls the enterprise_scale module (as a caf solution add-on)

**Comment by lachaves** [comment]
Hi @MarcelHeek, looking into it right now.

**Comment by MarcelHeek** [comment]
@lachaves It's been a while, but diagnostics for MG's are still not set for our tenants. I have the required versions of the providers in place that are documented [here](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4a0e61ce2f6230cbace76607901ec92ae458a183/README.md#requirements)

As you can see in this screenshot the version requirements are all met 
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/84451910/29b7e270-c4fd-4248-930a-12794bb1bae2)

Have you any idea what might be the issue?

**Comment by matt-FFFFFF** [comment]
closed by #1053
