### ISSUE TITLE
Feature Request: Manually Created root management group, policy definitions

### ISSUE THREAD

**Issue by sorenhuus** [Azure/terraform-azurerm-caf-enterprise-scale#678]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I am creating the standard ES management group hierachy. I want to run the deployment in a SPN context,  where the SPN has access to the level 1 management group "Contoso", insted of the management group root. This is for security reasons.

Ive created the "Contoso" management group manually, and assigned my SPN "Owner" to it. Using custom_landing_zones, the remaining management groups are being deployed.

#### Describe the solution you'd like

Be able to create policy defintions/definition sets on management groups not created by the CAF module and assign them at that level or lower.

External from the module, create policy definitions/definition sets at the root. And assign them using the module. But that is not possible either

**Comment by matt-FFFFFF** [comment]
Hi @sorenhuus 

You can do this by importing the management group into the Terraform state.

When you try to apply with an existing management group, you'll get an error that the management group exists. You'll then be able to import it using the import command.
