### ISSUE TITLE
Feature Request: Policy Remediation

### ISSUE THREAD

**Issue by ChrisTav424** [Azure/terraform-azurerm-caf-enterprise-scale#684]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

I'm using the Archetypes to deploy policies which is working great, I can't see a way using the modules to configure remediation. For example, I've deployed Deploy-MDFC-Config with DeployIfNotExists but looks like I need azurerm_policy_remediation resource block to remediate. 

#### Describe the solution you'd like

A bool in the archetype, in order to activate a remediation, set to false by default

#### Additional context

Love the module, great work as always!

**Comment by jtracey93** [comment]
Hey @ChrisTav424,

Thanks for logging.

Out of interest was this on a new subscription by chance that didn't automatically remediate via DINE, when placed in a Management Group?

A cheeky workaround is to move the sub out and back into the management group and that will trigger subscription level policies like this one to trigger as per https://learn.microsoft.com/en-us/azure/governance/policy/how-to/get-compliance-data#evaluation-triggers

For your ask, we would need to add support for [`azurerm_management_group_policy_remediation`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_policy_remediation). But you could technically add these outside of the module today to trigger remediations 

Let us know

Thanks

Jack

**Comment by ChrisTav424** [comment]
Thanks for the quick reply Jack! 

The subscription has been around for some time but was built after the management group structure. I'll try moving it out and back in again, I didn't realise that might trigger it! 

If that doesn't work, I'll add it using the native resource block you suggested :)
