### ISSUE TITLE
Incorrect Variable Validation for custom_landing_zones keys

### ISSUE THREAD

**Issue by rudolphjacksonm** [Azure/terraform-azurerm-caf-enterprise-scale#700]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `1.3.9`

**azure provider**:  `3.54.0`

**module**: `3.1.2`

#### Describe the bug

The validation expression used for checking the length of keys in the `custom_landing_zones` keys looks to be incorrect. In the Portal, a Management Group can be created with an ID that is 90 characters long. The current validation block restricts this to 36 characters, which is quite a bit shorter.

We have the need to nest 5 or 6 levels deep in our management group structure, and as these grow it would mean we would consistently hit that limit and need creative ways of breaking naming conventions to stay under the limit.

#### Steps to Reproduce

1. Supply a key to `custom_landing_zones` that is greater than 36 characters in length
2. Validation will fail.

#### Additional context
The validation block was introduced in this commit: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/commit/b2e59083426e443651bee5bd82610fab473a0934

**Comment by matt-FFFFFF** [comment]
Thanks for raising this @rudolphjacksonm 

I will research why the current limit of 36 characters was selected

**Comment by matt-FFFFFF** [comment]
Hi. I think we can change this, look out for a patch release soon

**Comment by stevenicholl** [comment]
Thank you @matt-FFFFFF . Are there any rough estimates for the availability of the fix?
