### ISSUE TITLE
How is Virtual WAN and private dns zone links suppose to work? 

### ISSUE THREAD

**Issue by tlfzhylj** [Azure/terraform-azurerm-caf-enterprise-scale#705]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.4.4

**azure provider**: 3.50.0

**module**: 3.3.0

#### Describe the bug

This is probably not a bug, but I just wonder how it is supposed to work.

When deploying Virtual WAN, Azure Firewall and a secured virtual hub - and the the DNS deployment is also set to `true`, together with both `enable_private_dns_zone_virtual_network_link_on_hubs` and `enable_private_dns_zone_virtual_network_link_on_spokes`.

Some questions regarding this:
1. Will `enable_private_dns_zone_virtual_network_link_on_hubs` have any effect when deploying Virtual WAN, and not the traditional hub-spoke-model?
2. When `enable_private_dns_zone_virtual_network_link_on_spokes` is `true`, will all the spokes defined in `spoke_virtual_network_resource_ids` and `secure_spoke_virtual_network_resource_ids` be linked to all of the enabled Private DNS zones?
3. Is  the meaning of `virtual_network_resource_ids_to_link` to link virtual networks which is not handled by the ones mentioned in question 2?
4. What is the correct way of doing this when using Virtual WAN?

Thanks again for all your good work!

#### Steps to Reproduce

1. Create connectivity resources with Virtual WAN and private DNS zones enabled
6. Private DNS zones are not linked to hub

**Comment by tlfzhylj** [comment]
Thank you for clearing up, @matt-FFFFFF! Appreciate it.

Then I belive the answer for question four is to link the DNS zones to the spokes, like discussed in question and answer two and three.

**Comment by matt-FFFFFF** [comment]
By the way the recommended way to configure spoke networking is now through the [Azure/terraform-azurerm-lz-vending](https://github.com/Azure/terraform-azurerm-lz-vending) module.

We do not have private DNS zone support yet but it is on our backlog.
