### ISSUE TITLE
v4.0 - Policy assignment "Deploy-AzSqlDb-Auditing" - Log Analytics Workspace ID

### ISSUE THREAD

**Issue by tlfzhylj** [Azure/terraform-azurerm-caf-enterprise-scale#707]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.4.6

**azure provider**: 3.55

**module**: 4.0.1

#### Describe the bug

I was trying out the 4.0 module version. One question came up when I was running terraform plan:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4a1239683296b0668171ef8e75ed09105297064a/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_azsqldb_auditing.tmpl.json#L22

How can I set a custom value here?

For example, in `Deploy-VM-Monitoring` I can set the following if I have custom naming:

```hcl
archetype_config_overrides = {
    root = {
      archetype_id = "es_root"
      parameters = {
        Deploy-VM-Monitoring = {
          logAnalytics_1 = local.log_analytics_workspace_id
        }
     }
  }
}
```

**Comment by matt-FFFFFF** [comment]
Hi,

If the policy is assigned by a default archetype, you can override it using the syntax in your example.

This is part of the landing_zones archetype:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/4a1239683296b0668171ef8e75ed09105297064a/modules/archetypes/lib/archetype_definitions/archetype_definition_es_landing_zones.tmpl.json#L12

Therefore your overrise would look like this:

```terraform
archetype_config_overrides = {
    landing_zones = {
      archetype_id = "es_landing_zones"
      parameters = {
        Deploy-AzSqlDb-Auditing = {
          logAnalyticsWorkspaceId = "MYVALUE"
        }
     }
  }
}
```

**Comment by matt-FFFFFF** [comment]
I got the information by looking in the assignment file:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_azsqldb_auditing.tmpl.json
