### ISSUE TITLE
Feature Request: Using "policyType: BuiltIn" policies and initiatives

### ISSUE THREAD

**Issue by jefutte** [Azure/terraform-azurerm-caf-enterprise-scale#708]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

I am trying to use the ISO 27001:2013 policy initiative that is built-in in Azure, but I can't figure out if this is even possible to use Azure BuiltIn policies/initiative with this module. If it's possible it would be great to have an example of how to do it. If it is not possible, consider this a feature request to do it. 

I have tried creating a policy assignment with this path: lib/policy_assignments/policy_assignment_es_iso27001.json and add the initiative to lib/archetype_extension_es_root.tmpl.json, but no luck. 

I've also tried creating my own initiative in lib/policy_set_definitions which is just a copy of the builtin initiative (but policyType changed from BuiltIn to Custom), but that didn't help either. 

I have also not been able to find any mentions of this in previous issues.

#### Describe the solution you'd like

Documentation of how to use BuiltIn policy types.

If it's not possible, then adding this feature to the module, so we can utilize the many BuiltIn policies and initiatives, without having to copy everything in to our own codebase.

**Comment by jtracey93** [comment]
Hey @jefutte have you seen and followed https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Assign-a-Built-in-Policy ?

let us know

**Comment by jefutte** [comment]
@jtracey93 thanks! Don't know how I managed to not see that when going through the docs :-)
