### ISSUE TITLE
`strict_subscription_association` variable description seems misleading

### ISSUE THREAD

**Issue by eehret** [Azure/terraform-azurerm-caf-enterprise-scale#710]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
1.4.6

**azure provider**:
3.55.0

**module**:
4.0.1

#### Describe the bug

The current description of the `strict_subscription_association` variable states:

> If set to true, subscriptions associated to management groups will be exclusively set by the module and any added by another process will be removed. If set to false, the module will will only enforce association of the specified subscriptions and those added to management groups by other processes will not be removed.

However, I have observed in my usage of the module that this seems to be untrue.  If I leave the default value of `true` for this variable, even though I am creating resources in several of the Management, Connectivity and Identity subscriptions and setting their IDs using the `subscription_id_management`, `subscription_id_connectivity`, and `subscription_id_identity` variables, the module makes no attempt to create any `azurerm_management_group_subscription_association` resources.
Only when I set the `azurerm_management_group_subscription_association` variable to `false` does the module then attempt to create `azurerm_management_group_subscription_association` resources.

#### Steps to Reproduce

1. Create a configuration, leaving `strict_subscription_association` set to `true`
2. terraform plan

The plan indicates that no `azurerm_management_group_subscription_association` will be created.  Switching `subscription_id_management` to `false` and repeating shows that associations will be created.
This doesn't seem to align with the variable description, as currently written.

#### Additional context

Right now the `strict_subscription_association` seems all or nothing.   It's quite possible that I'm missing something, but it seems like you either get no `azurerm_management_group_subscription_association` resources when the variable is set to `false` or you get all of them when it is set to `true`.

What I'm actually trying to achieve is more nuanced.  I have one existing subscription, in which I would like to create Connectivity resources but NOT associate it with a different management group than it is currently associated with.
Simultaneously I would like to also create resources in existing Identity and Management subscriptions that were newly created for this module to consume and use and DO want to re-associate those with the correct management groups per 'standard' CAF structure.  It is unclear to me if this is possible.

In any case it would be great if there were more examples of how to use `strict_subscription_association` , and one example showing how I might achieve the above if that is possible.

**Comment by matt-FFFFFF** [comment]
Hi,

In short - strict sub association means we use the subscription ids property of the `azurerm_management_group` resource. If it's false we use the `azurerm_management_group_subscription_association`.

To answer other question, you can use another instance of the module to deploy connectivity resources in your existing subscription. Just turn off all the other variables that deploy management groups.

**Comment by eehret** [comment]
@matt-FFFFFF Thanks for the quick response.  Trying to get my head around the first part of what you said.... I might come back and ask additional questions.

Regarding the second part though, I actually want to deploy connectivity resources (particularly private DNS zones).  I just don't want to move that Connectivity subscription under a different management group just yet.  So I'm hoping there's a way of achieving the best of both worlds and be selective about which subscriptions get reassociated.

This is because we're executing a transition from a non-enterprise scale landing zone architecture, into a new ESLZ structure.   One of our legacy subscriptions has resources that cannot be moved, so in the future it will become our Connectivity subscription, and when we're ready at a later date we would then want to change something in this module's config so that it now becomes reassociated under the 'correct' management group.

Just trying to take advantage of all the goodness this module has while not break anything currently in flight :)

**Comment by eehret** [comment]
@matt-FFFFFF Ah, I think I'm understanding better now what you meant.   When you say another instance of the module you literally mean call it more than once with different things turned on.  Yes, that might work.  I'll play around with that and see.

**Comment by eehret** [comment]
@matt-FFFFFF Hello ...  I'm now attempting what you suggested above, regarding calling the module a second time with only connectivity stuff turned on.   I guess in order to achieve the effect that I want, I need to include management resources otherwise the policies for deploying private endpoint DNS configuration in landing zones, won't be available.   Right?

What I have right now is two invocations of the module:
1. Main one where I've got everything turned on except for connectivity (`deploy_connectivity_resources` is false for this invocation)
2. One just for connectivity (`deploy_connectivity_resources` is true and everything else is turned off).  I think this is what you were suggesting to do.....

Problem is, the thing I'm *most* interested in here, the DINE policies for PE, are not included when I do the above.  I get the actual zones, but I already had most of those already so that's not a big win in my view.

Not sure what is the best way to achieve the desired effect.  Is there any simple way to do this besides creating a custom archetype?

**Comment by eehret** [comment]
@matt-FFFFFF  Thanks for your suggestions above.  Between that, reading the docs some more and playing around the the module a little more I was finally able to get the desired result.  It may not be the prettiest solution but it works.

**Comment by matt-FFFFFF** [comment]
Great to hear. Will close for now
