### ISSUE TITLE
`Deploy-AzSqlDb-Auditing` policy assignment is not getting Log Analytics Workspace ID set correctly

### ISSUE THREAD

**Issue by eehret** [Azure/terraform-azurerm-caf-enterprise-scale#713]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.4.6

**azure provider**: 3.55.0

**module**: 4.0.1

#### Describe the bug

When running the module with `deploy_core_landing_zones` and `deploy_management_resources`, and subscription IDs set using `subscription_id_management`, the `Deploy-AzSqlDb-Auditing` policy assignment ends up with an incorrect log analytics workspace ID.

#### Steps to Reproduce

1. Set variables as described above
2. Terraform plan

#### Screenshots

Here's the relevant output:
```
 # module.enterprise_scale.azurerm_management_group_policy_assignment.enterprise_scale["/provider
s/Microsoft.Management/managementGroups/lzroot-landing-zones/providers/Microsoft.Authorization/policy
Assignments/Deploy-AzSqlDb-Auditing"] will be created
  + resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
      + description          = "To ensure the operations performed against your SQL assets 
are captured, SQL servers should have auditing enabled. If auditing is not enabled, this policy will 
configure auditing events to flow to the specified Log Analytics workspace."
      + display_name         = "Configure SQL servers to have auditing enabled to Log Analy
tics workspace"
      + enforce              = true
      + id                   = (known after apply)
      + location             = "canadacentral"
      + management_group_id  = "/providers/Microsoft.Management/managementGroups/lzroot-lan
ding-zones"
      + metadata             = (known after apply)
      + name                 = "Deploy-AzSqlDb-Auditing"
      + not_scopes           = []
      + parameters           = jsonencode(
            {
              + logAnalyticsWorkspaceId = {
                  + value = "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegr
oups/lzroot-mgmt/providers/Microsoft.OperationalInsights/workspaces/lzroot-la"
                }
            }
        )
      + policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/25da7d
fb-0666-4a15-a8f5-402127efd8bb"

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }

      + non_compliance_message {
          + content = "SQL servers must have auditing enabled to Log Analytics workspace."
        }
    }
```
#### Additional context

Please note that other policy assignments involving log analytics workspace parameters appear to be getting computed correctly.
This is the only one that doesn't have the correct value.

**Comment by tlfzhylj** [comment]
I asked a similar question a couple of days ago: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/707

Please see last post in thread for the solution that worked for me. I have used custom naming.

**Comment by eehret** [comment]
@tlfzhylj I don't understand.   This is *expected* behaviour?  Why would all of the other policies hook up to the correct log analytics workspace without special configuration, but not this one?

**Comment by tlfzhylj** [comment]
@eehret I don't belive it's expected. In my case, I think it is because I have seperate environments (Terraform states) for core, management and connectivity. I also have custom naming. I'm not sure if it is because of one of them, both, the combination or none of them.

How do you provision your environment? Do you have seperated tf states between core, connectivity and management? Custom naming?

**Comment by eehret** [comment]
@tlfzhylj Thanks for the reply :)

I think none of those situations you mentioned apply to me.  I'm using more or less vanilla configuration, with the exception of excluding one policy, and setting another to 'Audit' instead of 'Deny'.

No separated states for those things, I have it all together in one project and probably going to keep it that way...

As I said in the issue description, log analytics workspace ID is getting set correctly for everything except this one specific policy assignment.

**Comment by tlfzhylj** [comment]
Okey, then it sounds like a bug. I'll leave it up to @matt-FFFFFF and rest of the guys :)

**Comment by eehret** [comment]
@matt-FFFFFF Super responsive, thanks so much for the quick work!
