### ISSUE TITLE
Azure Firewall basic - how will this affect the enterprise scale architecture?

### ISSUE THREAD

**Issue by tlfzhylj** [Azure/terraform-azurerm-caf-enterprise-scale#715]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**module**: 4.0.1

### Description

With v4 of the module you have implemented support for Azure Firewall basic. That's great!

Other than capacity, what features will we be missing? From what I can see in the article [Choosing the right Azure Firewall SKU to meet your needs](https://learn.microsoft.com/en-us/azure/firewall/choose-firewall-sku), _DNS proxy + Custom DNS_ is not supported in the basic sku.

How will this affect us using a standardised setup with Virtual WAN? What actual scenarios will not work if changing to basic sku?

Thanks!

### Terraform plan - changing from `Standard` to `Basic`

```hcl
Terraform will perform the following actions:

  # module.alz_connectivity.azurerm_firewall.virtual_wan["/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/azureFirewalls/xxx"] will be updated in-place
  ~ resource "azurerm_firewall" "virtual_wan" {
        id                  = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/azureFirewalls/xxx"
        name                = "xxx"
      ~ sku_tier            = "Standard" -> "Basic"
        tags                = {
            "deployedBy" = "terraform/azure/caf-enterprise-scale"
        }
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # module.alz_connectivity.azurerm_firewall_policy.virtual_wan["/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/firewallPolicies/xxx"] must be replaced
-/+ resource "azurerm_firewall_policy" "virtual_wan" {
      - auto_learn_private_ranges_enabled = false -> null
      ~ child_policies                    = [] -> (known after apply)
      ~ firewalls                         = [
          - "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/azureFirewalls/xxx",
        ] -> (known after apply)
      ~ id                                = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/firewallPolicies/xxx" -> (known after apply)
        name                              = "xxx"
      - private_ip_ranges                 = [] -> null
      ~ rule_collection_groups            = [
          - "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/firewallPolicies/xxx/ruleCollectionGroups/DefaultApplicationRuleCollectionGroup",
        ] -> (known after apply)
      ~ sku                               = "Standard" -> "Basic" # forces replacement
        tags                              = {
            "deployedBy" = "terraform/azure/caf-enterprise-scale"
        }
        # (3 unchanged attributes hidden)

      - dns {
          - proxy_enabled = true -> null
          - servers       = [] -> null
        }
    }

Plan: 1 to add, 1 to change, 1 to destroy.
```

**Comment by matt-FFFFFF** [comment]
Hi @tlfzhylj 

The decision on which Azure Firewall SKU to choose is probably one for another forum. In terms of this module we have included the capability, but you should consult the product documentation to ensure you select the correct SKU for your needs.

It looks like you have the correct document link to enable this comparison.

**Comment by tlfzhylj** [comment]
@matt-FFFFFF Okey, thanks. I can agree with that. Thank you for taking the time to answer anyway :-)
