### ISSUE TITLE
unable to assign a policy after defining it

### ISSUE THREAD

**Issue by pcsprashanth** [Azure/terraform-azurerm-caf-enterprise-scale#718]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.1 

**azure provider**: 3.42.0

**module**: 

### Description: Hi,

I defined policyset at top management group level and I'm able to see that in Azure Portal as well. However, the issue is when I'm trying to assign it.

It throws me the below error:

Error: Invalid index

  on .terraform/modules/enterprise_scale/modules/archetypes/locals.policy_assignments.tf line 100, in locals:
 100:       template    = local.archetype_policy_assignments_map[policy_assignment]
    ├────────────────
    │ local.archetype_policy_assignments_map is object with 33 attributes

The given key does not identify an element in this collection value.
Error: Terraform exited with code 1.
Terraform Plan Failed!

Policyset-Definition:

{
    "name": "Azure-Cloud-Security-BenchMark",
    "type": "Microsoft.Authorization/policySetDefinitions",
    "properties": {
      "name": "Cloud-Security-BenchMark",  
      "displayName": "Cloud security benchmark",
      "policyType": "Custom",
      "description": "The Microsoft cloud security benchmark initiative represents the policies and controls implementing security recommendations defined in Microsoft cloud security benchmark, see https://aka.ms/azsecbm. This also serves as the Microsoft Defender for Cloud default policy initiative. You can directly assign this initiative, or manage its policies and compliance results within Microsoft Defender for Cloud.",
      "metadata": {
        "version": "1.0.0",
        "category": "Security Center"
      },
      "parameters": {
        "installLogAnalyticsAgentOnVmMonitoringEffect": {
            "type": "String",
            "metadata": {
              "displayName": "Log Analytics agent should be installed on your virtual machine for Microsoft Defender for Cloud monitoring",
              "description": "This policy audits any Windows/Linux virtual machines (VMs) if the Log Analytics agent is not installed which Security Center uses to monitor for security vulnerabilities and threats"
            },
            "allowedValues": [
              "AuditIfNotExists",
              "Disabled"
            ],
            "defaultValue": "AuditIfNotExists"
          },
          "installLogAnalyticsAgentOnVmssMonitoringEffect": {
            "type": "String",
            "metadata": {
              "displayName": "Log Analytics agent should be installed on your virtual machine scale sets for Microsoft Defender for Cloud monitoring",
              "description": "Security Center collects data from your Azure virtual machines (VMs) to monitor for security vulnerabilities and threats."
            },
            "allowedValues": [
              "AuditIfNotExists",
              "Disabled"
            ],
            "defaultValue": "AuditIfNotExists"
          }
      },
      "policyDefinitions": [
        {
          "policyDefinitionReferenceId": "installLogAnalyticsAgentOnVmMonitoring",
          "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/a4fe33eb-e377-4efb-ab31-0784311bc499",
          "parameters": {
            "effect": {
              "value": "[parameters('installLogAnalyticsAgentOnVmMonitoringEffect')]"
            }
          },
          "groupNames": []
        },
        {
          "policyDefinitionReferenceId": "installLogAnalyticsAgentOnVmssMonitoring",
          "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/a3a6ea0c-e018-4933-9ef0-5aaa1501449b",
          "parameters": {
            "effect": {
              "value": "[parameters('installLogAnalyticsAgentOnVmssMonitoringEffect')]"
            }
          },
          "groupNames": []
        }
      ],
      "policyDefinitionGroups": null
   }

}

Policy Assignment:

{
    "type": "Microsoft.Authorization/policyAssignments",
    "apiVersion": "2022-06-01",
    "name": "Cloud-Security-BenchMark",
    "dependsOn": [],
    "properties": {
      "description": "The Microsoft cloud security benchmark initiative represents the policies and controls implementing security recommendations defined in Microsoft cloud security benchmark, see https://aka.ms/azsecbm. This also serves as the Microsoft Defender for Cloud default policy initiative. You can directly assign this initiative, or manage its policies and compliance results within Microsoft Defender for Cloud.",
      "displayName": "Azure Cloud Security BenchMark",
      "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/mg-itaudev/providers/Microsoft.Authorization/policySetDefinitions/Azure-Cloud-Security-BenchMark",
      "enforcementMode": null,
      "nonComplianceMessages": [
        {
          "message": "Subnets {enforcementMode} have a Network Security Group."
        }
      ],
      "scope": "mg-itaudev-sandbox",
      "notScopes": [],
      "parameters": {}
    }
  }

Please have a look at it.
Thank you in Advance

**Comment by cveld** [comment]
@pcsprashanth can you make the title more specific?

**Comment by pcsprashanth** [comment]
In short, I'm unable to assign a policy after defining it. It is throwing me error, when trying to assign it. below is the error:

Error: Invalid index

  on .terraform/modules/enterprise_scale/modules/archetypes/locals.policy_assignments.tf line 100, in locals:
 100:       template    = local.archetype_policy_assignments_map[policy_assignment]
    ├────────────────
    │ local.archetype_policy_assignments_map is object with [49](https://github.com/pcsprashanth/itau-landingzone-terraform/actions/runs/5001820062/jobs/8961000792#step:10:50) attributes

The given key does not identify an element in this collection value.
Error: Terraform exited with code 1.
Terraform Plan Failed!
Error: Process completed with exit code 1.

**Comment by jtracey93** [comment]
@pcsprashanth please review https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy-Sets-and-Assignments and let us know how you get on

**Comment by pcsprashanth** [comment]
> @pcsprashanth please review https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy-Sets-and-Assignments and let us know how you get on

Thank you Tracey. However, I have issue while assigning the "Cloud Security BenchMark" initiative. I've defined it by copying the definition from Azure portal and made required changes. Definition looks good. 

However, when assigning it...Terraform plan shoots error.

Error: Invalid index

  on .terraform/modules/enterprise_scale/modules/archetypes/locals.policy_assignments.tf line 92, in locals:
  92:       template    = local.archetype_policy_assignments_map[policy_assignment]
    ├────────────────
    │ local.archetype_policy_assignments_map is object with 39 attributes

The given key does not identify an element in this collection value.


Not sure, if we there is any limitations on attributes value in local.archetype_policy_assignments_map, as the initiative has 211 policies in it.

**Comment by pcsprashanth** [comment]
> @pcsprashanth Have you created the archetype extension file as described here:
> 
> https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy-Sets-and-Assignments#make-the-custom-policy-definitions-and-policy-set-definition-available-for-use

yeah, I have it...That is how, I was able to define it under policyset-definition.

{
    "es_root": {
        "policy_assignments": [],
        "policy_definitions": [],
        "policy_set_definitions": [ "Cloud Security" ],
        "role_definitions": [],
        "archetype_config": {
            "parameters": {},
            "access_control": {}
        }
    }
}

**Comment by matt-FFFFFF** [comment]
Hi, you need to reference the assignment as well.

You need to reference them by the `name` key in the respective JSON document.

```json
{
  "es_root": {
    "policy_assignments": [ "Cloud-Security-BenchMark" ],
    "policy_definitions": [],
    "policy_set_definitions": [ "Azure-Cloud-Security-BenchMark" ],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {},
      "access_control": {}
    }
  }
}
```

**Comment by pcsprashanth** [comment]
> 
Hi,

I believe we need only policy-assignment file and extension file for an In-Built Policy assignment.
Issue is with any inbuilt policy:

1. Configure machines to create the default Microsoft Defender for Cloud Pipeline using Azure Monitor Agent

Policy-Assignment.json file

{
  "name": "Microsoft-Defender",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
      "description": "Configure machines to automatically install the Azure Monitor and Azure Security agents. Microsoft Defender for Cloud collects events from the agents and uses them to provide security alerts and tailored hardening tasks (recommendations). Create a resource group, a Data Collection Rule and Log Analytics workspace in the same region as the machine to store audit records. Target machines must be in a supported location.",
      "displayName": "[Preview]: Configure machines to create the default Microsoft Defender for Cloud pipeline using Azure Monitor Agent",
      "notScopes": [],
      "parameters": {
      },
      "policyDefinitionId": "/providers/Microsoft.Authorization/policySetDefinitions/362ab02d-c362-417e-a525-45805d58e21d",
      "nonComplianceMessages": [
        {
          "message": "Azure Monitor and Security agents {enforcementMode} be enforced"
        }
      ],
      "scope": "${current_scope_resource_id}",
      "enforcementMode": null
  },
  "location": "${default_location}",
  "identity": {
      "type": "SystemAssigned"
  }
}

Extension-File:

{
    "es_root": {
        "policy_assignments": [ "Microsoft-Defender" ],
        "policy_definitions": [],
        "policy_set_definitions": [],
        "role_definitions": [],
        "archetype_config": {
            "parameters": {},
            "access_control": {}
        }
    }
}

Error:



<img width="432" alt="image" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/52338785/2f08992d-075e-40f6-9325-508bbd4b7e7a">

Let me know, if we can connect on teams and work on it

**Comment by pcsprashanth** [comment]
Hi @cveld, you can use this:

https://github.com/pcsprashanth/pcs-landingzone-terraform.git

I've used OIDC authentication...you can update them and run the workflow.

From extensions, under policy-assignment...the code runs with no error.
The moment you add policy initiative name in the extension...it throws error
Below are the two initiatives, I tested and it failed.

1. Microsoft Cloud SecurityBenchMark
2. [Preview]: Configure machines to create the default Microsoft Defender for Cloud pipeline using Azure Monitor Agent


Thank you in Advance.

**Comment by pcsprashanth** [comment]
> Can you make a small git repo with a reproduction of your issue?

Hi Mate, any update on the issue. Cheers!!

**Comment by pcsprashanth** [comment]
Issue was with the naming of the policy_assignments file. I have suggestion, can we have separate folders for assignment of  policy initiatives and individual policies. As it would be difficult to identify which policy set or policy if all are in single policy assignment folder.

Thank you all

**Comment by matt-FFFFFF** [comment]
Glad you sorted it @pcsprashanth 

You can have whatever folder structure you like. It's the file name that's important.

The module searches all paths under the defined lib directory.
