### ISSUE TITLE
Move away from legacy policies

### ISSUE THREAD

**Issue by eehret** [Azure/terraform-azurerm-caf-enterprise-scale#719]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

n/a - no problem right now .   I guess this is more of a question about the road map.   And I realize some of the answers may depend on what happens in the enterprise-scale repo.
Right now there are a number of policy definitions that are marked as "Legacy" or otherwise indicated as approaching deprecation somehow.   An example of this:  /providers/Microsoft.Authorization/policySetDefinitions/75714362-cae7-409e-9b99-a8e5075b7fad
All of the current log analytics policies will be or have been replaced by ones for Azure Monitor Agent.
When will the module reflect that reality?  AMA is already available and I think a lot of customers would be in the process of migrating already.

#### Describe the solution you'd like

Replace deprecated policies with the one ones :)

**Comment by jtracey93** [comment]
Hey @eehret, thanks for the issue. Please see: https://github.com/Azure/Enterprise-Scale/issues/1055 & https://github.com/Azure/Enterprise-Scale/wiki/FAQ#why-hasnt-azure-landing-zones-migrated-to-the-azure-monitor-agent-yet

**Comment by eehret** [comment]
@jtracey93 Thanks for the quick response and pointing me in the right direction!  💯
