### ISSUE TITLE
`Deploy-Private-DNS-Zones` is not enforced

### ISSUE THREAD

**Issue by tlfzhylj** [Azure/terraform-azurerm-caf-enterprise-scale#721]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**module**: 4.0.2

#### Describe the bug

In my setup  the policy assignment for `Deploy-Private-DNS-Zones` on the `<myorg>-corp` management group have `enforcement_mode` set to `false`.

Is this expected behaviour? Shouldn't this policy assignment be enabled by default?

#### Additional context

To set it to `true` I had to configure the following:

```hcl
  archetype_config_overrides = {
    <myorg>-corp = {
      enforcement_mode = {
        Deploy-Private-DNS-Zones = true
      }
    }
  }
```

**Comment by matt-FFFFFF** [comment]
Hi @tlfzhylj thanks for porting we will look into this

**Comment by eehret** [comment]
I'm having the same issue, except that even when I try to set enforcement mode in the archetype_config_overrides , it doesn't work.... here is what I have in the config (omitting the rest of the config which has been working fine)

``
      enforcement_mode = {
        Deploy-Private-DNS-Zones = true
      }
``

I'm currently on v4.0.2

**Comment by tlfzhylj** [comment]
Hi, @eehret.

I assume this is for your corp archetype.

Remember to also include `<your root_id>-corp` in your config under `archetype_config_overrides`. In the example below you see that `root_id = "orgname"`.

```hcl
module "alz_core" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "4.0.2"

  # (...) Most of the config removed in example. Only relevant is shown.

  root_id = "orgname"

  archetype_config_overrides = {
    orgname-corp = {
      enforcement_mode = {
        Deploy-Private-DNS-Zones = true
      }
    }
  }
}
```

I'm not sure if it helps, but let us know how it goes.

**Comment by tlfzhylj** [comment]
@eehret, you have to put `enforcement_mode` under `<whatever you have defined under root_id>-corp` as shown in my example above.

**Comment by tlfzhylj** [comment]
@eehret Check out this Wiki article: [[Examples] Deploy policies without enforcing them
](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-policies-without-enforcing-them)

**Comment by eehret** [comment]
@tlfzhylj Thanks.  Yes I did see that documentation.  But apparently that is not the only way to specify archetype_config_overrides.  In this contradictory documentation it uses the archetype_id instead of naming convention. 
As I mentioned, I am using this method instead.  And apparently it does not work.

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/fb0c46b6d7b7a911302fd50446cbc0508d24bd96/docs/wiki/%5BExamples%5D-Set-parameter-values-for-Policy-Assignments.md#option-archetype_config_overrides-input-variable

**Comment by tlfzhylj** [comment]
@eehret If you just use 10 minutes and try what I suggest you'll see it will work.

**Comment by eehret** [comment]
@tlfzhylj Hm.  You seem to be responding as though you think I don't believe you.   I assure you that is not the case.  I'm trying to be helpful and report something else that is not performing as documented.   If you don't like the fact that I've piggybacked on your issue to add an addition thing that isn't working to the list, then I'd be happy to open a separate issue :)

**Comment by matt-FFFFFF** [comment]
We understand this issue now and are going to close this in favour of #758
