### ISSUE TITLE
Getting Management Group already exist error while deploying connectivity and management resources

### ISSUE THREAD

**Issue by RakhilRavindran007** [Azure/terraform-azurerm-caf-enterprise-scale#726]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: Terraform v1.4.6

**azure provider**: v3.57.0

**module**: 3.1.2

### Description
Hi 
Im trying to deploy the landing zone core, management and connectivity resources through a layered based approach. the core management groups, archtype policies are deployed as part the first layer run of the code. for the connectivity and management resources Im deploying the code in its individual layer which has it own tfstate file. 
The core management groups and archtype policies are deployed successfully however when I try to run the management or connectivity layer the terminal throws below error.
"A resource with the ID "/providers/Microsoft.Management/managementGroups/xxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group" for more information."
How can we exclude the redeployment of management groups and archtypes when we are running the code for connectivity and management resources. all other resources are deployed successfully in the management and connectivity modules. 
#### Describe the bug

The core management groups and archtype policies are deployed successfully however when I try to run the management or connectivity layer the terminal throws below error.
"A resource with the ID "/providers/Microsoft.Management/managementGroups/xxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group" for more information."
How can we exclude the redeployment of management groups and archtypes when we are running the code for connectivity and management resources. all other resources are deployed successfully in the management and connectivity modules. 

#### Steps to Reproduce

1. step 1: run the core, management group and archtype module and the code executed successfully.
2. step 2: run the connectivity and management module all the resources are deployed successfully however this module tries to deploy the management groups and archtype policies along with the connectivity or management resources.
3. you get it...

#### Screenshots

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/34547346/ba4916f4-67b5-4547-8649-d14a61e498d3)

#### Additional context
connectivity main.tf

# Configure Terraform to set the required AzureRM provider
# version and features{} block.

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.54.0"
    }
  }
}

data "azurerm_client_config" "current" {}

module "alz" {
  # To enable correct testing of our examples, we must source this
  # module locally. Please remove the local `source = "../../../"`
  # and uncomment the remote `source` and `version` below.
  source = "../terraform-azurerm-caf-enterprise-scale"
  # source  = "Azure/caf-enterprise-scale/azurerm"
  # version = "3.1.2"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }
  root_parent_id   = data.azurerm_client_config.current.tenant_id
  root_id          = local.root_id
  root_name        = local.root_name
 
  default_location = local.default_location

  deploy_connectivity_resources    = local.deploy_connectivity_resources
  configure_connectivity_resources = local.configure_connectivity_resources
  subscription_id_connectivity     = local.subscription_id_connectivity
}

**Comment by robertbrandso** [comment]
Hi, @RakhilRavindran007.

You need to set `deploy_core_landing_zones = false` in your module configuration where you deploy connectivity and management.

Check out [[Examples] Deploy using multiple module declarations with remote state](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-remote-state) for more information about this topic.

**Comment by matt-FFFFFF** [comment]
Hi @RakhilRavindran007 

Did you try the suggestion above? It should fix your issue.

Thank you @robertbrandso!

**Comment by RakhilRavindran007** [comment]
It fixed my issue. Thank you
