### ISSUE TITLE
Unable to change the enforcement mode to disable Azure Policy Initiative

### ISSUE THREAD

**Issue by pcsprashanth** [Azure/terraform-azurerm-caf-enterprise-scale#727]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Description: Unable to change the enforcementmode of an inbuilt policy. Below is the code:

{
  "name": "security-cloud-benchmark",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
      "description": "The Microsoft cloud security benchmark initiative represents the policies and controls implementing security recommendations defined in Microsoft cloud security benchmark, see https://aka.ms/azsecbm. This also serves as the Microsoft Defender for Cloud default policy initiative. You can directly assign this initiative, or manage its policies and compliance results within Microsoft Defender for Cloud.",
      "displayName": "Microsoft cloud security benchmark",
      "notScopes": [],
      "parameters": {
      },
      "policyDefinitionId": "/providers/Microsoft.Authorization/policySetDefinitions/1f3afdf9-d0c9-4c3d-847f-89da613e70a8",
      "nonComplianceMessages": [
        {
          "message": "Cloud Security Benchmark enabled"
        }
      ],
      "scope": "${current_scope_resource_id}",
      "enforcementMode": false
  },
  "location": "${default_location}",
    "identity": {
        "type": "SystemAssigned"
    }
}

I tried all the options for enforcementMode, but no luck...it is assigning with the default.
Please let me know, if there is something wrong with the code.

Regards,
Prash

**Comment by pcsprashanth** [comment]
Its resolved

**Comment by VenkateshJayachandra** [comment]
can you please let me know the fix? Am trying to disable the initiative, but even after setting the value to false in archetype_config_overrides still the enforce is set to true. 

It works on few of the initiatives but not for all initiatives.  

Below is one of the initiative am trying to set enforce mode to "donotenforce" but unable to change. Any help appreciated. 

Assignment Name - Enforce-TLS-SSL 
Set Definition Name - Enforce-EncryptTransit

**Comment by VenkateshJayachandra** [comment]
> can you please let me know the fix? Am trying to disable the initiative, but even after setting the value to false in archetype_config_overrides still the enforce is set to true.

It works on few of the initiatives but not for all initiatives.

Below is one of the initiative am trying to set enforce mode to "donotenforce" but unable to change. Any help appreciated.

Assignment Name - Enforce-TLS-SSL
Set Definition Name - Enforce-EncryptTransit

**Comment by VenkateshJayachandra** [comment]
> Its resolved

can you please let me know the fix? Am trying to disable the initiative, but even after setting the value to false in archetype_config_overrides still the enforce is set to true.

It works on few of the initiatives but not for all initiatives.

Below is one of the initiative am trying to set enforce mode to "donotenforce" but unable to change. Any help appreciated.

Assignment Name - Enforce-TLS-SSL
Set Definition Name - Enforce-EncryptTransit
