### ISSUE TITLE
Managementgroup displayname example differ

### ISSUE THREAD

**Issue by Jefajers** [Azure/terraform-azurerm-caf-enterprise-scale#73]
Managementgroup display name example in the deployment examples with "myorg-x" differ from Enterprise-Scale examples with "Management Group prefix".

![pics](https://user-images.githubusercontent.com/64077181/115539838-bda1e100-a29d-11eb-8dfb-0ab440d3464f.PNG)

When using any of the Enterprise-Scale references from: https://github.com/Azure/Enterprise-Scale the "Management Group prefix" is also appended as part of each child Management Group display name without any spaces etc.

Streamlining the examples would make it easier to grasp and move between these solutions.

**Comment by krowlandson** [comment]
Thank you for the feedback @Jefajers.

We've actually been discussing this and considering whether to update on the module to match [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale) or the other way around.

We'll use this issue to finalise this discussion and make a decision either way.

cc: @ljtill

**Comment by krowlandson** [comment]
@jtracey93 and @krnese... One for us to discuss please, especially in light of the recent move to offering an IaC experience in ARM.

**Comment by krowlandson** [comment]
Closing this as we will track any changes to naming standards via #292 where we are looking at the option to simplify enabled user-specified naming, but also to offer a method by which to implement the CAF naming standards.

As part of this, we will look to implement consistency across the ARM, Bicep and Terraform implementation options.
