### ISSUE TITLE
Policy definitions not available in AzureGov

### ISSUE THREAD

**Issue by sandman-battelle** [Azure/terraform-azurerm-caf-enterprise-scale#74]
In Azure commercial I can see the policies needed e.g.

```

$ az cloud set -n AzureCloud
Switched active cloud to 'AzureCloud'.

$ az policy definition show --name "9d2b61b4-1d14-4a63-be30-d4498e7ad2cf"
{
  "description": "This policy deploys the Log Analytics agent to Linux Azure Arc machines if the agent isn't installed.",
  "displayName": "[Preview]: Deploy Log Analytics agent to Linux Azure Arc machines",
  "id": "/providers/Microsoft.Authorization/policyDefinitions/9d2b61b4-1d14-4a63-be30-d4498e7ad2cf",
...
```
But AzureGov....

```
$ az cloud set -n AzureUSGovernment
Switched active cloud to 'AzureUSGovernment'.

$ az policy definition show --name "9d2b61b4-1d14-4a63-be30-d4498e7ad2cf"
The policy definition '9d2b61b4-1d14-4a63-be30-d4498e7ad2cf' could not be found.
```
I also tried to find them by `displayName` in case the IDs (`name`) was different for some reason.  No luck
![image](https://user-images.githubusercontent.com/78104304/115788210-51a0a500-a391-11eb-99ee-9bd2b51f3c43.png)

This is a continuation of a discussion that started in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/23#issuecomment-825064454

**Comment by sandman-battelle** [comment]
@krowlandson, until this get figured out, is there a reasonable way to skip the referenced policies for now but be able to add them back later?

**Comment by sandman-battelle** [comment]
After a bit more code reading, it seems like I should be able to create a custom archetype for AzureGov that ignores the missing policies. I'll try that just to prove it to myself.  Then I'll work through each reference in [modules/archetypes/lib](https://github.com/azure/terraform-azurerm-caf-enterprise-scale/tree/main/modules/archetypes/lib) to identify which are missing and/or try to create a mapping between commercial and government cloud.

**Comment by krowlandson** [comment]
> After a bit more code reading, it seems like I should be able to create a custom archetype for AzureGov that ignores the missing policies. I'll try that just to prove it to myself. Then I'll work through each reference in [modules/archetypes/lib](https://github.com/azure/terraform-azurerm-caf-enterprise-scale/tree/main/modules/archetypes/lib) to identify which are missing and/or try to create a mapping between commercial and government cloud.

Yes, this would be the best approach I think but please let us know if you need any further guidance.

**Comment by krowlandson** [comment]
@sandman-battelle... how are you getting on with this? Is there anything we can do from our side to help?

**Comment by sandman-battelle** [comment]
Tx @krowlandson, I am making some progress.  Hope to have a PR ready next week sometime after I get a few more things working.  Oh, and I've not documenting anything either :(  so that needs done too ;)

**Comment by sblair01** [comment]
Hi @sandman-battelle - just following up on this case to see if you need further assistance.

**Comment by sandman-battelle** [comment]
I don't think so.  We've decide to move on to other ways, the lift to get AzureGov in alignment with commercial is just too great.  I wish MSFT didn't make this so hard.  It's really something they should consider cleaning up across-the-board, not just these policies.
