### ISSUE TITLE
Tracking changes made from the portal

### ISSUE THREAD

**Issue by infazops** [Azure/terraform-azurerm-caf-enterprise-scale#744]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Describe the solution you'd like

Now that we have a way of deploying an initial caf and enabled github actions to magically carry out any changes made via terraform, what happens if somebody, using the Azure Portal, grabs an empty subscription from the pool, adds it to the corp managent group and then adds resources? Is there a way these actions could update the tfstate file, which lives in an Azure storage account by the way, so we can continue to have a single point of truth?

I don't have any suggestions as I'm really not sure if this is already possible and I just don't understand the methods. I'm just looking for some help and guidance. Thanks.

#### Additional context
I'm not a terraform guru and a quick search didn't reveal any answers to my question, so excuse me if this is just a lack of knowledge.

**Comment by matt-FFFFFF** [comment]
Hi @infazops 

When managing a resource using Terraform, or any state based IaC tool for that matter, it is best to only use said IaC tool to manage the resource.

Making changes to a tracked resource will always cause issue where you have to either update the IaC to match the reality, or face the problem of the reality being reset to match the stat of the IaC.

I recommend you look at the subscription vending solution that we have https://aka.ms/sub-vending/tf

Also make sure you disable strict subscription association

**Comment by infazops** [comment]
Thanks Matt

Thought that might be the case. We'll stick to performing all from terraform as it looks like the only safe bet.
Thanks for the link to sub-vending. It will prove handy for other things we need to do.

Closing the issue
