### ISSUE TITLE
Error: local.lookup_azure_backup_geo_codes is object with 67 attributes

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/terraform-azurerm-caf-enterprise-scale#747]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
**terraform**: 1.5.0

**azure provider**: 3.53.0 

**module**: 4.0.2

### Description
on running the Terraform plan for the Management module I get the following error, since upgrading to 4.0.2

#### Describe the bug

Error: Invalid index

  on .terraform/modules/management.alz/modules/connectivity/locals.tf line 1436, in locals:
1436:       "privatelink.${local.lookup_azure_backup_geo_codes[location]}.backup.windowsazure.com"
    ├────────────────
    │ local.lookup_azure_backup_geo_codes is object with 67 attributes

The given key does not identify an element in this collection value.
##[error]Error: Terraform Plan failed with exit code: 1

#### Steps to Reproduce
run terraform plan

**Comment by ashley-kainos** [comment]
West Europe

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jtracey93** [comment]
Thanks.

How is this set, which variable input are you using, or are you using both:

1. `default_location`
2. `configure_connectivity_resources.settings.dns.config.private_link_locations`

Also are you specifying `westeurope` all in lowercase? If not, could you try that?

Let me know

Thanks

Jack

**Comment by ashley-kainos** [comment]
HI We are setting teh default location here: 
module "alz" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "4.0.2"

  default_location = "westeurope"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }
  # Base module configuration settings
  root_parent_id = data.azurerm_client_config.current.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.module}/lib"

which is all in lowercase, we've done teh same in Connectivity module and that works its just in the Management Module we get the error message. 

We don't use the "configure_connectivity_resources.settings.dns.config.private_link_locations"

**Comment by jtracey93** [comment]
Could you share your entire config in a [Gist](https://gist.github.com/)

**Comment by ashley-kainos** [comment]
added to gist

**Comment by jtracey93** [comment]
Can you share a link to the gist

**Comment by ashley-kainos** [comment]
<script src=https://gist.github.com/ashley-kainos/5f440bd106eeec308dc5c3c6bcd2fadf.js></script>

**Comment by jtracey93** [comment]
@ashley-kainos did you follow this verbatim: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-orchestration

**Comment by ashley-kainos** [comment]
When we 1st created the code base yes, but have developed more since then but modules are still base on that

**Comment by jtracey93** [comment]
Can you try and replicate it if you follow this verbatim, as customiziation of the modules isnt something we really support

**Comment by ashley-kainos** [comment]
HI Jack,

Followed those instructions vertbatim and get this error now .. I believe adding the default location as mentioned in issue #746 resolves this.

Regards
Ashley

**Comment by ashley-kainos** [comment]
ops sorry, missing default_location. Which when you look back at the examples in levels 100 to 300 is added, but missing for examples/documentation for level 400. 

When 1st created we use the Deploy using multiple module declarations with orchestration guide, but customised it a little so it now more meets with Deploy using multiple module declarations with remote state. 

So have configured that from scratch and looking at whats differnet from that base code set and ours to work out why we are getting errors, other than adding additional modules we are basiclly the same.

**Comment by jtracey93** [comment]
so adding the default location to each module declaration has fixed this, to confirm?

**Comment by ashley-kainos** [comment]
yes
