### ISSUE TITLE
Separation of concern

### ISSUE THREAD

**Issue by mw8er** [Azure/terraform-azurerm-caf-enterprise-scale#749]
Currently, we are setting up our management groups like this:
- one service principal covers root, tenant root group and the default management group for new subscriptions
- one service principals cover the subtree of their ALZ implementation, e.g. contoso or contoso-canary
- one service principal for central subscription vending 

Hence, it would be awesome if the implementation could be extended or adapted like that.
I.e. the terraform module currently works pretty well:

- it may not import its lz root (e.g. contoso)
- but it would be able to create the lz root with Management Group Contributor on Tenant Root Group
- after the creation of its lz root, you could drop the Management Group Contributor on Tenant Root Group
- In addition the service principal is either able to due subscription vending itself or is able to move subscriptions out of the default management group for new subscriptions.

**Comment by mw8er** [comment]
Thanks for that input @jtracey93 

Yes, I also had a look at that. Currently implemented it for each the different ALZ instances (contoso and contoso-canary).

**Comment by matt-FFFFFF** [comment]
Hi @mw8er 

I think the easier option is to create the intermediate root manually and then use Terraform 1.5's import block for the level 1 management group.

We have tested this successfully and it works well.

In terms of other permissions required, write permissions on whichever is the default management group are required. Also owner on any subscription that you wish to move into the MG hierarchy.

**Comment by mw8er** [comment]
@matt-FFFFFF 
I completely agree.
At the time I tested it, the import failed. Looking forward to implementing it in the suggested way the next time.

To simplify the operation task, both LZ service principals get Owner on the "default" management group. This way one SP can move a subscription into its subtree wirhout having to remove the other SP

**Comment by matt-FFFFFF** [comment]
Hi @mw8er 

This should help https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/613#issuecomment-1604195837

Let me know

**Comment by mw8er** [comment]
Seems promising, going to give it a try. Might take a while due to other more urgent topics.
