### ISSUE TITLE
Pass parameters to a policy assignment inherited from parent MG - Custom LZ

### ISSUE THREAD

**Issue by VenkateshJayachandra** [Azure/terraform-azurerm-caf-enterprise-scale#751]
### Community Note

Am trying to pass in parameters to a policy assignment which is inherited from the parent MG. Is there any work around? 

Below is what am trying to achieve, 

Am having a custom LZ called "A" and there are two child MG "A1" and "A2" for this custom lz "A". 

There are few policies which are inherited from "A" to "A1" and "A2".  And just for "A1" and  on one of the inherited policies from "A" I would like to pass in a parameter/value. Is this possible? 

To achieve this I tried to exclude the policy assignment in A1 which got inherited from "A" and then directly assign a policy to "A1" with the preferred value, but that didn't work for me. Because exclusion didn't work on the child custom lz. 

A real world example is, I have the in-built policy "Audit-AppGW-WAF" assigned to "A" with "Deny" effect and to the child "A1" I would like to change it to "Audit" and for "A2" I would like to change it to "Deny" 

Any insight is appreciated.

**Comment by matt-FFFFFF** [comment]
Hi @VenkateshJayachandra 

Can I ask the reason for the management group design?

If you have this sort of requirement then it may be the hierarchy is not optimal.

Thanks

**Comment by gbr759** [comment]
I can answer that @matt-FFFFFF - unfortunately this is one of those 1/100 scenarios where we’ve had to deviate a little from the standards.  The environment we’re working on has multiple third parties who also look after the environment.  In this case we have a requirement to have multiple “staging” areas - specifically around security where there is a requirement for workloads to be moved to an MG that a third party can use to “test” their Sentinel alerts in a “staging” LAW, that is separate from the “production” LAW, which means we need to pass different parameters for the activity and diagnostic logging whilst this testing takes place.  Once it is signed off the subs are then moved to the Corp or Online MGs.  The second child MG has all Corp level policies assigned to it, albeit all set to audit, as there are multiple brownfield subscriptions that need to be migrated and the client would like a safe area to move these to to evaluate and remediate policy compliance without any policies being set to deny.  It’s basically a small canary environment.

A long story, hopefully that makes sense.

**Comment by chrsundermann** [comment]
@gbr759 That's understandable but not everyone has this kind of architecture and is working with such Corp/Online setup. Moving subscriptions between different MGs where different policies are "working" can cause a lot of "pain". In the end it makes totally sense that parameters which are closer to the final "object" overwrites the above ones.
