### ISSUE TITLE
Deploy only MG structure without any policies

### ISSUE THREAD

**Issue by elsalvos** [Azure/terraform-azurerm-caf-enterprise-scale#753]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The goal: is to create a custom MG structure without any assigned policies and assigned only selective policies/sets at the scope I decide.

I would like to be able to create either only create the default MG structure, or even better, create my own custom structure starting from the ALZ root name to the other lower layers/scopes of MGs
If I'm not mistaken, the vNext module solution update version (5) may contain what I'm asking but how about now? how would go about deploying something similar?

#### Is your feature request related to a problem?
No, I would like an option to have and customize deployment for specific environments

#### Describe the solution you'd like

I would like an option to have and customize deployment for specific environments

#### Additional context

If there is anyone that has created a similar deployment successfully, please share your code and findings.

**Comment by jtracey93** [comment]
Hey @esalvos,

This is possible today by specifying only `custom_landing_zones` as per: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes

And then to have no policy definitions and assignments just set the `archetype_id` to `default_empty` which is the built-in empty archetype we provide in the module here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/archetype_definitions/archetype_definition_default_empty.json

You can then create your own custom archetypes, as per the first wiki article linked above and you should be good to go 👍

### An alternative

Another option is to use the archetype include/exclude functionality as documented here against the built-in archetypes: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions

Hope that helps

But yes v.next will help here further as well

**Comment by elsalvos** [comment]
Hey @jtracey93, 

Thank you for this great guidance and prompt response. I've tried the two top documented options, and I've been able to create a new archetype outside the default landing zone, by placing them under es_root and customizing the default landing zone display to 'my custom landing zones'. But I have not been able to find any documentation or example code to change the display name of 'platform' and MG under it or prevent that MG/sub-MGs from being created.

to override policies, I've been trying the include/exclude options, and has worked to meet my current need but I would like to use a blanket option that I can use on the root MG where no default assignments are done. 

I think your recommended option to use archetype_id with default_empty may work better, do you have an example of how I would use it when sourcing the repo from the GitHub/TF gallery module? is it by using the archetype override blocks?

**Comment by jtracey93** [comment]
Hey @esalvos, 

The example of archetypes overrides are shown here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes

As for disabling the ALZ default hierarchy, whilst not suggested, it is possible by setting [`deploy_core_landing_zones`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale#input_deploy_core_landing_zones) to `false` in the module declaration

**Comment by elsalvos** [comment]
Thanks @jtracey93!
