### ISSUE TITLE
Configure SQL servers to have auditing enabled to Log Analytics workspace

### ISSUE THREAD

**Issue by anwarnk** [Azure/terraform-azurerm-caf-enterprise-scale#756]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.2 (latest)

**azure provider**: 3.63.0

**module**: 4.0.2

#### Describe the bug

Definition ID: /providers/Microsoft.Authorization/policyDefinitions/25da7dfb-0666-4a15-a8f5-402127efd8bb
The "Configure SQL servers to have auditing enabled to Log Analytics workspace" at the assignment level shows our log analytics workspace. However, when the policy is executed it enables auditing but does not add the log analytics workspace information.

Parameter is set as: 
/subscriptions/xxxxxxxxxxxxxxx/resourceGroups/xxxxxx-mgmt/providers/Microsoft.OperationalInsights/workspaces/xxxxxxxx-la

It does not like the uppercase in the parameter. If I go to assignment in the portal and click 'Edit Assignment' and 'Review + Save' without making any changes it automatically changes the value to all lowercase

/subscriptions/xxxxxxxxxxxxxxx/resourceGroups/xxxxxx-mgmt/providers/microsoft.operationalinsights/workspaces/xxxxxx-la

The policy executes successfully.

#### Steps to Reproduce

Create a SQL Server and wait for policy to trigger.

#### Screenshots
In the portal with proper case parameters, the auditing shows as this:  
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/105373983/7c596e9e-6394-411d-b151-0f8101f6778b)

**Comment by anwarnk** [comment]
Supporting evidence, when 'Review + Save ' is carried out even though no changes have been made. When the CAF module is executed the plan states that it will change it back:

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/105373983/2da95da8-2008-41f6-ad2d-1368cde923d5)

**Comment by paulgrimley** [comment]
@jaredfholgate is going to look into this AB#29528

**Comment by jaredfholgate** [comment]
Working on a reproduction. Then will figure out the best way to resolve without a high impact on all users.

**Comment by matt-FFFFFF** [comment]
Will be in the next release
