### ISSUE TITLE
archetype_config_overrides conflicts

### ISSUE THREAD

**Issue by scorgatelli** [Azure/terraform-azurerm-caf-enterprise-scale#758]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.5.2

**azure provider**: v3.63.0

**module**: v4.0.2

#### Describe the bug

There is a conflict when using `archetype_config_overrides` to specify both `enforcement_mode` and `parameters` for the same archetype.

- For `enforcement_mode`, the top-level keys must include the root_id (ie: org, org-landing-zones)
- For `parameters`, the keys must not include the root_id (ie: root, landing-zones)
- Based on which keys you choose, either the `enforcement_mode` or the `parameters` will not be applied

#### Steps to Reproduce

1. Configure `archetype_config_overrides` with top-level keys using the root id (ie: org, org-landing-zones)
2. Specify both `enforcement_mode` and `parameters` for the same archetype
3. Run terraform plan - the parameter overrides will not be applied
4. Change the top-level keys so they are not using the root id (ie: root, landing-zones)
5. Run terraform plan - the parameter overrides will now be applied, but the enforcement mode will not.

See the attached tf files and plan outputs for examples of the different scenarios.

#### Screenshots

N/A

#### Additional context

I believe this has to do with the difference in how parameters and enforcement is handled.

- In [locals.management_groups.tf](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/2a47653116a92a016ea835c792d05f57a8df7591/locals.management_groups.tf#L86C1-L94C2), it explicitly looks for the base names in `archetype_config_overrides` and maps the keys to the org-basename convention. It then merges this with the defaults. If you include the root id in the keys, then the mapping will not work and the defaults will not get overridden. 
- In [main.tf](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/2a47653116a92a016ea835c792d05f57a8df7591/main.tf#L19C1-L24C4), it does a lookup directly on `archetype_config_overrides` based on the basename of the `es_landing_zones_map` which includes the root id prefix. So, if the root id is missing from the key, it will not find the enforcement override.

#721 may be related to this.

#### Workaround

I am able to work around this by duplicating the configuration so that includes duplicate copies of the config using both keying methods. See the attached files for the workaround and resulting plan.

#### Examples
- Without the root id
[archetype_config_overrides_without-id.tf.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/11986724/archetype_config_overrides_without-id.tf.txt)
[plan-without-root-id.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/11986699/plan-without-root-id.txt)
- With the root id
[archetype_config_overrides_with_root_id.tf.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/11986698/archetype_config_overrides_with_root_id.tf.txt)
[plan-with-root-id.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/11986700/plan-with-root-id.txt)
- Workaround
[archetype_config_overrides_workaround.tf.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/11986697/archetype_config_overrides_workaround.tf.txt)
[plan-workaround.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/11986701/plan-workaround.txt)

**Comment by matt-FFFFFF** [comment]
Hi @eehret 

Yes this is intentional. The LA workspace is deployed by Terraform when configure_management_resources is enabled. We encountered race conditions in deployment so disabled the policy to avoid this.

We hope that consumers of the module manage the LA workspace through Terraform rather than relying on Policy to deploy such a resource.

**Comment by eehret** [comment]
@matt-FFFFFF I see.  Thanks for the clarification :)
