### ISSUE TITLE
bug: storage policy reporting non-compliance for existing resources

### ISSUE THREAD

**Issue by msp9799** [Azure/terraform-azurerm-caf-enterprise-scale#759]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:  1.4.6

**azure provider**:  3.54.0

**module**: 4.0.0 

#### Describe the bug

**[Related to storage accounts policies ]** There seems to be an issue with the new policy refresh to initiative **Deploy Diagnostic Settings to Azure Services** after upgrading the AZ LZ CAF Module to 4.0.0 version. Earlier below policies used to have same resource diagnostics logs profile name, but now seems all these policies have differnet profile names which is not aligned with the name setup in the initiative.

#### Steps to Reproduce

1. Go to portal and Choose initiative **Deploy Diagnostic Settings to Azure Services**
2. Go to view definition and search for porfilename parameter, it will show as default value **setbypolicy**
3. Now go to any of the below 5 polices mentioned in snapshots, the profilename is changed to align with resource name , not same as initiative , which was there earlier.

#### Screenshots

1. Initiative profile name set as default

<img width="989" alt="initiative" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/129297171/8d2c204b-fe87-4d1d-9b7c-3b12f7f71338">

2.  Storage policies in question.

<img width="915" alt="policy_defs" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/129297171/a7fdc32c-0030-4ee9-981c-70b03f482d3e">

3. Example of one the policy def with different diagnostics profile name than the initiative

<img width="1482" alt="policy_def_profilename" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/129297171/6218cf24-b126-4998-8658-c3e1731648e3">
 

#### Additional context

This initiative and polices underneath are built-in and managed by Microsoft, so we wanted to know the reason behind changing the default profile name in each policy defs which is resulting into non compliance to our security score. If you could help us understanding this and fixing this , that would be great to improve our secure score.

**Comment by matt-FFFFFF** [comment]
Hi @msp9799 

Have you tested the assignment with the default profile names?

From the `existenceCondition` in the policy, I can't see reference to the profile name:

```json
"existenceCondition": {
  "allOf": [
    {
      "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",
      "equals": "[parameters('logsEnabled')]"
    },
    {
      "field": "Microsoft.Insights/diagnosticSettings/metrics.enabled",
      "equals": "[parameters('metricsEnabled')]"
    },
    {
      "field": "Microsoft.Insights/diagnosticSettings/workspaceId",
      "equals": "[parameters('logAnalytics')]"
    }
  ]
},
```

Therefore, is there any other reason for the non-compliance? Can you see which resources are not compliant?

**Comment by msp9799** [comment]
This issue is specifically for storage account policies. if we take an example of storage account policy def below, it looks for the location profilename to be setup on the resource, whereas the initiative have differnet name "setbypolicy", if we change the name to setbypolicy, then these policy will be compliant.

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/129297171/131d994a-8d0e-4d65-a92b-843034a0b2ea)


Profilename in policy def

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/129297171/b4702e62-478e-439c-b5a6-c68a97abdff0)

Profilename in initiative, they both needs to be same to work. Other azure resource policies dont have profilename parameter in them, whereas these new storage account policies have and that too with different name than initiative.

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/129297171/d26453e0-a04d-454e-9b58-3cc9c0a73843)

**Comment by msp9799** [comment]
Just to add my reply, we are using the default settings only for these in-built parameters for assignment

profileName. Profile name "setbypolicy". Default value

The only thing is the policy defs for storage act have their own profilename , which is causing the problems in compliance.

**Comment by matt-FFFFFF** [comment]
I think this isn't an issue with the profile name. I cannot see anything in the policy logic that would report non-compliance based on the profile name. It also does not make sense that new resources are compliant, whereas existing resources are not.

In the non-compliant resources, can you use the portal to display a list of all instances that are non-compliance. I believe they may be the `default` instances, which would align with your explanation that new resources are correctly marked as compliant.

**Comment by matt-FFFFFF** [comment]
Tagging @paulgrimley

**Comment by Springstone** [comment]
I'm not sure I'm understanding the issue. [Configure diagnostic settings for Storage Accounts to Log Analytics workspace](https://www.azadvertizer.net/azpolicyadvertizer/59759c62-9a22-4cdf-ae64-074495983fef.html) is a built-in policy that has defined the default value for Profile Name as `storageAccountsDiagnosticsLogsToWorkspace`. However, in our ALZ default initiative assignment we override the Profile Name to be `setByPolicy`. 

What isn't working for you? Is it that your existing resources are configured with another Profile Name? Are you looking for a way to go back and update your existing storage account diag settings profile name to `setByPolicy`?

**Comment by msp9799** [comment]
Hi, our existing resources use to have the profile name as setbypolicy which got changed dont know how with the profile names mentioned differently in the policy defs . You are right we are looking for help on updating our  existing storage account diag settings profile name to setByPolicy so that it aligns with the policy assignment profile name

**Comment by jtracey93** [comment]
Hi @msp9799,

Just been taking a look into this and from what I can see the default value in the [initiative](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json#L29) and [assignment](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_resource_diag.tmpl.json) for `profileName` is `setbypolicy` (as expected)

Can you check your assignment of the initiative `Deploy-Diagnostics-LogAnalytics` and see what the parameter values are there on assignment, as this is what will be enforced and will override the default values in the initiative and it's child definitions as seen here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json#L841-L856

Let us know

**Comment by msp9799** [comment]
@jtracey93 , here is the snapshot of the assignment you have asked for. it also says setbypolicy, but dont know why our existing resources profilename got overwritten by the individial policy definitions i uploaded the snapshot at first.
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/129297171/2a99ff34-44d3-4102-9d89-51c2cc30f3e3)

**Comment by jtracey93** [comment]
What did you upgrade from in regards to the module version?

As back in December 2022 we swapped out the storage account child definitions in this initiative as documented here: https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#policy-6:~:text=Updated%20%22Deploy%20Diagnostic%20Settings%20to%20Azure%20Services%22%20initiative%20replacing%20deprecated%20policy%20for%20diagnostic%20settings%20on%20Storage%20Account 

So it may be the version of the module were on before was pre-December 2022 and this is why they have changed as we have migrated in the initiative to using the new built-in definitions

**Comment by msp9799** [comment]
We upgraded the caf module version from "3.0.0" to "4.0.0" on 16th June 2023.

**Comment by msp9799** [comment]
Thanks for the response @jtracey93 , could you pls help us how can we get this complaint now as policy defs have diff profilename than assignment?

**Comment by jtracey93** [comment]
Hey @msp9799 the policy definitions are irrelevant its what is sent on the assignment that takes effect.

you can look at what values are set for the parameter on the assignment via the portal, powershell or az cli.

For non-compliant resources that dont have diag settings with the correct profile name, but it is set as you desire on the assignment of the policy, just run a remediation task on the assignment and this should resolve it. You can then remove the old, incorrect diag settings profile names

**Comment by msp9799** [comment]
Hi , I tried starting the remediation task, it says confict error as the diag settings are allready available for the respource, here is the pic

{
    "status": "Failed",
    "error": {
        "code": "Conflict",
        "message": "Data sink '/XXXXXXXXX/resourceGroups/xxxx/providers/Microsoft.OperationalInsights/workspaces/es-la' is already used in diagnostic setting 'storageAccountsDiagnosticsLogsToWorkspace' for category 'Transaction'. Data sinks can't be reused in different settings on the same category for the same resource."
    }
}

**Comment by jtracey93** [comment]
Ah this is because they are targeting the same Log Analytics Workspace, so you will need to remove then, then run the remediation task.

Thanks

Jack

**Comment by msp9799** [comment]
So, if we take a reference  of this resource we have to remove diag settings storageAccountsDiagnosticsLogsToWorkspace and then run the remediation task?

**Comment by jtracey93** [comment]
> So, if we take a reference of this resource we have to remove diag settings storageAccountsDiagnosticsLogsToWorkspace and then run the remediation task?

Correct @msp9799

**Comment by msp9799** [comment]
@jtracey93 ...sure i will check and udpate

**Comment by msp9799** [comment]
Thanks @jtracey93 i was able to test them in my canary environment by removing the existing settings and running the remediation task again. 

I have a query, now i can see the new storage account diag settings are setup with below settings, is this expected behavour? we dont need diag settings for queue and table ?

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/129297171/1c87bcaa-3ca8-4f90-bd4d-b546dcbd5f52)

**Comment by jtracey93** [comment]
Hey @msp9799,

What tier/sku/type of storage account is this?

Also have you deployed anything into the queue or table services on that storage account?

Or have you set any policy assignment archetype_config_overrides? Or the enforcement modes?

**Comment by msp9799** [comment]
Hi,

1. For sandbox we are using Standard/Storage/ and for rest /Standard/StorageV2
2. No, i dont think we are using table or queue, so if we don't put any data on these services, the diag settings will be disabled ? and when we actually use it, the diag settings policy will kick in and set the settings?
3. We are only using built-in policies from MS and there is no overrides applied for this particular assignment.

**Comment by jtracey93** [comment]
I think this may be because of the storage account type/SKU. Can you test it with a v2 general purpose account and let us know?

**Comment by msp9799** [comment]
Hi @jtracey93 , the act i shared snapshot above is of StorageV2 (general purpose v2) type only.

**Comment by msp9799** [comment]
@jtracey93 , could you please share any update on this .

**Comment by jtracey93** [comment]
Hey @msp9799, apologies for delay I was OOF last week.

I have repro'd this today and I was then reminded this is a known issue for table and queue services as they have a `default` instance called `default` that is hidden, but you'd see it if you did a GET/LIST on them.

At this time there are no workarounds from the PG owning these polices, and as we don't own them or the storage service theres not a lot we can do. I'd advise opening a support case and take it further there.

**IMPORTANT:** thee policy does work correctly if you create a table or queue service on the storage account though, even if you call it default. It's just an annoying one that if you deploy a fresh storage account and not configure table or queue at all, you get this.

**Some workarounds from us:**

1. Create an exemption for the resources
    2. Could also use resource selectors on the exemption

### Previous Related Issues

- https://github.com/Azure/Enterprise-Scale/issues/1173
- https://github.com/Azure/Enterprise-Scale/issues/1203

With this in mind I will close this issue, but please let us know if you need further assistance.
