### ISSUE TITLE
Unable to create Azure Firewall - "address_prefixes.0" to not be an empty string

### ISSUE THREAD

**Issue by thy143** [Azure/terraform-azurerm-caf-enterprise-scale#761]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.3

**azure provider**: 3.64.0

**module**: 4.0.2

#### Describe the bug

Upon trying to deploy Azure Firewall (basic) to a existing vNet the following error is produced during the plan step:

```
╷
│ Error: expected "address_prefixes.0" to not be an empty string, got 
│ 
│   with module.enterprise_scale.azurerm_subnet.connectivity["/subscriptions/<removed>/resourceGroups/<removed>-connectivity-northeurope/providers/Microsoft.Network/virtualNetworks/<removed>-hub-northeurope/subnets/AzureFirewallManagementSubnet"],
│   on .terraform/modules/enterprise_scale/resources.connectivity.tf line 55, in resource "azurerm_subnet" "connectivity":
│   55:   address_prefixes     = each.value.template.address_prefixes
│ 
```

#### Steps to Reproduce

connecivity settings:

```
  configure_connectivity_resources = {
    settings = {
      hub_networks = [
        {
          enabled = true
          config = {
            address_space                = ["10.100.0.0/16", ]
            location                     = "northeurope"
            dns_servers                  = []
            subnets                      = [
            ]
            virtual_network_gateway = {
              enabled = false
            }
            azure_firewall = {
              enabled = false
              config = {
                address_prefix                = "10.100.0.0/24"
                enable_dns_proxy              = true
                dns_servers                   = []
                sku_tier                      = "Basic"
                base_policy_id                = ""
                private_ip_ranges             = []
                threat_intelligence_mode      = ""
                threat_intelligence_allowlist = []
                availability_zones = {
                  zone_1 = true
                  zone_2 = false
                  zone_3 = false
                }
              }
            }
....
```

The above configuration is based on https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings .

#### Screenshots

n/a

#### Additional context
 N/A

**Comment by luke-taylor** [comment]
Hey @thy143 because you have opted for the "Basic" SKU option the Azure Firewall Management subnet is necessary, please add             `address_management_prefix = "<Prefix>"` as a line in the `azure_firewall.config` map.

**Comment by thy143** [comment]
@luke-taylor  Thank you, that did the trick. I did not know basic SKU required it.
