### ISSUE TITLE
Feature Request - Deploy / Use muliple Log Analytics Workspaces

### ISSUE THREAD

**Issue by thy143** [Azure/terraform-azurerm-caf-enterprise-scale#763]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Currently we have a requirement that we deploy two different log analytics workspaces within different regions and configure resources to send logs to both log analytics workspaces.

Justification for this is LAW, is region bound and in the event Azure region was to have an issue, and we need to review logs from resources in a different region, we be unable to.

#### Describe the solution you'd like

Ability to create two different LAW instances and configure policy to configure logging to multiple instances.

And / Or

Provide the ability to give multiple LAW instance ID to configure policy to send logs to multiple LAW Instances

**Comment by matt-FFFFFF** [comment]
Hi,

We currently have no plans to support this as a core feature of this module. It's not currently a recommendation for ALZ.

**Comment by Mousling1992** [comment]
we also have the same requierement. Is this at the moment maybe planed ? Because it ll be great if we can use that.

**Comment by hannesbreit** [comment]
same here. Is there any chance to see this feature soon? It would be great to have this integrated natively, than creating our own stuff around CAF.
I cannot imagine that other customers do not need this, since data residency is a big topic for companies which act globally.
