### ISSUE TITLE
Customize Policy settings

### ISSUE THREAD

**Issue by thy143** [Azure/terraform-azurerm-caf-enterprise-scale#764]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.3

**azure provider**:  3.64.0

**module**: 4.0.2

#### Describe the bug

(This is not a bug – I don’t think, however i unable to work out how to achieve this form the documentation). 

There are two things I would like to do/achieve regarding policy assignment. On the “corp” management group, I would firstly like to permit only certain regions as deployable (I think I need to list ones I need to deny). The second thing, is I would like to disable the assign NSG policy for the certain management groups (as they way we create subnets does not seem to work with the policy set).

#### Steps to Reproduce

The below code is my attempt at denying certain regions:

```
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "4.0.2"

  default_location = "westeurope"

  providers = {
    azurerm              = azurerm.identity
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = "CAFROOTID"
  root_name      = "CAF ROOT NAME"

  deploy_core_landing_zones = true
  deploy_corp_landing_zones = true
  deploy_online_landing_zones = true

  archetype_config_overrides = {
    corp = {
      archetype_id = "CAFROOTID-corp"
      parameters =  {
          Deny-Resource-Locations = {
            listOfAllowedLocations = ["eastus", ]
          }
          Deny-RSG-Locations = {
            listOfAllowedLocations = ["eastus", ]
          }
        }
      access_control = {}
    }
  }
}
```

When i run this, i get this error:

```

│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with 12 attributes
│     │ local.archetype_id is "CAFROOTID-corp"
│
│ The given key does not identify an element in this collection value.
╵
```

#### Screenshots

N/A

#### Additional context

N/A

**Comment by thy143** [comment]
@luke-taylor   Thank you for getting back to me. 

I give that a go later today and confirm if it worked. Could i ask what the prefix of "es" stands for? 

Regading excluding a policy, how do you go about that? ie i want to disable the NSG policy as the `azurerm_virtual_network` resource does not let you set advance subnet features, so would like to use `azurerm_subnet` instead, which Azure Policy wont allow by default using your module.

I applogies if these are simple questions, English is not my first language and so far been unable to interpritate the docuementation correctly.

Side note: I notice i did not set a title. so just updated it

**Comment by luke-taylor** [comment]
Hey @thy143,

You could always continue to use the `archetype_config_overrides`
```hcl
...
 parameters = {
...
          Deny-Subnet-Without-Nsg = {
           effect = "Audit"
          }
...
}
```

This will the set the policy to audit as opposed to its default, Deny.

**Comment by thy143** [comment]
@luke-taylor I tried you suggest and had mix results.

When i define:
```
Deny-Subnet-Without-Nsg = {
          effect = "Audit"
        }
```
My Terraform plan always want to make a change, but nothing actually changes (policy still appled)

```

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.enterprise_scale.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/CAFROOTID-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deny-Subnet-Without-Nsg"] will be updated in-place
  ~ resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
        id                   = "/providers/Microsoft.Management/managementGroups/CAFROOTID-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deny-Subnet-Without-Nsg"
        name                 = "Deny-Subnet-Without-Nsg"
      - parameters           = jsonencode({})
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

"Deny-RSG-Locations" and "Deny-Resource-Locations" do not effect anything on the plan.



Config:
```

  deploy_core_landing_zones = true
  deploy_corp_landing_zones = true
  deploy_online_landing_zones = true

  subscription_id_overrides = {
    corp = [
      "<ID>"
      ]
  }

  deploy_identity_resources = true
  subscription_id_identity  = "<ID>"
  configure_identity_resources = local.configure_identity_resources

  deploy_management_resources    = true
  subscription_id_management = "<ID>"
  configure_management_resources = local.configure_management_resources

  deploy_connectivity_resources = false
  subscription_id_connectivity  = "<ID>"
  configure_connectivity_resources = local.configure_connectivity_resources

  archetype_config_overrides = {
    corp = {
      archetype_id = "es_corp"
      parameters =  {
        Deny-Subnet-Without-Nsg = {
          effect = "Audit"
        }
        Deny-Resource-Locations = {
          listOfAllowedLocations = [
            "westus",
            "uksouth",
            "westeurope"
          ]
       }
       Deny-RSG-Locations = {
          listOfAllowedLocations = [
            "westus",
            "uksouth",
            "westeurope"
          ]
       }
      }
      access_control = {}
    }
  }

```

Any idea why this might not be working?  

Thanks

**Comment by anwarnk** [comment]
Hi,

Have a look at this Wiki:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-built-in-archetype-definitions

That is how we got it to work.

Thanks

**Comment by thy143** [comment]
Thanks both,  I was hoping / thought i could overwrite it at a lower level. Once i targeted the "landing zone" level, the changes applied.  One thing i did notice is the Key seems to be case sensative.
