### ISSUE TITLE
Error: expected "address_prefixes.0" to not be an empty string

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/terraform-azurerm-caf-enterprise-scale#769]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.0

**azure provider**: 3.60.0

**module**: 4.0.2

### Description
Error: expected "address_prefixes.0" to not be an empty string, got 

  with module.connectivity.module.alz.azurerm_subnet.connectivity["/subscriptions/1ba2c686-9231-4bfd-bb2e-aadb1309cfac/resourceGroups/slz-connectivity-westeurope/providers/Microsoft.Network/virtualNetworks/slz-hub-westeurope/subnets/AzureFirewallManagementSubnet"],
  on .terraform/modules/connectivity.alz/resources.connectivity.tf line 55, in resource "azurerm_subnet" "connectivity":
  55:   address_prefixes     = each.value.template.address_prefixes

##[error]Error: Terraform Plan failed with exit code: 1

#### Describe the bug

on running terraform plan for Connectivity as we've have used the seperate State file for Core/Connectivity and managment version we get the error 

#### Steps to Reproduce

1. step 1 - terraform Init
2. step 2 - terraform Validate 
3. step 3 - terraform plan
4. you get it...

#### Screenshots

<img width="627" alt="image" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/109275604/f04d96ae-d859-46e3-bbcf-b2fdf2a91a07">
[error.msg.pdf](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/12078612/error.msg.pdf)

#### Additional context

I've attached screen shot the setting.connectivity.tf file

**Comment by luke-taylor** [comment]
Hey @ashley-kainos, 

If you're using the Basic SKU for the Azure Firewall you need to specify the `address_management_prefix` for the Management Subnet. 

Here's some sample code for deploying the Basic SKU that we test for:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/fcb459e26bbd199a5fa5d2f5b9e95a329c49d2b0/tests/modules/settings/settings.connectivity.tf#L84-L100

**Comment by ashley-kainos** [comment]
Hi Luke,

Thanks, for the reply. I've edited my settings.connectivity.tf to add the address_management_prefix as in your example but now get this error.

Error: Missing required argument
on main.tf line 35, in module "connectivity":
35: module "connectivity" {
The argument "firewall_management_address_prefix" is required, but no
definition was found.
##[error]Error: The process '/agent/_work/_tool/terraform/1.5.0/x64/terraform' failed with exit code 1
Finishing: Terraform : validate

Regards
Ashley

**Comment by ashley-kainos** [comment]
THis is now resolved and issue was not to do with code but Azure DevOPs not using the correct version of teh branch as changes were not syncing correctly to repo
