### ISSUE TITLE
Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#77]
## Problem statement

Since `2020-04-22`, the test framework has been unable to complete successfully despite the module working on individual deployments.

## Observations

- Some `Unit` pipeline jobs complete `terraform plan` without any problems, but others take up to 4x longer to complete, or fail to complete before Terraform terminates the operation with `Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded`.
- Re-running the failed `Unit` pipeline jobs will eventually end in success.
- Running the `E2E` pipeline jobs has the same issue as the `Unit` pipeline jobs. Assuming the job gets past the `terraform plan` step, `terraform apply` is unable to complete, and `terraform destroy` also then fails.
  - `terraform apply` terminates with error: `Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded`
  - `terraform destroy` terminates with error: `Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded`
- The module logic is working and can be deployed successfully, as long as the `429` errors aren't observed

There's clearly a common pattern linked to `Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded`, suggesting API throttling.

This requires further investigation as this wasn't previously an issue.

Although this is primarily a problem with our test framework, we have also observed this when running individual deployments from a workstation, mostly impacting 'terraform plan' and `terraform destroy`, but also when running `terraform apply` with a high setting for `-parallelism`.

## Similar issues

These issues also exhibit similar behaviors with the azurerm provider

- [Request throttling while deploying](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7694)
- [Request throttling while refreshing state](https://github.com/terraform-providers/terraform-provider-azurerm/issues/202)
- [Failure sending request: StatusCode=429](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9816)

## Call to customers

If you are seeing similar behaviour, please :+1: this Issue and add your comments below!

**Comment by krowlandson** [comment]
Proposed approach:

- [ ] Gather further evidence of the issue (how widespread is this problem)
- [ ] Investigate retry and backoff behaviour in Terraform / AzureRM provider / autorest (why is Terraform not backing off to allow the API to return to normal operation)
- [ ] Are customers being impacted by this?
- [ ] Can we tune the test framework down to reduce the impact of the API throttling without unreasonably increasing the test duration or reducing test coverage?

**Comment by dan-leanix** [comment]
Don't know if this is helpful but I left the following comment on the issue with the DNS resources.

> Whatever it is it was introduced with the Terraform Azure provider 2.x versions from the very beginning. We could reproduce it with version 2.1.0. So, I assume that this exists since version 2.0.0.
> 
> Terraform Azure provider version 1.44.0 just works.

https://github.com/terraform-providers/terraform-provider-azurerm/issues/9816

**Comment by krowlandson** [comment]
Interesting observation @dan-leanix... I've not had a chance to pinpoint the exact point where it became the primary method of controlling requests to the AzureRM API, but the autorest client was introduced from v2.3.0 so I suspect there was a general effort from v2.0.0 to change the way the provider interacts with the API.

In our particular case, there has clearly been a change on the platform side which is resulting in a provider throttling requests when it didn't previously. However 429 responses are common across most others, including the DNS service as mentioned in [Creating Over 2000 DNS Records Gives me StatusCode=429 hashicorp/terraform#27266](https://github.com/hashicorp/terraform/issues/27266).

Unfortunately it seems that when running high numbers of parallel tasks against the same API (on an individual Resource Provider / Service), Terraform isn't correlating related HTTP/429 responses, so the backoff isn't aggressive enough to let the API rate limiting to be lifted.

**Comment by krowlandson** [comment]
Workaround implemented by #80 but leaving issue open to collect additional feedback and in case additional work is needed.

Not ideal having to reduce parallelism setting from `256` to `50`.
