### ISSUE TITLE
Error: creating Azure Storage Account ..."Storage accounts should restrict network access","policyDefinitionEffect":"Deny"

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#771]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: Terraform v1.5.3

**azure provider**: 3.65.0

**module**: terraform-azurerm-caf-enterprise-scale-2.4.1

### Description

When creating and Azure Storage Account using terraform with public access disabled in the landing zone, a policy denies the storage account creation even though the terraform configuration specifies the correct parameters in the storage account to disable public access.

It appears the azure policy is ignoring the configuration parameters of the storage account which disable public access.

#### Describe the bug

Azure policy included in the `terraform-azurerm-caf-enterprise-scale v2.4.1` module seems to generate a false positive when deploying azure storage account in a landing zone.

#### Steps to Reproduce

Azure landing zone policy denies storage paas even though config is correct:

1. Public access is disabled in terraform

```
resource "azurerm_storage_account" "hk_caf_level4splunkea_sa" {
  name                     = azurecaf_name.hk_caf_level4splunkea_sa.result
  resource_group_name      = azurerm_resource_group.hk_caf_level4_lz000_app000_rg.name
  location                 = azurerm_resource_group.hk_caf_level4_lz000_app000_rg.location
  account_tier             = local.level4splunkea_sa["caf_sa_tier"]             //"Standard"
  account_replication_type = local.level4splunkea_sa["caf_sa_replication_type"] //GRS"

  //double encryption layer. requires storage rebuild
  infrastructure_encryption_enabled = false

  //provide a system assigned identity to allow the storage account to retrieve it's encryption key
  identity {
    type = "SystemAssigned"
  }

  //Explicitly deny public network access to this storage account
  //and anything in it. NOTE: This is disallowed by landing zone policy
  public_network_access_enabled   = false
  allow_nested_items_to_be_public = false

  tags = {
    environment = local.tags_lz000_app000_splunk["environment"]
    owner       = local.tags_lz000_app000_splunk["owner"]
    team        = local.tags_lz000_app000_splunk["team"]
    system      = local.tags_lz000_app000_splunk["system"]
    product     = local.tags_lz000_app000_splunk["product"]
    lifecycle   = local.tags_lz000_app000_splunk["lifecycle"]
    expiry      = local.tags_lz000_app000_splunk["expiry_date"]
  }
}

```

2. The plan indicates public access is disabled

```
Terraform will perform the following actions:

  # azurerm_storage_account.hk_caf_level4splunkea_sa will be created
  + resource "azurerm_storage_account" "hk_caf_level4splunkea_sa" {
      + access_tier                       = (known after apply)
      + account_kind                      = "StorageV2"
      + account_replication_type          = "GRS"
      + account_tier                      = "Standard"
      + allow_nested_items_to_be_public   = false
      + cross_tenant_replication_enabled  = true
      + default_to_oauth_authentication   = false
      + enable_https_traffic_only         = true
      + id                                = (known after apply)
      + infrastructure_encryption_enabled = false
      + is_hns_enabled                    = false
      + large_file_share_enabled          = (known after apply)
      + location                          = "eastasia"
      + min_tls_version                   = "TLS1_2"
      + name                              = "eanprdstsecurity002"
      + nfsv3_enabled                     = false
      + primary_access_key                = (sensitive value)
      + primary_blob_connection_string    = (sensitive value)
      + primary_blob_endpoint             = (known after apply)
      + primary_blob_host                 = (known after apply)
      + primary_connection_string         = (sensitive value)
      + primary_dfs_endpoint              = (known after apply)
      + primary_dfs_host                  = (known after apply)
      + primary_file_endpoint             = (known after apply)
      + primary_file_host                 = (known after apply)
      + primary_location                  = (known after apply)
      + primary_queue_endpoint            = (known after apply)
      + primary_queue_host                = (known after apply)
      + primary_table_endpoint            = (known after apply)
      + primary_table_host                = (known after apply)
      + primary_web_endpoint              = (known after apply)
      + primary_web_host                  = (known after apply)
      + public_network_access_enabled     = false
      + queue_encryption_key_type         = "Service"
      + resource_group_name               = "security-splunk-ea-nprd-rg-002"
      + secondary_access_key              = (sensitive value)
      + secondary_blob_connection_string  = (sensitive value)
      + secondary_blob_endpoint           = (known after apply)
      + secondary_blob_host               = (known after apply)
      + secondary_connection_string       = (sensitive value)
      + secondary_dfs_endpoint            = (known after apply)
      + secondary_dfs_host                = (known after apply)
      + secondary_file_endpoint           = (known after apply)
      + secondary_file_host               = (known after apply)
      + secondary_location                = (known after apply)
      + secondary_queue_endpoint          = (known after apply)
      + secondary_queue_host              = (known after apply)
      + secondary_table_endpoint          = (known after apply)
      + secondary_table_host              = (known after apply)
      + secondary_web_endpoint            = (known after apply)
      + secondary_web_host                = (known after apply)
      + sftp_enabled                      = false
      + shared_access_key_enabled         = true
      + table_encryption_key_type         = "Service"
      + tags                              = {
          + "environment" = "nprd"
        }

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }
    }

  # azurerm_storage_container.hk_caf_level4splunkea_sc will be created
  + resource "azurerm_storage_container" "hk_caf_level4splunkea_sc" {
      + container_access_type   = "private"
      + has_immutability_policy = (known after apply)
      + has_legal_hold          = (known after apply)
      + id                      = (known after apply)
      + metadata                = (known after apply)
      + name                    = "l4-splunk-ea-nprd-stct-002"
      + resource_manager_id     = (known after apply)
      + storage_account_name    = "eanprdstsecurity002"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

3. However the landing zone policy still thinks the resource is setting public access:

```
azurerm_storage_account.hk_caf_level4splunkea_sa: Creating...
╷
│ Error: creating Azure Storage Account "eanprdstsecurity002": storage.AccountsClient#Create: Failure sending request: StatusCode=403 -- Original Error: Code="RequestDisallowedByPolicy" Message="Resource 'eanprdstsecurity002' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Public network access should be disabled for PaaS services\",\"id\":\"/providers/Microsoft.Management/managementGroups/lolcorp-lz-000/providers/Microsoft.Authorization/policyAssignments/Deny-Public-Endpoints\"},\"policyDefinition\":{\"name\":\"Storage accounts should restrict network access\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/34c877ad-507e-4c82-993e-3452a6e0ad3c\"},\"policySetDefinition\":{\"name\":\"Public network access should be disabled for PaaS services\",\"id\":\"/providers/Microsoft.Management/managementGroups/lolcorp/providers/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints\"}}]'." Target="eanprdstsecurity002" AdditionalInfo=[{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"type","expressionKind":"Field","expressionValue":"Microsoft.Storage/storageAccounts","operator":"Equals","path":"type","result":"True","targetValue":"Microsoft.Storage/storageAccounts"},{"expression":"Microsoft.Storage/storageAccounts/networkAcls.defaultAction","expressionKind":"Field","expressionValue":"Allow","operator":"NotEquals","path":"properties.networkAcls.defaultAction","result":"True","targetValue":"Deny"}]},"policyAssignmentDisplayName":"Public network access should be disabled for PaaS services","policyAssignmentId":"/providers/Microsoft.Management/managementGroups/lolcorp-lz-000/providers/Microsoft.Authorization/policyAssignments/Deny-Public-Endpoints","policyAssignmentName":"Deny-Public-Endpoints","policyAssignmentParameters":{},"policyAssignmentScope":"/providers/Microsoft.Management/managementGroups/lolcorp-lz-000","policyDefinitionDisplayName":"Storage accounts should restrict network access","policyDefinitionEffect":"Deny","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/34c877ad-507e-4c82-993e-3452a6e0ad3c","policyDefinitionName":"34c877ad-507e-4c82-993e-3452a6e0ad3c","policyDefinitionReferenceId":"StorageDenyPaasPublicIP","policyExemptionIds":[],"policySetDefinitionDisplayName":"Public network access should be disabled for PaaS services","policySetDefinitionId":"/providers/Microsoft.Management/managementGroups/lolcorp/providers/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints","policySetDefinitionName":"Deny-PublicPaaSEndpoints"},"type":"PolicyViolation"}]
│ 
│   with azurerm_storage_account.hk_caf_level4splunkea_sa,
│   on main.tf line 37, in resource "azurerm_storage_account" "hk_caf_level4splunkea_sa":
│   37: resource "azurerm_storage_account" "hk_caf_level4splunkea_sa" {
```

4. The policy itself is this one implemented in the aztfmod CAF module (`enterprise-scale-2.4.1`):

https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deny-PublicPaaSEndpoints.html

I've tried some versions of azurerm provider:

- 3.65.0
- 3.25.0

I'm currently using aztfmod version: `2.4.1`

#### Additional context

In module v2.4.1 quite a number of the policies seem to generate false positives.

**Comment by matt-FFFFFF** [comment]
Hi @archmangler 

Can you upgrade to the latest version of this module?

I see you are using aztfmod, if you need help doing this then please raise an issue on that repo.

**Comment by archmangler** [comment]
Thanks, testing upgrade.

**Comment by archmangler** [comment]
I get this error when upgrading 2.4.1 -> 4.0.2:

```


Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/azurerm: no available releases match the given constraints
│ 3.24.0, >= 3.54.0
```

**Comment by archmangler** [comment]
@matt-FFFFFF  I get the following errors around policy upgrade:

```
```

│ Error: updating Policy Set Definition "Enforce-EncryptTransit": policy.SetDefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicySetParameterUpdate" Message="The existing policy has '28' parameter(s) which is greater than the count of parameter(s) '27' in the policy being added. Policy parameters cannot be removed during policy update."
│ 
│   with module.enterprise_scale.azurerm_policy_set_definition.enterprise_scale["/providers/Microsoft.Management/managementGroups/hkjc-lz-001/providers/Microsoft.Authorization/policySetDefinitions/Enforce-EncryptTransit"],
│   on ../modules/enterprise-scale-4.0.2/resources.policy_set_definitions.tf line 1, in resource "azurerm_policy_set_definition" "enterprise_scale":
│    1: resource "azurerm_policy_set_definition" "enterprise_scale" {
│ 
╵
╷
│ Error: updating Policy Set Definition "Enforce-EncryptTransit": policy.SetDefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicySetParameterUpdate" Message="The existing policy has '28' parameter(s) which is greater than the count of parameter(s) '27' in the policy being added. Policy parameters cannot be removed during policy update."
│ 
│   with module.enterprise_scale.azurerm_policy_set_definition.enterprise_scale["/providers/Microsoft.Management/managementGroups/hkjc-dev/providers/Microsoft.Authorization/policySetDefinitions/Enforce-EncryptTransit"],
│   on ../modules/enterprise-scale-4.0.2/resources.policy_set_definitions.tf line 1, in resource "azurerm_policy_set_definition" "enterprise_scale":
│    1: resource "azurerm_policy_set_definition" "enterprise_scale" {
│ 
╵
╷
│ Error: updating Policy Set Definition "Enforce-EncryptTransit": policy.SetDefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicySetParameterUpdate" Message="The existing policy has '28' parameter(s) which is greater than the count of parameter(s) '27' in the policy being added. Policy parameters cannot be removed during policy update."
│ 
│   with module.enterprise_scale.azurerm_policy_set_definition.enterprise_scale["/providers/Microsoft.Management/managementGroups/hkjc-lz-000/providers/Microsoft.Authorization/policySetDefinitions/Enforce-EncryptTransit"],
│   on ../modules/enterprise-scale-4.0.2/resources.policy_set_definitions.tf line 1, in resource "azurerm_policy_set_definition" "enterprise_scale":
│    1: resource "azurerm_policy_set_definition" "enterprise_scale" {
│ 
╵
╷
│ Error: updating Policy Set Definition "Enforce-EncryptTransit": policy.SetDefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicySetParameterUpdate" Message="The existing policy has '28' parameter(s) which is greater than the count of parameter(s) '27' in the policy being added. Policy parameters cannot be removed during policy update."
│ 
│   with module.enterprise_scale.azurerm_policy_set_definition.enterprise_scale["/providers/Microsoft.Management/managementGroups/hkjc-sat/providers/Microsoft.Authorization/policySetDefinitions/Enforce-EncryptTransit"],
│   on ../modules/enterprise-scale-4.0.2/resources.policy_set_definitions.tf line 1, in resource "azurerm_policy_set_definition" "enterprise_scale":
│    1: resource "azurerm_policy_set_definition" "enterprise_scale" {
│ 
╵
╷
│ Error: updating Policy Set Definition "Enforce-EncryptTransit": policy.SetDefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicySetParameterUpdate" Message="The existing policy has '28' parameter(s) which is greater than the count of parameter(s) '27' in the policy being added. Policy parameters cannot be removed during policy update."
│ 
│   with module.enterprise_scale.azurerm_policy_set_definition.enterprise_scale["/providers/Microsoft.Management/managementGroups/hkjc/providers/Microsoft.Authorization/policySetDefinitions/Enforce-EncryptTransit"],
│   on ../modules/enterprise-scale-4.0.2/resources.policy_set_definitions.tf line 1, in resource "azurerm_policy_set_definition" "enterprise_scale":
│    1: resource "azurerm_policy_set_definition" "enterprise_scale" {
│ 
```
```

**Comment by archmangler** [comment]
Is there some way I can disable "Enforce-EncryptTransit" policy in the module itself?

**Comment by matt-FFFFFF** [comment]
I think we cover this in the upgrade guides on the wiki

**Comment by matt-FFFFFF** [comment]
We do!

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v3.3.0-to-v4.0.0

**Comment by archmangler** [comment]
Thanks @matt-FFFFFF  - the upgrade seems to have resolved this issue.
