### ISSUE TITLE
feat: configure Hub Subnet Service Endpoints (e.g Microsoft.Storage) ?

### ISSUE THREAD

**Issue by archmangler** [Azure/terraform-azurerm-caf-enterprise-scale#773]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

- There is no mention in the documentation for the module on how to configure service endpoints (e.g Microsoft.Storage) in a given hub subnet.
- This means that these service endpoints must be specified outside of the module breaking the consistency of management.

#### Describe the solution you'd like

- Provide an example of how to configure a hub subnet service endpoint in the hub
- Something along the lines of (`variables.tf`):

```
      hub_networks = [
        {
          enabled = true
          config = {
            address_space                = ["10.216.0.0/20"]
            location                     = "eastasia"
            link_to_ddos_protection_plan = false
            dns_servers                  = []
            bgp_community                = "12076:20202"
            subnets = [
              {
                name                      = "hkjc-ea-hub00-sbt-shared00"
                address_prefixes          = ["10.216.0.0/24"]
                network_security_group_id = "/subscriptions/....-hub-001-nsg000"
                route_table_id            = null
                service_endpoints         = ["Microsoft.Storage"]
              },
              {
                name                      = "hkjc-ea-hub00-sbt-shared01"
                address_prefixes          = ["10.216.5.0/24"]
                network_security_group_id = "/subscriptions/....hub-001-nsg001"
                route_table_id            = null
                service_endpoints         = ["Microsoft.Storage"]
              },
              {
                name                      = "AzureBastionSubnet"
                address_prefixes          = ["10.216.6.0/24"]
                network_security_group_id = null
                route_table_id            = null
              },
.
.
.

```

#### Additional context

- Using terraform module version `4.0.2` with the following  configuration produces no effect or errors:

```
       subnets = [
              {
                name                      = "hkjc-ea-hub00-sbt-shared00"
                address_prefixes          = ["10.216.0.0/24"]
                network_security_group_id = "/subscriptions/....-hub-001-nsg000"
                route_table_id            = null
                service_endpoints         = ["Microsoft.Storage"]
              },
              {
                name                      = "hkjc-ea-hub00-sbt-shared01"
                address_prefixes          = ["10.216.5.0/24"]
                network_security_group_id = "/subscriptions/....hub-001-nsg001"
                route_table_id            = null
                service_endpoints         = ["Microsoft.Storage"]
              },
     

```

**Comment by archmangler** [comment]
Thanks @matt-FFFFFF  - Just to give some more context as to the general use case:

- This request comes up in deployments for enterprise customers.
- There is almost always a need to service endpoints to be associated to a given subnet in the hub, most often storage and keyvault since 'spoke' storage accounts  in enterprises are mandated to retrieve customer key and access credentials from keyvaults in a hub or access storage in a spoke from a hub deploy tool.
- Therefore if this feature is not present a post terraform script needs to run to add the service endpoint on existing subnets - or - the subnet must be managed in another terraform module.

Making service_endpoint part of the enterprise  module would provide an immensely convenient solution to this very hacky approach to managing azure infrastructure.

**Comment by matt-FFFFFF** [comment]
Noted @archmangler 

As a workaround could you create the subnet outside the module? I realise this might need a terraform state move...

**Comment by archmangler** [comment]
Hi @matt-FFFFFF 

Thanks for the suggestion. We'll need to use an alternative module for subnets. It will complicate the configuration and management process for cloud ops engineers by multiples and increase the probability of errors and failures, but I suppose there's no easier option for now.

**Comment by matt-FFFFFF** [comment]
Apologies @archmangler this is possible today with the advanced block:

See this post: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/711#issuecomment-1546602146

And here in the code: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/76a1c6dd1df2947d10ded7516cdbe1e6d0ed5294/resources.connectivity.tf#L60

**Comment by matt-FFFFFF** [comment]
@archmangler Appreciate the linked example is for a slightly different configuration, you can add the `service_endpoints` attribute instead and it should work

**Comment by archmangler** [comment]
Thanks @matt-FFFFFF  - this works:

```
.
.
.
              lolcorp-ea-hub00-sbt-shared01 = {
                service_endpoints = [
                  "Microsoft.Storage"
                ]
              },
.
.
.
```
