### ISSUE TITLE
Not able to assign policy set Deploy-Diagnostics-LogAnalytics

### ISSUE THREAD

**Issue by rvcu90** [Azure/terraform-azurerm-caf-enterprise-scale#774]
**terraform**: 1.5.1

**azure provider**:  v3.63.0

**module**: 4.0.2

### Description

I am trying to assign the policy Deploy-Diagnostics-LogAnalytics, however I am getting an error. 

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/130703568/93ab34c7-33d9-4fc0-8bd4-b7fdd3bf3ec5)

I am able to assign other policies from the CAF enterprise module except this one. 

#### Describe the bug

Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.policy_assignments.tf line 100, in locals:
│  100:       template    = local.archetype_policy_assignments_map[policy_assignment]
│     ├────────────────
│     │ local.archetype_policy_assignments_map is object with 49 attributes
│
│ The given key does not identify an element in this collection value.

#### Steps to Reproduce

1. Assign the Deploy-Diagnostics-LogAnalytics at the root archetype definition 
2. Use the custom_landing_zones variable which defines the root. 
3. Run terraform plan

**Comment by matt-FFFFFF** [comment]
Hi @rvcu90 

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_resource_diag.tmpl.json

You have to use the policy assignment name, not the policy (set) definition name.

**Comment by rvcu90** [comment]
I see! I used the ID that was showed on the [azadvertizer](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Diagnostics-LogAnalytics.html)

But thanks this will solve my issue.
