### ISSUE TITLE
Looking to Gain Better Understanding of How to Customize Policy/Role Assignments

### ISSUE THREAD

**Issue by lwooden** [Azure/terraform-azurerm-caf-enterprise-scale#776]
Hey All,

I've been pouring over all of the documentation concerning the module on how to customize it to fit my needs. I am struggling a bit to understand how to tailor policy/role definitions and assignments at specific scopes. I am trying to accomplish the following.

Under the Landing Zone Management Group I have (2) custom management groups defined:
```
Landing Zones
  Non-Prod
  Production
```

My desire is to set policy definitions/assignments at these levels because I will have department level management groups below them like so and I would like policy to flow down to those child MGs and their underlying subscriptions
```
Landing Zones
   Non-Prod                                                  <--- Non-Prod Policy Defs/Assignments HERE
     Department_1_Non-Prod                      <-- Custom Role Defs/Assignments HERE (diff team/user access, etc)
        Department_1_Dev-Test_Subscription
        Department_1_Staging_Subscription
     Department_2_Non-Prod                     <-- Custom Role Defs/Assignments HERE  (diff team/user access, etc);
        Department_2_Dev-Test_Subscription
        Department_2_Staging_Subscription
   Production                                                <--- Production Policy Defs/Assignments HERE
     Department_1_Production                    <-- Custom Role Defs/Assignments HERE (diff team/user access, etc)
        Department_1_Production_Subscription
     Department_2_Production                   <-- Custom Role Defs/Assignments HERE  (diff team/user access, etc);
        Department_2_Production_Subscription
```
I have the base of this setup so far in by code, but so far I have had no luck demystifying how to set up the policy and role assignments the way I would like to:

main.tf
```
....
custom_landing_zones = {
    "Non-Prod-MG" = {
      display_name               = "Non-Prod"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
      archetype_id   = "default_empty"
      parameters     = {}
      access_control = {}
    }
      }
    "Dept-1-Non-Prod-MG" = {
      display_name = "Dept-1-Non-Prod-MG"
      parent_management_group_id = "Non-Prod-MG"
      subscription_ids = []
      archetype_config = {
      archetype_id   = "default_empty"
      parameters     = {}
      access_control = {}

      }
    }
    "Prod-MG" = {
      display_name               = "Prod"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
      archetype_id   = "default_empty"
      parameters     = {}
      access_control = {}
    }
      }
    "Dept-1-Prod-MG" = {
      display_name = "Dept-1-Prod-MG"
      parent_management_group_id = "Prod-MG"
      subscription_ids = []
      archetype_config = {
      archetype_id   = "default_empty"
      parameters     = {}
      access_control = {}
      }
```

Any help in trying to get to this goal would be greatly appreciated.

**Comment by matt-FFFFFF** [comment]
Hi!

Sorry for the delay.

The policy files are in this repo in modules/archetype/lib.

You can copy them to your own lib directory and change them. This will replace the module defaults.

**Comment by lwooden** [comment]
Got it @matt-FFFFFF. One last question:

How do I deploy a subscription underneath the LandingZone Management Group? What files provide the definition for what that environment/subscription looks like? If you refer to the diagram posted in the base of the repository [https://github.com/Azure/terraform-azurerm-caf-enterprise-scale](url) you have a subscription deployed under

`
Landing Zones
  Corp
    Landing Zone A1
    Landing Zone A2
       *Landing Zone Subscription*
`

How do I define the configuration of a LandingZone subscription in that same manner?

**Comment by matt-FFFFFF** [comment]
Hi @lwooden 

Use archetype config overrides and supply the subscription id
