### ISSUE TITLE
Bug Report:  "privatelink.${local.lookup_azure_backup_geo_codes[location]}.backup.windowsazure.com" The given key does not identify an element in this collection value.

### ISSUE THREAD

**Issue by lupass93** [Azure/terraform-azurerm-caf-enterprise-scale#777]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
 terraform -version
Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/azure/azapi v1.8.0
+ provider registry.terraform.io/hashicorp/azurerm v3.54.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1

**terraform**: v1.5.4

**azure provider**:
+ provider registry.terraform.io/azure/azapi v1.8.0
+ provider registry.terraform.io/hashicorp/azurerm v3.54.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1

**module**:

  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "v4.1.0" 

### Description

Starting From:

`
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.54.0"
    }
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_client_config" "core" {}

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "v4.1.0" 

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  default_location  = "North Europe"

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = "LuPassOrg"
  root_name      = "LuPass Organization"
}
`

#### Describe the bug

Running terraform apply or terraform plan we got this error:
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/enterprise_scale/modules/connectivity/locals.tf line 1448, in locals:
│ 1448:       "privatelink.${local.lookup_azure_backup_geo_codes[location]}.backup.windowsazure.com"
│     ├────────────────
│     │ local.lookup_azure_backup_geo_codes is object with 67 attributes
│ 
│ The given key does not identify an element in this collection value.

#### Steps to Reproduce

1. step 1 terraform init
2. step 2 terraform apply 

#### Screenshots
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/35664309/03a16566-208c-4b33-8c24-cd735a5adea8)

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/35664309/160e910f-6146-4192-8145-d30306e922b5)

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/35664309/692d4b0a-f714-4590-b52a-87b6687dadc4)

#### Additional context

Now, it is impossible to use this module.

**Comment by lupass93** [comment]
Thank you very much @jtracey93 . Now seems to work!

Is it possible to add this information about the format in the docs?  The provider’s resources accept the word "North Europe", so anyone could fall into this error.

Thank you very much!

Luca

**Comment by jtracey93** [comment]
Hey @lupass93 

Glad it's working. We might be better off making it accept both and do a lookup on both short and full name. 

I'll take a look or feel free to PR in yourself 👍
