### ISSUE TITLE
Creating Subscriptions needed for this module

### ISSUE THREAD

**Issue by letmetechyou** [Azure/terraform-azurerm-caf-enterprise-scale#781]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.4

**azure provider**: 3.66

**module**: 4.1.0

#### Describe the bug

When running the deploy_connectivity_resources and configure_connectivity_resources, is there a way for subscriptions to be created for that.  Do i need to pair this with the lz vending module first to create the subscriptions then use this module.

**Comment by matt-FFFFFF** [comment]
Hi @letmetechyou 

You can use lz-vending to do this yes - just create the subscription but do not set the management group membership in the lz-vending module as this module will manage that. I recommend disabling strict subscription association.

Subscription creation is not in scope for this module.

**Comment by letmetechyou** [comment]
With the creation of the subscriptions.  We have the need to have it created under a specific enterprise agreement user account.  Is there a way to specifically do that.

**Comment by matt-FFFFFF** [comment]
> With the creation of the subscriptions.  We have the need to have it created under a specific enterprise agreement user account.  Is there a way to specifically do that. 

You will need to configure another provider alias for the AzureRM provider and pass that into the LZ vending module.

You should use a workload identity (service principal) and grant access to the billing account on the EA. Using a user account will not work when using automation, e.g. GitHub actions.

**Comment by letmetechyou** [comment]
ok thanks yea that did work.  I had one other question in regards to subscriptions.  If I say for instance wanted 2 connectivity subscriptions to use the configure_connectivity_resources argument how can i do that and use different local values without duplicating code. Or is it just best practice to have one subscription that manages the connectivity resources.

**Comment by matt-FFFFFF** [comment]
Hi!

You can add the other subscription in using archetype config overrides.

You'd could then use the module again to deploy connectivity resources.
