### ISSUE TITLE
Log Analytics solutions for AMA and MDFC can't be configured

### ISSUE THREAD

**Issue by rikunarhi-cloud2** [Azure/terraform-azurerm-caf-enterprise-scale#783]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

AMA requires 2 solutions to be deployed with MDFC. https://learn.microsoft.com/en-us/azure/defender-for-cloud/auto-deploy-azure-monitoring-agent#log-analytics-workspace-solutions. These solutions currently can't be configured. Only Security solution can be configured if ``enable_sentinel`` is added. 

#### Describe the solution you'd like

I would like to be able to add both Security and SecurityCenterFree solution to the Log Analytics created by the module.

The solutions could be enabled independently  with for example parameters ``enable_solution_for_security`` and ``enable_solution_for_securitycenterfree`` or this could be done with one ``enable_solution_for_azure_monitor_agent_mdfc`` that would deploy both solutions.

#### Additional context

I understand that this might not be in the scope of the enterprise scale as the AMA with MDFC is still in preview

**Comment by jtracey93** [comment]
Hey @rikunarhi-cloud2,

I'd advise a review and read of this article before committing to AMA and MDFC: https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/microsoft-defender-for-cloud-strategy-and-plan-towards-log/ba-p/3883341

**Comment by rikunarhi-cloud2** [comment]
Hey,

Thank you I had missed this blog post totally. This is enough information in my option that this can be closed. I will check if something changes with the MDFC agent in the future
