### ISSUE TITLE
Can't set policy parameter with es_corp and Deploy-Private-DNS-Zones

### ISSUE THREAD

**Issue by anthonhassel** [Azure/terraform-azurerm-caf-enterprise-scale#788]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.4.6

**azure provider**: v3.68.0

**module**: enterprise_scale

#### Describe the bug

We are trying to configure the "Configure Azure PaaS services to use private DNS zones" with the es_corp archetype_id since we already have the private DNS Zones deployed. But for some reason, Terraform doesn't seem to pick up the changes. I have tried other assignments like resource location and it works fine.

Is there something wrong in the following code:

```json
{
    "extend_es_corp": {
      "policy_assignments": ["Deploy-Private-DNS-Zones"],
      "policy_definitions": [],
      "policy_set_definitions": [],
      "role_definitions": [],
      "archetype_config": {
        "parameters": {
          "Deploy-Private-DNS-Zones": {
            "azureAcrPrivateDnsZoneId": "/subscriptions/0000000-0000-0000-0000-000000000000/resourceGroups/dnszones-rg/providers/Microsoft.Network/privateDnsZones/privatelink.his.arc.azure.com"
          }
        },
        "access_control": {}
      }
    }
  }
```

**Comment by matt-FFFFFF** [comment]
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/archetype_definitions/archetype_definition_es_corp.tmpl.json

You see here that that policy is already enabled for the corp MG.

You can add this parameter with the archetype_config_overrides variable.

**Comment by anthonhassel** [comment]
Thank you Matt for your quick answer! :)

I did manage to get it working with archetype_config_overries:

```json
 archetype_config_overrides = {
    corp = {
      archetype_id = "es_corp"
      parameters = {
        Deploy-Private-DNS-Zones = {
          azureMachineLearningWorkspacePrivateDnsZoneId = "Test"
        }
      }
      access_control = {
      }
    }
  }
```

But if that is the solution I'm a little bit confused why the extend_es_corp didn't work? What is the difference in this case?

**Comment by matt-FFFFFF** [comment]
Extend is to add additional resources to the archetype. E.g. a new assignment altogether.

**Comment by anthonhassel** [comment]
> Extend is to add additional resources to the archetype. E.g. a new assignment altogether.

Ok, that makes sense. Thank you Matt for the help! :)
