### ISSUE TITLE
Unable to deploy firewall when tagging policy is enforced

### ISSUE THREAD

**Issue by cyb3n3tic** [Azure/terraform-azurerm-caf-enterprise-scale#790]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.5

**azure provider**: 3.67.0

**module**: source = "Azure/caf-enterprise-scale/azurerm"
version = "v4.1.0"

### Description

I have applied a mandatory tagging policy and having done so I am nolonger able to deploy an Azure standard firewall, which deployed before tagging was enforced. I have read the closed issues relating to this but still can't pin down how to apply a suitable fix for this. 

In issue #531 Kevin suggests  the configure_connectivity_resources.settings.tags option but I was unable to make sense from there.

I have tried using tags     = var.connectivity_resources_tags in settings.connectivity.tf and variable "default_tags" in variables.tf but clearly I'm missing something obvious and would appreciate being set straight please. Thanks in advance.

#### Describe the bug

Having applied mandatory tags policy using policy_set_definition_enforce_mandatory_tags and running terraform apply the errors as attached are logged and the plan fails.

#### Steps to Reproduce

1. Added Enforce-Mandatory-Tags via policy_set_definition_enforce_mandatory_tags.json in /lib/policy_set_definitions
2. Populated variable "connectivity_resources_tags" in variables.tf to conform with policy
3. Terraform Plan

[Policy violation.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/12357449/Policy.violation.txt)

**Comment by cyb3n3tic** [comment]
In an attempt to move forward I have tried removing the tagging policy but now got to a position where I cannot even get past terraform plan with everything as it was, I now received Error: Attempt to get attribute from null value and Error: Insufficient policy_definition_reference blocks - see plan errors attached.
[Plan errors.txt](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/12360902/Plan.errors.txt)

**Comment by jtracey93** [comment]
It looks like from the errors, the policy initiative/set definition is invalid as a file as it cant find properties within it. Likely a missing bracket or comma somewhere

**Comment by jtracey93** [comment]
As for the initial tagging question you have the following options:

1. Use `default_tags` variable at root of the module
2. Specify `configure_connectivity_resources.settings.tags` to apply tags to all connectivity resources
3. Or declare a custom advanced in `configure_connectivity_settings` block like below for each resource you want to set tags on:

```hcl
# inside configure_connectivity_settings block
advanced = {
  custom_settings_by_resource_type = {
    azurerm_firewall = {
      connectivity = {
        ukwest = { # Replace 'ukwest' with the location you are deploying this resource to
          tags= {
            Application = ""
            Criticality = ""
            Environment = ""
            Owner = ""
          }
        }
      }
    }
  }
}
```

Hope that helps

**Comment by cyb3n3tic** [comment]
Thanks Jack, it was an error in archetype_extension_es_root.tmpl.json in the end so I'm now back to addressing the tagging policy at least.

Where is configure_connectivity_resources.settings.tags placed and would it simplyt have a tag block underneath like this?

          tags = {
            Department = "IT"
            Owner = "Joe Blogs"
            }

**Comment by jtracey93** [comment]
Hey,

Yup its a block just like that of key/value pairs.

It goes anywhere inside the 

```
configure_connectivity_resources = {
    settings = {
    ... # other properties removed for ease of reading
    tags     = {
        Department = "IT"
        Owner = "Joe Blogs"
    }
  }
}
```

A full example of the `configure_connectivity_resources` block is available here in the wiki: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings#settingsconnectivitytf

> look near the bottom for tags

**Comment by cyb3n3tic** [comment]
Thanks again. I have now resolved all issues and have a fully tagged deployment. Only remaining issue is that the actual firewall is not being created now, just a  policy and the various network bits - any ideas how to give it a nudge to solve that?

azure_firewall = {
              enabled = true

Same settings worked a few days ago, maybe worthwhile deleting the state file (test env)?

**Comment by jtracey93** [comment]
Awesome 👍 

Id suggest making sure your blocks for `configure_connectivity_resources` aligns to the wiki page: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Connectivity-Resources-With-Custom-Settings

**Comment by cyb3n3tic** [comment]
Ignore that, pilot fixation on my part! I wasn't completing the pipeline process!

Thanks for the help, all good now.

One thing I haven't got clear in my mind is where configure_connectivity_resources.settings.tags could fit in - I haven't been able to find that explained in the wiki but Kevin also referenced it in #531

**Comment by jtracey93** [comment]
its just for if you want to set different tags for just the connectivity module resources as you'd set for other resources, like management etc...

Hope that helps, will close this one out now as resolved
