### ISSUE TITLE
unable to configure vpn_client_configuration due to revoked_certificate block defined with wrong parameters 

### ISSUE THREAD

**Issue by gogondi1** [Azure/terraform-azurerm-caf-enterprise-scale#791]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions  4.2,4.1

**terraform**:  Terraform v1.5.5
**azure provider**:  v3.61.0
**module**: [terraform-azurerm-caf-enterprise-scale](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale)
### Description
Variable virtual_network_gateway revoked_certificate defined wrongly

#### Describe the bug
Error: Invalid value for input variable
│ 
│   on main.tf line 145, in module "caf-enterprise-scale-networking":
│  145:   configure_connectivity_resources = local.configure_connectivity_resources
│ 
│ The given value is not suitable for module.caf-enterprise-scale-networking.var.configure_connectivity_resources declared at .terraform/modules/caf-enterprise-scale-networking/variables.tf:174,1-44: attribute
│ "settings": attribute "hub_networks": incorrect list element type: attribute "config": attribute "virtual_network_gateway": attribute "config": attribute "advanced_vpn_settings": attribute
│ "vpn_client_configuration": incorrect list element type: attribute "revoked_certificate": element 0: attribute "public_cert_data" is required.

#### Steps to Reproduce

1. step 1 : enabling vpn_client_configuration
2. step 2: provides revoked_certificate details
4. you get it...

#### Screenshots

![Screenshot 2023-08-16 at 15 48 44](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/53465177/9437ec9e-fd46-406e-bb2d-1d44280d9a9f)
![Screenshot 2023-08-16 at 15 52 19](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/53465177/6392218a-b5da-4eea-8c44-c3de82733d3a)

`Error: Invalid value for input variable
│ 
│   on main.tf line 145, in module "caf-enterprise-scale-networking":
│  145:   configure_connectivity_resources = local.configure_connectivity_resources
│ 
│ The given value is not suitable for module.caf-enterprise-scale-networking.var.configure_connectivity_resources declared at .terraform/modules/caf-enterprise-scale-networking/variables.tf:174,1-44: attribute
│ "settings": attribute "hub_networks": incorrect list element type: attribute "config": attribute "virtual_network_gateway": attribute "config": attribute "advanced_vpn_settings": attribute
│ "vpn_client_configuration": incorrect list element type: attribute "revoked_certificate": element 0: attribute "public_cert_data" is required.

`[](url)`

**Comment by matt-FFFFFF** [comment]
fixed in v5
