### ISSUE TITLE
Want to understand Subscription assignments to MGs better

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/terraform-azurerm-caf-enterprise-scale#793]
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Latest Version on Terraform, Provider and CAF module

### Description
Want to understand better how to move Subscriptions into Decommissioned MG , Sandbox MG and LZ MGs better when using a setup based on  "400-multi-with-remote-state"

#### Steps to Reproduce
Have edited Settings.core.tf as in screen shot below
#### Screenshots
<img width="288" alt="decomissioned_settings_core_tf" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/109275604/a5d41704-c443-49f3-a9b2-010982e47c3d">

**Comment by ashley-kainos** [comment]
In basic terms when we add the Subscription to the settings.core.tf under the section for that management group the Subscription remains in Root MG and doesn't move

**Comment by jtracey93** [comment]
Sounds like a bug but I can't help noticing the code syntax highlighting in your screenshot isnt right either. 

Couple of things, don't think the variables should have Var with a capital, also dont think they should be wrapped in quotes as you want the values of them not the string literal of var.xzy.....

Change these and let us know

**Comment by ashley-kainos** [comment]
so tried a few different formats so even if I do it as shown below, it still doesn't move the subscriptions
Decommissioned = {
    "${var.root_id}-decommissioned" = {
      display_name               = "decommissioned"
      parent_management_group_id = "${var.root_id} Organisation"
      subscription_ids           = [
        "648b9e67-6f78-4ae2-b729-c2466fd0a8e2", 
        "b1cdc9c0-de05-4c7b-b29c-6dcf7e815a8b", 
        "525b2b0d-f4b4-4d0a-9b8c-c286294b2335", 
        "bee53a59-8c39-4831-b113-d66083fd6237", 
        "f7ceb774-15e9-46ec-a0ca-b73607c07572"
        ]           
      archetype_config = {
        archetype_id   = "Decommissioned"
        parameters     = {}
        access_control = {}
      }

**Comment by jtracey93** [comment]
@ashley-kainos that looks better but i think the top key name should be lowercase `decommissioned` and also for the `archetype_id` this is should be `es_decommissioned`

Can you try those and give it a go?
