### ISSUE TITLE
Wrong policy assignments in archetype_exclusion_es_landing_zones.tmpl.json

### ISSUE THREAD

**Issue by Maestroff** [Azure/terraform-azurerm-caf-enterprise-scale#797]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Describe the bug

Wrong policy assignment examples in archetype_extension_es_landing_zones.tmpl.json  There are no such assignments in the repository.
/archetype_definitions

#### Steps to Reproduce

1. add exclusion using the guide in here https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions
2. terraform plan
3. terraform won't show any difference between the state and your configuration

#### Additional context
to got this working I've used the correct policy assignments 
"policy_assignments": [
        "Deny-Priv-Esc-AKS",
        "Deny-Privileged-AKS",
        "Enforce-AKS-HTTPS"
      ],

**Comment by JefferyMitchell** [comment]
@jaredfholgate 

Items to check-
-archetype definitions update
-review for additional updates

**Comment by jaredfholgate** [comment]
@Maestroff these docs have been updated to match the refreshed policies, it will go out in out next release. Thanks for reporting.
