### ISSUE TITLE
Bug Report - subscription_id_overrides not assigning subscriptions to Default Management Groups

### ISSUE THREAD

**Issue by letmetechyou** [Azure/terraform-azurerm-caf-enterprise-scale#800]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.6

**azure provider**: azurerm

**module**: Azure/caf-enterprise-scale/azurerm

#### Describe the bug

When defining 
`  subscription_id_overrides = {
   Decommissioned = [
    "0000000-0000-0000-000000000000"
   ]
  }`

no change is detected and does not move a subscription into the Decommissioned management group

**Comment by jtracey93** [comment]
Hey @letmetechyou,

Can you try this with a lowercase `D` e.g. `decommissioned`?

**Comment by letmetechyou** [comment]
I tried that and it didn’t work either

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jtracey93** [comment]
Thanks for letting us know, we may have a bug as #793 is similar.

cc: @matt-FFFFFF, @luke-taylor, @jaredfholgate for awareness

**Comment by letmetechyou** [comment]
`
module "alz" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "4.1.0" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  # Base module configuration settings
  root_parent_id = data.azurerm_client_config.current.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  disable_telemetry = true
  library_path   = "${path.module}/lib"

  # Enable creation of the core management group hierarchy
  # and additional custom_landing_zones
  deploy_core_landing_zones = true
  custom_landing_zones      = local.custom_landing_zones
  default_location = "centralus"


  # Configuration settings for identity resources is
  # bundled with core as no resources are actually created
  # for the identity subscription
  deploy_identity_resources    = true
  configure_identity_resources = local.configure_identity_resources
  subscription_id_identity     = var.subscription_id_identity

  subscription_id_overrides = {
   decommissioned  = [
    ""
   ]
  }

  # The following inputs ensure that managed parameters are
  # configured correctly for policies relating to connectivity
  # resources created by the connectivity module instance and
  # to map the subscription to the correct management group,
  # but no resources are created by this module instance
  deploy_connectivity_resources    = false
  #configure_connectivity_resources = data.terraform_remote_state.connectivity.outputs.configuration
  subscription_id_connectivity     = data.terraform_remote_state.connectivity.outputs.subscription_id

  # The following inputs ensure that managed parameters are
  # configured correctly for policies relating to management
  # resources created by the management module instance and
  # to map the subscription to the correct management group,
  # but no resources are created by this module instance
  deploy_management_resources    = false
  #configure_management_resources = data.terraform_remote_state.management.outputs.configuration
  subscription_id_management     = data.terraform_remote_state.management.outputs.subscription_id
}
`

**Comment by letmetechyou** [comment]
Ah dang it never mind i see what is wrong i had mine misspelled.

**Comment by luke-taylor** [comment]
@letmetechyou no problem, are you happy for me to close the issue?

**Comment by letmetechyou** [comment]
yes good to close
