### ISSUE TITLE
Bug Report Missing prerequisites - example level 200 Deploy management resources fails with error 400

### ISSUE THREAD

**Issue by themathmagician** [Azure/terraform-azurerm-caf-enterprise-scale#801]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.6 (using Terraform Cloud)

**azure provider**: 3.71.0

**module**: 4.2.0

#### Describe the bug

I am missing a prerequisites section, that will describe what permissions the Terraform service principal should have in order to be able to run your examples.
On level 200, I am  getting a 400 error, when trying the [Deploy management resources](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Management-Resources) example.
(The permissions were fine for the previous examples.)

I would appreciate, if a guidance is given, for the minimal set of IAM permissions required for the service principal, in order to be able to run the terraform code.

#### Steps to Reproduce

1. Create a service principal, with Contributor role to a subscription

Run the following code in the root module
```
module "enterprise_scale" {
  source = "Azure/caf-enterprise-scale/azurerm"
  version = "4.2.0"

  default_location = var.location

  providers = {
    azurerm = azurerm
    azurerm.connectivity = azurerm
    azurerm.management = azurerm
  }

  root_parent_id = data.azurerm_client_config.client_config.tenant_id
  root_id = local.root_id
  root_name = local.root_name

  deploy_management_resources = true
  # the workspace that deploys this module is connected to the management subscription
  subscription_id_management = var.subscription_id   # <---- this is the offending line
}
```

Core ressources get created, but the module fails to move the subscription into the "management" management group.
Here is the error message: 

> Error: [DEBUG] Error assigning Subscription ID "xxx" to Management Group "xx-management": 
> managementgroups.SubscriptionsClient#Create: Failure responding to request: StatusCode=400 -- Original Error:
> autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Permission to write and delete on
> resources of type 'Microsoft.Authorization/roleAssignments' is required on the subscription or its ancestors." 
> Details[{"raw":"Subscription ID: '/subscriptions/xxx'"}]
> with module.enterprise_scale.azurerm_management_group.level_3["/providers/Microsoft.Management/managementGroups/xx-management"]
> on .terraform/modules/enterprise_scale/resources.management_groups.tf line 31, in resource "azurerm_management_group" "level_3":

**Comment by jtracey93** [comment]
Please review the required permissions here: https://learn.microsoft.com/azure/governance/management-groups/overview#moving-management-groups-and-subscriptions

**Comment by themathmagician** [comment]
Thanks, will look at it!

Generally, it would be extremely helpful, if the pre-requisites were stated. 

I will go and hunt down our Global Admin - are you aware, whether there are any other permissions needed for the service principal to run the terraform code with this module ?

**Comment by jtracey93** [comment]
Hi @themathmagician, they are all listed here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Module-Permissions

Thanks

**Comment by themathmagician** [comment]
Thanks 😃
