### ISSUE TITLE
Azure China Support?

### ISSUE THREAD

**Issue by binaryPUNCH** [Azure/terraform-azurerm-caf-enterprise-scale#802]
Hello maintainers!

We are now in the early phases of assessing Azure China in a single subscription. In preparation for a potential upscaling, we wanted to be a bit proactive and ask here how well this repository and the services used within are supported on Azure China. 

Management groups, policies, Defender for Cloud, log analytics workspace, etc. These foundational building blocks should hopefully just work?

I'm aware it's a different story for many other services, but at least `terraform-azurerm-caf-enterprise-scale` should be fully covered? Or are there any caveats?

Thanks!

**Comment by matt-FFFFFF** [comment]
Hi @binaryPUNCH 

The module works well with Azure China, however you must exclude the policy definitions that do not exist.
