### ISSUE TITLE
wrong example for archetype_config_overrides.tf

### ISSUE THREAD

**Issue by Maestroff** [Azure/terraform-azurerm-caf-enterprise-scale#803]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Describe the bug

The following guide is not working the way it should. The example needs to be fixed. Here is the link to the guide https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-policies-without-enforcing-them

#### Steps to Reproduce

1. Declare archetype_config_overrides.tf
2. Set a reference to archetype_config_overrides.tf in the main.tf
3. run terraform plan

#### Additional context

To get this working I've used the following archetype_config_overrides.tf 
locals {
  archetype_config_overrides = {
    landing-zones = {
      archetype_id = "es_landing_zones"
      enforcement_mode = {
        "Audit-AppGW-WAF"         = false,
        "Deny-IP-forwarding"      = false,
        "Deny-MgmtPorts-Internet" = false,
        "Deny-Priv-Esc-AKS"       = false,
        "Deny-Privileged-AKS"     = false,
        "Deny-Storage-http"       = false,
        "Deny-Subnet-Without-Nsg" = false,
        "Deploy-AKS-Policy"       = false,
        "Deploy-AzSqlDb-Auditing" = false,
        "Deploy-SQL-Threat"       = false,
        "Deploy-VM-Backup"        = false,
        "Enable-DDoS-VNET"        = false,
        "Enforce-AKS-HTTPS"       = false,
        "Enforce-GR-KeyVault"     = false,
        "Enforce-TLS-SSL"         = false,
      }
      parameters     = {}
      access_control = {}
    }
  }

}

**Comment by jaredfholgate** [comment]
@Maestroff Please could you supply the exact error you are seeing and also show us the content of your `main.tf` (redacted if necessary. Thanks

**Comment by chrholt** [comment]
I can relate to this. Trying to override an enforcement on `Deny-Public-IP` assignment on identity archetype.
Using the example in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-policies-without-enforcing-them I was not able to influence the changes shown in plan.

Finally after trying this I could change the enforcement of `Deny-Public-IP`
```
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "4.2.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }
....
....
....
....
archetype_config_overrides = {
    identity = {
      archetype_id = "es_identity"
      enforcement_mode = {
        "Deny-Public-IP"          = true
      }
    }
  }
```

Using 
```
archetype_config_overrides = {
    <root_id>-identity = {
      enforcement_mode = {
        Deny-Public-IP = true
      }
``` 
as stated in the example did not give any error at all. Just not altering the result of plan.

I started to wonder after looking at [variables.tf](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/variables.tf#L461) and got it to work as expected after finding this issue.

**Comment by jaredfholgate** [comment]
@Maestroff and @chrholt This has been fixed in the code and will be deployed in the next release.
