### ISSUE TITLE
deploy-mdfc-config 4 policies still set to DeployIfNotExists

### ISSUE THREAD

**Issue by mehliku** [Azure/terraform-azurerm-caf-enterprise-scale#809]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.6

**azure provider**:
azurerm 3.54.0

**module**:
registry.terraform.io/Azure/caf-enterprise-scale/azurerm 4.2.0

### Description

Using CAF module 4.2.0, deploying initiative 'deploy-mdfc-config' out-of-the-box. Looking at the assignment file
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/v4.2.0/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_mdfc_config.tmpl.json

the following 4 values are set to disabled.

enableAscForApis							
enableAscForCosmosDbs						
enableAscForCspm							
enableAscForServersVulnerabilityAssessments

However, once deployed im seeing these values in the portal set to 

enableAscForApis							Effect	"DeployIfNotExists"	User defined parameter
enableAscForCosmosDbs						Effect	"DeployIfNotExists"	User defined parameter
enableAscForCspm							Effect	"DeployIfNotExists"	User defined parameter
enableAscForServersVulnerabilityAssessments	       Effect	"DeployIfNotExists"	User defined parameter
#

Ive tried to override the paramter using the archetype 'archetype_extension_es_root.tmpl.json'

               "Deploy-MDFC-Config": {
                    "vulnerabilityAssessmentProvider": {
                        "value": "mdeTvm"
                      },
                    "enableAscForServersVulnerabilityAssessments":{
                        "value":"Disabled"
                    }  
                }

not able to set this value to 'Disabled'

#### Screenshots
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/107051454/f1eccc7c-55cd-42c8-9e6f-50dab09c28e9)

**Comment by matt-FFFFFF** [comment]
Hi @mehliku 

Can you try specifying the value directly instead of using a child object with a value attribute?

Thanks

**Comment by qaiser-tele2** [comment]
@matt-FFFFFF 
Is there any progress on this? I'm also encountering the same issue while trying to disable the defender for servers through archtype extension

`"Deploy-MDFC-Config": {
            "enableAscForServers": "Disabled"
          }`

**Comment by qaiserali** [comment]
@matt-FFFFFF 
Is there any progress on this? I'm also encountering the same issue while trying to disable the defender for servers through archtype extension

`"Deploy-MDFC-Config": { "enableAscForServers": "Disabled" }`
