### ISSUE TITLE
Error upgrading from v0.1.2 to v0.2.0

### ISSUE THREAD

**Issue by pauldotyu** [Azure/terraform-azurerm-caf-enterprise-scale#81]
Wanted to post this in case folks run into this error when attempting to upgrade from v0.1.2 to v0.2.0

`│ Error: deleting Policy Definition "Deploy-Diagnostics-PublicIP": policy.DefinitionsClient#DeleteAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDeletePolicyDefinitionRequest" Message="The policy definition 'Deploy-Diagnostics-PublicIP' cannot be deleted.  It is referenced by the policy set definition '/providers/Microsoft.Management/managementgroups/cu/providers/Microsoft.Authorization/policySetDefinitions/Deploy-Diag-LogAnalytics'. Please remove this policy definition from all policy set definitions that reference it."`

[Release notes](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases/tag/v0.2.0) indicate that the `Deploy-Diagnostics-PublicIP` custom policy definition has been removed in favor of a built-in policy.

If you had v0.1.2 running in your environment, this policy was included in the Policy Initiative (policySet) `Deploy-Diag-LogAnalytics`. This policy is no longer included in the policy set but the `terraform apply` command attempts to delete the policy before removing it from the policy set. 

To work around this error, you'll manually remove the policy from the policy set. Go to the Azure Portal, navigate to [Policy definitions](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyMenuBlade/Definitions) and search for the policy definition named **Deploy Diagnostic Settings to Azure Services**.  Edit the initiative and remove the **Deploy Diagnostic Settings for Public IP addresses to Log Analytics workspace** policy then re-run the `terraform plan` and `terraform apply` commands.

**Comment by krowlandson** [comment]
Thank you @pauldotyu... will see if we can replicate this as the module (and Terraform) should be able to handle this. If not, we will need to document this as a known issue, but also worth noting for future releases where we may need to "sunset" policies before removing from the module library.

**Comment by krowlandson** [comment]
This issue will not be fixed as this is an old version, but we believe this is no longer an issue in the latest updates.
