### ISSUE TITLE
Feature Request: Policy Remediation

### ISSUE THREAD

**Issue by cyb3n3tic** [Azure/terraform-azurerm-caf-enterprise-scale#810]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
This is probably already in place and I am missing the obvious but I'd like to be able to configure policy remediation tasks.

I have a fresh landing zone deployed with just management and connectivity subscriptions, at the moment these are showing that several assignments have resources to remediate, mostly Deploy Microsoft Defender for Cloud configuration and Deploy Diagnostic Settings to Azure Services.

#### Describe the solution you'd like

Is it possible to configure this in Terraform to bring compliance state to fully compliant out of the box as such?
I'm hoping that as new subscriptions are added there is no intervention required and they are compliant from day one.

Thanks

**Comment by hlokensgard** [comment]
As far as I know this can't be done with terraform. 
I have solved the same issue by having a post-deployment/test step in my pipeline. I then run the step and it gathers all the deployifnotexists policies that are non compliant and then starts a remediation task for those. It can be a bit tricky.

**Comment by cyb3n3tic** [comment]
Kind of good to hear as I thought maybe I was missing something obvious.
Do you think there would be any issue in managing remediation manually via the console?

**Comment by hlokensgard** [comment]
Not a problem, just that DINE should be automated from my perspective. No reason for those to be a manual process. Takes time and it should just work. 
You can look into this [Az.PolicyInsights](https://learn.microsoft.com/en-us/powershell/module/az.policyinsights/?view=azps-10.2.0) module ans the function: 
- https://learn.microsoft.com/en-us/powershell/module/az.policyinsights/get-azpolicystate?view=azps-10.2.0

If you have a small environment and not many policies it could be managed by a manuell process, but a manuell process don't scale.

**Comment by cyb3n3tic** [comment]
Thanks for the pointers

**Comment by torivara** [comment]
You could check this module, @cyb3n3tic :
https://registry.terraform.io/modules/gettek/policy-as-code/azurerm/2.1.0#automate-remediation-tasks

I haven't actually used it or verified it myself, but it claims to automate remediation tasks with Terraform.

Seems like [this](https://github.com/gettek/terraform-azurerm-policy-as-code/tree/main/modules/def_assignment) part of the module handles remediation tasks:

```terraform
## remediation tasks ##
resource "azurerm_management_group_policy_remediation" "rem" {
  count                = local.create_remediation + local.remediate.mg > 1 ? 1 : 0
  name                 = lower("${var.definition.name}-${formatdate("DD-MM-YYYY-hh:mm:ss", timestamp())}")
  management_group_id  = local.remediation_scope
  policy_assignment_id = local.assignment.id
  location_filters     = var.location_filters
  failure_percentage   = var.failure_percentage
  parallel_deployments = var.parallel_deployments
  resource_count       = var.resource_count
}

resource "azurerm_subscription_policy_remediation" "rem" {
  count                   = local.create_remediation + local.remediate.sub > 1 ? 1 : 0
  name                    = lower("${var.definition.name}-${formatdate("DD-MM-YYYY-hh:mm:ss", timestamp())}")
  subscription_id         = local.remediation_scope
  policy_assignment_id    = local.assignment.id
  resource_discovery_mode = local.resource_discovery_mode
  location_filters        = var.location_filters
  failure_percentage      = var.failure_percentage
  parallel_deployments    = var.parallel_deployments
  resource_count          = var.resource_count
}

resource "azurerm_resource_group_policy_remediation" "rem" {
  count                   = local.create_remediation + local.remediate.rg > 1 ? 1 : 0
  name                    = lower("${var.definition.name}-${formatdate("DD-MM-YYYY-hh:mm:ss", timestamp())}")
  resource_group_id       = local.remediation_scope
  policy_assignment_id    = local.assignment.id
  resource_discovery_mode = local.resource_discovery_mode
  location_filters        = var.location_filters
  failure_percentage      = var.failure_percentage
  parallel_deployments    = var.parallel_deployments
  resource_count          = var.resource_count
}

resource "azurerm_resource_policy_remediation" "rem" {
  count                   = local.create_remediation + local.remediate.resource > 1 ? 1 : 0
  name                    = lower("${var.definition.name}-${formatdate("DD-MM-YYYY-hh:mm:ss", timestamp())}")
  resource_id             = local.remediation_scope
  policy_assignment_id    = local.assignment.id
  resource_discovery_mode = local.resource_discovery_mode
  location_filters        = var.location_filters
  failure_percentage      = var.failure_percentage
  parallel_deployments    = var.parallel_deployments
  resource_count          = var.resource_count
}
```

The name part that will change based on date might trigger new remediation tasks because the resource needs to be updated? I would need to test this myself, but I assume the new name would at least force a replacement of the remediation task resource, thereby doing a remediation.

Theoretically you could do remediation tasks with Terraform, I guess 🙂

**Comment by matt-FFFFFF** [comment]
Hi. Since remediation tasks need to await a policy scan result and corresponding noncompliant resources, we don't feel they are a good fit for this module.

You can of course use other solutions to achieve this outcome.

**Comment by cyb3n3tic** [comment]
Appreciate all the advice given - will test out options.
Closing issue.
