### ISSUE TITLE
Feature Request - Allow for configuring of TLS certificate for Virtual WAN Azure Firewall

### ISSUE THREAD

**Issue by NathanDunning** [Azure/terraform-azurerm-caf-enterprise-scale#812]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Unable to specify a TLS Certificate for the Virtual WAN Azure Firewall Policy configuration option. This is an option that can be provided though the UI but this option is not something I can configure via the module. I can see that this option is available when using the Hub/Spoke (connectivity) scope Azure Firewall configuration.

#### Describe the solution you'd like

Similar to how I can supply this configuration option for the `connectivity` Azure Firewall, I would like an advanced configuration option to allow me to supply a TLS Certificate for the Azure WAN deployment of Azure Firewall.

I imagine it would look a little something like this:

![AZFW_tls](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/39353409/3b36bd65-6450-4fe4-a611-eecaeb07a206)

Either this or a temporary workaround could be to use an `ignore_changes` lifecycle block to prevent this module from removing the setting that I would need to set and manage elsewhere.

**Comment by matt-FFFFFF** [comment]
Hi!

Can you configure the fw policy outside the module and then pass in the resource id to link it?

**Comment by NathanDunning** [comment]
Sure can, that does work as a workaround, cheers!
