### ISSUE TITLE
Bug Report: strict_subscription_association set to false / to be managed via Terraform this resource needs to be imported into the State

### ISSUE THREAD

**Issue by cyb3n3tic** [Azure/terraform-azurerm-caf-enterprise-scale#815]
Community Note

    Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
    Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
    If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Versions**

module "caf-enterprise-scale" {
source = "Azure/caf-enterprise-scale/azurerm"
version = "4.2.0"
module "lz_vending" {
source = "Azure/lz-vending/azurerm"
version = "=3.4.1"

**Description**

I have deployed a landing zone using caf-enterprise-scale, now trying to update to add additional landing zones/subscriptions however with strict_subscription_association set to false I run into an error on terraform apply stating that management and connectivity subscriptions already exist.

**Error**
resource with the ID "/managementGroup/lztest-management/subscription/xxxxx" already exists - to be managed via Terraform this resource needs to be imported into the State.

I have the same configuration running in another environment that has deployed ok with strict_subscription_association set to false so expecting this to work here also, any suggestions?

Is the issue that I am doing this after the initial deployment? Anyway to override this behaviour?

I intend to use lz-vending module to add additional subscriptions so as far as i understand I need to set strict_subscription_association to false to ensure that will work?

**Full error output is:**

module.enterprise_scale.azurerm_management_group_subscription_association.enterprise_scale["/providers/Microsoft.Management/managementGroups/lztest-connectivity/subscriptions/xxxxxxxxx"]: Creating...
module.enterprise_scale.azurerm_management_group_subscription_association.enterprise_scale["/providers/Microsoft.Management/managementGroups/lztest-management/subscriptions/yyyyyyyy"]: Creating...

A resource with the ID "/managementGroup/lztest-management/subscription/yyyyyyyy" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_subscription_association" for more information.

with module.enterprise_scale.azurerm_management_group_subscription_association.enterprise_scale["/providers/Microsoft.Management/managementGroups/lztest-management/subscriptions/yyyyyyyy"],
on .terraform/modules/enterprise_scale/resources.management_groups.tf line 114, in resource "azurerm_management_group_subscription_association" "enterprise_scale":
114: resource "azurerm_management_group_subscription_association" "enterprise_scale"

A resource with the ID "/managementGroup/lztest-connectivity/subscription/xxxxxxxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_subscription_association" for more information

with module.enterprise_scale.azurerm_management_group_subscription_association.enterprise_scale["/providers/Microsoft.Management/managementGroups/lztest-connectivity/subscriptions/xxxxxxxx"]
on .terraform/modules/enterprise_scale/resources.management_groups.tf line 114, in resource "azurerm_management_group_subscription_association" "enterprise_scale":
114: resource "azurerm_management_group_subscription_association" "enterprise_scale"

[error]Bash exited with code '1'.
[section]Finishing: Terraform Apply

Thanks in advance

**Comment by QBY-ThimoLimpert** [comment]
Hey,
I would think, that something or someone already moved the subscription to the correct management groups. You added the subscription to the management groups, so terraform want to move the subscriptions to the correct management groups. Because they are already there, there is the error. To fix this, you can easily import the "azurerm_management_group_subscription_association" resource, as they are already moved if I'm correct.

**Comment by matt-FFFFFF** [comment]
Hi,

Did you previously have strict association set to true and are now switching to false?

**Comment by cyb3n3tic** [comment]
Hi Matt,

No, initially it was without that a strict_subscription_association line at all, after deploying the initial LZ with just the basics I then added strict_subscription_association set to false and re-ran my pipeline at which point I ran into the issue.

I think I will just be conscious to make this choice at the beginning next time so I can go ahead with LZ-Vending without any drama.

**Comment by matt-FFFFFF** [comment]
Hi @cyb3n3tic 

Thanks for confirming.

When you initially deployed the resources the strict mode setting was on by default. When you set it to off, this is where the import error occurs.

You can either import the subscription association resources, or temporarily move the subscriptions into a different management group. The latter option would mean that this module would move them back.

Finally, we recommend managing LZ subscriptions with the LZ-vending module as this enables entire lifecycle ownership in a scalable manner.

**Comment by cyb3n3tic** [comment]
OK, thanks - understood.

So would I be right in thinking that if I were to deploy a new landing zone in the future and planned to then use LZ-Vending to manage subscriptions I just need to add the strict_subscription_association = false from the outset? That is what seems to have worked for me.
 
If that is the case, is it worth mentioning in documentation / Wiki to avoid a requirement for importing or moving subscriptions manually? Possibly same on the LZ-Vending Wiki?

**Comment by matt-FFFFFF** [comment]
Yes this is a good idea. We plan to release a major version soon and may default this to `false` to better integrate with lz vending

**Comment by Romiko** [comment]
Awesome, we have set it to false by default for now and had to do a retro fix in the level 1 TFState

**Comment by matt-FFFFFF** [comment]
You can use managed `import {}` now

https://developer.hashicorp.com/terraform/language/import
