### ISSUE TITLE
Can these be deployed into 1 subscription?

### ISSUE THREAD

**Issue by cengxiye** [Azure/terraform-azurerm-caf-enterprise-scale#817]
Hi Team,

I am wondering if multiple subscriptions are needed as prerequisites to try this Terraform module.

I only have 1 subscription, is it possible to deploy Management/Connectivity/Identity into one subscription?

Thanks

**Comment by QBY-ThimoLimpert** [comment]
Hi,

we are using only one subscription in our development environments. So it is possible. I can't provide an example right now :(, but it was quite straight forward as far as I remember.

**Comment by matt-FFFFFF** [comment]
Hi @cengxiye 

Yes just supply the same subscription id for all inputs.

You'll need to provide the same provider alias 'azurerm' for all the required provider inputs to the module.
