### ISSUE TITLE
How to use Inbuilt initiatives/Policies for archetype definitions

### ISSUE THREAD

**Issue by Raphael-kainos** [Azure/terraform-azurerm-caf-enterprise-scale#818]
Hey everyone, I was wondering you had any guidance on how to implement inbuilt polices into managements groups using archetype definitions. Ive seen this doc on using custom policies. https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy-Sets-and-Assignments  However not sure what exactly I need to do for inbuilt policies/initiatives 

for example  https://github.com/Azure/azure-policy/blob/master/built-in-policies/policySetDefinitions/Regulatory%20Compliance/FedRAMP_H_audit.json

any examples would helpful, thanks in advance

**Comment by praveenambati1233** [comment]
What was the solution ? @Raphael-kainos
