### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by mesmashu** [Azure/terraform-azurerm-caf-enterprise-scale#820]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.54.0"
    }
  }
}

**azure provider**:
provider "azurerm" {
  skip_provider_registration = true
  environment = "usgovernment"
  features {}
}

**module**:
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "4.2.0" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  default_location = "usgovvirginia"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

### Description
Error: reading Policy Set Definition

#### Describe the bug

terraform init = OK
terraform plan - getting the following error after the plan runs and displays Plan: 155 to add... then get this error:
│ Error: reading Policy Set Definition "e20d08c5-6d64-656d-6465-ce9e37fd0ebc": policy.SetDefinitionsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicySetDefinitionNotFound" Message="The policy set 
definition 'e20d08c5-6d64-656d-6465-ce9e37fd0ebc' could not be found."
│
│   with module.enterprise_scale.data.azurerm_policy_set_definition.external_lookup["/providers/Microsoft.Authorization/policySetDefinitions/e20d08c5-6d64-656d-6465-ce9e37fd0ebc"],
│   on .terraform\modules\enterprise_scale\locals.policy_assignments.tf line 88, in data "azurerm_policy_set_definition" "external_lookup":      
│   88: data "azurerm_policy_set_definition" "external_lookup" {

Thanks for any help getting past this error.  Let me know if you need more info.

**Comment by jferry-pm** [comment]
This looks to be an issue with the policy set not being found, possibly due to policy differences in environments (as you're building against **usgovernment**)

Can you run a plan against a standard environment and see if it runs through without issue?

**Comment by matt-FFFFFF** [comment]
This looks correct, try excluding that policy set and assignment,

**Comment by mesmashu** [comment]
> This looks to be an issue with the policy set not being found, possibly due to policy differences in environments (as you're building against **usgovernment**)
> 
> Can you run a plan against a standard environment and see if it runs through without issue?

i ran az set cloud to go back to AzureCloud and verified i was logged into a commercial subscription and ran init/plan and got the same error.

**Comment by mesmashu** [comment]
> This looks correct, try excluding that policy set and assignment,

is there documentation on how to exclude specific policies?  thanks!

**Comment by hlokensgard** [comment]
@mesmashu the procedure for excluding policy assignment is explained [here](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions)
