### ISSUE TITLE
Question relating to sub-dividing components if using multiple modules

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-caf-enterprise-scale#821]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the [documentation example for multiple modules](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-orchestration), the following comment is made:

```Consider how else you might further sub-divide your deployment. For example, it's actually possible to implement a single hub per instance and still integrate them for peering. You can also deploy DNS resources independently, whilst maintaining the ability to link the DNS zones to the hub virtual networks (and spokes).```

I'm unclear what point is being made here & how this would work.  I read this as saying it is possible to split the connectivity aspect into further modules.  If you do this the how would this integrate with the core module, which I understand is needed to ensure policy is aligned, but which takes a single parameter for for configured resources?

I can see how I could supply different "connectivity modules" which support different solutions, e.g. you could have different modules for hub & spoke vs vwan, but not when they are split.

I don't see the connection to the second sentence - to me that sounds like using the outputs to get information about the deployed spokes and use this to link DNS zones.

I'm confused 😅 

#### Is your feature request related to a problem?

No.

#### Describe the solution you'd like

Please would you clarify what this subdivision might look like please?

**Comment by matt-FFFFFF** [comment]
Hi @kewalaka 

We are saying that you can use a single module instance per hub network, if you want to. However I'd be more interested in your desired scenario?

**Comment by kewalaka** [comment]
Thanks for the feedback @matt-FFFFFF.  I am coming from an alternative implementation of landing zones for customers and looking to build on this offering, so the motivation is just to understand potential design patterns.

I've watched the recent community call, had a look at the terraform alz accelerator and drawing some more inspiration from that, specifically using the separate module for hub/spoke or vwan rather than the built in connectivity resources block in this repo, which honestly I wasn't thrilled with as I see that as a separate concern.

I'm watching the vnext / alz provider with interest.  Is the intention to pull down the policies from the parent enterprise scale repo as the default starting point?   I see in v0.2 there are options appearing to add or remove specific policies.  If that's correct, would you also consider a flag to remove _all_ policies - this would be useful for users of EPAC.  At the moment I'm using archetype exclusions to do this but obviously this needs to be tracked somehow.

Finally i know you can't make promises, but do you have an inkling when the experimental tag might be lifted on the vnext provider - be useful in deciding where to direct development effort - if it is close I am keen to help with testing & feedback.

**Comment by matt-FFFFFF** [comment]
Hi @kewalaka 

You can use the `empty` base_archetype to start empty.

The new provider and module are ready for non-production testing. We cannot speculate on when v1 will be available.
