### ISSUE TITLE
Issue when configuring Automation Account Identity

### ISSUE THREAD

**Issue by michael-brown-22** [Azure/terraform-azurerm-caf-enterprise-scale#823]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.4.6

**azure provider**: 3.54.0

**module**: 4.2.0

#### Describe the bug

When trying to configure the advanced settings for the Azure automation account using the configuration below an error is received which prevents us from configuring it. 
```
  management_advanced_settings = {
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_automation_account = {
          management = {
            name = "aa-management-${var.environment}-${local.azure_geo_codes[local.location]}"
            identity = {
              type = "SystemAssigned"
            }
          }
        }
      }
    }
  }
```

Error 1;
Can't access attributes on a primitive-typed value (string).

Error2;
Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.

#### Steps to Reproduce

1. Build out the landing zone
2. Update the variables to add in the identity type
3. Run the plan which fails producing the error

#### Screenshots

<img width="727" alt="Screenshot 2023-09-25 at 11 26 29" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/108287539/28743ea3-d735-46b4-9011-bf2e81e35803">

**Comment by hlokensgard** [comment]
Hi @michael-brown-22 
Try to encapsulate the element with ". So you get: 

```
  management_advanced_settings = {
    advanced = {
      custom_settings_by_resource_type = {
        "azurerm_automation_account" = {
          "management" = {
            "name" = "aa-management-${var.environment}-${local.azure_geo_codes[local.location]}"
            "identity" = {
              "type" = "SystemAssigned"
            }
          }
        }
      }
    }
  }
```

Should work :)

**Comment by michael-brown-22** [comment]
Hi @hlokensgard,

Thanks for the response I have tested that this morning and looks like I get the same issue. Have you been able to replicate this locally?

<img width="716" alt="Screenshot 2023-09-26 at 08 46 49" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/108287539/43ff89b4-8063-4c07-bba3-740d22b8b293">

<img width="855" alt="Screenshot 2023-09-26 at 08 46 41" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/108287539/fefc85bf-560e-4772-8799-52f8127482ea">

**Comment by hlokensgard** [comment]
@michael-brown-22 I understand the error message and it is because you have missed one elemenet in your code. The **value** parameter in the identity parameter. You need to set that to `"type" = "SystemAssigned"`. Try that and I think it should work. I have the below code running in production. 

```
"azurerm_automation_account" = {
  "management" = {
    "identity" = {
      "value" = {
        "type" = "SystemAssigned"
       }
    }
  }
}
```

**Comment by michael-brown-22** [comment]
@hlokensgard Just tested and works thanks. It might be worth having a section in the Wiki for advanced settings for any gotchas similar to this.

**Comment by hlokensgard** [comment]
@michael-brown-22 I agree. I just reversed engineered the code to get it to work when I did it.
Great that it works.
