### ISSUE TITLE
Question - AKS Private DNS

### ISSUE THREAD

**Issue by amcfalls** [Azure/terraform-azurerm-caf-enterprise-scale#824]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When deploying a private AKS cluster in a landing zone, a private AKS DNS Zone is created with an A record in the MC_ resource group. 

We are using the Hub and Spoke approach with centralized DNS in the Hub/Connectivity subscription and have enabled several of the private link services in the DNS section of the settings.connectivity.tf file. We have also enabled the private DNS Zone virtual network links on the spoke networks. 

We have a private DNS Zone for kubernetes in the Connectivity subscription along with other private DNS Zones for other services. 

With the deploy-private-dns-zones policy (Configure Azure PaaS services to use private DNS zones) policy enabled we are able to deploy private link endpoints for services such as Key Vault and have the policy automatically create the A record in the appropriate private DNS Zone in the Connectivity subscription. This is working well for us. 

I don't see AKS being one of the services in the above policy though. 

I understand that we can configure AKS to create the appropriate A record in the private DNS Zone but then we need to use either User Assigned identity or the now deprecated service principal and grant that identity Private DNS Zone Contributor. 

What is the best way to get A records created in the centralized Private DNS Zone when using a private AKS cluster? 

Is it possible to have AKS included in the deploy-private-dns-zones policy?

Should I create a standalone policy that will do this similar to the other policy and reuse the Deploy-PrivateDNS-Zones identity that the other policy uses?

Any help would be appreciated as I don't want to make this more complicated then is needed especially with the simplicity of the existing policy that takes care of this for other services.

**Comment by anwarnk** [comment]
Just from my experience you cannot create a private K8s cluster without specifying the private DNZ zone (someone can correct me, if I am wrong!)

We ended up doing a data to the resource in connectivity

*redacted 
```
  private_cluster_enabled = true
  private_dns_zone_id     = data.azurerm_private_dns_zone.azmk8s.id
```

**Comment by amcfalls** [comment]
Thanks for providing the approach you took. I will give it a try and see how it works out.

**Comment by matt-FFFFFF** [comment]
Hi!

The policy for deploying DNS zone groups (deploy-private-dns-zones) only works for private endpoint resources.

It seems that @anwanrk has a good solution.

Otherwise, a DNS delegation from your hub DNS zone to a AKS one seems a logical idea.

Flagging @jtracey93 as this could be a good addition to the AKS LZA. We should reach out to them

**Comment by qaiserali** [comment]
Hi,
We're getting a similar issue while creating the AKS private cluster. We are assigning the private DNS zone ID as mentioned by @anwarn above. However, upon running the Terraform code to create the private cluster, we get the customPrivateDNSZoneMissingPermission error, as shown below. 
`Service principal or user-assigned identity must be given permission to read and write to custom private dns zone /subscriptions/{sub-id}/resourceGroups/rg-dns-connectivity/providers/Microsoft.Network/privateDnsZones/privatelink.westeurope.azmk8s.io. Check access result not allowed for action Microsoft.Network/privateDnsZones/write.`

One way to solve this is to assign the "Private DNS Contributor" permissions to the AKS user-assigned identity, but that doesn't seem to be a good solution following the hub-spoke approach, as in this case, we will be allowing landing zone corp subscriptions services to get permissions over the private DNS zones in the connectivity subscription.

Another way I am thinking of solving this is to delegate the private DNS zones to the land-zones subscriptions, but the CAF module doesn't have any such feature to enable this.

Following the CAF best practices, any suggestions or help for solving this issue would be appreciated.
