### ISSUE TITLE
Problem behavior when using templatefile to map archetype_extension_es_root.tmpl.tftpl

### ISSUE THREAD

**Issue by Kompita** [Azure/terraform-azurerm-caf-enterprise-scale#825]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.5.3

**azure provider**: ">= 3.65.0"

**module**: "Azure/caf-enterprise-scale/azurerm"  "4.0.2"

#### Describe the bug

When I try to map the archetype_extension_es_root.tmpl.tftpl file with the templatefile in locals to include variables when deploying it doesn't give an error but it doesn't seem to apply it.

#### Steps to Reproduce

archetype_extension_es_root.tmpl.tftpl
{
    "extend_es_root": {      
      "policy_assignments": jsonencode(var.policy_assignments),
      "policy_definitions": jsonencode(var.policy_definitions), 
      "policy_set_definitions": jsonencode(var.policy_set_definitions),
      "role_definitions": jsonencode(var.role_definitions),
      "archetype_config": {
        "parameters": jsonencode(var.parameters),
        "access_control": jsonencode(var.access_control)
      }      
    }
}

locasl_core.tf
conf = templatefile("${path.module}/lib/archetype_extension_es_root.tmpl.tftpl", {
    policy_assignments = var.policy_assignments
    policy_definitions =  var.policy_definitions
    policy_set_definitions = var.policy_set_definitions
    role_definitions = var.role_definitions
    parameters = var.parameters
    access_control = var.access_control
  })

variables.tf

variable "policy_assignments" {
  type        = list(string)
  description = "Policy Assignments"
  default     = []
}

variable "policy_definitions" {
  type        = list(string)
  description = "Policy Definitions"
  default     = []
}

variable "policy_set_definitions" {
  type        = list(string)
  description = "Policy Set Definitions"
  default     = []
}

variable "role_definitions" {
  type        = list(string)
  description = "Role Definition"
  default     = []
}

variable "parameters" {
  type        = map(any)
  description = "Parameters"
  default     = {}
}

variable "access_control" {
  type        = map(list(string))
  description = "Access Control"
  default     = {}
}

file.tfvars
policy_assignments =  ["Deploy-Antimalware-Ext", "NIST-SP-800-53-Rev5", "Enforce-Mandatory-Tags"]
policy_definitions =  ["Enforce-RG-Tags", "Enforce-Resource-Tags"]
policy_set_definitions = ["Enforce-Mandatory-Tags"]
role_definitions = []
parameters =  {
          "Deploy-MDFC-Config":{
            "emailSecurityContact": "ddddd"
          },
          "Enforce-Mandatory-Tags":{
            "EnforceRGTags-tag1": "tag1",                   
            "EnforceResourceTags-tag1": "tag1"
          }
        }
access_control = {}

**Comment by matt-FFFFFF** [comment]
Hi @Kompita 

Have you seen this wiki article?

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions#example-root-module

The filename should end in `.json`

**Comment by Kompita** [comment]
Yes, my actual config contains this feature with archetype_extension_es_root.tmpl.sjon
{
    "extend_es_root": {
      "policy_assignments": ["Deploy-Antimalware-Ext", "NIST-SP-800-53-Rev5", "Enforce-Mandatory-Tags"], 
      "policy_definitions":  ["Enforce-RG-Tags", "Enforce-Resource-Tags"],
      "policy_set_definitions": ["Enforce-Mandatory-Tags"],
      "role_definitions": [],
      "archetype_config": {
        "parameters": {
          "Enforce-Mandatory-Tags":{
            "EnforceRGTags-BusinessUnit": "BusinessUnit",    
            "EnforceRGTags-Workgroup": "Workgroup",    
            "EnforceResourceTags-BusinessUnit": "BusinessUnit",    
            "EnforceResourceTags-Workgroup": "Workgroup",               
          }
        },
        "access_control": {}
      }
    }
  }
but I need to be able to use variables instead of hardcoded text, for example somethis like this "policy_assignments": $list[Strings], for this reason I have used templafile  but it doesn't seem to translate well.

Can you help me with this , please?

**Comment by matt-FFFFFF** [comment]
Hi, we have not tested this scenario unfortunately. 

Have you tried extending the [template_file_vars](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale#input_template_file_variables) to include the data you want?

This is a map of the variable name to the value.

E.g. 

```hcl
{
  my_var = var.foo
}
```

Then in the template file you could use `{my_var}`.

The file should end in .tmpl.json
