### ISSUE TITLE
Question: Managing Cloud Security Benchmark Default Initiative via Terraform Enterprise-Scale

### ISSUE THREAD

**Issue by DariaSliusar** [Azure/terraform-azurerm-caf-enterprise-scale#826]
Hi. 

Could you please let me know if it's possible to manage Cloud Security Benchmark Default Initiative via Terraform Enterprise-Scale? If so, where can I find any guidance or documentation for it? I can't seem to find anything...

Thank you in advance.

**Comment by matt-FFFFFF** [comment]
Hi @DariaSliusar 

If this is a policy initiative then yes. We support assigning built-in and custom policies.

**Comment by DariaSliusar** [comment]
Hi @matt-FFFFFF , thanks for getting back to me. Is there any guidance or documentation that I can follow to implement that?

**Comment by jtracey93** [comment]
This policy is already assigned to the intermediate root management group by default under the assignment name of `Deploy-ASC-Monitoring` by all ALZ implementations as per https://aka.ms/alz/policies  

**Sources:**
- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/archetype_definitions/archetype_definition_es_root.tmpl.json#L7C8-L7C29
- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json

**Comment by DariaSliusar** [comment]
Thanks, @jtracey93! That helped.
