### ISSUE TITLE
Bug Report: Two vWan Hubs in the same Region not possible

### ISSUE THREAD

**Issue by steph409** [Azure/terraform-azurerm-caf-enterprise-scale#828]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.5.1

**azure provider**: 3.35

**module**: 4.2.0

#### Describe the bug

When deploying virtual vwan for big customers, there are cases where two hubs in the same region are required. E.g. two hubs in northeurope. Azure supports this, but the module does not unfortunately. 

#### Steps to Reproduce

Follow [this guide](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Virtual-WAN-Resources-With-Custom-Settings) to deploy vwan with custom settings. Modify the location of the hubs, e.g. set them both to northeurope.

#### Screenshots

<img width="814" alt="image" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/33083326/93c16438-ba3d-454e-9391-e350db1359b3">

**Comment by hlokensgard** [comment]
@steph409 I had the same problem, so this would be great.
For my case we could implement a workaround with using two module calls with different input but the same region. But then again you end up with two virtual wan that you need to peer.

**Comment by matt-FFFFFF** [comment]
Hi @steph409 

You are correct in that, due to the module using the location as a map key, it isn't possible to have multiple vwan hubs in a single region, at least not without significant breaking changes.

Due to this constraint, we do not have plans to change this in the current module, however @hlokensgard provides a workaround.

We do have distinct modules now for vwan and h&s. Both of which are unencumbered by the limitations above.

**Comment by steph409** [comment]
Hi,
thanks for the clarification. Which modules do you mean for the vwan? Can you send me a link here? I followed the vwan tutorial.
 
I have a workaround, this is not so much the problem. I just wanted to mention it because it should be designed differently in the module.

Thanks,
Stephanie

**Comment by matt-FFFFFF** [comment]
Hi @steph409 

https://github.com/Azure/terraform-azurerm-avm-ptn-virtualwan

This is the vwan module

**Comment by steph409** [comment]
Hi,
what is the recommendation then? To use the enterprise-scale, but not for connectivity? and then use this one for connectivity? I will try it out then to see it this fits my purpose.

thanks for the link!

**Comment by matt-FFFFFF** [comment]
Hi @steph409 

Yes in this scenario I would recommend using the dedicated module.
