### ISSUE TITLE
ItalyNorth location not working

### ISSUE THREAD

**Issue by marcelloformica** [Azure/terraform-azurerm-caf-enterprise-scale#830]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.7

**azure provider**: 3.75.0

**module**: 4.2.0

### Description

Tests using provided examples, for example https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-remote-state, fail when the new ItalyNorth region is specified as location

#### Describe the bug

locals.geo_codes.tf.json does not contain ItalyNorth and its geocode

#### Steps to Reproduce

1. Prepare Terraform folders and files according to example https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-using-multiple-module-declarations-with-remote-state
2. Edit connectivity/variables.tf  by setting italynorth as primary_location
3. Execute terraform plan
4. the following error is generated:

│ Error: Invalid index
│
│   on .terraform/modules/alz/modules/connectivity/locals.tf line 1448, in locals:
│ 1448:       "privatelink.${local.lookup_azure_backup_geo_codes[location]}.backup.windowsazure.com"
│     ├────────────────
│     │ local.lookup_azure_backup_geo_codes is object with 134 attributes
│
│ The given key does not identify an element in this collection value.

**Comment by matt-FFFFFF** [comment]
fixed by #834
