### ISSUE TITLE
Assign Policies at Subscription

### ISSUE THREAD

**Issue by pcsprashanth** [Azure/terraform-azurerm-caf-enterprise-scale#832]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

I'm struggling to find out a way to assign an inbuilt policy to a subscription. In my Management Group, I have a lot of subscriptions. so, each subscription needs different set of policies. If I apply on Management group, it is reflects to all subscriptions under it.

I searched entire guide but no luck. 
Please suggest me on how to proceed further.

**Comment by matt-FFFFFF** [comment]
Hi @pcsprashanth 

We don't support policy assignments at subscription scope.

You can still do this outside the configuration of the module.

**Comment by pcsprashanth** [comment]
Any reference for getting this done would much appreciated.
Cheers

**Comment by matt-FFFFFF** [comment]
Hi,

Using this resource you can assign a policy to a subscription: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_assignment
