### ISSUE TITLE
Italynorth as default_location

### ISSUE THREAD

**Issue by emlain** [Azure/terraform-azurerm-caf-enterprise-scale#833]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.9 

**azure provider**:  "3.75.0"

**module**: 4.2.0

### Description

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "4.2.0" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  default_location = "italynorth"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

### **### _Using "italynorth" as default_location in main.tf, i get this error on plan_**

PS C:\Azure\ISP\SYS> terraform plan
data.azurerm_client_config.core: Reading...
data.azurerm_client_config.core: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD1jMDgxNTQyMi02OTEwLTQ4OWMtYWNiNS00Mjc3MDAyMWZlNjE7b2JqZWN0SWQ9ZDAwY2IyOTItNTZlYy00ZGVlLWEwY2UtYzBkYTI1NTU3ODcyO3N1YnNjcmlwdGlvbklkPTVhM2U3YTQ1LThmMGEtNGNiMy1hZWYyLTM4ZDNjNmE5YmQwNzt0ZW5hbnRJZD1hMzYxYzE4NS1mZTFhLTQwZjYtODczNC03Njc5NjJlMGRkNWQ=]
╷
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\connectivity\locals.tf line 1448, in locals:
│ 1448:       "privatelink.${local.lookup_azure_backup_geo_codes[location]}.backup.windowsazure.com"
│     ├────────────────
│     │ local.lookup_azure_backup_geo_codes is object with 134 attributes
│
│ The given key does not identify an element in this collection value.

 **_Changing it on "westeurope" for example, the plan run correctly.

"Italynorth" seems to be missing on https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/connectivity/locals.geo_codes.tf.json_**

-->

**Comment by jaredfholgate** [comment]
This has been merged and will be included in the next release.

**Comment by jaredfholgate** [comment]
AB#31258
