### ISSUE TITLE
Bug Report: v5.0.0 Upgrade Documentation Error

### ISSUE THREAD

**Issue by MISO-mgriffin** [Azure/terraform-azurerm-caf-enterprise-scale#847]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: latest

**azure provider**: 3.77.0

**module**: 5.0.0

### Description

The example terraform import code is incorrect.

#### Describe the bug

When attempting to import the module from a Linux runner you need single quotes and to use singular works in the id portion of the import. [Upgrade from v4.2.0 to v5.0.0](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v4.2.0-to-v5.0.0)

#### Steps to Reproduce

1. Try importing - it will error out.

#### Additional context

update the terraform import example.

Per [Command: import](https://developer.hashicorp.com/terraform/cli/commands/import) 

Linux runners require single quotes around the module reference. My below example is for a Linux runner; if using a windows runner users need to remove the single quotes.

```
terraform import 'module.<YOUR_MODULE_REFERENCE>.azurerm_management_group_subscription_association.enterprise_scale["/providers/Microsoft.Management/managementGroups/<YOUR_MG>/subscriptions/<YOUR_SUBSCRIPTION_ID>"]' /providers/Microsoft.Management/managementGroup/<YOUR_MG>/subscription/<YOUR_SUBSCRIPTION_ID>
```
***Please note: the ID needs managementGroups to be managementGroup and subscriptions to be subscription.***

/providers/Microsoft.Management/**managementGroup**/<YOUR_MG>/**subscription**/<YOUR_SUBSCRIPTION_ID>

**Comment by matt-FFFFFF** [comment]
Thank you for this big report, we will correct the quote issue.

On the resource provider URI, the Azure REST service uses the plural pattern described in the upgrade guide:

https://learn.microsoft.com/en-us/azure/templates/microsoft.management/managementgroups/subscriptions?pivots=deployment-language-terraform

Does your Terraform resource id use the singular pattern?

**Comment by matt-FFFFFF** [comment]
quote issue fixed in ecf0601

**Comment by MISO-mgriffin** [comment]
> Does your Terraform resource id use the singular pattern?

I am not sure why it required I use singular format. I assumed it was something built into the CAF-ES Terraform Module. I didn't do anything I am aware of to force it to be singular; but while trying to update kept running into errors; realizing singular is what it was expecting.

**Comment by matt-FFFFFF** [comment]
There is no use of 'Microsoft.Management/managementGroup/' in the code so I am going to close this. Please re-open if there is an issue
