### ISSUE TITLE
DNS Proxy and Custom DNS policy error when using Basic Firewall SKU

### ISSUE THREAD

**Issue by simondtaylor** [Azure/terraform-azurerm-caf-enterprise-scale#848]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.7

**azure provider**: 3.77.0

**module**: 5.0.0

### Description

Error when using Basic Firewall SKU

#### Describe the bug

We are seeing an error when selecting a basic firewall SKU.

'Firewall Policy cafffe7f-5ac3-4bbd-a0eb-61b72c142d55 contains higher tier only properties - DNS Proxy and Custom DNS'

We have attempted to add some logic to the dns proxy configuration (below) but still get the above error. We don't typically set custom dns_servers.

          enable_dns_proxy         = lower(var.firewall_sku) != "Basic" ? true : false
          dns_servers                   = []

#### Steps to Reproduce

1. Use version 5.0.0 of the CAF module.
2. Deploy a Hub and Spoke landing zone using Azure Firewall with Basic SKU

**Comment by simondtaylor** [comment]
Hi, yes I know. The logic above sets enable_dns_proxy to false is the SKU is basic, does it not? Likewise dns_servers is not set. Even if we set both enable_dns_proxy and dns_servers to false it still throws the same error.

**Comment by birdnathan** [comment]
I'm seeing a similar issue where v5.0.0 wants to remove the Firewall Policy DNS Settings, i'm not using a basic sku though and i need these settings to remain. 
If I add a custom_settings block it then ignores the changes. So I now have this in place in my settings.connectivity.tf file to workaround the issue:
<img width="259" alt="image" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/42775203/922bb4c0-70c0-4265-9880-b23013a863dd">

**Comment by andrewdmay** [comment]
> I'm seeing a similar issue where v5.0.0 wants to remove the Firewall Policy DNS Settings, i'm not using a basic sku though and i need these settings to remain.

Looking through recent changes I _think_ it might be due to this PR https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/845 where some of the settings switch from being dependent upon the sku to whether or not `address_management_prefix` is being set.

I'm seeing a similar issue, and we want the DNS proxy (we're using it for our VPN clients so that they can resolve private DNS zones), but don't need the management prefix.
