### ISSUE TITLE
Security Recommendation: vWan Storage - Allow Blob anonymous access 

### ISSUE THREAD

**Issue by steph409** [Azure/terraform-azurerm-caf-enterprise-scale#849]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I got a security warning, that "Allow Blob anonymous access" should be disabled for a storage account. This storage account got created from the vWan in the landing zone deployment. I tried to see if I can set this property in the landing zone but it does not seem to be the case. Does vwan need this anonymous access? Or can it be disabled? If yes how? 

#### Describe the solution you'd like

Probably it would just be good to specify in the documentation how to set this property.

#### Additional context

[Documentation](https://learn.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal#set-the-storage-accounts-allowblobpublicaccess-property)

**Comment by jtracey93** [comment]
Hi @steph409,

This module doesn't create any storage accounts, only assigns policies to apply certain constraints to a storage account etc. as per aka.ms/alz/policies 

Is it this module, or is it another?
