### ISSUE TITLE
Do we have Option for exclusions in Policy?

### ISSUE THREAD

**Issue by pcsprashanth** [Azure/terraform-azurerm-caf-enterprise-scale#853]
### Community Note 

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### I have query or request:  Do we have any option for exclusion in policy where we can exclude them for a resource?
Below is the screenshot which is achievable through Azure Portal:

<img width="912" alt="image" src="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/52338785/01e3c45d-741f-4f1b-8708-228d04f65782">

 
Please let me know if it is possible?
Thank you in Advance

Regards,
Chandra

**Comment by matt-FFFFFF** [comment]
Hi @pcsprashanth 

We support notScopes (exclusions) in the policy assignment JSON.

**Comment by pcsprashanth** [comment]
Hi @matt-FFFFFF, Thank you for the Response.

Can this be used for a specific policy in a policyset definition?
Also, Does notscope supports a resource as well?

Regards,
Chandra

**Comment by matt-FFFFFF** [comment]
Hi @pcsprashanth You can't be selective on the specific definition in a set, no.

notScopes supports any resource container or resource: https://github.com/Azure/alz-terraform-accelerator/wiki/Frequently-Asked-Questions#questions-about-using-custom-starter-modules
