### ISSUE TITLE
custom_landing_zones Keys cannot contain periods

### ISSUE THREAD

**Issue by cloudchristoph** [Azure/terraform-azurerm-caf-enterprise-scale#855]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.6.3

**azure provider**: 1.10.0

**module**: 5.0.0

#### Describe the bug

When I try to add a management group with a period in the ID, it fails the validation.
Periods are allowed for Management Group IDs.

#### Steps to Reproduce

1. Add a custom_landing_zone like this:
```terraform
  custom_landing_zones = {
    "com.mycompany" = {
      display_name               = "My Company"
      parent_management_group_id = "${data.azurerm_client_config.core.tenant_id}"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "mycompany_root"
        parameters     = {}
        access_control = {}
      }
    }

```
2. `terraform plan`
3. You'll get an validation error:
```
│     │ var.custom_landing_zones is object with 1 attribute "com.mycompany"
│
│ The custom_landing_zones keys must be between 2 to 89 characters long and can only contain lowercase letters, numbers and hyphens.
│
│ This was checked by the validation rule at .terraform/modules/enterprise_scale/variables.tf:605,3-13.
```
#### Possible fix:

I've changed the validation rule in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/ecf060141da1151b6dcda088aa04f4150e2d2371/variables.tf#L606-L607

...to:

```terraform
    condition     = can([for k in keys(var.custom_landing_zones) : regex("^[a-zA-Z0-9-.]{2,89}$", k)]) || length(keys(var.custom_landing_zones)) == 0
    error_message = "The custom_landing_zones keys must be between 2 to 89 characters long and can only contain lowercase letters, numbers, periods and hyphens."
```
#### Additional context

I'm still creating the environment where this issue has hit me. So I'm not sure, if there are side effects with Management Groups containing a period in the ID. So far I have not observed any problems.

I would also like to point out that I don't think it's a good idea. I follow customer specifications here and see no technical reason not to allow it.

**Comment by matt-FFFFFF** [comment]
Hi I agree - we will fix

**Comment by cloudchristoph** [comment]
Wow that was fast Matt. 😲

Didn't have the chance to test all components. Just using this for Policy deployments tbh.
I'll let you know, if I see issues with those Management Groups.

**Comment by matt-FFFFFF** [comment]
I need to get this reviewed but should be able to merge and release tomorrow
