### ISSUE TITLE
Role definition for running provisioning of landing zones from Terraform Cloud

### ISSUE THREAD

**Issue by c4milo** [Azure/terraform-azurerm-caf-enterprise-scale#858]
### Description
We would like to configure Terraform Cloud workspaces to provision the resources managed by this project. Is there a role definition available you would suggest we use? 

#### Is your feature request related to a problem?
Sort of a feature request, not related to a problem. 

#### Describe the solution you'd like
A role definition we can attach to a managed identity used by Terraform Cloud to execute Terraform. More details about this can be read here https://developer.hashicorp.com/terraform/cloud-docs/workspaces/dynamic-provider-credentials/azure-configuration

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jaredfholgate** [comment]
Hi @c4milo 

The service principal you use for Terraform Cloud, whether using federated credentials, managed identity of an agent compute instance or client secret requires the same permissions. The permissions are unrelated to the fact using are using federated credentials. 

The minimum permissions required is `Management Group Contributor` on the root management group you are building your hierarchy under. It would require `Owner` permissions on any subscriptions you are targeting for management, identity or connectivity.

If you let us know specifically what you are stuck on, we'd be happy to help. 

Thanks

**Comment by c4milo** [comment]
Hi @jaredfholgate, we are not stuck but so far I've been provisioning things using my user, which has Owner role. I was sort of hesitant to grant the Owner role to the Terraform Cloud workers but it looks like there is no other way around it based on what you are saying.

**Comment by jaredfholgate** [comment]
@c4milo There are extra guardrails you can put in place, but at the end of the day whatever service principal runs the apply is going to need the relevant permissions.

Here are examples of other guardrails, whether you can implement these depends on whether you are using CLI or VCS driven workspaces in Terraform cloud.

- Separate service principals for plan and apply. The plan only requires reader permissions.
- Required templates for plan and apply. Centrally control what the service principal can be used for. (available in GitHub and Azure DevOps)
- Manual approvals for apply.

The [Azure Landing Zones Terraform Accelerator](https://aka.ms/alz/terraform/accelerator) has examples of some of these already and we plan to expand it to include the others and also a Terraform Cloud option in the next few months.
