### ISSUE TITLE
Default MG Sandboxes - lifecycle of subscriptions not clear

### ISSUE THREAD

**Issue by XristophD** [Azure/terraform-azurerm-caf-enterprise-scale#860]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:  v1.6.3

**azure provider**: v3.77.0

**module**: 4.2.0

### Description
Not sure if bug or need for guidance. 

We set our default Management Group to Sandboxes. 
Running without any further configuration, subscriptions added to Sandboxes MG are tried to be removed by CAF on terraform plan: 

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/10231267/42219785-e5cd-4266-bdb4-32595443a8c9)

#### Steps to Reproduce

1. Set Default Management Group to Sandboxes
2. Add subscription to Management Group Sandboxes, do not configure anything else
3. Result: CAF tries to remove subscription on terraform plan
   Expected: CAF ignores the subscription in Default MG Sandboxes

#### Additional context

There was an old issue that has been closed due to an update on subscription and MG handling, but it doesn't seem to be fixed: 
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/24

Any help on this would be highly appreciated.

**Comment by matt-FFFFFF** [comment]
Hi!

Have you tried setting strict mode for subscriptions to be false?

This should fix your issue, though you will either have to run terraform import or move the subs into another MG before the next plan/apply.

**Comment by XristophD** [comment]
Hey @matt-FFFFFF, thank you for your fast response on this issue/question. 
I guess you are refering to [strict_subscription_association](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale#input_strict_subscription_association). 
I will try with the switch, wanted to migrate to v5.0.x anyways and this item came up for migration pre-tasks. 

Anyway, with this set to false we still will run into issues if new Subscriptions are onboarded and put into our Default-MG Sandboxes. 

For me, the lifecycle is not clear, since we probably block our deployments (plan/apply) because of new Subscriptions within a Default-MG that sits below root-MG of the caf-module. We always would have to import new subscriptions to the state first, even if they are not yet in our scope of management (and therefore are moved to a secured default-mg). 

How could we handle this differently without breaking our lifecycle. 

Currently, I worked around this by setting subscription_id_overrides for sandboxes (our default-MG) like this: 

```terraform
locals {
  # Define Subscriptions to be placed into Management Groups
  subscriptions = {
    sandboxes = [
      # List subscriptions that need to go into sanboxes-MG by definition
    ]
  }
}
 
# read all subscription within our sandboxes-MG (Default-MG)
data "azurerm_management_group" "sandboxes" {
  name = "${var.root_id}-sandboxes"
}

#...

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "4.2.0"
  
  # ... 
  subscription_id_overrides = {
     # Set subscription for Sandboxes
     sandboxes = distinct(concat(local.subscriptions.sandboxes, data.azurerm_management_group.sandboxes.subscription_ids))
  }
}
```

With this setup, new subscriptions within the sandbox-MG are more or less ignored, since we do define them via a DataSource. But the code is not really clean, since we reference MGs in the DataSource that are created by the CAF module...whereas we reference the DataSource-Output in the CAF-Module again. 

I will discuss with our team if we can set the strict_subscription_association to false and live with the downside of the blocker when new subscriptions are added to Sandboxes-MG via Default-MG assignment.

**Comment by matt-FFFFFF** [comment]
Hi! Yes I was referring to that variable.

I don't agree that you will have the same issue. With strict association set to false, any new subscriptions that are added to sandboxes will not be removed by the module.

You will have a one time task to deal with the conversion to management group subscription association resources - as per the v5 release notes.
