### ISSUE TITLE
routing_intent does not find the next hop destination when deployed with the azurerm firewall in vhub.

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-azurerm-caf-enterprise-scale#868]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**: azurerm 3.81.0

**module**: 5.0.2

#### Describe the bug

When you deploy routing intent with azurerm firewall in the same deployment in virtual hub, routing intent fails as the firewall resource id is not there at the time of the deployment. This is due to an explicit depends_on missing.

```
 API Response:
│ 
│ ----[start]----
│ {"status":"Failed","error":{"code":"InvalidNextHop","message":"The next hop '/subscriptions/xxxxxx/resourceGroups/connectivity/providers/Microsoft.Network/azureFirewalls/fw-hub-japaneast' in route/policy 'routing-intent-policy-all' in the resource '/subscriptions/xxxxxx/resourceGroups/connectivity/providers/Microsoft.Network/virtualHubs/hub-japaneast/routingIntent/routingintent-japaneast' is invalid.","details":[]}}
│ -----[end]-----
│ 
│ 
│   with module.alz.azurerm_virtual_hub_routing_intent.virtual_wan["/subscriptions/xxxxxxx/resourceGroups/connectivity/providers/Microsoft.Network/virtualHubs/hub-japaneast/routingintent-japaneast"],
│   on ../../alz/resources.virtual_wan.tf line 364, in resource "azurerm_virtual_hub_routing_intent" "virtual_wan":
│  364: resource "azurerm_virtual_hub_routing_intent" "virtual_wan" {
│ 
│ creating Routing Intent (Subscription: "xxxxxxx"
│ Resource Group Name: "connectivity"
│ Virtual Hub Name: "hub-japaneast"
│ Routing Intent Name: "routingintent-japaneast"): polling after RoutingIntentCreateOrUpdate: polling failed: the Azure API returned the following error:
│ 
│ Status: "InvalidNextHop"
│ Code: ""
│ Message: "The next hop '/subscriptions/xxxxxxx/resourceGroups/connectivity/providers/Microsoft.Network/azureFirewalls/fw-hub-japaneast' in route/policy 'routing-intent-policy-all' in
│ the resource '/subscriptions/xxxxxx/resourceGroups/connectivity/providers/Microsoft.Network/virtualHubs/hub-japaneast/routingIntent/routingintent-japaneast' is invalid."
│ Activity Id: ""
│ 
│ ---
```

#### Steps to Reproduce

Deploy virtual wan in connectivity

1. enable azurerm firewall (Premium sku + base firewall policy)
2. enable routing_intent

**Comment by matt-FFFFFF** [comment]
fixed in v5.0.3
