### ISSUE TITLE
Multiple secure hubs in virtual wan cannot share the same azure firewall base policy

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-azurerm-caf-enterprise-scale#869]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**: 5.0.2

#### Describe the bug

Cx has a requirement to share the same base firewall policy when deploying virtual wan secure hub across multiple regions. The goal is to centralize in the base firewall policy the rules that will be applied to all regional firewalls.

The current version of the module deploys a firewall and configure as well a firewall policy (see https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/557a3fc134e3e7a76c85759950818aeed68df6d4/modules/connectivity/locals.tf#L1003)

When sharing a base policy with multiple child policies, there is a requirement in Azure to colocate the policies within the same region. The error bellow highlight that requirement ***Please make sure base policy ID is a valid firewall policy ID in same region.***

```
module.alz.azurerm_firewall_policy.virtual_wan["/subscriptions/xxxx/resourceGroups/connectivity/providers/Microsoft.Network/firewallPolicies/fw-hub-japaneast-policy"]: Creating...
╷
│ Error: creating/updating Firewall Policy (Subscription: "xxxxx"
│ Resource Group Name: "connectivity"
│ Firewall Policy Name: "fw-hub-japaneast-policy"): performing CreateOrUpdate: unexpected status 400 with error: FirewallPolicyBasePolicyDoesnotExist: Base Firewall Policy /subscriptions/xxxxx/resourceGroups/connectivity-fw-policies/providers/Microsoft.Network/firewallPolicies/fw-hub-policy-base does not exist. Please make sure base policy ID is a valid firewall policy ID in same region.
│ 
│   with module.alz.azurerm_firewall_policy.virtual_wan["/subscriptions/xxxxx/resourceGroups/connectivity/providers/Microsoft.Network/firewallPolicies/fw-hub-japaneast-policy"],
│   on ../../alz/resources.virtual_wan.tf line 146, in resource "azurerm_firewall_policy" "virtual_wan":
│  146: resource "azurerm_firewall_policy" "virtual_wan" {
```

Looking at the code into more details it looks like the firewall policy got assigned the location from the azure firewall. Meaning there is no current option to set a different location to the firewall policy to deploy it within the same region as the base firewall policy.

Firewall policy location:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/557a3fc134e3e7a76c85759950818aeed68df6d4/modules/connectivity/locals.tf#L1011

Firewall location:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/557a3fc134e3e7a76c85759950818aeed68df6d4/modules/connectivity/locals.tf#L966C31-L966C39

#### Steps to Reproduce

1. Create a base policy with azurerm (region1)
2. Create a vwan hub (hub1 in region 1)
3. Create a second vhub (hub2 in region2)

Firewall policy in region 2 will fail with the above error.

One of the proposition to remediate that issue if to introduce a specific attribute to override the firewall location like **firewall_policy_location**

Extract of a possible modification for 
```hcl
azure_firewall = {
              enabled = false
              config = {
                enable_dns_proxy = true
                dns_servers = []
                sku_tier                      = "Premium"
                firewall_policy_location   = "name of the region of the base policy"
                base_policy_id                = azurerm_firewall_policy.base.id
                private_ip_ranges             = []
                threat_intelligence_mode      = "Alert"
                threat_intelligence_allowlist = []
                availability_zones = {
                  zone_1 = false # Datacenter SG Zone 1 with capacity restricted - required whitelisting by Microsoft account team
                  zone_2 = true
                  zone_3 = true
                }
              }
            }
```

**Comment by matt-FFFFFF** [comment]
Hi @LaurentLesle Thanks for flagging this - feel free to submit a PR if you would like, otherwise we will flag an an enhancement

**Comment by LaurentLesle** [comment]
Found a workaround by leveraging the configure_connectivity_resources.advanced settings with custom_settings_by_resource_type

```yaml
advanced:
 custom_settings_by_resource_type:
  azurerm_firewall:
   region:
    firewall_policy_id: <set the resource id to a firewall policy created outside of the module. >
```
