### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by shyamshindekpmg** [Azure/terraform-azurerm-caf-enterprise-scale#877]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

terraform : >= 1.3.1
azure provider : >= 3.54.0
module : enterprise_scale

#### Description: 
We are trying to do a CAF upgrade from v1.0.0 to v4.0.2. Apparently we noticed several policies and role assignments getting updated and destroyed via TF on the custom landing zones and the root management group. To mitigate the removal of policies in the code we added a file archetype_definition_es_root.tmpl.json where we added all the details present in the file
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/v4.0.2/modules/archetypes/lib/archetype_definitions/archetype_definition_es_root.tmpl.json

But we are getting below errors, probably someone can help or guide us how we can proceed with the upgrade.
One example of one of the policy.

Error decoding
"module.enterprise_scale.azurerm_policy_definition.enterprise_scale[\"/providers/Microsoft.Management/managementGroups/ngdn/providers/Microsoft.Authorization/policyDefinitions/Append-KV-SoftDelete\"]"
from prior state: unsupported attribute "management_group_name"

#### Steps to Reproduce

1. Create an environment with custom landing zones using CAF v1.0.0
2. Upgrade CAF to v4.0.2 

Please let me know if more details are required.

**Comment by matt-FFFFFF** [comment]
Hi!

This is cause by the provider change between v2 and v2:

https://registry.terraform.io/providers/hashicorp/azurerm/2.99.0/docs/resources/policy_definition

I think you might have to upgrade in stages to support the state migration between `management_group_name` and `management_group_id`.

**Comment by shyamshindekpmg** [comment]
Thank you @matt-FFFFFF for your reply.
So to resolve this should we first migrate CAF to lower version where ARM 2.99.0 or less is required and then migrate to a higher version?
Is there any other alternative that we could use? As it will double the migration effort.

**Comment by matt-FFFFFF** [comment]
I don't believe there is an alternative unfortunately
