### ISSUE TITLE
Feature Request - Policy Only Deployment

### ISSUE THREAD

**Issue by zansarif** [Azure/terraform-azurerm-caf-enterprise-scale#878]
Hi Team,

Looking for a feature to deploy the Azure Policies alone as per the below architecture without deploying all the resources in Management Group as per the below architecture.

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/115616320/d7bce3c8-1d0a-441e-9322-380690a09e43)

https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jtracey93** [comment]
Hey @zansarif,

Thanks for the issue, if you just want the management groups and the policy definitions and assignments you can follow the guidance here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Demo-Landing-Zone-Archetypes

**Comment by SteveBurkettNZ** [comment]
@jtracey93:  Is it possible to deploy just the policy definitions and policy assignments (no management groups, for those brownfield scenarios where they've deployed the management group structure previously but haven't yet got any Azure Policy in place?)
