### ISSUE TITLE
Unable to create policy for custom landing zone

### ISSUE THREAD

**Issue by alefrau** [Azure/terraform-azurerm-caf-enterprise-scale#880]
I've tried to assign one custom policy to a customs landing zone, i've followed this guide [Enforce-RG-Tags](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy-Sets-and-Assignments#libpolicy_definitionspolicy_definition_es_enforce_rg_tagsjson). When i run terraform plan i obtain this error:

`╷
│ Error: reading Policy Definition "Enforce-RG-Tags": policy.DefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicyDefinitionNotFound" Message="The policy definition 'Enforce-RG-Tags' could not be found."
│
│   with module.enterprise_scale.data.azurerm_policy_definition.external_lookup["/providers/Microsoft.Management/managementGroups/ROOT/providers/Microsoft.Authorization/policyDefinitions/Enforce-RG-Tags"],
│   on .terraform/modules/enterprise_scale/locals.policy_assignments.tf line 167, in data "azurerm_policy_definition" "external_lookup":
│  167: data "azurerm_policy_definition" "external_lookup" {
│
╵`
Seems that the module try to search the policy in the Root Mgmt group.

BR,
Ale

**Comment by praveenambati1233** [comment]
I am hitting to the same error, how this issue is resolved ? @alefrau
