### ISSUE TITLE
Public network access must be disabled for PaaS services policy is  blocking storage account even thus it set to have public_access = false

### ISSUE THREAD

**Issue by hungbui78** [Azure/terraform-azurerm-caf-enterprise-scale#881]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
Terraform v1.6.2
on darwin_arm64

**azure provider**:
provider registry.terraform.io/hashicorp/azurerm v3.85.0

**module**:
4.2.0

#### Describe the bug

We are trying to create storage account on our tenant which has been deployed by this CAF module version 4.2.0. We are getting errors where it say the Public network access must be disabled for PaaS services policy  is blocking the creation.

We have set both parameters below to false but it is still not working.

```
 allow_nested_items_to_be_public = false

  public_network_access_enabled = false 
```

#### Steps to Reproduce

1. Add this code
```
resource "azurerm_storage_account" "example" {
 
  name                                          = "storageaccountname"
  resource_group_name             = "Project1"
  location                                      = "Sweden Central"
  account_replication_type        = "LRS"
  account_tier                              = "Premium"
  allow_nested_items_to_be_public = false
  public_network_access_enabled = false

  tags = {
    environment = "staging"
  }
}
```
3. terraform init and terraform apply
4. 
 And you will get this error.
 
 "Storage Account Name: "storageaccountname"): storage.AccountsClient#Create: Failure sending request: StatusCode=403 -- Original Error: Code="RequestDisallowedByPolicy" Message="Resource 'storageaccountname' was disallowed by policy. Reasons: 'Public network access must be disabled for PaaS services.'. See error details for policy resource IDs." Target="storageaccountname" AdditionalInfo=[{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"type","expressionKind":"Field","expressionValue":"Microsoft.Storage/storageAccounts","operator":"Equals","path":"type","result":"True","targetValue":"Microsoft.Storage/storageAccounts"},{"expression":"Microsoft.Storage/storageAccounts/networkAcls.defaultAction","expressionKind":"Field","expressionValue":"Allow","operator":"NotEquals","path":"properties.networkAcls.defaultAction","result":"True","targetValue":"Deny"}],"reason":"Public network access must be disabled for PaaS services."},"policyAssignmentDisplayName":"Public network access should be disabled for PaaS services","policyAssignmentId":"/providers/Microsoft.Management/managementGroups/prodTF-corp/providers/Microsoft.Authorization/policyAssignments/Deny-Public-Endpoints","policyAssignmentName":"Deny-Public-Endpoints","policyAssignmentParameters":{},"policyAssignmentScope":"/providers/Microsoft.Management/managementGroups/prodTF-corp","policyDefinitionDisplayName":"Storage accounts should restrict network access","policyDefinitionEffect":"Deny","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/34c877ad-507e-4c82-993e-3452a6e0ad3c","policyDefinitionName":"34c877ad-507e-4c82-993e-3452a6e0ad3c","policyDefinitionReferenceId":"StorageDenyPaasPublicIP","policyExemptionIds":[],"policySetDefinitionDisplayName":"Public network access should be disabled for PaaS services","policySetDefinitionId":"/providers/Microsoft.Management/managementGroups/prodTF/providers/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints","policySetDefinitionName":"Deny-PublicPaaSEndpoints"},"type":"PolicyViolation"}]
│ 
│   with azurerm_storage_account.example,
│   on main.tf line 25, in resource "azurerm_storage_account" "example":
│   25: resource "azurerm_storage_account" "example" {
│ "

#### Additional context

How do we get past this with the policy activated?

**Comment by matt-FFFFFF** [comment]
Can you try creating the storage account with AzAPI?

This might be a issue with the provider's imperative operations

**Comment by terryseddonpm** [comment]
Hi, i'm getting this problem too. What was the fix?
