### ISSUE TITLE
Log Analytics SKU and other settings being reverted

### ISSUE THREAD

**Issue by cmohams9** [Azure/terraform-azurerm-caf-enterprise-scale#883]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.2

**azure provider**:  3.85

**module**:

### Description

Log Analytics settings modified outside Terraform is being reverted when running the CAF code for other changes

#### Describe the bug

Log Analytics workspace pricing Tier was changed in the Azure Portal directly to 100 GB Commitment Tier. However, this change is getting reverted while running the TF CAF code for applying other changes. Please see plan output below.

Terraform will perform the following actions:

  # module.enterprise_scale.azurerm_log_analytics_workspace.management["/subscriptions/4c526d48-4f3e-462b-b979-61011fcae45e/resourceGroups/jci-mgmt/providers/Microsoft.OperationalInsights/workspaces/jci-la"] will be updated in-place
  ~ resource "azurerm_log_analytics_workspace" "management" {
      - data_collection_rule_id                 = "/subscriptions/4c526d48-4f3e-462b-b979-61011fcae45e/resourceGroups/jci-mgmt/providers/Microsoft.Insights/dataCollectionRules/ServiceAccounts_Exclusion" -> null
        id                                      = "/subscriptions/4c526d48-4f3e-462b-b979-61011fcae45e/resourceGroups/jci-mgmt/providers/Microsoft.OperationalInsights/workspaces/jci-la"
        name                                    = "jci-la"
      - reservation_capacity_in_gb_per_day      = 100 -> null
      ~ sku                                     = "CapacityReservation" -> "PerGB2018"
        tags                                    = {
            "deployedBy" = "terraform/azure/caf-enterprise-scale"
        }
        # (13 unchanged attributes hidden)
    }

#### Steps to Reproduce

1. step 1
Update Loganalytics pricing tier outside Terraform module

2. step 2

Run Terraform plan which informs you of the changes being reverted

5. you get it...

**Comment by matt-FFFFFF** [comment]
Hi - you have changed settings that are managed by TF, you can set custom settings using the advanced block:

- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/332
