### ISSUE TITLE
Conflict Error when Deleting Linked Automation Account

### ISSUE THREAD

**Issue by Mousling1992** [Azure/terraform-azurerm-caf-enterprise-scale#884]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.6.3

**azure provider**: 3.85.0

**module**: 5.0.3

### Description
I’m encountering a conflict error when trying to delete an Automation Account that is linked to a workspace using the terraform-azurerm-caf-enterprise-scale module. The error message is as follows:
`unexpected status 409 with response: {"code":"Conflict","message":"\"Automation account is linked to a workspace so it cannot be deleted.
`
#### Describe the bug
The module throws a conflict error when trying to delete an Automation Account that is linked to a workspace.

#### Steps to Reproduce

1. Deploy Caf with Management Settings
2. Try a change on the the automation account like the name
3. New Automation get created but the old cannot be delete and throws the above failure

#### Screenshots
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/96351261/e973968e-7d54-4fda-a67b-60ed2d965e5e)

**Comment by matt-FFFFFF** [comment]
Hi, unfortunately you will have to manually unlink the AA from the workspace

**Comment by Mousling1992** [comment]
ok

**Comment by Mousling1992** [comment]
This is not so easy because you ll also have to unlink the solutions also like mention here: `(Linked Service is used by a solution) The link cannot be updated or deleted because it is linked to Update Management and/or ChangeTracking Solutions.`

**Comment by matt-FFFFFF** [comment]
It is unfortunate that Terraform is not able to do this for you but I do not believe it is possible sadly.
