### ISSUE TITLE
tfstate management. 

### ISSUE THREAD

**Issue by d4kverma** [Azure/terraform-azurerm-caf-enterprise-scale#888]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
 - There is no preper Guidance to use Remote tfstate conslidated managment for all managment group resources

**Comment by jtracey93** [comment]
Hey @d4kverma,

Checkout our accelerator here: https://aka.ms/alz/tf/accelerator

**Comment by d4kverma** [comment]
@jtracey93 I have checkout accelerator repo . After using this repo i am not able to locally download the parent module and sync with my child module code.

**Comment by matt-FFFFFF** [comment]
Hi @d4kverma 

We do not support using this code as a root module, especially as you have modified it.

The ALZ Accelerator helps you by configuring a repo for your code (and many other things). Just add your code to the repo it creates and it will work.
