### ISSUE TITLE
feat: private DNS zone for OpenAI. 

### ISSUE THREAD

**Issue by panwar28** [Azure/terraform-azurerm-caf-enterprise-scale#890]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

**Comment by panwar28** [comment]
As per the documentation, it should be created during the deployment but it is not being created **privatelink.openai.azure.com.** 

"By default the module create a private DNS zone for all services which currently [support private endpoints](https://learn.microsoft.com/azure/private-link/private-endpoint-dns#azure-services-dns-zone-configuration). New private DNS zones may be added in future releases as additional services offer private endpoint support."

**Comment by matt-FFFFFF** [comment]
Hi!

This is not a bug but we will add it to our backlog as a feature request

**Comment by glloyd2010f** [comment]
If we are adding new Private DNS Zones, would it be possible to include `scm.privatelink.azurewebsites.net` so that app service deployments can be done completely internally?
