### ISSUE TITLE
Module outputs refer to sensitive values

### ISSUE THREAD

**Issue by JaegerP** [Azure/terraform-azurerm-caf-enterprise-scale#892]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.7 (latest shipped for MacOS with homebrew)

**azure provider**: >= 3.74.0

**module**: 5.0.3

#### Describe the bug

I'm deploying a testing version of the landing zone, with demo landing zones, and identity, management, and connectivity resources enabled, without any additional configuration.

Running terraform plan results in the following error:

```
Error: Output refers to sensitive values
│ 
│   on outputs.tf line 84:
│   84: output "azurerm_log_analytics_workspace" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true
```

and a similar one on line 102.

#### Steps to Reproduce

1. Configure the module as follows:

```
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "5.0.3" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  default_location = var.location
  default_tags     = var.tags

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name

  deploy_demo_landing_zones = true

  deploy_management_resources = true
  subscription_id_management  = module.subscriptions.subscription_id_map[local.subscription_name_management]

  deploy_identity_resources = true
  subscription_id_identity  = module.subscriptions.subscription_id_map[local.subscription_name_identity]

  deploy_connectivity_resources = true
  subscription_id_connectivity  = module.subscriptions.subscription_id_map[local.subscription_name_connectivity]
}
```

2. run `terraform plan`

### Proposed solution

1. Add the `sensitive = true` argument to the above-mentioned outputs on lines 84 and 102 in outputs.tf (I'm currently using this as a fix on my fork of the repository)
2. Since the outputs are considered sensitive, consider removing said outputs

I'm willing to submit a pull request once the solution has been decided.

**Comment by Laudenlaruto** [comment]
Hey @JaegerP I just tested your solution locally and it seems to work.

**Comment by matt-FFFFFF** [comment]
Hi can you please confirm terraform versions, provider versions and module version.

Can you please also supply module config?

Thanks!

**Comment by matt-FFFFFF** [comment]
Hi - apologies we will try and repro this. Can you confirm the exact provider version that you are experiencing the issue with?

**Comment by JaegerP** [comment]
Hi @matt-FFFFFF, I've tried several provider versions, since I first assumed it might be an issue with 3.89, but the problem persisted with 3.88, and all the way back to 3.74.

**Comment by JaegerP** [comment]
@matt-FFFFFF any update on this?

**Comment by Laudenlaruto** [comment]
@JaegerP I created the pull request to fix this.

**Comment by JaegerP** [comment]
Thanks @Laudenlaruto. Any estimate when the fix will be included in a release?
