### ISSUE TITLE
Customdata was not executing my script using CAF

### ISSUE THREAD

**Issue by madhulikasarangam** [Azure/terraform-azurerm-caf-enterprise-scale#912]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

**Comment by madhulikasarangam** [comment]
Hi Team,

I am passing the commands in vm.tfvars customdata block but it is not executing. Could some one please assist

**Comment by matt-FFFFFF** [comment]
Hi please could you detail the configuration you are using? I don't understand what you mean by customdata and vm.tfvars

**Comment by madhulikasarangam** [comment]
Issue was resolved.

I am talking about below custom_data configuration.

        disable_password_authentication = true
        custom_data = "../../singtel/level3/Ss/scripts/fs.sh"

Regards,
Madhulika

**Comment by matt-FFFFFF** [comment]
Thanks, I don't think this pertains to this module. Nevertheless thanks for letting me know we can close the issue
