### ISSUE TITLE
Upgrade to 5.2.0 will recreate all public dns zones created by the module

### ISSUE THREAD

**Issue by endreigesund** [Azure/terraform-azurerm-caf-enterprise-scale#921]
Upgrade from 5.1.0 to 5.2.0 will destroy and create all public dns zones thats earlier created by the module.

This is mentioned already in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/910 

Should at least be warned in upgrade docomentation.

**Comment by matt-FFFFFF** [comment]
Hi - fair comment. Did you use the `moved {}` block to remedy this>?

**Comment by endreigesund** [comment]
Yes, or maybe i altered it using terraform state commands. But state modification was needed :)

**Comment by matt-FFFFFF** [comment]
Understood - apologies
