### ISSUE TITLE
Network Gateway gets new default parameters with azurerm >= 3.84.0

### ISSUE THREAD

**Issue by chrsundermann** [Azure/terraform-azurerm-caf-enterprise-scale#924]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

We are using the module to deploy hub and spoke topology. Since we have some dependencies to azurerm version 3.84.0 and upwards the following parameters for azurerm_virtual_network_gateway will change by default:

- remote_vnet_traffic_enabled = true => false
- virtual_wan_traffice_enabled = true => false

#### Describe the solution you'd like

We need to control these parameters to keep them as they are.

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/35773501/ea9b54f6-ade0-4163-84c0-87531e0bff21)

**Comment by matt-FFFFFF** [comment]
fixed by #968
