### ISSUE TITLE
is there a way to remove the default Policy assigned in the root management group?

### ISSUE THREAD

**Issue by christiancruz11** [Azure/terraform-azurerm-caf-enterprise-scale#926]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We are using a different Log Analytics Workspaces for each landing zone and we want to create a new policy assignment for "Deploy-Resource-Diag" so we can assign the Log Analytics Workspace ID separately.

How can we remove the default role assignment of "Deploy-Resource-Diag" policy in the root management group.

#### Is your feature request related to a problem?

I'm not sure if this feature already exist.

#### Describe the solution you'd like

Remove the default role assignment of "Deploy-Resource-Diag" policy in the root management group.
So we can assign it separately.

**Comment by chrsundermann** [comment]
You can think about doing it with the archetype_config_overrides option and using the template from the original source code file but deleting the "Deploy-Resource-Diag" entry. Just an idea.

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/archetype_definitions/archetype_definition_es_root.tmpl.json

**Comment by matt-FFFFFF** [comment]
You can also use the archetype exclusions: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions#to-enable-the-exclusion-function
