### ISSUE TITLE
How can I create a Custom initiative

### ISSUE THREAD

**Issue by diegosrp** [Azure/terraform-azurerm-caf-enterprise-scale#927]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.7.4

**azure provider**: 3.91.0

**module**: core

#### I would like to create custom initiatives, but I can't reproduce it, I tried following: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy -Sets-and-Assignments#libpolicy_definitionspolicy_definition_es_enforce_rg_tagsjson

and I received a return of the created resources ok but at the end I got an error message

│ Error: reading Policy Set Definition "Enforce-Mandatory-Tags": policy.SetDefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicySetDefinitionNotFound" Message="The policy set definition 'Enforce-Mandatory-Tags' could not be found."
│ 
│   with module.enterprise_scale.data.azurerm_policy_set_definition.external_lookup["/providers/Microsoft.Management/managementGroups/mg-space/providers/Microsoft.Authorization/policySetDefinitions/Enforce-Mandatory-Tags"],
│   on .terraform/modules/enterprise_scale/locals.policy_assignments.tf line 88, in data "azurerm_policy_set_definition" "external_lookup":
│   88: data "azurerm_policy_set_definition" "external_lookup" {
│ 

Releasing state lock. This may take a few moments...

**If I want to create and associate the initiative: ISO 27001:2013**

I could access: https://www.azadvertizer.net/azpolicyinitiativesadvertizer/89c6cddc-1c73-4ac1-b19c-54d1a15a42f2.html

copy the json definition and put it in a policy_set_definition file and add it to the extend? Or do I need to create policy_assignment for all policies? Is there any less laborious way to acquire this information?
what would be the step by step?

Cheers

**Comment by diegosrp** [comment]
I see on the question too https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Assign-a-Built-in-Policy
for Nist all good but Iso or NZ ISM Restricted etc I can't

**Comment by chrsundermann** [comment]
Because this is already a Policy Initiative, you just have to do a Policy Assignment pointing on the PolicyID. For example ISO:
/providers/Microsoft.Authorization/policySetDefinitions/89c6cddc-1c73-4ac1-b19c-54d1a15a42f2

And then you must put the name of the assignment in your "archetype_extend" file to scope it on your favorite management group scope.

**Comment by diegosrp** [comment]
Right, can you give me an example of what the extend would look like? because I had the impression that I would only be able to associate what is in the module and not in the portal without creating the files and at the same time to create a customized one, which would be necessary?

currently:
{
  "extend_es_landing_zones": {
    "policy_assignments": [
      "Deny-Resource-Locations",
      "Deny-RSG-Locations",
      "Deny-Resource-Types"
      
  ],
  "policy_definitions": [
    
],
  "policy_set_definitions": [
   
  ],
  "role_definitions": [],
  "archetype_config": {
      "parameters": {
          "Deny-Resource-Locations": {
              "listOfAllowedLocations": [
                  "eastus",                 
                  "global"
              ]
          },
          "Deny-RSG-Locations": {
            "listOfAllowedLocations": [
                "eastus",
                "global"
            ]
          },
          "Deny-Resource-Types": {
                    "listOfResourceTypesNotAllowed":{
              "value": ["Microsoft.Network/azureFirewalls"]
          } 
        }           
      },
      "access_control": {}
  }
 }
}

**Comment by chrsundermann** [comment]
I don't know the name of the assignment but in theory it should look like:

currently:
{
"extend_es_landing_zones": {
"policy_assignments": [
"Deny-Resource-Locations",
"Deny-RSG-Locations",
"Deny-Resource-Types"
**"<name_of_your_iso_policy_assignment>"**
],
"policy_definitions": [

],
"policy_set_definitions": [

],
"role_definitions": [],
"archetype_config": {
"parameters": {
"Deny-Resource-Locations": {
"listOfAllowedLocations": [
"eastus",
"global"
]
},
"Deny-RSG-Locations": {
"listOfAllowedLocations": [
"eastus",
"global"
]
},
"Deny-Resource-Types": {
"listOfResourceTypesNotAllowed":{
"value": ["Microsoft.Network/azureFirewalls"]
}
}
},
"access_control": {}
}
}
}

**Comment by diegosrp** [comment]
Your logic is correct, for policies where the files exist, but for those that don't exist, it's not quite like that because otherwise, it wouldn't make sense to have the extra files in my view. I tried but no success, thank you @chrsundermann

if anyone have info about that I appreciate

**Comment by krowlandson** [comment]
@diegosrp there are three critical parts to this.

Firstly, you need to ensure you add definition files to the `lib` folder for any custom definitions or iniatives you want to add.

You then need to ensure suitable assignment files are also added to the `lib` folder.

Finally, you need to extend your archetype definition as per the example shared by @chrsundermann.

Hope this helps but please post if you need further assistance.

**Comment by diegosrp** [comment]
For example I would like to apply "NZ-ISM-Restricted-v3.5"

1 - I would create the 162 policy file and add it to folder policy_assignments
2 - I would create its policy set definition file with all the policies it will have in policy_set_definition folder.
3 - And Extend I would add in policy assignments as 162 policy name and in policy_set_definition the name of the initiative from the set_definition file that I created, would that be it?

example:
{
  "extend_es_root": {
      "policy_assignments": [
        "policy1",
        "policy2", ......
      ],
      "policy_definitions": [],
      "policy_set_definitions": [
        "NZ-ISM-Restricted-v3.5"

      ],
      "role_definitions": [],
      "archetype_config": {
          "parameters": { },
          "access_control": {}
      }
  }
}

**Comment by diegosrp** [comment]
?

**Comment by matt-FFFFFF** [comment]
Hi,

You only need to add the _new_ policy artifacts to you local `lib`. So in this case the set definition and the assignment.

You can then use the extend archetype to add the new assets.

You can then use archetype config override to set the new archetype on a MG
