### ISSUE TITLE
Possible to have more than one landing zone implementation share core subscriptions?

### ISSUE THREAD

**Issue by jpg9503** [Azure/terraform-azurerm-caf-enterprise-scale#932]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am interested in exploring the possibility of having 2 instances of a landing zone. Once instance would be a complete implementation with "core", "management", "networking" and "identity" resources. The second instance I would like to just implement the "core" (Landing zone management groups and associated policies) resources and point to the management, networking and identity resources of the first implementation. 

The reasoning behind this is to provide "early access" of changes in applicable Azure Policy to a subset of workloads before those same policy changes are applied to the workloads in the "complete" landing zone implementation. The thinking here is that it is policy changes that workload administrators would need to evaluate and respond to whereas the mgmt/network/idm resources are more centrally managed where change can be evaluated differently and don't need to be re-implemented. Since Policy is defined at the root and "Landing Zones" levels (in addition to specific landing zones beneath), it would seem that the only way to be prepared to evaluate potential policy changes in module upgrades, etc,  would be to instantiate two different LZ implementations. 

I thought I could just use the pattern of separate module instantiations with remote terraform state as shown in the wiki as a way to achieve this - but where I run into a problem is that if I define subscription_id_management/subscription_id_connectivity to have the module reference those subscription ids in policy, etc - it also wants to place those subscriptions under the core management groups and I only want them placed under the core management groups of the complete landing zone implementation (and not the core policy only implementation).

In looking at the documentation/code, I didn't see an option for preventing the module from attempting to place the subscription_id_management (as well as the the connectivity one) under the corresponding management group? Am I missing some configuration that could accomplish this? If not, it would be nice for this capability to be a new configuration feature.

Thanks for your consideration! - John

**Comment by matt-FFFFFF** [comment]
Hi! This module is somewhat opinionated - therefore it expects to deploy the core MGs in a fixed configuration.

You can disable this by deploy_core_landing_zones to false and then configuring everything as a custom_landing_zone
