### ISSUE TITLE
Issue related to the Management module-with module.enterprise_scale.azurerm_subscription_template_deployment.telemetry_core[0],

### ISSUE THREAD

**Issue by azhaq12** [Azure/terraform-azurerm-caf-enterprise-scale#936]
We have deployed landing zone with the help of terraform coding using this to reference  on the "Management" 

**Steps to reproduce**

1.Go the module called "Management"
2.Set the management subscription 
3.if you have backend variable then add get your environment up and running
4.then run "terraform init" ---- follow by "terraform plan -out current.tfplan" and then "terraform apply  current.tfplan"  you will see the error on that  

**Screenshots**
Issue screenshot below:
![Error 1 ](https://github.com/Azure/Enterprise-Scale/assets/164519925/4901e8ec-32fb-432c-b46b-cd35da46abeb)

**Comment by azhaq12** [comment]
Any update on this one?

**Comment by matt-FFFFFF** [comment]
You look to have tried to deploy the module, then have removed resources in Azure and tried to re-deploy.

You can either:

* add an import block to import the template deployment
* manually remove the telemetry ARM template deployment from the subscription, you can use the portal Subscriptions -> deployments, or use cli tools and delete by resource id
*
