### ISSUE TITLE
Issue related to the Core module-with Error: Duplicate object key │ │   on .terraform\modules\enterprise_scale\modules\archetypes\locals.policy_set_definitions.tf line 52, in locals: │   50:   custom_policy_set_definitions_map_from_json = try(length(local.custom_policy_set_definitions_dataset_from_json) > 0, false) ? { Bug Report

### ISSUE THREAD

**Issue by azhaq12** [Azure/terraform-azurerm-caf-enterprise-scale#937]
We have deployed landing zone with the help of terraform coding using this to reference on the "Core"

Steps to reproduce

1.Go the module called "Core"
2.Set the Core subscription
3.if you have backend variable then add get your environment up and running
4.then run "terraform init" ---- follow by "terraform plan -out current.tfplan" and then "terraform apply current.tfplan" you will see the error on that

Screenshots
Issue screenshot below:
![image](https://github.com/Azure/Enterprise-Scale/assets/164519925/5e1c51d6-1fc5-46e6-b484-d7caf4c77d0c)

**Comment by azhaq12** [comment]
Any update on this issue?

**Comment by matt-FFFFFF** [comment]
Please can you post your module configuration?

**Comment by azhaq12** [comment]
# You can use the azurerm_client_config data resource to dynamically
# extract connection settings from the provider configuration.

data "azurerm_client_config" "core" {}

# Call the caf-enterprise-scale module directly from the Terraform Registry
# pinning to the latest version

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "5.1.0" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  default_location = var.primary_location

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
    
  }

  subscription_id_connectivity = var.subscription_id_connectivity
  subscription_id_management = var.subscription_id_management
  subscription_id_identity = var.subscription_id_identity

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.root}/lib"

  custom_landing_zones = {
    "${var.root_id}-Public" = {
      display_name               = "${upper(var.root_id)} Public"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "customer_online"
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-Internal" = {
      display_name               = "${upper(var.root_id)} Internal"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id = "customer_online"
        parameters = {
          Deny-Resource-Locations = {
            listOfAllowedLocations = ["swedencentral", ]
          }
          Deny-RSG-Locations = {
            listOfAllowedLocations = ["swedencentral", ]
          }
        }
        access_control = {}
      }
    }
  }
}



###########TERRAFORM File 
# We strongly recommend using the required_providers block to set the
# Azure Provider source and version being used.

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.74.0"
    }
  }
  backend "azurerm" {
    resource_group_name    = "rg-terraformstate-prod"
    storage_account_name 	 = "ahlensstterraform01"
    container_name 	 = "core"
    key 	 = "terraform.tfstate"
  }
}

provider "azurerm" {
  features {}
}

#####################################
variable "root_id" {
  type        = string
  description = "Sets the value used for generating unique resource naming within the module."
  default     = ""
}

variable "root_name" {
  type        = string
  description = "Sets the value used for the \"intermediate root\" management group display name."
  default     = ""
}

variable "primary_location" {
  type        = string
  description = "Sets the location for \"primary\" resources to be created in."
  default     = "swedencentral"
}

variable "secondary_location" {
  type        = string
  description = "Sets the location for \"secondary\" resources to be created in."
  default     = "westeurope"
}

variable "subscription_id_connectivity" {
  type        = string
  description = "Subscription ID to use for \"connectivity\" resources."
  default     = "
}
 
variable "subscription_id_management" {
  type        = string
  description = "Subscription ID to use for \"management\" resources."
  default     = 

variable "subscription_id_identity" {
  type        = string
  description = "Subscription ID to use for \"identity\" resources."
  default     = "
}

**Comment by matt-FFFFFF** [comment]
This looks like an issue with your custom library configuration. You seems to have duplicate names for the policy definitions and another duplicate name for the policy set definitions.

Review the JSON files and inspect the `.Name` property so find duplicates,

**Comment by azhaq12** [comment]
The issue is not in the .name file these are by default given by AZURE CAF model no further changes have been made from our end

**Comment by matt-FFFFFF** [comment]
You have a custom library set, what files are in your `./lib` dir?
