### ISSUE TITLE
Bug Report : Continuous Destroy and then Create of azapi_resource diag_settings

### ISSUE THREAD

**Issue by Keetika-Yogendra** [Azure/terraform-azurerm-caf-enterprise-scale#939]
Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Continuos Destroy and then Create of azapi_resource diag_settings**

The module successfully deploys the Cloud Adoption Framework. However, when doing a plan with no changes to the parameters in the module, we are getting 10 add and 10 destroy of the resource "azapi_resources"  "diag_settings". 

__________________
module.enterprise_scale.azapi_resource.diag_settings["/providers/Microsoft.Management/managementGroups/testtenant-sandboxes"] must be replaced
-/+ resource "azapi_resource" "diag_settings" {
      ~ id                        = "/providers/Microsoft.Management/managementGroups/testtenant-sandboxes/providers/Microsoft.Insights/diagnosticSettings/toLA" -> (known after apply)
      - location                  = "global" -> null # forces replacement
        name                      = "toLA"
      ~ output                    = jsonencode({}) -> (known after apply)
        # (7 unchanged attributes hidden)
    }

Plan: 10 to add, 0 to change, 10 to destroy.

_____________________________________________________________________________________

Help regarding resolution of this issue will be much appreciated.

**Comment by matt-FFFFFF** [comment]
fixed by #968
