### ISSUE TITLE
failed to upload alerts to security tab caf-enterprise-scale terraform

### ISSUE THREAD

**Issue by kissimajanneh** [Azure/terraform-azurerm-caf-enterprise-scale#942]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.8.0

**azure provider**: 3.102.0

**module**: 5.2.1

### Description
Code Scanning could not process the submitted SARIF file:
#### Describe the bug

We are using the Azure Landing Zone terraform module to deploy Infrastructure.  The module works fine, but when we configure the "Microsoft Security DevOps GitHub action" to work with the module it fails with the below error message.

Error: Code Scanning could not process the submitted SARIF file:
an invalid URI was provided as a SARIF location: parse ":https:/github.com/Azure/terraform-azurerm-caf-enterprise-scale": missing protocol scheme, an invalid URI was provided as a SARIF location: parse ":https:/github.com/Azure/terraform-azurerm-caf-enterprise-scale": missing protocol scheme
Error: Code Scanning could not process the submitted SARIF file:
an invalid URI was provided as a SARIF location: parse ":https:/github.com/Azure/terraform-azurerm-caf-enterprise-scale": missing protocol scheme, an invalid URI was provided as a SARIF location: parse ":https:/github.com/Azure/terraform-azurerm-caf-enterprise-scale": missing protocol scheme
    at Object.waitForProcessing (D:\a\_actions\github\codeql-action\v3\lib\upload-lib.js:437:[27](https://github.com/Finanstilsynet-enterprise/rp-tf-infra-management/actions/runs/8967096410/job/24631875005#step:6:30))
    at async run (D:\a\_actions\github\codeql-action\v3\lib\upload-sarif-action.js:63:13)
    at async runWrapper (D:\a\_actions\github\codeql-action\v3\lib\upload-sarif-action.js:84:9)

#### Additional context
![msdo](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/100125910/e23a2c9a-2612-45ec-9310-a7603fb75cc5)

**Comment by matt-FFFFFF** [comment]
Hi looks like you have a prefix colon in your URL - this is the issue. As it's not pertaining ot his module I'm going to close this issue
