### ISSUE TITLE
 Error: Invalid index error: archetype_definition = local.archetype_definitions[local.archetype_id] on tf apply/delete etc

### ISSUE THREAD

**Issue by kevinjlo** [Azure/terraform-azurerm-caf-enterprise-scale#947]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.6.5

**azure provider**:3.87.0

**module**:enterprise_scale 5.2.1

#### Describe the bug

Upon execution of terraform apply for the azure scale landing zone basic deployment i get the following errors
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with no attributes
│     │ local.archetype_id is "es_management"
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with no attributes
│     │ local.archetype_id is "es_decommissioned"
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with no attributes
│     │ local.archetype_id is "es_identity"
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with no attributes
│     │ local.archetype_id is "es_connectivity"
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with no attributes
│     │ local.archetype_id is "es_platform"
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with no attributes
│     │ local.archetype_id is "es_landing_zones"
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with no attributes
│     │ local.archetype_id is "es_sandboxes"
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\enterprise_scale\modules\archetypes\locals.archetype_definitions.tf line 175, in locals:
│  175:   archetype_definition = local.archetype_definitions[local.archetype_id]
│     ├────────────────
│     │ local.archetype_definitions is object with no attributes
│     │ local.archetype_id is "es_root"
│
│ The given key does not identify an element in this collection value.

#### Steps to Reproduce

run terraform apply upon the enterprise scale tf code with the basic block
module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "5.2.1" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  default_location = "Canada Central"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = "xxx"
  root_name      = "xxx"
}

**Comment by kevinjlo** [comment]
Ive been trying to redeploy this script and it mainly happens after subsequent terraform plans and updates 
On first try, the script will deploy level 100 AZ ES landing zones

**Comment by matt-FFFFFF** [comment]
It seems like the module has no archetype definitions. Can you try the configuration outside of caf-terraform-landingzones?

**Comment by davidsandbrand** [comment]
@kevinjlo & anyone else that might find this in the future,

I have traced this error to be an issue with **OneDrive**.  If you move the folder out of OneDrive and onto local storage, the plan will build correctly after the first run.  Dropbox does not have the same issue, FWIW.

Part of my troubleshooting involved having the folder **out** of OneDrive, pausing the OneDrive sync, and moving the folder back into the paused OneDrive.  In this case, the plan will build correctly multiple times - until OneDrive sync is un-paused at which point it then throws the same error.  And it's always the same error, referencing the same line of the same file (175 of locals.archetype_definitions.tf).

It's worth noting that the first time building the plan always works even with OneDrive sync enabled, and it's only subsequent builds that are blocked.  There seems to be no difference if the folder in OneDrive is flagged to 'Always keep on this device', or the sync is later paused - it continues to fail 100% of the time once OneDrive has sync'd the folder once after the initial plan build.
