### ISSUE TITLE
`root_name` limited to 24 characters, should be 90

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/terraform-azurerm-caf-enterprise-scale#948]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.8.3

**azure provider**: 3.74.0

**module**: 5.2.1

#### Describe the bug

Customer set a `root_name` variable with a length of more than 24 but less than 90. The terraform validation failed. However, the root_name is the name of a management group, and they can be up to 90 characters long: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftmanagement

#### Steps to Reproduce

1. Define `root_name` variable as something like `Some University System Name`
2. Run `terraform plan`

**Comment by jtracey93** [comment]
Hey @SvenAelterman,

Thanks for the feature ask

Today the code in the module checks if `var.root_name` is a string of 3 to 24 characters long, starts and ends with a letter or number, and the middle can contain letters, numbers, hyphens, spaces, dots, or underscores.

Would you like to submit a PR to change this and provide testing evidence?
