### ISSUE TITLE
Error: Invalid for_each argument" because local.azurerm_policy_definition_external_lookup will be known only after apply

### ISSUE THREAD

**Issue by krmohansingh** [Azure/terraform-azurerm-caf-enterprise-scale#950]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

terraform: 1.3.4 (also tried with 1.3.2)

azure provider: ">=3.2"

module: Azure/caf-enterprise-scale/azurerm : 3.3.0

### Description

Running the terraform github workflow to run terraform plan getting below error even after reverting back the latest change and after that none of the pipeline is running fine.

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/50234904/c860e864-29fb-4ad0-aa34-6a135c0ecaf1)

Please let us know do we have to do anything with the state file, as nothing is working. Tried below options

1. Tried older caf module version 
2. Reverted back the last change we made before this error.

#### Steps to Reproduce

Unable to find why this error, is there something wrong with the state file. Do we need to do terraform refresh??

**Comment by krmohansingh** [comment]
Even tried to compare the state file for the time stamp when the pipeline start throwing error with the pipeline got succeeded, not able to find any difference.

Tried to restore the state file for the previous when pipeline was running file , still unable to fix the problem. 

Could you please suggest what else we could do as a troubleshooting steps.

**Comment by jtracey93** [comment]
This generally indicates a policy definition ID in one of the lib files is incorrect or has an ID to a policy that is incorrect. 

Have you checked all these for any changes?

Have you also tried disabling the custom lib and running a plan to see if it completes? As I take it this happens at plan stage?

**Comment by krmohansingh** [comment]
@jtracey93  Here is the scenario, we have two branches 

1. Develop branch ------ > we use feature/xxxx to deploy anything to development environment 
2. Main branch --------> we use release from develop branch to deploy to production environment via main branch 

We have tried to disable custom lib and run terraform plan, it succeeds. But when we create any feature branch out of main branch or develop branch terraform plan fails with the above error. 

Although if there is an issue with main branch, it should throw the same error, but it's not throwing any error in the main branch. Only develop or feature branches are getting failed.

Could you please suggest something else we could try to troubleshoot this?

However, I am verifying all the policy definition ID again and see if something is going wrong in the ID of them.

**Comment by jtracey93** [comment]
The fact it succeeds without a custom lib suggests this is something wrong in the lib...

**Comment by krmohansingh** [comment]
may be and we are trying to isolate the problem here. Now we were able to run the pipeline without any issue, but with no policy assignment defined in the archtype. 

And as soon as we keep one policy assignment, we are getting below error related to role_assignment. 

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/50234904/47074eb4-22f0-497f-b3cf-41c26fb52ddc)

We checked state file and remove all the role assignment reference and still we are getting this. Please find below is our policy assignment .json file 

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/50234904/6ba7193b-e065-4427-9d7a-5630f3c14716)

Please suggest how can we resolve this, as this was working before without any issues.

**Comment by matt-FFFFFF** [comment]
Hi @krmohansingh would you consider a workaround to assign the built-in policies directly?

I can then help triage and repro

**Comment by thejrayasam** [comment]
Hi @krmohansingh, as we are facing the error only for the built-in policies, could you please share the sample tf files that you used for referring the built-in policies? It will help us in replicating the issue

Furthermore, Terraform is not able to get the list of Role Definitions per scope as I understand the error.
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/role_assignments_for_policy/locals.tf


> may be and we are trying to isolate the problem here. Now we were able to run the pipeline without any issue, but with no policy assignment defined in the archtype.
> 
> And as soon as we keep one policy assignment, we are getting below error related to role_assignment.
> 
> ![image](https://private-user-images.githubusercontent.com/50234904/335835866-47074eb4-22f0-497f-b3cf-41c26fb52ddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTg1NTgsIm5iZiI6MTcxNzY5ODI1OCwicGF0aCI6Ii81MDIzNDkwNC8zMzU4MzU4NjYtNDcwNzRlYjQtMjJmMC00OTdmLWIzY2YtNDFjMjZmYjUyZGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4MjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYzA5YmFjZjhiZmY5MjBkYjY0ZTA2NmU2NzY5ZGUwMzg1MzJiZDljNGYwYjE3NWZkNjlkMzMwYTllNjViZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCCwjBUsB4qw4cWIWeGOTUie8oYn5dXaoUrRhNrk8LE)
> 
> We checked state file and remove all the role assignment reference and still we are getting this. Please find below is our policy assignment .json file
> 
> ![image](https://private-user-images.githubusercontent.com/50234904/335836013-6ba7193b-e065-4427-9d7a-5630f3c14716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTg1NTgsIm5iZiI6MTcxNzY5ODI1OCwicGF0aCI6Ii81MDIzNDkwNC8zMzU4MzYwMTMtNmJhNzE5M2ItZTA2NS00NDI3LTlkN2EtNTYzMGYzYzE0NzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4MjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMTA4YTY3ZDAxMzRhZmVkOTkxMDg5ZTkzOTdjYzE4ZTUwYjY4Y2JhMjljZGI5YWQzYmRmYTY5MDIyZTg4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1oGK4weenG2lXVBKfrIwv2zHmfxMZiwzIOeGhAn7gWE)
> 
> Another thing which i observed is whenever we are referencing the custom policies defined within the initiatives, we are not seeing any issues . But, when we are referencing built-in policies within the policy set definition we started getting below error . Seems like data source is not working. Please suggest how can we resolve this, as this was working before without any issues.

**Comment by matt-FFFFFF** [comment]
I cannot see the attachment from the last post. Please reattach using GitHub's website.

**Comment by krmohansingh** [comment]
@thejrayasam Please find the policy set definition and assignment we tried to use.

Policy_set_definition.json

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/50234904/0283f8a1-9565-4ac5-8056-d16110466514)

Policy_assignement.json

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/50234904/499fc4a1-0128-486e-a4d5-4c77a4cff07d)

Archetype definition where we called this assignment 

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/50234904/a3ca6a2c-a0c5-4ca9-b04f-62f86d3cb9e8)

@matt-FFFFFF As we have discussed over call, please find the screenshot below like as soon as we assign that assignment that has reference to built-in policy, we start getting the below error related to role assignement.

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/50234904/c6ad192b-519f-4a42-8976-392835ae4b9c)

How we managed to resolve the issue temporary basis we ran terraform apply -var-file terraform.tfvars and then tried to add the policy reference which had built-in reference, terraform plan started working with policy with even built-in reference. 

After that there were some subscriptions defined in the terraform.tfvars file which our customer found that those subscriptions are already decommissioned, after removing that we are not seeing the error anymore. But, question is if removing the stale subscription fixed the issues then why it started working temporarily when we ran terraform apply -ver-file terraform.tfvars file  
. Please check and let us know if you were able to replicate.

**Comment by matt-FFFFFF** [comment]
Hi

please make sure that inputs to this module are literals, and do not come from the resource graph.

using data sources or other resources can cause issues like this.

**Comment by krmohansingh** [comment]
@matt-FFFFFF thank you for your inputs, that can be the possibility.
@thejrayasam Issue seems to be fixed now. 

Based on my analysis which I have done, I feel below could be the root cause of the issue which I would your help to confirm my analysis. 

**Analysis** 
The pipeline was working till now because subscription was decommissioned. Based on the documents if the subscription is in disabled mode, it will take 90 days to get permanently deleted.
https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/subscription-states

The root cause could be that a manual Terraform apply fixed the pipeline issues temporarily. Subsequently, another Terraform apply from the develop pipeline tried to download all dependencies for the subscriptions mentioned in the dev/terraform.tfvars file. However, these subscription IDs reference were missing from the prod/terraform.tfvars file. As a result, the develop pipeline was failing while the release pipeline was working fine. Essentially, after one change that executed a policy to the subscriptions, all subscriptions defined in the tfvars files were read for execution. Due to some subscriptions being missing, the pipeline encountered an error. When we manually ran "terraform plan" and removed the deleted subscriptions, the issue was resolved.


To ensure this issue does not recur, please make sure we remove all references to deleted subscriptions from the terraform.tfvars file.

**Comment by matt-FFFFFF** [comment]
Can this be closed now?
