### ISSUE TITLE
Policy Definition 'Deploy Diagnostic Settings for Log Analytics to Log Analytics workspace' incorrectly reports non-compliance

### ISSUE THREAD

**Issue by donk-msft** [Azure/terraform-azurerm-caf-enterprise-scale#951]
Policy Definition 'Deploy Diagnostic Settings for Log Analytics to Log Analytics workspace' in Policy Set 'Deploy Diagnostic Settings for Log Analytics to Log Analytics workspace' reports non-compliance incorrectly.

The policy configures one out of two categories (Audit). but expects all categories to be enabled.

Resource configuration:
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/17045753/569a83d9-2e77-4296-b675-11390b87fea6)

Reason for non-compliance:
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/17045753/6a983767-2a43-4a0c-bd21-f4aa05a6ed18)

Suggestion to replace custom policy definition by built-in definition 'Enable logging by category group for Log Analytics workspaces (microsoft.operationalinsights/workspaces) to Log Analytics' or replace the Policy Set with new built-in one 'Enable audit category group resource logging for supported resources to Log Analytics'.

**Comment by jtracey93** [comment]
Hey @donk-msft 

This is being replaced by the built ins as you suggest in the next policy refresh which we are just completing now and hope to have in TF by the end of June.
