### ISSUE TITLE
Add a way to manage excluded scopes in the policy assignment

### ISSUE THREAD

**Issue by simonsanschagrin** [Azure/terraform-azurerm-caf-enterprise-scale#96]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Add a way to manage excluded scopes in the policy assignment**

This module works great. The only missing feature on our side is that there is no way to manage the excluded scopes in the policy assignment. It is always an empty array in the definition JSON file ("notScopes": []).

Adding a parameter to the archetype definition that would be passed to the assignment OR having a specific module variable mapping assignments to excluded scopes would fit our needs.

Thanks

**Comment by krowlandson** [comment]
Hi @simonsanschagrin... thank you for the great feedback and feature request.

As it stands, I believe we already have the ability to achieve the outcome you are asking for but not using parameters or variables as you have described. This is currently undocumented though, so I will mark this as an example scenario to add to our Wiki.

Assuming you are wanting to modify this setting on one of the Policy Assignments included within the module, please let me know whether the following approach will work for you.

> The below will also work for your own Policy Assignment templates if you are creating additional ones.

1. Ensure you have [setup a _custom library_](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BVariables%5D-library_path) within your root module.
2. Create a copy of the Policy Assignment you would like to add exclusions to in your custom library, ensuring you maintain the required naming convention matching `**/policy_assignment_*.{json,yml,yaml}`. The module will use any templates 
3. To keep things simple at this point, we will assume you retain the original Policy Assignment name(s) but note that you can use different names and then add the new assignments by [extending the existing archetype definition](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions) with your new Policy Assignment(s), or by [creating a new custom archetype definition](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions) using one of the supported approaches.
4. Edit your copy of the Policy Assignment(s) in your custom library, adding the required value(s) to the `not_scopes` field.
> **NOTE:** You can also use the templating capabilities to ensure any values are populated dynamically with values such as `root_scope_id` or `root_scope_resource_id`) as needed.

As an example, consider the following Policy Assignment from the root scope, where we decide to exclude anything under the `platform` and `sandboxes` Management Group scopes:

File name: `lib/policy_assignment_es_deploy_asc_defender.tmpl.json`
Template:
```json
{
  "name": "Deploy-ASC-Defender",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Deploy-ASC-Defender.",
    "displayName": "Deploy-ASC-Defender",
    "notScopes": [
      "${root_scope_resource_id}-platform",
      "${root_scope_resource_id}-sandboxes"
    ],
    "parameters": {
      "emailSecurityContact": {
        "value": "security_contact@replace_me"
      },
      "logAnalytics": {
        "value": "${root_scope_id}-la"
      },
      "ascExportResourceGroupName": {
        "value": "${root_scope_id}-asc-export"
      },
      "ascExportResourceGroupLocation": {
        "value": "${default_location}"
      }
    },
    "policyDefinitionId": "${root_scope_resource_id}/providers/Microsoft.Authorization/policySetDefinitions/Deploy-ASC-Config",
    "scope": "${current_scope_resource_id}",
    "enforcementMode": "Default"
  },
  "location": "${default_location}",
  "identity": {
    "type": "SystemAssigned"
  }
}
```

Based on my testing, this should result in the Policy Assignment being updated with the `notScopes` as requested:

![image](https://user-images.githubusercontent.com/12268562/117830878-f402c880-b26b-11eb-8d1d-513a2d9a23c5.png)

> You will probably come across issue #90 when running `terraform apply` on an existing deployment when making these changes.

Please let me know whether this answers your request.

**Comment by krowlandson** [comment]
@simonsanschagrin ... just checking in to see whether the above resolved your issue? Thank you

**Comment by simonsanschagrin** [comment]
Yes, thanks for the answer.
