### ISSUE TITLE
How to avoid Decommissioned, Landing Zones and Sandboxes Management Groups creation

### ISSUE THREAD

**Issue by praveenambati1233** [Azure/terraform-azurerm-caf-enterprise-scale#979]
**terraform**: latest

**azure provider**: >= 3.74.0

**module**: latest

#### Describe the bug

I am able to create the Management Groups , but as per the standards the module is creating 
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/49944591/f17e2952-01a6-437a-b07e-b7345d4539b3)
But I don't want **Decommissioned, Landing Zones and Sandboxes** Management Groups to be created during the process or by default. As per my client requirement these have to be created in different management group level. 

Reference - https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Default-Configuration

#### Steps to Reproduce

Run default terraform main.tf- https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Default-Configuration

**Comment by matt-FFFFFF** [comment]
Hi

Unfortunately this isn't possible without deploying all management groups though custom landing zones.

However doing so means many of the convenience features of the module do not work.

**Comment by praveenambati1233** [comment]
Okay. I have used custom_landing_zones approach to create desired Management Group structure.
