### ISSUE TITLE
Bug Report: Policy Sets not found in Azure Government

### ISSUE THREAD

**Issue by dsimpson-evotek** [Azure/terraform-azurerm-caf-enterprise-scale#980]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.8.5

**azure provider**: 3.107.0

**module**: terraform-azurerm-caf-enterprise-scale

### Description

When running a Terraform plan in Azure Government, we get the following error:
`Error:
reading Policy Set Definition "e20d08C5-6d64-656d-6465-ce937fdBebc": policy.SetDefinitionsClient#Get: Failure responding to request: StatusCode=404 --
Original
Error: autorest/azure: Service returned
an error. Status=404 Code="PolicySetDefinitionNotFound™ Message="The policy set definition 'e20d08c5-6d64-656d-6465-ce9e37fdbebc' could not
be found.`

#### Describe the bug

Trying to follow CAF docs for a basic CAF implementation in Azure Government.

#### Steps to Reproduce

1. Clone CAF
2. Set location to US Gov Virginia
3. Follow level 100 example from documentation

**Comment by matt-FFFFFF** [comment]
Hi!

This is unfortunately the case sometimes. We can't test the module in usgov as most of the team are based in EMEA.

In order to fix this you'll have to exclude the policy definition and any related assignments from the archetype.

@springstone do you know if there are any plans to put the latest policies into gov?

**Comment by matt-FFFFFF** [comment]
The standard way to do this is to exclude the policies as you encounter them - use the exclusions process documented in the wiki
