### ISSUE TITLE
Importing Subscriptions into Management Groups

### ISSUE THREAD

**Issue by mmoreno43** [Azure/terraform-azurerm-caf-enterprise-scale#992]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

terraform: 1.8.5

azure provider: 3.107.0

module: terraform-azurerm-caf-enterprise-scale

#### Describe the bug
To give some context, my Terraform Principal could not move the subscriptions into the correct management group. Afterwards, I updated my custom management group with the correct subscription in Terraform. When running Terraform apply I was getting an  error saying this resource already existed and we need to import the resource. So I was trying to import subscriptions into Management Groups and I get an error saying: 
`Error: Index value required  on <import-address> line 1: 
1: module.caf-enterprise-scale.azurerm_management_group_subscription_association.enterprise_scale[/providers/Microsoft.Management/managementGroups/<MGMT GROUP>/subscriptions/<SUB-ID>]
Index brackets must contain either a literal number or a literal string.`

The import command I am using is:
`terraform import -no-color 'module.caf-enterprise-scale.azurerm_management_group_subscription_association.enterprise_scale["/providers/Microsoft.Management/managementGroups/<MGMT-GROUP>/subscriptions/<SUB-ID>"]' '/providers/Microsoft.Management/managementGroups/<MGMT Group>/subscriptions/<SUB-ID>'`

I did read issue #891 and they mentioned a different import command which I have tried and still fails.

I am also not using `strict_subscription_association.`

#### Steps to Reproduce

1. Create a subscription manually
2. Move subscription into Management Group manually
3. Add subscription ID into the management group via Terraform
5. Run terraform import command

**Comment by matt-FFFFFF** [comment]
Hi! Have you tried using `import {}` blocks in your terraform code - this is the best way to import resources.

You can leave the import statements in place after the resource has been imported

**Comment by kayahk** [comment]
> Hi! Have you tried using `import {}` blocks in your terraform code - this is the best way to import resources.
> 
> You can leave the import statements in place after the resource has been imported

I tried it and couldn't get it to work with the `import` statement either, would you mind giving an example that you verified it works?

I think the import of pre-existing subscriptions into a management group structure built with this module is a very common use case and should probably be mentioned somewhere in the documentation.

Thank you for your valued efforts.
