### ISSUE TITLE
Bug Report : Unable to create policy for custom landing zone

### ISSUE THREAD

**Issue by praveenambati1233** [Azure/terraform-azurerm-caf-enterprise-scale#995]
I've tried to assign one custom policy to a customs landing zone, i've followed this guide [Enforce-RG-Tags](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Create-Custom-Policies-Policy-Sets-and-Assignments#libpolicy_definitionspolicy_definition_es_enforce_rg_tagsjson). When i run terraform plan i obtain this error:

╷ │ Error: reading Policy Definition "Enforce-RG-Tags": policy.DefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicyDefinitionNotFound" Message="The policy definition 'Enforce-RG-Tags' could not be found." │ │   with module.enterprise_scale.data.azurerm_policy_definition.external_lookup["/providers/Microsoft.Management/managementGroups/**ROOT**/providers/Microsoft.Authorization/policyDefinitions/Enforce-RG-Tags"], │   on .terraform/modules/enterprise_scale/locals.policy_assignments.tf line 167, in data "azurerm_policy_definition" "external_lookup": │  167: data "azurerm_policy_definition" "external_lookup" { │ ╵
Seems that the module try to search the policy in the Root Mgmt group.

**Comment by matt-FFFFFF** [comment]
Can you replace the policy definition id in the assignment with the correct one?

**Comment by praveenambati1233** [comment]
It is as below 
`        "policyDefinitionId": "${root_scope_resource_id}/providers/Microsoft.Authorization/policyDefinitions/Enforce-RG-Tags",
`

@matt-FFFFFF

**Comment by matt-FFFFFF** [comment]
So replace that with the correct resource id for the definition that you want to apply

**Comment by praveenambati1233** [comment]
Below is my project setup, I am not sure what exactly the resource id should be that policy assigns to all the custom landing zones ?

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/49944591/99715b0c-cd2e-4492-926e-cbf74cb15cc7)

**Comment by matt-FFFFFF** [comment]
Hi,

Is there a common parent management group in which you can place the policy definition?

You'll need an archetype that just contains the definition.

Then you'll need another archetype that contains the assignment that references said definition.

**Comment by praveenambati1233** [comment]
I have refactored everything and post the issue at https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/998
